/**
 * DOCX Export utility for AI tool outputs (IEP, Lesson Plan, Social Story etc.)
 *
 * Uses the docx npm package to generate a professional Word document
 * from plain-text AI output. Runs entirely client-side — no server needed.
 *
 * Usage:
 *   import { exportToDocx } from "@/lib/docx-export";
 *   await exportToDocx({ title: "IEP Goals — JS (Year 9)", content: "..." });
 */

export interface DocxExportOptions {
  title: string;
  content: string;
  subtitle?: string;
  schoolName?: string;
}

export async function exportToDocx({ title, content, subtitle, schoolName }: DocxExportOptions): Promise<void> {
  // Dynamically import docx to keep the main bundle lean
  const {
    Document, Packer, Paragraph, TextRun, HeadingLevel,
    AlignmentType, BorderStyle, ShadingType, LevelFormat,
    WidthType,
  } = await import("docx");

  // ── Parse the AI text into structured paragraphs ────────────────────────────
  // The AI output uses markdown-ish formatting: ## headings, **bold**, bullet lines
  const lines = content.split(/\n/);

  const paragraphs: InstanceType<typeof Paragraph>[] = [];

  // Title paragraph
  paragraphs.push(
    new Paragraph({
      heading: HeadingLevel.HEADING_1,
      children: [new TextRun({ text: title, bold: true, color: "166534", size: 36 })],
      spacing: { after: 120 },
    })
  );

  // Subtitle if provided
  if (subtitle || schoolName) {
    paragraphs.push(
      new Paragraph({
        children: [new TextRun({
          text: [schoolName, subtitle].filter(Boolean).join(" · "),
          color: "6B7280", size: 20, italics: true
        })],
        spacing: { after: 240 },
      })
    );
  }

  // Divider line
  paragraphs.push(
    new Paragraph({
      border: { bottom: { style: BorderStyle.SINGLE, size: 6, color: "16A34A", space: 1 } },
      spacing: { after: 240 },
      children: [],
    })
  );

  // Parse content lines
  for (const raw of lines) {
    const line = raw.trimEnd();

    if (!line.trim()) {
      paragraphs.push(new Paragraph({ children: [], spacing: { after: 80 } }));
      continue;
    }

    // H1 heading: # Title
    const h1 = line.match(/^# (.+)/);
    if (h1) {
      paragraphs.push(
        new Paragraph({
          heading: HeadingLevel.HEADING_1,
          children: [new TextRun({ text: h1[1], bold: true, size: 28, color: "166534" })],
          spacing: { before: 240, after: 120 },
        })
      );
      continue;
    }

    // H2 heading: ## Title
    const h2 = line.match(/^## (.+)/);
    if (h2) {
      paragraphs.push(
        new Paragraph({
          heading: HeadingLevel.HEADING_2,
          children: [new TextRun({ text: h2[1], bold: true, size: 24, color: "166534" })],
          spacing: { before: 200, after: 80 },
        })
      );
      continue;
    }

    // H3 heading: ### Title
    const h3 = line.match(/^### (.+)/);
    if (h3) {
      paragraphs.push(
        new Paragraph({
          heading: HeadingLevel.HEADING_3,
          children: [new TextRun({ text: h3[1], bold: true, size: 22, color: "374151" })],
          spacing: { before: 160, after: 60 },
        })
      );
      continue;
    }

    // Bullet: - item or * item or • item
    const bullet = line.match(/^[\-\*•] (.+)/);
    if (bullet) {
      paragraphs.push(
        new Paragraph({
          numbering: { reference: "adaptly-bullets", level: 0 },
          children: parseInlineMarkdown(bullet[1], TextRun),
          spacing: { after: 60 },
        })
      );
      continue;
    }

    // Numbered list: 1. item
    const numbered = line.match(/^(\d+)\. (.+)/);
    if (numbered) {
      paragraphs.push(
        new Paragraph({
          numbering: { reference: "adaptly-numbers", level: 0 },
          children: parseInlineMarkdown(numbered[2], TextRun),
          spacing: { after: 60 },
        })
      );
      continue;
    }

    // Regular paragraph with inline formatting
    paragraphs.push(
      new Paragraph({
        children: parseInlineMarkdown(line, TextRun),
        spacing: { after: 100 },
      })
    );
  }

  // Footer paragraph
  paragraphs.push(
    new Paragraph({
      border: { top: { style: BorderStyle.SINGLE, size: 4, color: "D1FAE5", space: 1 } },
      spacing: { before: 360, after: 0 },
      children: [
        new TextRun({
          text: `Generated by Adaptly${schoolName ? ` for ${schoolName}` : ""} · adaptly.co.uk · ${new Date().toLocaleDateString("en-GB", { day: "2-digit", month: "long", year: "numeric" })}`,
          color: "9CA3AF",
          size: 16,
          italics: true,
        }),
      ],
    })
  );

  // ── Build Document ──────────────────────────────────────────────────────────
  const doc = new Document({
    numbering: {
      config: [
        {
          reference: "adaptly-bullets",
          levels: [
            {
              level: 0,
              format: LevelFormat.BULLET,
              text: "•",
              alignment: AlignmentType.LEFT,
              style: { paragraph: { indent: { left: 720, hanging: 360 } } },
            },
          ],
        },
        {
          reference: "adaptly-numbers",
          levels: [
            {
              level: 0,
              format: LevelFormat.DECIMAL,
              text: "%1.",
              alignment: AlignmentType.LEFT,
              style: { paragraph: { indent: { left: 720, hanging: 360 } } },
            },
          ],
        },
      ],
    },
    styles: {
      default: {
        document: { run: { font: "Arial", size: 22 } }, // 11pt
      },
      paragraphStyles: [
        {
          id: "Heading1",
          name: "Heading 1",
          basedOn: "Normal",
          next: "Normal",
          quickFormat: true,
          run: { size: 32, bold: true, font: "Arial", color: "166534" },
          paragraph: { spacing: { before: 240, after: 120 }, outlineLevel: 0 },
        },
        {
          id: "Heading2",
          name: "Heading 2",
          basedOn: "Normal",
          next: "Normal",
          quickFormat: true,
          run: { size: 26, bold: true, font: "Arial", color: "166534" },
          paragraph: { spacing: { before: 200, after: 80 }, outlineLevel: 1 },
        },
        {
          id: "Heading3",
          name: "Heading 3",
          basedOn: "Normal",
          next: "Normal",
          quickFormat: true,
          run: { size: 22, bold: true, font: "Arial", color: "374151" },
          paragraph: { spacing: { before: 160, after: 60 }, outlineLevel: 2 },
        },
      ],
    },
    sections: [
      {
        properties: {
          page: {
            size: { width: 11906, height: 16838 }, // A4
            margin: { top: 1440, right: 1080, bottom: 1440, left: 1080 },
          },
        },
        children: paragraphs,
      },
    ],
  });

  // ── Generate and download ───────────────────────────────────────────────────
  const buffer = await Packer.toBlob(doc);
  const url = URL.createObjectURL(buffer);
  const a = document.createElement("a");
  a.href = url;
  // Sanitise title for filename
  a.download = `${title.replace(/[^a-z0-9\s\-\_]/gi, "").replace(/\s+/g, "_").slice(0, 60)}.docx`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

// ── Inline markdown parser (bold/italic) ──────────────────────────────────────
function parseInlineMarkdown(text: string, TextRun: any): any[] {
  const runs: any[] = [];
  // Split on **bold** and *italic*
  const parts = text.split(/(\*\*[^*]+\*\*|\*[^*]+\*)/g);
  for (const part of parts) {
    if (part.startsWith("**") && part.endsWith("**")) {
      runs.push(new TextRun({ text: part.slice(2, -2), bold: true }));
    } else if (part.startsWith("*") && part.endsWith("*")) {
      runs.push(new TextRun({ text: part.slice(1, -1), italics: true }));
    } else if (part) {
      runs.push(new TextRun({ text: part }));
    }
  }
  return runs.length > 0 ? runs : [new TextRun({ text })];
}
