/**
 * Shared formatter for AIToolPage output that injects school logo + branding.
 * Used by BehaviourPlan, SmartTargets, WellbeingSupport and similar tools.
 */

export function formatToolOutput(
  text: string,
  options: {
    logoUrl?: string;
    schoolName?: string;
    accentColor?: string;
    accentBg?: string;
    title?: string;
    emoji?: string;
  } = {}
): string {
  const {
    logoUrl,
    schoolName,
    accentColor = "#6366f1",
    accentBg = "#eef2ff",
    emoji = "📋",
  } = options;

  const logoHtml = logoUrl
    ? `<img src="${logoUrl}" alt="School logo" style="height:40px;width:auto;object-fit:contain;border-radius:4px;background:rgba(255,255,255,0.9);padding:2px;" />`
    : `<div style="width:36px;height:36px;border-radius:8px;background:${accentColor};display:flex;align-items:center;justify-content:center;font-size:18px;">${emoji}</div>`;

  const paragraphs = text.split(/\n\n+/);
  const bodyHtml = paragraphs.map(p => {
    const t = p.trim();
    if (!t) return "";
    if (t.startsWith("##")) {
      return `<h3 style="font-size:14px;font-weight:700;color:${accentColor};margin:16px 0 6px;border-left:3px solid ${accentColor};padding-left:8px;">${t.replace(/^##\s*/, "")}</h3>`;
    }
    if (t.startsWith("#")) {
      return `<h2 style="font-size:17px;font-weight:800;color:${accentColor};margin:20px 0 8px;">${t.replace(/^#\s*/, "")}</h2>`;
    }
    // Bullet lists
    if (t.startsWith("- ") || t.startsWith("• ")) {
      const items = t.split("\n").filter(l => l.trim());
      const lis = items.map(l => `<li style="margin:3px 0;color:#374151;">${l.replace(/^[-•]\s*/, "").replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>")}</li>`).join("");
      return `<ul style="margin:8px 0 8px 16px;padding:0;">${lis}</ul>`;
    }
    // Numbered lists
    if (/^\d+\./.test(t)) {
      const items = t.split("\n").filter(l => l.trim());
      const lis = items.map(l => `<li style="margin:4px 0;color:#374151;">${l.replace(/^\d+\.\s*/, "").replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>")}</li>`).join("");
      return `<ol style="margin:8px 0 8px 18px;padding:0;">${lis}</ol>`;
    }
    const formatted = t.replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>").replace(/\n/g, "<br/>");
    return `<p style="font-size:13px;color:#1f2937;line-height:1.7;margin:0 0 10px;">${formatted}</p>`;
  }).filter(Boolean).join("");

  return `<div style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;max-width:680px;margin:0 auto;background:#fff;border-radius:14px;overflow:hidden;box-shadow:0 3px 16px rgba(0,0,0,0.08);">
    <div style="background:linear-gradient(135deg,${accentColor},${accentColor}cc);padding:16px 20px;display:flex;align-items:center;gap:12px;">
      ${logoHtml}
      <div>
        <div style="font-size:15px;font-weight:800;color:white;">${options.title || "Support Document"}</div>
        <div style="font-size:11px;color:rgba(255,255,255,0.75);margin-top:2px;">${schoolName || "Adaptly"} · Generated ${new Date().toLocaleDateString("en-GB")}</div>
      </div>
    </div>
    <div style="padding:18px 22px;">${bodyHtml}</div>
    <div style="padding:10px 20px;background:#f9fafb;border-top:1px solid #e5e7eb;font-size:10px;color:#9ca3af;">Generated by Adaptly · adaptly.co.uk · This document is confidential</div>
  </div>`;
}
