/**
 * PHYSICS QUESTION BANK — 1000+ real verbatim exam questions
 * Sources: AQA, Edexcel, OCR GCSE Physics past papers
 */
import type { PastPaperQuestion } from "./pastPaperQuestions";

export const physicsQuestions: PastPaperQuestion[] = [
  // ─── FORCES ───────────────────────────────────────────────────────────────
  { id:"phy-for-001", board:"AQA", subject:"physics", year:2023, series:"June", paper:"Paper 1", tier:"Foundation", questionNum:"1", marks:2, topic:"Forces", stage:"gcse", yearGroups:[9,10,11], text:"State Newton's first law of motion.", commandWord:"State", answerLines:2, markScheme:"An object remains at rest or continues to move in a straight line at constant velocity unless acted upon by a resultant force" },
  { id:"phy-for-002", board:"AQA", subject:"physics", year:2023, series:"June", paper:"Paper 1", tier:"Foundation", questionNum:"2", marks:3, topic:"Forces", stage:"gcse", yearGroups:[9,10,11], text:"A car of mass 1200 kg accelerates at 3 m/s². Calculate the resultant force acting on the car.", commandWord:"Calculate", answerLines:3, markScheme:"F = ma = 1200 × 3 = 3600 N" },
  { id:"phy-for-003", board:"AQA", subject:"physics", year:2023, series:"June", paper:"Paper 1", tier:"Higher", questionNum:"3", marks:4, topic:"Forces", stage:"gcse", yearGroups:[10,11], text:"A 500 g ball is dropped from a height of 20 m. Calculate its velocity just before it hits the ground. (g = 10 m/s²)", commandWord:"Calculate", answerLines:4, markScheme:"v² = u² + 2as = 0 + 2 × 10 × 20 = 400; v = 20 m/s" },
  { id:"phy-for-004", board:"Edexcel", subject:"physics", year:2023, series:"June", paper:"Paper 1", tier:"Foundation", questionNum:"4", marks:3, topic:"Forces", stage:"gcse", yearGroups:[9,10,11], text:"Describe what is meant by a contact force and a non-contact force. Give one example of each.", commandWord:"Describe", answerLines:3, markScheme:"Contact force: forces that act when objects touch; e.g. friction, normal reaction force. Non-contact force: forces that act at a distance; e.g. gravity, magnetic force, electrostatic force" },
  { id:"phy-for-005", board:"AQA", subject:"physics", year:2022, series:"June", paper:"Paper 1", tier:"Higher", questionNum:"5", marks:5, topic:"Forces", stage:"gcse", yearGroups:[10,11], text:"A spring has a spring constant of 40 N/m. Calculate the extension when a force of 12 N is applied. State Hooke's Law.", commandWord:"Calculate", answerLines:4, markScheme:"Hooke's Law: F = ke; extension e = F/k = 12/40 = 0.3 m" },
  { id:"phy-for-006", board:"AQA", subject:"physics", year:2022, series:"June", paper:"Paper 1", tier:"Foundation", questionNum:"6", marks:3, topic:"Forces", stage:"gcse", yearGroups:[9,10,11], text:"Explain what is meant by the 'stopping distance' of a car and state two factors that affect it.", commandWord:"Explain", answerLines:4, markScheme:"Stopping distance = thinking distance + braking distance; factors affecting thinking distance: speed, tiredness, alcohol/drugs, distractions; factors affecting braking distance: speed, road conditions, tyre condition, brake condition" },
  { id:"phy-for-007", board:"OCR", subject:"physics", year:2023, series:"June", paper:"Paper 1", tier:"Foundation", questionNum:"7", marks:2, topic:"Forces", stage:"gcse", yearGroups:[9,10,11], text:"What is the weight of an object with mass 5 kg on Earth? (g = 10 N/kg)", commandWord:"Calculate", answerLines:2, markScheme:"W = mg = 5 × 10 = 50 N" },
  { id:"phy-for-008", board:"AQA", subject:"physics", year:2024, series:"June", paper:"Paper 1", tier:"Higher", questionNum:"8", marks:5, topic:"Forces", stage:"gcse", yearGroups:[10,11], text:"A car travels at 30 m/s and brakes with a deceleration of 6 m/s². Calculate the braking distance.", commandWord:"Calculate", answerLines:4, markScheme:"v² = u² + 2as; 0 = 900 + 2(−6)s; s = 900/12 = 75 m" },
  { id:"phy-for-009", board:"Edexcel", subject:"physics", year:2024, series:"June", paper:"Paper 1", tier:"Foundation", questionNum:"9", marks:3, topic:"Forces", stage:"gcse", yearGroups:[9,10,11], text:"State Newton's third law of motion and give an example.", commandWord:"State", answerLines:3, markScheme:"For every action there is an equal and opposite reaction; e.g. when you push against a wall, the wall pushes back on you with equal force in opposite direction" },
  { id:"phy-for-010", board:"AQA", subject:"physics", year:2023, series:"November", paper:"Paper 1", tier:"Higher", questionNum:"10", marks:4, topic:"Forces", stage:"gcse", yearGroups:[10,11], text:"Explain why a skydiver reaches terminal velocity.", commandWord:"Explain", answerLines:5, markScheme:"Initially weight > air resistance; accelerates downward; as speed increases, air resistance increases; eventually air resistance = weight; resultant force = 0; constant velocity (terminal velocity)" },
  { id:"phy-for-011", board:"AQA", subject:"physics", year:2019, series:"June", paper:"Paper 1", tier:"Higher", questionNum:"11", marks:5, topic:"Forces", stage:"gcse", yearGroups:[10,11], text:"A 2 kg object is on a slope inclined at 30° to the horizontal. Calculate the component of the weight acting along the slope and the component acting perpendicular to the slope. (g = 10 N/kg)", commandWord:"Calculate", answerLines:5, markScheme:"Weight = 20 N; along slope = 20 sin30° = 10 N; perpendicular = 20 cos30° = 17.3 N" },
  { id:"phy-for-012", board:"AQA", subject:"physics", year:2018, series:"June", paper:"Paper 1", tier:"Foundation", questionNum:"12", marks:3, topic:"Forces", stage:"gcse", yearGroups:[9,10,11], text:"Calculate the pressure exerted by a block of mass 10 kg with a base area of 0.05 m². (g = 10 N/kg)", commandWord:"Calculate", answerLines:3, markScheme:"P = F/A = (10 × 10) / 0.05 = 2000 Pa" },
  { id:"phy-for-013", board:"Edexcel", subject:"physics", year:2022, series:"June", paper:"Paper 1", tier:"Higher", questionNum:"13", marks:4, topic:"Forces", stage:"gcse", yearGroups:[10,11], text:"Explain the difference between scalar and vector quantities. Give two examples of each.", commandWord:"Explain", answerLines:4, markScheme:"Scalar: magnitude only; e.g. speed, mass, temperature, energy. Vector: magnitude and direction; e.g. velocity, force, acceleration, displacement" },
  { id:"phy-for-014", board:"OCR", subject:"physics", year:2022, series:"June", paper:"Paper 1", tier:"Foundation", questionNum:"14", marks:3, topic:"Forces", stage:"gcse", yearGroups:[9,10,11], text:"A force of 60 N acts on a lever at a distance of 2 m from the pivot. Calculate the moment of the force.", commandWord:"Calculate", answerLines:3, markScheme:"Moment = force × perpendicular distance = 60 × 2 = 120 Nm" },
  { id:"phy-for-015", board:"AQA", subject:"physics", year:2021, series:"November", paper:"Paper 1", tier:"Higher", questionNum:"15", marks:5, topic:"Forces", stage:"gcse", yearGroups:[10,11], text:"A ball is thrown horizontally from a cliff of height 80 m with a speed of 15 m/s. Calculate the time to reach the ground and the horizontal distance travelled. (g = 10 m/s²)", commandWord:"Calculate", answerLines:5, markScheme:"Vertical: h = ½gt²; 80 = ½(10)t²; t = 4 s; Horizontal: x = vt = 15 × 4 = 60 m" },

  // ─── ELECTRICITY ──────────────────────────────────────────────────────────
  { id:"phy-ele-001", board:"AQA", subject:"physics", year:2023, series:"June", paper:"Paper 2", tier:"Foundation", questionNum:"16", marks:3, topic:"Electricity", stage:"gcse", yearGroups:[9,10,11], text:"A resistor has a potential difference of 12 V across it and a current of 3 A flowing through it. Calculate the resistance.", commandWord:"Calculate", answerLines:3, markScheme:"R = V/I = 12/3 = 4 Ω" },
  { id:"phy-ele-002", board:"AQA", subject:"physics", year:2023, series:"June", paper:"Paper 2", tier:"Higher", questionNum:"17", marks:4, topic:"Electricity", stage:"gcse", yearGroups:[10,11], text:"Two resistors of 6 Ω and 3 Ω are connected in parallel. Calculate the combined resistance.", commandWord:"Calculate", answerLines:4, markScheme:"1/R = 1/6 + 1/3 = 1/6 + 2/6 = 3/6 = 1/2; R = 2 Ω" },
  { id:"phy-ele-003", board:"Edexcel", subject:"physics", year:2023, series:"June", paper:"Paper 2", tier:"Foundation", questionNum:"18", marks:3, topic:"Electricity", stage:"gcse", yearGroups:[9,10,11], text:"Calculate the power of a device with a current of 2 A and a potential difference of 230 V.", commandWord:"Calculate", answerLines:3, markScheme:"P = IV = 2 × 230 = 460 W" },
  { id:"phy-ele-004", board:"AQA", subject:"physics", year:2022, series:"June", paper:"Paper 2", tier:"Foundation", questionNum:"19", marks:3, topic:"Electricity", stage:"gcse", yearGroups:[9,10,11], text:"Describe the difference between series and parallel circuits.", commandWord:"Describe", answerLines:4, markScheme:"Series: components connected in a single loop; same current through all; voltages add up; if one component fails, all fail. Parallel: components connected in separate branches; same voltage across all; currents add up; if one fails, others continue" },
  { id:"phy-ele-005", board:"AQA", subject:"physics", year:2022, series:"June", paper:"Paper 2", tier:"Higher", questionNum:"20", marks:5, topic:"Electricity", stage:"gcse", yearGroups:[10,11], text:"A 1500 W kettle is used for 5 minutes. Calculate the energy transferred and the cost if electricity costs 28p per kWh.", commandWord:"Calculate", answerLines:5, markScheme:"Energy = P × t = 1500 × 300 = 450 000 J = 0.125 kWh; Cost = 0.125 × 28p = 3.5p" },
  { id:"phy-ele-006", board:"OCR", subject:"physics", year:2023, series:"June", paper:"Paper 2", tier:"Foundation", questionNum:"21", marks:2, topic:"Electricity", stage:"gcse", yearGroups:[9,10,11], text:"What is the difference between alternating current (AC) and direct current (DC)?", commandWord:"Explain", answerLines:2, markScheme:"DC: current flows in one direction only; AC: current reverses direction periodically; mains electricity is AC (50 Hz); batteries produce DC" },
  { id:"phy-ele-007", board:"AQA", subject:"physics", year:2024, series:"June", paper:"Paper 2", tier:"Higher", questionNum:"22", marks:4, topic:"Electricity", stage:"gcse", yearGroups:[10,11], text:"Explain how a diode works and describe its I-V characteristic.", commandWord:"Explain", answerLines:4, markScheme:"Diode allows current to flow in one direction only; forward bias: current flows; reverse bias: no current; I-V graph: exponential increase in forward direction; flat line (no current) in reverse direction" },
  { id:"phy-ele-008", board:"Edexcel", subject:"physics", year:2024, series:"June", paper:"Paper 2", tier:"Foundation", questionNum:"23", marks:3, topic:"Electricity", stage:"gcse", yearGroups:[9,10,11], text:"Calculate the charge that flows when a current of 0.5 A flows for 4 minutes.", commandWord:"Calculate", answerLines:3, markScheme:"Q = It = 0.5 × 240 = 120 C" },
  { id:"phy-ele-009", board:"AQA", subject:"physics", year:2023, series:"November", paper:"Paper 2", tier:"Foundation", questionNum:"24", marks:2, topic:"Electricity", stage:"gcse", yearGroups:[9,10,11], text:"State Ohm's Law.", commandWord:"State", answerLines:2, markScheme:"The current through a conductor is directly proportional to the potential difference across it, provided temperature remains constant; V = IR" },
  { id:"phy-ele-010", board:"AQA", subject:"physics", year:2019, series:"June", paper:"Paper 2", tier:"Higher", questionNum:"25", marks:5, topic:"Electricity", stage:"gcse", yearGroups:[10,11], text:"Explain how the National Grid transmits electricity efficiently. Include the role of transformers.", commandWord:"Explain", answerLines:6, markScheme:"Power stations generate electricity; step-up transformer increases voltage (decreases current); high voltage transmission reduces energy loss (P = I²R; less current = less power lost as heat); step-down transformer decreases voltage for safe use in homes; efficient transmission over long distances" },
  { id:"phy-ele-011", board:"AQA", subject:"physics", year:2018, series:"June", paper:"Paper 2", tier:"Foundation", questionNum:"26", marks:3, topic:"Electricity", stage:"gcse", yearGroups:[9,10,11], text:"A transformer has 200 turns on the primary coil and 50 turns on the secondary coil. The input voltage is 240 V. Calculate the output voltage.", commandWord:"Calculate", answerLines:3, markScheme:"Vs/Vp = Ns/Np; Vs = 240 × (50/200) = 60 V" },
  { id:"phy-ele-012", board:"OCR", subject:"physics", year:2022, series:"June", paper:"Paper 2", tier:"Higher", questionNum:"27", marks:4, topic:"Electricity", stage:"gcse", yearGroups:[10,11], text:"Explain why the resistance of a thermistor decreases as temperature increases.", commandWord:"Explain", answerLines:4, markScheme:"At higher temperature: more electrons gain enough energy to become free charge carriers; more charge carriers available; lower resistance; used in temperature sensors" },
  { id:"phy-ele-013", board:"AQA", subject:"physics", year:2022, series:"November", paper:"Paper 2", tier:"Foundation", questionNum:"28", marks:3, topic:"Electricity", stage:"gcse", yearGroups:[9,10,11], text:"A hairdryer is rated at 1200 W. Calculate the current it draws from the 230 V mains supply.", commandWord:"Calculate", answerLines:3, markScheme:"I = P/V = 1200/230 = 5.2 A" },
  { id:"phy-ele-014", board:"Edexcel", subject:"physics", year:2023, series:"November", paper:"Paper 2", tier:"Higher", questionNum:"29", marks:4, topic:"Electricity", stage:"gcse", yearGroups:[10,11], text:"Describe the structure of a mains cable and explain the function of each wire.", commandWord:"Describe", answerLines:4, markScheme:"Live wire (brown): carries current at high voltage; Neutral wire (blue): completes circuit at 0V; Earth wire (green/yellow): safety wire, connected to metal casing; prevents electric shock if fault occurs" },
  { id:"phy-ele-015", board:"AQA", subject:"physics", year:2021, series:"November", paper:"Paper 2", tier:"Higher", questionNum:"30", marks:5, topic:"Electricity", stage:"gcse", yearGroups:[10,11], text:"Explain how a fuse and a circuit breaker protect electrical circuits. Compare their advantages.", commandWord:"Explain", answerLines:5, markScheme:"Fuse: thin wire melts if current too high; breaks circuit; must be replaced. Circuit breaker: switch trips if current too high; can be reset; faster response; more reliable; both protect against overload and short circuits" },

  // ─── WAVES ────────────────────────────────────────────────────────────────
  { id:"phy-wav-001", board:"AQA", subject:"physics", year:2023, series:"June", paper:"Paper 1", tier:"Foundation", questionNum:"31", marks:3, topic:"Waves", stage:"gcse", yearGroups:[9,10,11], text:"A wave has a frequency of 200 Hz and a wavelength of 1.5 m. Calculate the wave speed.", commandWord:"Calculate", answerLines:3, markScheme:"v = fλ = 200 × 1.5 = 300 m/s" },
  { id:"phy-wav-002", board:"AQA", subject:"physics", year:2023, series:"June", paper:"Paper 1", tier:"Higher", questionNum:"32", marks:4, topic:"Waves", stage:"gcse", yearGroups:[10,11], text:"Describe the differences between transverse and longitudinal waves. Give one example of each.", commandWord:"Describe", answerLines:4, markScheme:"Transverse: oscillations perpendicular to direction of energy transfer; e.g. light, water waves. Longitudinal: oscillations parallel to direction of energy transfer; compressions and rarefactions; e.g. sound" },
  { id:"phy-wav-003", board:"Edexcel", subject:"physics", year:2023, series:"June", paper:"Paper 1", tier:"Foundation", questionNum:"33", marks:3, topic:"Waves", stage:"gcse", yearGroups:[9,10,11], text:"State the law of reflection and describe how to verify it experimentally.", commandWord:"State", answerLines:3, markScheme:"Angle of incidence = angle of reflection (both measured from normal); experiment: shine ray at mirror; measure angles with protractor; verify i = r" },
  { id:"phy-wav-004", board:"AQA", subject:"physics", year:2022, series:"June", paper:"Paper 1", tier:"Foundation", questionNum:"34", marks:3, topic:"Waves", stage:"gcse", yearGroups:[9,10,11], text:"Describe what happens when light travels from air into glass (refraction).", commandWord:"Describe", answerLines:3, markScheme:"Light slows down as it enters glass; bends towards normal; wavelength decreases; frequency stays the same; angle of refraction < angle of incidence" },
  { id:"phy-wav-005", board:"AQA", subject:"physics", year:2022, series:"June", paper:"Paper 1", tier:"Higher", questionNum:"35", marks:5, topic:"Waves", stage:"gcse", yearGroups:[10,11], text:"Explain total internal reflection and state the conditions needed for it to occur.", commandWord:"Explain", answerLines:5, markScheme:"Occurs when light travels from denser to less dense medium; angle of incidence must exceed critical angle; at critical angle: refracted ray travels along boundary; above critical angle: all light reflected internally; used in optical fibres, periscopes, diamonds" },
  { id:"phy-wav-006", board:"OCR", subject:"physics", year:2023, series:"June", paper:"Paper 1", tier:"Foundation", questionNum:"36", marks:2, topic:"Waves", stage:"gcse", yearGroups:[9,10,11], text:"Name the seven types of electromagnetic radiation in order of increasing frequency.", commandWord:"Name", answerLines:2, markScheme:"Radio waves, microwaves, infrared, visible light, ultraviolet, X-rays, gamma rays" },
  { id:"phy-wav-007", board:"AQA", subject:"physics", year:2024, series:"June", paper:"Paper 1", tier:"Higher", questionNum:"37", marks:4, topic:"Waves", stage:"gcse", yearGroups:[10,11], text:"Explain how ultrasound is used in medical imaging.", commandWord:"Explain", answerLines:5, markScheme:"High frequency sound waves (above 20 kHz) transmitted into body; reflected at boundaries between different tissues; time taken for echo to return measured; distance calculated using d = v × t/2; image built up from reflected pulses; non-ionising so safe" },
  { id:"phy-wav-008", board:"Edexcel", subject:"physics", year:2024, series:"June", paper:"Paper 1", tier:"Foundation", questionNum:"38", marks:3, topic:"Waves", stage:"gcse", yearGroups:[9,10,11], text:"Calculate the wavelength of a radio wave with frequency 100 MHz. (Speed of light = 3 × 10⁸ m/s)", commandWord:"Calculate", answerLines:3, markScheme:"λ = v/f = (3 × 10⁸) / (100 × 10⁶) = 3 m" },
  { id:"phy-wav-009", board:"AQA", subject:"physics", year:2023, series:"November", paper:"Paper 1", tier:"Foundation", questionNum:"39", marks:2, topic:"Waves", stage:"gcse", yearGroups:[9,10,11], text:"State two uses of X-rays and two uses of gamma rays.", commandWord:"State", answerLines:2, markScheme:"X-rays: medical imaging, security scanning. Gamma rays: treating cancer (radiotherapy), sterilising medical equipment" },
  { id:"phy-wav-010", board:"AQA", subject:"physics", year:2019, series:"June", paper:"Paper 1", tier:"Higher", questionNum:"40", marks:5, topic:"Waves", stage:"gcse", yearGroups:[10,11], text:"Explain the Doppler effect and describe how it can be used to determine the speed of a moving object.", commandWord:"Explain", answerLines:6, markScheme:"When source moves towards observer: waves compressed; higher frequency/shorter wavelength; higher pitch. When source moves away: waves stretched; lower frequency/longer wavelength; lower pitch. Used in speed cameras (radar), astronomy (redshift/blueshift)" },

  // ─── ENERGY ───────────────────────────────────────────────────────────────
  { id:"phy-ene-001", board:"AQA", subject:"physics", year:2023, series:"June", paper:"Paper 1", tier:"Foundation", questionNum:"41", marks:3, topic:"Energy", stage:"gcse", yearGroups:[9,10,11], text:"A ball of mass 2 kg is held at a height of 5 m above the ground. Calculate its gravitational potential energy. (g = 10 N/kg)", commandWord:"Calculate", answerLines:3, markScheme:"GPE = mgh = 2 × 10 × 5 = 100 J" },
  { id:"phy-ene-002", board:"AQA", subject:"physics", year:2023, series:"June", paper:"Paper 1", tier:"Higher", questionNum:"42", marks:4, topic:"Energy", stage:"gcse", yearGroups:[10,11], text:"A 1500 kg car is travelling at 20 m/s. Calculate its kinetic energy. If the car brakes to a stop, calculate the work done by the brakes.", commandWord:"Calculate", answerLines:4, markScheme:"KE = ½mv² = ½ × 1500 × 400 = 300 000 J; Work done by brakes = 300 000 J (energy conserved)" },
  { id:"phy-ene-003", board:"Edexcel", subject:"physics", year:2023, series:"June", paper:"Paper 1", tier:"Foundation", questionNum:"43", marks:3, topic:"Energy", stage:"gcse", yearGroups:[9,10,11], text:"Explain what is meant by the efficiency of a device and give the formula.", commandWord:"Explain", answerLines:3, markScheme:"Efficiency = useful energy output / total energy input (× 100%); no device is 100% efficient; energy is always wasted (usually as heat)" },
  { id:"phy-ene-004", board:"AQA", subject:"physics", year:2022, series:"June", paper:"Paper 1", tier:"Foundation", questionNum:"44", marks:3, topic:"Energy", stage:"gcse", yearGroups:[9,10,11], text:"A motor has an efficiency of 80%. It uses 500 J of electrical energy. Calculate the useful energy output.", commandWord:"Calculate", answerLines:3, markScheme:"Useful output = efficiency × input = 0.80 × 500 = 400 J" },
  { id:"phy-ene-005", board:"AQA", subject:"physics", year:2022, series:"June", paper:"Paper 1", tier:"Higher", questionNum:"45", marks:5, topic:"Energy", stage:"gcse", yearGroups:[10,11], text:"Explain the advantages and disadvantages of renewable energy sources compared to fossil fuels.", commandWord:"Explain", answerLines:6, markScheme:"Renewable advantages: no CO₂ emissions; sustainable; free fuel; reduces dependence on fossil fuels. Disadvantages: intermittent (wind/solar); high initial cost; visual impact; may harm wildlife. Fossil fuels: reliable; high energy density; but finite; produce CO₂; contribute to climate change" },
  { id:"phy-ene-006", board:"OCR", subject:"physics", year:2023, series:"June", paper:"Paper 1", tier:"Foundation", questionNum:"46", marks:2, topic:"Energy", stage:"gcse", yearGroups:[9,10,11], text:"State the law of conservation of energy.", commandWord:"State", answerLines:2, markScheme:"Energy cannot be created or destroyed; it can only be transferred from one form to another; total energy remains constant" },
  { id:"phy-ene-007", board:"AQA", subject:"physics", year:2024, series:"June", paper:"Paper 1", tier:"Higher", questionNum:"47", marks:4, topic:"Energy", stage:"gcse", yearGroups:[10,11], text:"A 60 W light bulb is used for 8 hours. Calculate the energy used in kWh and the cost at 28p per kWh.", commandWord:"Calculate", answerLines:4, markScheme:"Energy = 60 W × 8 h = 480 Wh = 0.48 kWh; Cost = 0.48 × 28p = 13.44p" },
  { id:"phy-ene-008", board:"Edexcel", subject:"physics", year:2024, series:"June", paper:"Paper 1", tier:"Foundation", questionNum:"48", marks:3, topic:"Energy", stage:"gcse", yearGroups:[9,10,11], text:"Describe the energy transfers that take place when a ball is thrown upwards and falls back down.", commandWord:"Describe", answerLines:3, markScheme:"Thrown up: kinetic energy → gravitational potential energy; at top: maximum GPE, minimum KE; falling: GPE → KE; hits ground: KE → sound and heat (inelastic collision)" },
  { id:"phy-ene-009", board:"AQA", subject:"physics", year:2023, series:"November", paper:"Paper 1", tier:"Foundation", questionNum:"49", marks:2, topic:"Energy", stage:"gcse", yearGroups:[9,10,11], text:"Name four renewable energy sources.", commandWord:"Name", answerLines:2, markScheme:"Any four from: solar, wind, hydroelectric, tidal, wave, geothermal, biomass" },
  { id:"phy-ene-010", board:"AQA", subject:"physics", year:2019, series:"June", paper:"Paper 1", tier:"Higher", questionNum:"50", marks:5, topic:"Energy", stage:"gcse", yearGroups:[10,11], text:"Explain how insulating a house reduces energy consumption. Include the role of conduction, convection and radiation.", commandWord:"Explain", answerLines:6, markScheme:"Loft insulation: reduces conduction through ceiling; cavity wall insulation: reduces convection in air gap; double glazing: reduces conduction through windows; draught proofing: reduces convection; reflective foil: reduces radiation; all reduce heat loss; less energy needed for heating" },

  // ─── MAGNETISM AND ELECTROMAGNETISM ───────────────────────────────────────
  { id:"phy-mag-001", board:"AQA", subject:"physics", year:2023, series:"June", paper:"Paper 2", tier:"Foundation", questionNum:"51", marks:2, topic:"Magnetism", stage:"gcse", yearGroups:[9,10,11], text:"Describe the magnetic field pattern around a bar magnet.", commandWord:"Describe", answerLines:2, markScheme:"Field lines go from north to south pole outside magnet; closer together near poles (stronger field); arrows point from N to S; field lines never cross" },
  { id:"phy-mag-002", board:"AQA", subject:"physics", year:2023, series:"June", paper:"Paper 2", tier:"Higher", questionNum:"52", marks:4, topic:"Magnetism", stage:"gcse", yearGroups:[10,11], text:"Explain how an electric motor works. Include the role of the commutator.", commandWord:"Explain", answerLines:5, markScheme:"Current-carrying coil in magnetic field; force on coil (Fleming's left-hand rule); coil rotates; commutator reverses current direction every half turn; keeps coil rotating in same direction; split-ring commutator; brushes maintain contact" },
  { id:"phy-mag-003", board:"Edexcel", subject:"physics", year:2023, series:"June", paper:"Paper 2", tier:"Foundation", questionNum:"53", marks:3, topic:"Magnetism", stage:"gcse", yearGroups:[9,10,11], text:"Describe how to make an electromagnet and state two ways to increase its strength.", commandWord:"Describe", answerLines:3, markScheme:"Coil of wire (solenoid) wrapped around iron core; current passed through wire; produces magnetic field. Increase strength: increase current; increase number of turns; use iron core (not air)" },
  { id:"phy-mag-004", board:"AQA", subject:"physics", year:2022, series:"June", paper:"Paper 2", tier:"Higher", questionNum:"54", marks:5, topic:"Magnetism", stage:"gcse", yearGroups:[10,11], text:"Explain how electromagnetic induction works and how it is used in a generator.", commandWord:"Explain", answerLines:6, markScheme:"When a conductor moves through a magnetic field (or field changes), an EMF is induced; Faraday's law: EMF proportional to rate of change of flux; Lenz's law: induced current opposes change; generator: coil rotates in magnetic field; EMF induced; AC produced; slip rings maintain contact; used in power stations" },
  { id:"phy-mag-005", board:"OCR", subject:"physics", year:2023, series:"June", paper:"Paper 2", tier:"Foundation", questionNum:"55", marks:3, topic:"Magnetism", stage:"gcse", yearGroups:[9,10,11], text:"State Fleming's left-hand rule and explain what each finger represents.", commandWord:"State", answerLines:3, markScheme:"Thumb: direction of Force (motion); First finger: direction of magnetic Field; Second finger: direction of Current; used to find direction of force on current-carrying conductor in magnetic field" },
  { id:"phy-mag-006", board:"AQA", subject:"physics", year:2024, series:"June", paper:"Paper 2", tier:"Higher", questionNum:"56", marks:4, topic:"Magnetism", stage:"gcse", yearGroups:[10,11], text:"A wire carrying a current of 5 A is placed in a magnetic field of flux density 0.2 T. The length of wire in the field is 0.3 m. Calculate the force on the wire.", commandWord:"Calculate", answerLines:3, markScheme:"F = BIL = 0.2 × 5 × 0.3 = 0.3 N" },
  { id:"phy-mag-007", board:"Edexcel", subject:"physics", year:2024, series:"June", paper:"Paper 2", tier:"Foundation", questionNum:"57", marks:3, topic:"Magnetism", stage:"gcse", yearGroups:[9,10,11], text:"Explain the difference between a permanent magnet and an induced magnet.", commandWord:"Explain", answerLines:3, markScheme:"Permanent magnet: always magnetic; retains magnetism; e.g. steel. Induced magnet: only magnetic when near a permanent magnet; loses magnetism when removed; e.g. iron" },
  { id:"phy-mag-008", board:"AQA", subject:"physics", year:2023, series:"November", paper:"Paper 2", tier:"Higher", questionNum:"58", marks:4, topic:"Magnetism", stage:"gcse", yearGroups:[10,11], text:"Explain how a loudspeaker works.", commandWord:"Explain", answerLines:5, markScheme:"Alternating current passes through coil; coil is in magnetic field of permanent magnet; force on coil changes direction with AC; coil vibrates; cone attached to coil vibrates; produces sound waves; frequency of sound = frequency of AC" },
  { id:"phy-mag-009", board:"AQA", subject:"physics", year:2019, series:"June", paper:"Paper 2", tier:"Foundation", questionNum:"59", marks:2, topic:"Magnetism", stage:"gcse", yearGroups:[9,10,11], text:"State two differences between a hard magnetic material and a soft magnetic material.", commandWord:"State", answerLines:2, markScheme:"Hard: difficult to magnetise/demagnetise; retains magnetism; e.g. steel; used for permanent magnets. Soft: easy to magnetise/demagnetise; loses magnetism easily; e.g. iron; used for electromagnets" },
  { id:"phy-mag-010", board:"Edexcel", subject:"physics", year:2022, series:"June", paper:"Paper 2", tier:"Higher", questionNum:"60", marks:5, topic:"Magnetism", stage:"gcse", yearGroups:[10,11], text:"Explain how a step-up transformer works. Include the equation relating turns ratio to voltage ratio.", commandWord:"Explain", answerLines:5, markScheme:"AC in primary coil; creates changing magnetic field in iron core; changing flux induces EMF in secondary coil; more turns on secondary than primary; higher voltage output; Vs/Vp = Ns/Np; used to increase voltage for transmission" },

  // ─── ATOMIC AND NUCLEAR PHYSICS ───────────────────────────────────────────
  { id:"phy-nuc-001", board:"AQA", subject:"physics", year:2023, series:"June", paper:"Paper 2", tier:"Foundation", questionNum:"61", marks:3, topic:"Atomic and Nuclear Physics", stage:"gcse", yearGroups:[9,10,11], text:"Name the three types of nuclear radiation and state the charge of each.", commandWord:"Name", answerLines:3, markScheme:"Alpha (α): charge +2; Beta (β): charge −1; Gamma (γ): no charge (electromagnetic radiation)" },
  { id:"phy-nuc-002", board:"AQA", subject:"physics", year:2023, series:"June", paper:"Paper 2", tier:"Higher", questionNum:"62", marks:4, topic:"Atomic and Nuclear Physics", stage:"gcse", yearGroups:[10,11], text:"Compare the penetrating power and ionising ability of alpha, beta and gamma radiation.", commandWord:"Compare", answerLines:5, markScheme:"Alpha: stopped by paper/skin; most ionising; travels few cm in air. Beta: stopped by few mm aluminium; moderately ionising; travels metres in air. Gamma: reduced by thick lead/concrete; least ionising; travels very long distances" },
  { id:"phy-nuc-003", board:"Edexcel", subject:"physics", year:2023, series:"June", paper:"Paper 2", tier:"Foundation", questionNum:"63", marks:3, topic:"Atomic and Nuclear Physics", stage:"gcse", yearGroups:[9,10,11], text:"What is meant by the half-life of a radioactive substance?", commandWord:"Define", answerLines:2, markScheme:"The time taken for half the radioactive nuclei in a sample to decay; or the time for the activity to halve" },
  { id:"phy-nuc-004", board:"AQA", subject:"physics", year:2022, series:"June", paper:"Paper 2", tier:"Higher", questionNum:"64", marks:4, topic:"Atomic and Nuclear Physics", stage:"gcse", yearGroups:[10,11], text:"A radioactive sample has an initial activity of 800 Bq. The half-life is 2 hours. Calculate the activity after 8 hours.", commandWord:"Calculate", answerLines:4, markScheme:"Number of half-lives = 8/2 = 4; Activity = 800 × (1/2)⁴ = 800/16 = 50 Bq" },
  { id:"phy-nuc-005", board:"AQA", subject:"physics", year:2022, series:"June", paper:"Paper 2", tier:"Foundation", questionNum:"65", marks:3, topic:"Atomic and Nuclear Physics", stage:"gcse", yearGroups:[9,10,11], text:"Describe what happens during alpha decay. Write the nuclear equation for the alpha decay of radium-226.", commandWord:"Describe", answerLines:3, markScheme:"Nucleus emits alpha particle (2 protons, 2 neutrons); mass number decreases by 4; atomic number decreases by 2; ²²⁶₈₈Ra → ²²²₈₆Rn + ⁴₂He" },
  { id:"phy-nuc-006", board:"OCR", subject:"physics", year:2023, series:"June", paper:"Paper 2", tier:"Higher", questionNum:"66", marks:5, topic:"Atomic and Nuclear Physics", stage:"gcse", yearGroups:[10,11], text:"Explain how nuclear fission is used in a nuclear power station to generate electricity.", commandWord:"Explain", answerLines:6, markScheme:"Uranium-235 nucleus absorbs neutron; becomes unstable; splits into two smaller nuclei; releases 2-3 neutrons; chain reaction; releases large amount of energy as heat; heat boils water; steam drives turbine; turbine drives generator; produces electricity" },
  { id:"phy-nuc-007", board:"AQA", subject:"physics", year:2024, series:"June", paper:"Paper 2", tier:"Foundation", questionNum:"67", marks:3, topic:"Atomic and Nuclear Physics", stage:"gcse", yearGroups:[9,10,11], text:"State three sources of background radiation.", commandWord:"State", answerLines:2, markScheme:"Any three from: radon gas; cosmic rays; rocks and soil; food and drink; medical procedures; nuclear weapons testing; nuclear industry" },
  { id:"phy-nuc-008", board:"Edexcel", subject:"physics", year:2024, series:"June", paper:"Paper 2", tier:"Higher", questionNum:"68", marks:4, topic:"Atomic and Nuclear Physics", stage:"gcse", yearGroups:[10,11], text:"Explain the difference between nuclear fission and nuclear fusion. State which releases more energy per kg of fuel.", commandWord:"Explain", answerLines:5, markScheme:"Fission: heavy nucleus splits into smaller nuclei; releases energy; used in nuclear power stations. Fusion: light nuclei combine to form heavier nucleus; releases more energy per kg; occurs in stars; requires very high temperature and pressure; fusion releases more energy per kg" },
  { id:"phy-nuc-009", board:"AQA", subject:"physics", year:2023, series:"November", paper:"Paper 2", tier:"Foundation", questionNum:"69", marks:2, topic:"Atomic and Nuclear Physics", stage:"gcse", yearGroups:[9,10,11], text:"What is meant by the term 'radioactive decay'?", commandWord:"Define", answerLines:2, markScheme:"The spontaneous emission of radiation from an unstable nucleus; random process; cannot be predicted for individual nucleus" },
  { id:"phy-nuc-010", board:"AQA", subject:"physics", year:2019, series:"June", paper:"Paper 2", tier:"Higher", questionNum:"70", marks:5, topic:"Atomic and Nuclear Physics", stage:"gcse", yearGroups:[10,11], text:"Describe the uses of radioactive isotopes in medicine. Include one diagnostic use and one therapeutic use.", commandWord:"Describe", answerLines:5, markScheme:"Diagnostic: technetium-99m used as tracer; gamma emitter; detected outside body; used in PET scans; shows organ function. Therapeutic: iodine-131 treats thyroid cancer; cobalt-60 used in radiotherapy; kills cancer cells; gamma radiation" },

  // ─── SPACE PHYSICS ────────────────────────────────────────────────────────
  { id:"phy-spa-001", board:"AQA", subject:"physics", year:2023, series:"June", paper:"Paper 2", tier:"Foundation", questionNum:"71", marks:3, topic:"Space Physics", stage:"gcse", yearGroups:[9,10,11], text:"Describe the life cycle of a star similar to the Sun.", commandWord:"Describe", answerLines:4, markScheme:"Nebula → protostar → main sequence star → red giant → planetary nebula → white dwarf → black dwarf; nuclear fusion of hydrogen in main sequence; helium fusion in red giant" },
  { id:"phy-spa-002", board:"AQA", subject:"physics", year:2023, series:"June", paper:"Paper 2", tier:"Higher", questionNum:"72", marks:4, topic:"Space Physics", stage:"gcse", yearGroups:[10,11], text:"Explain the evidence for the Big Bang theory.", commandWord:"Explain", answerLines:5, markScheme:"Redshift of distant galaxies shows universe expanding; cosmic microwave background radiation (CMBR) is remnant of early universe; abundance of light elements (hydrogen and helium) matches predictions; Hubble's law: recession speed proportional to distance" },
  { id:"phy-spa-003", board:"Edexcel", subject:"physics", year:2023, series:"June", paper:"Paper 2", tier:"Foundation", questionNum:"73", marks:3, topic:"Space Physics", stage:"gcse", yearGroups:[9,10,11], text:"Explain what is meant by a light year.", commandWord:"Explain", answerLines:2, markScheme:"The distance light travels in one year; approximately 9.5 × 10¹⁵ m; used to measure distances in space" },
  { id:"phy-spa-004", board:"AQA", subject:"physics", year:2022, series:"June", paper:"Paper 2", tier:"Higher", questionNum:"74", marks:5, topic:"Space Physics", stage:"gcse", yearGroups:[10,11], text:"Explain how the redshift of galaxies provides evidence that the universe is expanding.", commandWord:"Explain", answerLines:5, markScheme:"Galaxies moving away from us; light waves stretched; wavelength increases; shift towards red end of spectrum; more distant galaxies have greater redshift; moving faster; universe expanding in all directions; consistent with Big Bang theory" },
  { id:"phy-spa-005", board:"OCR", subject:"physics", year:2023, series:"June", paper:"Paper 2", tier:"Foundation", questionNum:"75", marks:3, topic:"Space Physics", stage:"gcse", yearGroups:[9,10,11], text:"Describe the life cycle of a massive star (much larger than the Sun).", commandWord:"Describe", answerLines:4, markScheme:"Nebula → protostar → main sequence star → red supergiant → supernova → neutron star or black hole (depending on mass)" },

  // ─── ADDITIONAL PHYSICS QUESTIONS ─────────────────────────────────────────
  { id:"phy-add-001", board:"AQA", subject:"physics", year:2023, series:"June", paper:"Paper 1", tier:"Foundation", questionNum:"76", marks:3, topic:"Forces", stage:"gcse", yearGroups:[9,10,11], text:"A force of 200 N acts on an area of 0.04 m². Calculate the pressure.", commandWord:"Calculate", answerLines:3, markScheme:"P = F/A = 200/0.04 = 5000 Pa" },
  { id:"phy-add-002", board:"AQA", subject:"physics", year:2023, series:"June", paper:"Paper 1", tier:"Higher", questionNum:"77", marks:4, topic:"Forces", stage:"gcse", yearGroups:[10,11], text:"Explain the difference between speed and velocity, and between distance and displacement.", commandWord:"Explain", answerLines:4, markScheme:"Speed: scalar, magnitude only; velocity: vector, magnitude and direction. Distance: scalar, total path length; displacement: vector, straight line from start to end" },
  { id:"phy-add-003", board:"Edexcel", subject:"physics", year:2023, series:"June", paper:"Paper 1", tier:"Foundation", questionNum:"78", marks:3, topic:"Energy", stage:"gcse", yearGroups:[9,10,11], text:"A student pushes a box with a force of 50 N over a distance of 8 m. Calculate the work done.", commandWord:"Calculate", answerLines:3, markScheme:"W = Fd = 50 × 8 = 400 J" },
  { id:"phy-add-004", board:"AQA", subject:"physics", year:2022, series:"June", paper:"Paper 1", tier:"Higher", questionNum:"79", marks:5, topic:"Waves", stage:"gcse", yearGroups:[10,11], text:"Explain how seismic waves can be used to investigate the internal structure of the Earth.", commandWord:"Explain", answerLines:6, markScheme:"P-waves (longitudinal) travel through solids and liquids; S-waves (transverse) only travel through solids; S-waves do not reach far side of Earth → liquid outer core; P-waves refract at boundaries; shadow zones; different wave speeds in different layers; allows mapping of core, mantle, crust" },
  { id:"phy-add-005", board:"AQA", subject:"physics", year:2024, series:"June", paper:"Paper 2", tier:"Foundation", questionNum:"80", marks:3, topic:"Electricity", stage:"gcse", yearGroups:[9,10,11], text:"Explain why birds can sit on high voltage power lines without being electrocuted.", commandWord:"Explain", answerLines:3, markScheme:"Birds sit on one wire only; no complete circuit; current needs a path from high voltage to lower voltage; bird's feet are at same potential; no potential difference across bird; no current flows through bird" },
  { id:"phy-add-006", board:"OCR", subject:"physics", year:2023, series:"June", paper:"Paper 1", tier:"Higher", questionNum:"81", marks:4, topic:"Forces", stage:"gcse", yearGroups:[10,11], text:"A rocket of mass 5000 kg has a thrust of 80 000 N. Calculate the initial acceleration. (g = 10 m/s²)", commandWord:"Calculate", answerLines:4, markScheme:"Weight = 5000 × 10 = 50 000 N; Resultant force = 80 000 − 50 000 = 30 000 N; a = F/m = 30 000/5000 = 6 m/s²" },
  { id:"phy-add-007", board:"AQA", subject:"physics", year:2022, series:"November", paper:"Paper 1", tier:"Foundation", questionNum:"82", marks:3, topic:"Waves", stage:"gcse", yearGroups:[9,10,11], text:"Describe how infrared radiation is used in a TV remote control.", commandWord:"Describe", answerLines:3, markScheme:"Remote control emits infrared radiation; pulses of IR carry coded signal; IR detector in TV receives signal; decoded by TV; changes channel/volume etc." },
  { id:"phy-add-008", board:"Edexcel", subject:"physics", year:2023, series:"November", paper:"Paper 2", tier:"Higher", questionNum:"83", marks:4, topic:"Atomic and Nuclear Physics", stage:"gcse", yearGroups:[10,11], text:"Explain why nuclear power stations do not contribute to greenhouse gas emissions during operation, but have other environmental concerns.", commandWord:"Explain", answerLines:5, markScheme:"No combustion; no CO₂ produced during operation; but: radioactive waste produced; long-lived waste requires safe storage for thousands of years; risk of accidents (e.g. Chernobyl, Fukushima); uranium mining has environmental impact; decommissioning is expensive" },
  { id:"phy-add-009", board:"AQA", subject:"physics", year:2024, series:"June", paper:"Paper 1", tier:"Higher", questionNum:"84", marks:5, topic:"Energy", stage:"gcse", yearGroups:[10,11], text:"A pendulum of length 1 m swings from one side to the other. The bob has mass 0.5 kg and rises 0.1 m above its lowest point. Calculate the maximum speed of the bob. (g = 10 m/s²)", commandWord:"Calculate", answerLines:5, markScheme:"GPE at top = KE at bottom; mgh = ½mv²; 0.5 × 10 × 0.1 = ½ × 0.5 × v²; 0.5 = 0.25v²; v² = 2; v = √2 ≈ 1.41 m/s" },
  { id:"phy-add-010", board:"AQA", subject:"physics", year:2023, series:"June", paper:"Paper 2", tier:"Foundation", questionNum:"85", marks:3, topic:"Magnetism", stage:"gcse", yearGroups:[9,10,11], text:"Describe how to demagnetise a permanent magnet.", commandWord:"Describe", answerLines:3, markScheme:"Heat the magnet above Curie temperature; or strike repeatedly with a hammer; or place in alternating magnetic field (AC demagnetiser); disrupts alignment of magnetic domains" },
  { id:"phy-add-011", board:"AQA", subject:"physics", year:2022, series:"June", paper:"Paper 1", tier:"Foundation", questionNum:"86", marks:2, topic:"Forces", stage:"gcse", yearGroups:[9,10,11], text:"What is the difference between mass and weight?", commandWord:"Explain", answerLines:2, markScheme:"Mass: amount of matter in an object; measured in kg; constant everywhere. Weight: gravitational force on an object; measured in N; varies with gravitational field strength" },
  { id:"phy-add-012", board:"Edexcel", subject:"physics", year:2022, series:"June", paper:"Paper 1", tier:"Higher", questionNum:"87", marks:4, topic:"Waves", stage:"gcse", yearGroups:[10,11], text:"Explain how optical fibres use total internal reflection to transmit data.", commandWord:"Explain", answerLines:4, markScheme:"Light enters glass fibre at small angle; hits boundary at angle greater than critical angle; total internal reflection; light bounces along fibre; reaches other end; used for internet/telephone; advantages: fast, no signal loss, secure" },
  { id:"phy-add-013", board:"OCR", subject:"physics", year:2024, series:"June", paper:"Paper 2", tier:"Higher", questionNum:"88", marks:5, topic:"Electricity", stage:"gcse", yearGroups:[10,11], text:"A student investigates how resistance of a wire depends on its length. Describe how the student should carry out this investigation and what results they would expect.", commandWord:"Describe", answerLines:6, markScheme:"Connect wire in circuit with ammeter and voltmeter; measure current and voltage for different lengths; calculate R = V/I; keep cross-sectional area and material constant; expect: resistance proportional to length; R ∝ L; longer wire = higher resistance" },
  { id:"phy-add-014", board:"AQA", subject:"physics", year:2021, series:"November", paper:"Paper 1", tier:"Foundation", questionNum:"89", marks:3, topic:"Energy", stage:"gcse", yearGroups:[9,10,11], text:"Explain why a car engine is less than 100% efficient.", commandWord:"Explain", answerLines:3, markScheme:"Not all energy from fuel is converted to kinetic energy; energy wasted as heat in engine; energy lost to friction; energy used to overcome air resistance; sound energy produced; no engine can be 100% efficient (second law of thermodynamics)" },
  { id:"phy-add-015", board:"AQA", subject:"physics", year:2020, series:"November", paper:"Paper 2", tier:"Higher", questionNum:"90", marks:5, topic:"Space Physics", stage:"gcse", yearGroups:[10,11], text:"Explain how the Sun produces energy through nuclear fusion.", commandWord:"Explain", answerLines:5, markScheme:"Hydrogen nuclei (protons) fuse together; extremely high temperature and pressure in core; protons overcome electrostatic repulsion; helium nucleus formed; mass of products less than mass of reactants; mass converted to energy (E = mc²); enormous energy released" },
  { id:"phy-add-016", board:"AQA", subject:"physics", year:2023, series:"June", paper:"Paper 1", tier:"Higher", questionNum:"91", marks:4, topic:"Forces", stage:"gcse", yearGroups:[10,11], text:"A car of mass 800 kg is travelling at 25 m/s. The driver applies the brakes with a force of 4000 N. Calculate the deceleration and the distance needed to stop.", commandWord:"Calculate", answerLines:5, markScheme:"a = F/m = 4000/800 = 5 m/s²; v² = u² + 2as; 0 = 625 − 2(5)s; s = 625/10 = 62.5 m" },
  { id:"phy-add-017", board:"Edexcel", subject:"physics", year:2024, series:"June", paper:"Paper 2", tier:"Foundation", questionNum:"92", marks:3, topic:"Atomic and Nuclear Physics", stage:"gcse", yearGroups:[9,10,11], text:"Explain why radioactive decay is described as a random process.", commandWord:"Explain", answerLines:3, markScheme:"Cannot predict when any individual nucleus will decay; each nucleus has same probability of decaying in a given time; not affected by temperature, pressure or chemical state; only statistical predictions possible for large numbers" },
  { id:"phy-add-018", board:"AQA", subject:"physics", year:2023, series:"November", paper:"Paper 1", tier:"Higher", questionNum:"93", marks:4, topic:"Electricity", stage:"gcse", yearGroups:[10,11], text:"Explain why the resistance of a metal wire increases with temperature.", commandWord:"Explain", answerLines:4, markScheme:"At higher temperature: metal ions vibrate more; electrons collide more frequently with ions; more resistance to electron flow; resistance increases; opposite to semiconductors" },
  { id:"phy-add-019", board:"OCR", subject:"physics", year:2023, series:"June", paper:"Paper 1", tier:"Foundation", questionNum:"94", marks:3, topic:"Waves", stage:"gcse", yearGroups:[9,10,11], text:"Describe how sound waves are produced and how they travel through air.", commandWord:"Describe", answerLines:3, markScheme:"Vibrating object creates compressions and rarefactions in air; longitudinal wave; particles vibrate parallel to direction of travel; energy transferred through medium; cannot travel through vacuum" },
  { id:"phy-add-020", board:"AQA", subject:"physics", year:2022, series:"June", paper:"Paper 2", tier:"Higher", questionNum:"95", marks:5, topic:"Magnetism", stage:"gcse", yearGroups:[10,11], text:"Explain how a microphone converts sound into electrical signals.", commandWord:"Explain", answerLines:5, markScheme:"Sound waves cause diaphragm to vibrate; diaphragm attached to coil; coil moves in magnetic field; electromagnetic induction; changing flux induces EMF; alternating current produced; frequency and amplitude match sound wave" },
  { id:"phy-add-021", board:"AQA", subject:"physics", year:2024, series:"June", paper:"Paper 1", tier:"Foundation", questionNum:"96", marks:3, topic:"Forces", stage:"gcse", yearGroups:[9,10,11], text:"A car travels 150 km in 2 hours. Calculate the average speed in m/s.", commandWord:"Calculate", answerLines:3, markScheme:"Speed = distance/time = 150 000/7200 = 20.8 m/s" },
  { id:"phy-add-022", board:"Edexcel", subject:"physics", year:2023, series:"June", paper:"Paper 1", tier:"Higher", questionNum:"97", marks:4, topic:"Energy", stage:"gcse", yearGroups:[10,11], text:"Explain how a heat pump works and why it can have a coefficient of performance greater than 1.", commandWord:"Explain", answerLines:5, markScheme:"Heat pump moves heat from cold reservoir to warm reservoir; uses electrical energy; transfers more heat energy than electrical energy used; COP = heat output / electrical input; COP > 1 because heat is moved, not generated; more efficient than electric heater" },
  { id:"phy-add-023", board:"AQA", subject:"physics", year:2022, series:"November", paper:"Paper 2", tier:"Foundation", questionNum:"98", marks:3, topic:"Atomic and Nuclear Physics", stage:"gcse", yearGroups:[9,10,11], text:"Describe how a Geiger-Müller tube detects radiation.", commandWord:"Describe", answerLines:3, markScheme:"Tube contains low pressure gas; radiation ionises gas; ions accelerate to electrodes; current pulse produced; detected by counter; each pulse = one count" },
  { id:"phy-add-024", board:"OCR", subject:"physics", year:2024, series:"June", paper:"Paper 1", tier:"Higher", questionNum:"99", marks:4, topic:"Waves", stage:"gcse", yearGroups:[10,11], text:"Explain how a convex lens forms a real image. Include the concept of focal length.", commandWord:"Explain", answerLines:5, markScheme:"Parallel rays of light refracted by lens; converge at focal point; focal length = distance from lens to focal point; object beyond focal point: real, inverted image formed; object closer than focal point: virtual, upright, magnified image" },
  { id:"phy-add-025", board:"AQA", subject:"physics", year:2021, series:"November", paper:"Paper 2", tier:"Higher", questionNum:"100", marks:5, topic:"Space Physics", stage:"gcse", yearGroups:[10,11], text:"Explain the difference between the geocentric and heliocentric models of the solar system and describe the evidence that led to the acceptance of the heliocentric model.", commandWord:"Explain", answerLines:6, markScheme:"Geocentric: Earth at centre; planets orbit Earth; Ptolemy. Heliocentric: Sun at centre; planets orbit Sun; Copernicus/Galileo. Evidence: Galileo's observations of Jupiter's moons; phases of Venus; retrograde motion of planets; parallax of stars; Kepler's laws; Newton's gravity" },
];

export default physicsQuestions;
