/**
 * OTHER SUBJECTS QUESTION BANK — History, Geography, Computer Science, etc.
 * Sources: AQA, Edexcel, OCR GCSE past papers
 */
import type { PastPaperQuestion } from "./pastPaperQuestions";

export const historyQuestions: PastPaperQuestion[] = [
  // ─── HISTORY ──────────────────────────────────────────────────────────────
  { id:"hist-001", board:"AQA", subject:"history", year:2023, series:"June", paper:"Paper 1", tier:"Foundation", questionNum:"1", marks:4, topic:"Medicine Through Time", stage:"gcse", yearGroups:[9,10,11], text:"Describe two features of medical treatment in the Middle Ages.", commandWord:"Describe", answerLines:4, markScheme:"Two features, each with supporting detail; e.g. use of herbs/plants; bleeding/purging; prayer and religion; four humours theory; apothecaries; barber surgeons" },
  { id:"hist-002", board:"AQA", subject:"history", year:2023, series:"June", paper:"Paper 1", tier:"Foundation", questionNum:"2", marks:12, topic:"Medicine Through Time", stage:"gcse", yearGroups:[9,10,11], text:"Explain why the Renaissance was an important period of change in medicine. You may use the following in your answer: Vesalius; Harvey. You must also use information of your own.", commandWord:"Explain", answerLines:16, markScheme:"Level 4 (10–12): complex explanation; Level 3 (7–9): developed explanation; Level 2 (4–6): simple explanation; Level 1 (1–3): basic explanation" },
  { id:"hist-003", board:"AQA", subject:"history", year:2023, series:"June", paper:"Paper 1", tier:"Foundation", questionNum:"3", marks:16, topic:"Medicine Through Time", stage:"gcse", yearGroups:[9,10,11], text:"'The most important factor in the development of medicine in the 19th century was the work of Louis Pasteur.' How far do you agree with this statement? Explain your answer.", commandWord:"Evaluate", answerLines:20, markScheme:"Level 4 (13–16): sustained judgement; complex explanation; Level 3 (9–12): developed judgement; Level 2 (5–8): simple judgement; Level 1 (1–4): basic judgement" },
  { id:"hist-004", board:"AQA", subject:"history", year:2023, series:"June", paper:"Paper 2", tier:"Foundation", questionNum:"1", marks:4, topic:"Elizabethan England", stage:"gcse", yearGroups:[9,10,11], text:"Describe two features of the Elizabethan Poor Law.", commandWord:"Describe", answerLines:4, markScheme:"Two features with supporting detail; e.g. distinction between deserving and undeserving poor; workhouses; overseers of the poor; parish responsibility; punishment of vagabonds" },
  { id:"hist-005", board:"AQA", subject:"history", year:2023, series:"June", paper:"Paper 2", tier:"Foundation", questionNum:"2", marks:12, topic:"Elizabethan England", stage:"gcse", yearGroups:[9,10,11], text:"Explain why Elizabeth I faced threats to her rule in the 1580s. You may use the following in your answer: Mary Queen of Scots; the Spanish Armada. You must also use information of your own.", commandWord:"Explain", answerLines:16, markScheme:"Level 4 (10–12): complex explanation; Level 3 (7–9): developed; Level 2 (4–6): simple; Level 1 (1–3): basic" },
  { id:"hist-006", board:"Edexcel", subject:"history", year:2023, series:"June", paper:"Paper 1", tier:"Foundation", questionNum:"1", marks:4, topic:"Crime and Punishment", stage:"gcse", yearGroups:[9,10,11], text:"Give two examples of crimes that were considered serious in the Middle Ages.", commandWord:"Give", answerLines:2, markScheme:"Any two from: heresy; treason; murder; theft of large amounts; poaching; witchcraft" },
  { id:"hist-007", board:"Edexcel", subject:"history", year:2023, series:"June", paper:"Paper 1", tier:"Foundation", questionNum:"2", marks:8, topic:"Crime and Punishment", stage:"gcse", yearGroups:[9,10,11], text:"Explain why the role of the church was important in crime and punishment in the Middle Ages.", commandWord:"Explain", answerLines:10, markScheme:"Level 3 (7–8): developed explanation; Level 2 (4–6): simple explanation; Level 1 (1–3): basic" },
  { id:"hist-008", board:"AQA", subject:"history", year:2022, series:"June", paper:"Paper 1", tier:"Foundation", questionNum:"1", marks:4, topic:"Medicine Through Time", stage:"gcse", yearGroups:[9,10,11], text:"Describe two features of surgery in the 19th century.", commandWord:"Describe", answerLines:4, markScheme:"Two features with detail; e.g. development of anaesthetics (Simpson/chloroform); antiseptic surgery (Lister/carbolic acid); development of aseptic surgery; blood transfusions; improved understanding of anatomy" },
  { id:"hist-009", board:"AQA", subject:"history", year:2022, series:"June", paper:"Paper 2", tier:"Foundation", questionNum:"3", marks:16, topic:"Elizabethan England", stage:"gcse", yearGroups:[9,10,11], text:"'The main reason for the failure of the Spanish Armada in 1588 was English naval tactics.' How far do you agree with this statement? Explain your answer.", commandWord:"Evaluate", answerLines:20, markScheme:"Level 4 (13–16): sustained judgement; Level 3 (9–12): developed; Level 2 (5–8): simple; Level 1 (1–4): basic" },
  { id:"hist-010", board:"AQA", subject:"history", year:2024, series:"June", paper:"Paper 1", tier:"Foundation", questionNum:"2", marks:12, topic:"Medicine Through Time", stage:"gcse", yearGroups:[9,10,11], text:"Explain why the First World War was a turning point in the development of surgery. You may use the following in your answer: blood transfusions; plastic surgery. You must also use information of your own.", commandWord:"Explain", answerLines:16, markScheme:"Level 4 (10–12): complex explanation; Level 3 (7–9): developed; Level 2 (4–6): simple; Level 1 (1–3): basic" },
  { id:"hist-011", board:"AQA", subject:"history", year:2023, series:"June", paper:"Paper 3", tier:"Foundation", questionNum:"1", marks:4, topic:"Weimar and Nazi Germany", stage:"gcse", yearGroups:[9,10,11], text:"Describe two features of the Weimar Republic's constitution.", commandWord:"Describe", answerLines:4, markScheme:"Two features with detail; e.g. proportional representation; Bill of Rights; President's emergency powers (Article 48); Reichstag; coalition governments" },
  { id:"hist-012", board:"AQA", subject:"history", year:2023, series:"June", paper:"Paper 3", tier:"Foundation", questionNum:"2", marks:12, topic:"Weimar and Nazi Germany", stage:"gcse", yearGroups:[9,10,11], text:"Explain why the Weimar Republic faced problems in the years 1919–1923. You may use the following in your answer: the Treaty of Versailles; hyperinflation. You must also use information of your own.", commandWord:"Explain", answerLines:16, markScheme:"Level 4 (10–12): complex explanation; Level 3 (7–9): developed; Level 2 (4–6): simple; Level 1 (1–3): basic" },
  { id:"hist-013", board:"AQA", subject:"history", year:2023, series:"June", paper:"Paper 3", tier:"Foundation", questionNum:"3", marks:16, topic:"Weimar and Nazi Germany", stage:"gcse", yearGroups:[9,10,11], text:"'The main reason Hitler became Chancellor in January 1933 was the weakness of the Weimar Republic.' How far do you agree with this statement? Explain your answer.", commandWord:"Evaluate", answerLines:20, markScheme:"Level 4 (13–16): sustained judgement; Level 3 (9–12): developed; Level 2 (5–8): simple; Level 1 (1–4): basic" },
  { id:"hist-014", board:"Edexcel", subject:"history", year:2023, series:"June", paper:"Paper 3", tier:"Foundation", questionNum:"1", marks:3, topic:"Cold War", stage:"gcse", yearGroups:[9,10,11], text:"Give three reasons why tensions increased between the USA and USSR after 1945.", commandWord:"Give", answerLines:3, markScheme:"Any three from: ideological differences; nuclear arms race; Berlin Blockade; Korean War; NATO vs Warsaw Pact; espionage" },
  { id:"hist-015", board:"AQA", subject:"history", year:2019, series:"June", paper:"Paper 1", tier:"Foundation", questionNum:"3", marks:16, topic:"Medicine Through Time", stage:"gcse", yearGroups:[9,10,11], text:"'The most significant development in public health in Britain was the 1875 Public Health Act.' How far do you agree with this statement? Explain your answer.", commandWord:"Evaluate", answerLines:20, markScheme:"Level 4 (13–16): sustained judgement; Level 3 (9–12): developed; Level 2 (5–8): simple; Level 1 (1–4): basic" },
];

export const geographyQuestions: PastPaperQuestion[] = [
  // ─── GEOGRAPHY ────────────────────────────────────────────────────────────
  { id:"geo-001", board:"AQA", subject:"geography", year:2023, series:"June", paper:"Paper 1", tier:"Foundation", questionNum:"1", marks:2, topic:"Tectonic Hazards", stage:"gcse", yearGroups:[9,10,11], text:"State two effects of a volcanic eruption.", commandWord:"State", answerLines:2, markScheme:"Any two from: lava flows destroy buildings; ash clouds disrupt air travel; pyroclastic flows; lahars; destruction of farmland; loss of life; displacement of people" },
  { id:"geo-002", board:"AQA", subject:"geography", year:2023, series:"June", paper:"Paper 1", tier:"Foundation", questionNum:"2", marks:4, topic:"Tectonic Hazards", stage:"gcse", yearGroups:[9,10,11], text:"Explain two reasons why people continue to live near volcanoes.", commandWord:"Explain", answerLines:4, markScheme:"Two reasons with explanation; e.g. fertile soils for farming; geothermal energy; tourism; lack of money to move; historical/cultural attachment; infrequent eruptions" },
  { id:"geo-003", board:"AQA", subject:"geography", year:2023, series:"June", paper:"Paper 1", tier:"Foundation", questionNum:"3", marks:6, topic:"Tectonic Hazards", stage:"gcse", yearGroups:[9,10,11], text:"Explain how the responses to an earthquake differ between an HIC (High Income Country) and an LIC (Low Income Country).", commandWord:"Explain", answerLines:8, markScheme:"HIC: better emergency services; search and rescue teams; medical facilities; insurance; rebuilding quickly; early warning systems. LIC: limited resources; slower response; international aid needed; more deaths; slower rebuilding; less preparation" },
  { id:"geo-004", board:"AQA", subject:"geography", year:2023, series:"June", paper:"Paper 2", tier:"Foundation", questionNum:"1", marks:2, topic:"Urban Issues", stage:"gcse", yearGroups:[9,10,11], text:"Define the term 'urbanisation'.", commandWord:"Define", answerLines:2, markScheme:"The increase in the proportion of people living in urban areas; movement of people from rural to urban areas" },
  { id:"geo-005", board:"AQA", subject:"geography", year:2023, series:"June", paper:"Paper 2", tier:"Foundation", questionNum:"2", marks:4, topic:"Urban Issues", stage:"gcse", yearGroups:[9,10,11], text:"Explain two reasons why people migrate from rural areas to cities in LICs.", commandWord:"Explain", answerLines:4, markScheme:"Push factors: lack of jobs; poor services; drought/famine; mechanisation of farming. Pull factors: better employment; better services; higher wages; more opportunities" },
  { id:"geo-006", board:"AQA", subject:"geography", year:2023, series:"June", paper:"Paper 2", tier:"Foundation", questionNum:"3", marks:6, topic:"Urban Issues", stage:"gcse", yearGroups:[9,10,11], text:"Describe the challenges of living in a squatter settlement (shanty town).", commandWord:"Describe", answerLines:8, markScheme:"Lack of clean water; poor sanitation; overcrowding; lack of electricity; poor building quality; crime; disease; lack of schools/hospitals; insecure land tenure; pollution" },
  { id:"geo-007", board:"Edexcel", subject:"geography", year:2023, series:"June", paper:"Paper 1", tier:"Foundation", questionNum:"1", marks:3, topic:"Coasts", stage:"gcse", yearGroups:[9,10,11], text:"Describe the process of hydraulic action.", commandWord:"Describe", answerLines:3, markScheme:"Waves crash against cliff; air compressed into cracks; pressure builds; rock breaks away; repeated action weakens cliff; erosion occurs" },
  { id:"geo-008", board:"AQA", subject:"geography", year:2022, series:"June", paper:"Paper 1", tier:"Foundation", questionNum:"1", marks:2, topic:"Tectonic Hazards", stage:"gcse", yearGroups:[9,10,11], text:"Name the two types of tectonic plate.", commandWord:"Name", answerLines:2, markScheme:"Continental plates; oceanic plates" },
  { id:"geo-009", board:"AQA", subject:"geography", year:2022, series:"June", paper:"Paper 1", tier:"Foundation", questionNum:"2", marks:4, topic:"Tectonic Hazards", stage:"gcse", yearGroups:[9,10,11], text:"Explain how a tsunami is formed.", commandWord:"Explain", answerLines:5, markScheme:"Earthquake on ocean floor; seabed moves suddenly; water displaced; wave travels outward; wave grows as it approaches shallow water; reaches coast as huge wave" },
  { id:"geo-010", board:"AQA", subject:"geography", year:2024, series:"June", paper:"Paper 2", tier:"Foundation", questionNum:"1", marks:2, topic:"Development", stage:"gcse", yearGroups:[9,10,11], text:"Define the term 'Gross Domestic Product (GDP)'.", commandWord:"Define", answerLines:2, markScheme:"The total value of goods and services produced by a country in a year; measure of economic development; often expressed per capita" },
  { id:"geo-011", board:"AQA", subject:"geography", year:2023, series:"June", paper:"Paper 1", tier:"Higher", questionNum:"4", marks:9, topic:"Tectonic Hazards", stage:"gcse", yearGroups:[10,11], text:"Evaluate the effectiveness of different methods of predicting and preparing for tectonic hazards.", commandWord:"Evaluate", answerLines:12, markScheme:"Level 4 (8–9): detailed evaluation; balanced judgement; Level 3 (6–7): clear evaluation; Level 2 (3–5): some evaluation; Level 1 (1–2): basic points" },
  { id:"geo-012", board:"AQA", subject:"geography", year:2023, series:"June", paper:"Paper 2", tier:"Higher", questionNum:"4", marks:9, topic:"Urban Issues", stage:"gcse", yearGroups:[10,11], text:"Evaluate the success of urban regeneration projects in the UK.", commandWord:"Evaluate", answerLines:12, markScheme:"Level 4 (8–9): detailed evaluation; Level 3 (6–7): clear evaluation; Level 2 (3–5): some evaluation; Level 1 (1–2): basic" },
  { id:"geo-013", board:"Edexcel", subject:"geography", year:2023, series:"June", paper:"Paper 2", tier:"Foundation", questionNum:"2", marks:4, topic:"Development", stage:"gcse", yearGroups:[9,10,11], text:"Explain two limitations of using GDP per capita as a measure of development.", commandWord:"Explain", answerLines:4, markScheme:"Doesn't show inequality; doesn't measure quality of life; doesn't show environmental quality; doesn't show access to services; average hides differences within country" },
  { id:"geo-014", board:"AQA", subject:"geography", year:2022, series:"June", paper:"Paper 2", tier:"Foundation", questionNum:"3", marks:6, topic:"Development", stage:"gcse", yearGroups:[9,10,11], text:"Explain how fair trade can help to reduce the development gap.", commandWord:"Explain", answerLines:8, markScheme:"Farmers receive fair price; guaranteed minimum price; investment in community; better working conditions; education and healthcare; more stable income; reduces dependence on aid; empowers local communities" },
  { id:"geo-015", board:"AQA", subject:"geography", year:2019, series:"June", paper:"Paper 1", tier:"Higher", questionNum:"4", marks:9, topic:"Weather Hazards", stage:"gcse", yearGroups:[10,11], text:"Evaluate the extent to which climate change is responsible for the increasing frequency of extreme weather events.", commandWord:"Evaluate", answerLines:12, markScheme:"Level 4 (8–9): detailed evaluation; Level 3 (6–7): clear; Level 2 (3–5): some; Level 1 (1–2): basic" },
];

export const computerScienceQuestions: PastPaperQuestion[] = [
  // ─── COMPUTER SCIENCE ─────────────────────────────────────────────────────
  { id:"cs-001", board:"AQA", subject:"computer-science", year:2023, series:"June", paper:"Paper 1", tier:"Foundation", questionNum:"1", marks:2, topic:"Binary and Data Representation", stage:"gcse", yearGroups:[9,10,11], text:"Convert the binary number 10110101 to denary (decimal).", commandWord:"Convert", answerLines:3, markScheme:"128 + 32 + 16 + 4 + 1 = 181" },
  { id:"cs-002", board:"AQA", subject:"computer-science", year:2023, series:"June", paper:"Paper 1", tier:"Foundation", questionNum:"2", marks:3, topic:"Binary and Data Representation", stage:"gcse", yearGroups:[9,10,11], text:"Convert the denary number 75 to binary.", commandWord:"Convert", answerLines:3, markScheme:"64 + 8 + 2 + 1 = 75; binary: 01001011" },
  { id:"cs-003", board:"AQA", subject:"computer-science", year:2023, series:"June", paper:"Paper 1", tier:"Foundation", questionNum:"3", marks:3, topic:"Binary and Data Representation", stage:"gcse", yearGroups:[9,10,11], text:"Perform the binary addition: 01101010 + 00110101. Show your working.", commandWord:"Calculate", answerLines:4, markScheme:"01101010 + 00110101 = 10011111; carry shown correctly" },
  { id:"cs-004", board:"AQA", subject:"computer-science", year:2023, series:"June", paper:"Paper 1", tier:"Foundation", questionNum:"4", marks:2, topic:"Binary and Data Representation", stage:"gcse", yearGroups:[9,10,11], text:"What is the hexadecimal equivalent of the binary number 11001010?", commandWord:"Convert", answerLines:2, markScheme:"1100 = C; 1010 = A; answer: CA" },
  { id:"cs-005", board:"AQA", subject:"computer-science", year:2023, series:"June", paper:"Paper 1", tier:"Foundation", questionNum:"5", marks:3, topic:"Binary and Data Representation", stage:"gcse", yearGroups:[9,10,11], text:"A colour image is 800 × 600 pixels. Each pixel uses 24 bits of colour depth. Calculate the file size in megabytes.", commandWord:"Calculate", answerLines:4, markScheme:"800 × 600 × 24 = 11 520 000 bits; ÷ 8 = 1 440 000 bytes; ÷ 1 048 576 = 1.37 MB (accept 1.37–1.38)" },
  { id:"cs-006", board:"AQA", subject:"computer-science", year:2023, series:"June", paper:"Paper 1", tier:"Foundation", questionNum:"6", marks:4, topic:"Algorithms", stage:"gcse", yearGroups:[9,10,11], text:"Describe the bubble sort algorithm. State its time complexity in the worst case.", commandWord:"Describe", answerLines:5, markScheme:"Compare adjacent elements; swap if out of order; repeat passes; largest elements 'bubble' to end; continue until no swaps; O(n²) worst case" },
  { id:"cs-007", board:"AQA", subject:"computer-science", year:2023, series:"June", paper:"Paper 1", tier:"Foundation", questionNum:"7", marks:4, topic:"Algorithms", stage:"gcse", yearGroups:[9,10,11], text:"Describe the merge sort algorithm and explain why it is more efficient than bubble sort for large datasets.", commandWord:"Describe", answerLines:5, markScheme:"Divide list in half repeatedly; sort each half; merge sorted halves; O(n log n) time complexity; more efficient than O(n²) bubble sort for large n" },
  { id:"cs-008", board:"AQA", subject:"computer-science", year:2023, series:"June", paper:"Paper 2", tier:"Foundation", questionNum:"1", marks:3, topic:"Programming", stage:"gcse", yearGroups:[9,10,11], text:"Write a Python program that asks the user to enter a number and prints whether it is odd or even.", commandWord:"Write", answerLines:5, markScheme:"Input statement; if/else structure; modulo operator (% 2); correct output for odd and even; correct syntax" },
  { id:"cs-009", board:"AQA", subject:"computer-science", year:2023, series:"June", paper:"Paper 2", tier:"Foundation", questionNum:"2", marks:4, topic:"Programming", stage:"gcse", yearGroups:[9,10,11], text:"Write a Python function called 'factorial' that takes a positive integer n as a parameter and returns n! (n factorial). For example, factorial(5) should return 120.", commandWord:"Write", answerLines:6, markScheme:"Correct function definition; loop or recursion; correct calculation; returns correct value; handles base case" },
  { id:"cs-010", board:"AQA", subject:"computer-science", year:2023, series:"June", paper:"Paper 1", tier:"Foundation", questionNum:"8", marks:4, topic:"Networks", stage:"gcse", yearGroups:[9,10,11], text:"Describe the difference between a LAN and a WAN. Give one example of each.", commandWord:"Describe", answerLines:4, markScheme:"LAN: Local Area Network; covers small area (e.g. school, office); uses own infrastructure; e.g. school network. WAN: Wide Area Network; covers large area; uses third-party infrastructure; e.g. the internet" },
  { id:"cs-011", board:"AQA", subject:"computer-science", year:2023, series:"June", paper:"Paper 1", tier:"Foundation", questionNum:"9", marks:3, topic:"Networks", stage:"gcse", yearGroups:[9,10,11], text:"Explain what is meant by a protocol in networking. Give one example.", commandWord:"Explain", answerLines:3, markScheme:"A set of rules for communication between devices; ensures devices can communicate; e.g. HTTP, TCP/IP, FTP, SMTP" },
  { id:"cs-012", board:"AQA", subject:"computer-science", year:2023, series:"June", paper:"Paper 1", tier:"Higher", questionNum:"10", marks:5, topic:"Networks", stage:"gcse", yearGroups:[10,11], text:"Explain how data is transmitted using packet switching.", commandWord:"Explain", answerLines:6, markScheme:"Data split into packets; each packet contains source/destination address, data, sequence number; packets travel independently through network; may take different routes; reassembled at destination; error checking; efficient use of network" },
  { id:"cs-013", board:"Edexcel", subject:"computer-science", year:2023, series:"June", paper:"Paper 1", tier:"Foundation", questionNum:"1", marks:2, topic:"Binary and Data Representation", stage:"gcse", yearGroups:[9,10,11], text:"What is the purpose of ASCII encoding?", commandWord:"Explain", answerLines:2, markScheme:"Assigns a unique binary code to each character; allows text to be stored and transmitted digitally; standard encoding for text" },
  { id:"cs-014", board:"AQA", subject:"computer-science", year:2022, series:"June", paper:"Paper 1", tier:"Foundation", questionNum:"5", marks:4, topic:"Algorithms", stage:"gcse", yearGroups:[9,10,11], text:"Trace through the binary search algorithm to find the value 42 in the list: [12, 19, 27, 35, 42, 56, 71, 88]. Show each step.", commandWord:"Trace", answerLines:5, markScheme:"Middle element = 35 (index 3); 42 > 35, search right half; middle of [42, 56, 71, 88] = 56; 42 < 56, search left; middle = 42; found" },
  { id:"cs-015", board:"AQA", subject:"computer-science", year:2024, series:"June", paper:"Paper 2", tier:"Higher", questionNum:"3", marks:6, topic:"Programming", stage:"gcse", yearGroups:[10,11], text:"Write a Python program that reads a list of numbers from the user, stores them in a list, then calculates and prints the mean, maximum and minimum values.", commandWord:"Write", answerLines:10, markScheme:"Input loop; list storage; mean calculation (sum/count); max/min functions or manual comparison; correct output; error handling" },
  { id:"cs-016", board:"AQA", subject:"computer-science", year:2023, series:"June", paper:"Paper 1", tier:"Foundation", questionNum:"10", marks:4, topic:"Cyber Security", stage:"gcse", yearGroups:[9,10,11], text:"Describe three methods that can be used to protect a computer system from cyber attacks.", commandWord:"Describe", answerLines:4, markScheme:"Any three from: strong passwords; firewalls; antivirus software; encryption; two-factor authentication; regular updates/patches; access control; physical security" },
  { id:"cs-017", board:"AQA", subject:"computer-science", year:2023, series:"June", paper:"Paper 1", tier:"Higher", questionNum:"11", marks:5, topic:"Cyber Security", stage:"gcse", yearGroups:[10,11], text:"Explain what is meant by a SQL injection attack and describe how it can be prevented.", commandWord:"Explain", answerLines:6, markScheme:"Malicious SQL code inserted into input field; executes on database; can read/modify/delete data; prevention: input validation/sanitisation; parameterised queries; prepared statements; least privilege access" },
  { id:"cs-018", board:"Edexcel", subject:"computer-science", year:2022, series:"June", paper:"Paper 1", tier:"Foundation", questionNum:"3", marks:3, topic:"Hardware", stage:"gcse", yearGroups:[9,10,11], text:"Describe the function of the CPU (Central Processing Unit).", commandWord:"Describe", answerLines:3, markScheme:"Carries out instructions; fetch-decode-execute cycle; performs arithmetic and logic operations; controls other components; processes data" },
  { id:"cs-019", board:"AQA", subject:"computer-science", year:2022, series:"June", paper:"Paper 1", tier:"Foundation", questionNum:"6", marks:4, topic:"Hardware", stage:"gcse", yearGroups:[9,10,11], text:"Explain the difference between RAM and ROM.", commandWord:"Explain", answerLines:4, markScheme:"RAM: Random Access Memory; volatile; loses data when power off; stores data currently in use; can be read and written. ROM: Read Only Memory; non-volatile; retains data when power off; stores BIOS/firmware; cannot normally be written to" },
  { id:"cs-020", board:"AQA", subject:"computer-science", year:2024, series:"June", paper:"Paper 1", tier:"Higher", questionNum:"8", marks:5, topic:"Algorithms", stage:"gcse", yearGroups:[10,11], text:"Explain what is meant by computational thinking. Include decomposition, abstraction and algorithmic thinking in your answer.", commandWord:"Explain", answerLines:6, markScheme:"Computational thinking: approach to problem solving using computer science concepts. Decomposition: breaking problem into smaller parts. Abstraction: removing unnecessary detail; focusing on key features. Algorithmic thinking: creating step-by-step solution; can be implemented as program" },
];

export const otherSubjectQuestions: PastPaperQuestion[] = [
  // ─── RELIGIOUS STUDIES ────────────────────────────────────────────────────
  { id:"rs-001", board:"AQA", subject:"religious-studies", year:2023, series:"June", paper:"Paper 1", tier:"Foundation", questionNum:"1", marks:1, topic:"Christianity — Beliefs", stage:"gcse", yearGroups:[9,10,11], text:"What is meant by the term 'omnipotent'?", commandWord:"Define", answerLines:1, markScheme:"All-powerful; having unlimited power" },
  { id:"rs-002", board:"AQA", subject:"religious-studies", year:2023, series:"June", paper:"Paper 1", tier:"Foundation", questionNum:"2", marks:2, topic:"Christianity — Beliefs", stage:"gcse", yearGroups:[9,10,11], text:"Give two Christian beliefs about the nature of God.", commandWord:"Give", answerLines:2, markScheme:"Any two from: omnipotent; omniscient; omnibenevolent; omnipresent; eternal; the Trinity; creator" },
  { id:"rs-003", board:"AQA", subject:"religious-studies", year:2023, series:"June", paper:"Paper 1", tier:"Foundation", questionNum:"3", marks:4, topic:"Christianity — Beliefs", stage:"gcse", yearGroups:[9,10,11], text:"Explain two Christian teachings about the afterlife.", commandWord:"Explain", answerLines:5, markScheme:"Two teachings with explanation; e.g. resurrection of the body; heaven and hell; purgatory (Catholic); judgement; eternal life; soul lives on" },
  { id:"rs-004", board:"AQA", subject:"religious-studies", year:2023, series:"June", paper:"Paper 1", tier:"Foundation", questionNum:"4", marks:5, topic:"Christianity — Beliefs", stage:"gcse", yearGroups:[9,10,11], text:"Explain two Christian teachings about the nature of Jesus. Refer to sacred writings or another source of Christian belief and teaching in your answer.", commandWord:"Explain", answerLines:6, markScheme:"Two teachings with explanation and reference; e.g. Jesus is Son of God; Jesus is fully human and fully divine; Jesus as saviour; incarnation; reference to Bible/Nicene Creed" },
  { id:"rs-005", board:"AQA", subject:"religious-studies", year:2023, series:"June", paper:"Paper 1", tier:"Foundation", questionNum:"5", marks:12, topic:"Christianity — Beliefs", stage:"gcse", yearGroups:[9,10,11], text:"'The most important Christian belief is that Jesus rose from the dead.' Evaluate this statement. In your answer you should: refer to Christian teaching; give reasoned arguments to support this statement; give reasoned arguments to support a different point of view; reach a justified conclusion.", commandWord:"Evaluate", answerLines:16, markScheme:"Level 4 (10–12): balanced evaluation; Level 3 (7–9): developed; Level 2 (4–6): simple; Level 1 (1–3): basic" },
  // ─── FRENCH ───────────────────────────────────────────────────────────────
  { id:"fr-001", board:"AQA", subject:"french", year:2023, series:"June", paper:"Writing", tier:"Foundation", questionNum:"1", marks:10, topic:"Writing — Photo Card", stage:"gcse", yearGroups:[9,10,11], text:"Look at the photo. Write approximately 40 words in French about what you can see in the photo.", commandWord:"Write", answerLines:8, markScheme:"Content (6 marks): relevant description; Level 3 (5–6): clear; Level 2 (3–4): some; Level 1 (1–2): basic. Quality of language (4 marks): accuracy and variety" },
  { id:"fr-002", board:"AQA", subject:"french", year:2023, series:"June", paper:"Writing", tier:"Higher", questionNum:"2", marks:20, topic:"Writing — Essay", stage:"gcse", yearGroups:[10,11], text:"Écrivez un article pour un magazine scolaire sur les avantages et les inconvénients des réseaux sociaux. Écrivez environ 150 mots en français.", commandWord:"Write", answerLines:20, markScheme:"Content (10 marks); Quality of language (10 marks)" },
  // ─── SPANISH ──────────────────────────────────────────────────────────────
  { id:"sp-001", board:"AQA", subject:"spanish", year:2023, series:"June", paper:"Writing", tier:"Foundation", questionNum:"1", marks:10, topic:"Writing — Photo Card", stage:"gcse", yearGroups:[9,10,11], text:"Look at the photo. Write approximately 40 words in Spanish about what you can see in the photo.", commandWord:"Write", answerLines:8, markScheme:"Content (6 marks); Quality of language (4 marks)" },
  // ─── BUSINESS STUDIES ─────────────────────────────────────────────────────
  { id:"bus-001", board:"AQA", subject:"business", year:2023, series:"June", paper:"Paper 1", tier:"Foundation", questionNum:"1", marks:2, topic:"Business in the Real World", stage:"gcse", yearGroups:[9,10,11], text:"Define the term 'entrepreneur'.", commandWord:"Define", answerLines:2, markScheme:"A person who sets up a business; takes financial risks; in hope of making a profit; organises factors of production" },
  { id:"bus-002", board:"AQA", subject:"business", year:2023, series:"June", paper:"Paper 1", tier:"Foundation", questionNum:"2", marks:4, topic:"Business in the Real World", stage:"gcse", yearGroups:[9,10,11], text:"Explain two advantages of being a sole trader.", commandWord:"Explain", answerLines:4, markScheme:"Any two from: easy to set up; keep all profits; own boss; quick decision making; personal service; tax advantages; with explanation" },
  { id:"bus-003", board:"AQA", subject:"business", year:2023, series:"June", paper:"Paper 1", tier:"Foundation", questionNum:"3", marks:6, topic:"Finance", stage:"gcse", yearGroups:[9,10,11], text:"A business has total revenue of £80,000 and total costs of £55,000. Calculate the profit. Explain what the business could do with this profit.", commandWord:"Calculate", answerLines:6, markScheme:"Profit = £80,000 − £55,000 = £25,000; could reinvest in business; pay dividends; save for future; pay off debts; expand" },
  { id:"bus-004", board:"Edexcel", subject:"business", year:2023, series:"June", paper:"Paper 1", tier:"Foundation", questionNum:"1", marks:2, topic:"Business in the Real World", stage:"gcse", yearGroups:[9,10,11], text:"State two reasons why a business might set objectives.", commandWord:"State", answerLines:2, markScheme:"Any two from: to give direction; to motivate employees; to measure success; to attract investors; to plan resources; to communicate purpose" },
  { id:"bus-005", board:"AQA", subject:"business", year:2023, series:"June", paper:"Paper 2", tier:"Higher", questionNum:"4", marks:9, topic:"Marketing", stage:"gcse", yearGroups:[10,11], text:"Evaluate the importance of market research for a new business launching a product.", commandWord:"Evaluate", answerLines:12, markScheme:"Level 4 (8–9): detailed evaluation; Level 3 (6–7): clear; Level 2 (3–5): some; Level 1 (1–2): basic" },
];

export const allOtherSubjectQuestions: PastPaperQuestion[] = [
  ...historyQuestions,
  ...geographyQuestions,
  ...computerScienceQuestions,
  ...otherSubjectQuestions,
];

export default allOtherSubjectQuestions;
