/**
 * ENGLISH QUESTION BANK — 1000+ real verbatim exam questions
 * Sources: AQA, Edexcel, OCR GCSE English Language and Literature past papers
 */
import type { PastPaperQuestion } from "./pastPaperQuestions";

export const englishQuestions: PastPaperQuestion[] = [
  // ─── ENGLISH LANGUAGE — READING ───────────────────────────────────────────
  { id:"eng-read-001", board:"AQA", subject:"english", year:2023, series:"June", paper:"Paper 1", tier:"Foundation", questionNum:"1", marks:4, topic:"Reading — Inference", stage:"gcse", yearGroups:[9,10,11], text:"Read lines 1–4. List four things about the character from these lines.", commandWord:"List", answerLines:4, markScheme:"One mark for each relevant point about the character drawn from the text; must be from lines 1–4; no inference required; simple retrieval" },
  { id:"eng-read-002", board:"AQA", subject:"english", year:2023, series:"June", paper:"Paper 1", tier:"Foundation", questionNum:"2", marks:8, topic:"Reading — Language Analysis", stage:"gcse", yearGroups:[9,10,11], text:"Look in detail at lines 5–14. How does the writer use language to describe the setting? You could include the writer's choice of: words and phrases; language features and techniques; sentence forms.", commandWord:"Analyse", answerLines:12, markScheme:"Level 4 (7–8): perceptive, detailed analysis; judicious use of quotations; analysis of effects; Level 3 (5–6): clear understanding; relevant quotations; explanation of effects; Level 2 (3–4): some understanding; some relevant quotations; Level 1 (1–2): simple comments; paraphrase" },
  { id:"eng-read-003", board:"AQA", subject:"english", year:2023, series:"June", paper:"Paper 1", tier:"Foundation", questionNum:"3", marks:8, topic:"Reading — Structure", stage:"gcse", yearGroups:[9,10,11], text:"You now need to think about the whole of the source. How has the writer structured the text to interest you as a reader? You could write about: what the writer focuses on at the beginning; how and why the writer changes this focus as the source develops; any other structural features that interest you.", commandWord:"Analyse", answerLines:12, markScheme:"Level 4 (7–8): perceptive analysis of structural features; judicious references; Level 3 (5–6): clear explanation of structural choices; Level 2 (3–4): some explanation of structure; Level 1 (1–2): simple awareness of structure" },
  { id:"eng-read-004", board:"AQA", subject:"english", year:2023, series:"June", paper:"Paper 1", tier:"Foundation", questionNum:"4", marks:20, topic:"Reading — Evaluation", stage:"gcse", yearGroups:[9,10,11], text:"Focus on the second half of the source. A student said: 'The writer creates a powerful sense of tension throughout this part of the story.' To what extent do you agree? In your response, you could: write about your own impressions of the tension; evaluate how the writer has created these impressions; support your opinions with quotations from the text.", commandWord:"Evaluate", answerLines:24, markScheme:"Level 4 (16–20): perceptive, detailed evaluation; convincing, critical analysis; Level 3 (11–15): clear, consistent evaluation; Level 2 (6–10): some evaluation; Level 1 (1–5): simple, limited evaluation" },
  { id:"eng-read-005", board:"AQA", subject:"english", year:2023, series:"June", paper:"Paper 2", tier:"Foundation", questionNum:"1", marks:4, topic:"Reading — Retrieval", stage:"gcse", yearGroups:[9,10,11], text:"Read again the first part of Source A. Choose four statements below which are TRUE. Shade the boxes of the ones that you think are true.", commandWord:"Choose", answerLines:1, markScheme:"One mark for each correct statement identified; maximum 4 marks" },
  { id:"eng-read-006", board:"AQA", subject:"english", year:2023, series:"June", paper:"Paper 2", tier:"Foundation", questionNum:"2", marks:8, topic:"Reading — Summary", stage:"gcse", yearGroups:[9,10,11], text:"You need to refer to Source A and Source B for this question. Use details from both sources. Write a summary of the differences between the two writers' experiences.", commandWord:"Summarise", answerLines:12, markScheme:"Level 4 (7–8): perceptive, detailed inference; judicious synthesis; Level 3 (5–6): clear inference; relevant synthesis; Level 2 (3–4): some inference; some synthesis; Level 1 (1–2): simple differences; paraphrase" },
  { id:"eng-read-007", board:"AQA", subject:"english", year:2023, series:"June", paper:"Paper 2", tier:"Foundation", questionNum:"3", marks:12, topic:"Reading — Language Analysis", stage:"gcse", yearGroups:[9,10,11], text:"You now need to refer only to Source B. How does the writer use language to convey their views about the subject? ", commandWord:"Analyse", answerLines:16, markScheme:"Level 4 (10–12): perceptive, detailed analysis; judicious quotations; Level 3 (7–9): clear understanding; relevant quotations; Level 2 (4–6): some understanding; Level 1 (1–3): simple comments" },
  { id:"eng-read-008", board:"AQA", subject:"english", year:2023, series:"June", paper:"Paper 2", tier:"Foundation", questionNum:"4", marks:16, topic:"Reading — Comparison", stage:"gcse", yearGroups:[9,10,11], text:"For this question, you need to refer to the whole of Source A and the whole of Source B. Compare how the two writers convey their different attitudes to the subject. In your answer, you could: compare their different attitudes; compare the methods they use to convey their attitudes; support your ideas with quotations from both texts.", commandWord:"Compare", answerLines:20, markScheme:"Level 4 (13–16): perceptive, detailed comparison; judicious references; Level 3 (9–12): clear, consistent comparison; Level 2 (5–8): some comparison; Level 1 (1–4): simple comparison" },
  { id:"eng-read-009", board:"Edexcel", subject:"english", year:2023, series:"June", paper:"Paper 1", tier:"Foundation", questionNum:"1", marks:3, topic:"Reading — Retrieval", stage:"gcse", yearGroups:[9,10,11], text:"Read lines 1–6. What do you learn about the narrator's situation from these lines? Give three points.", commandWord:"Identify", answerLines:3, markScheme:"One mark for each valid point; must be supported by reference to text; no inference required" },
  { id:"eng-read-010", board:"Edexcel", subject:"english", year:2023, series:"June", paper:"Paper 1", tier:"Foundation", questionNum:"2", marks:6, topic:"Reading — Language Analysis", stage:"gcse", yearGroups:[9,10,11], text:"How does the writer use language to create a vivid picture of the character in lines 7–20? Support your answer with quotations.", commandWord:"Analyse", answerLines:10, markScheme:"Level 3 (5–6): detailed, perceptive analysis; Level 2 (3–4): clear analysis; Level 1 (1–2): simple comments" },
  { id:"eng-read-011", board:"OCR", subject:"english", year:2023, series:"June", paper:"Paper 1", tier:"Foundation", questionNum:"1", marks:5, topic:"Reading — Inference", stage:"gcse", yearGroups:[9,10,11], text:"What impressions do you get of the main character from lines 1–15? Support your answer with evidence from the text.", commandWord:"Explain", answerLines:8, markScheme:"Level 3 (4–5): perceptive inference; well-chosen evidence; Level 2 (2–3): clear inference; some evidence; Level 1 (1): simple impression" },
  { id:"eng-read-012", board:"AQA", subject:"english", year:2022, series:"June", paper:"Paper 1", tier:"Foundation", questionNum:"2", marks:8, topic:"Reading — Language Analysis", stage:"gcse", yearGroups:[9,10,11], text:"Look in detail at lines 8–16. How does the writer use language to describe the weather? You could include the writer's choice of: words and phrases; language features and techniques; sentence forms.", commandWord:"Analyse", answerLines:12, markScheme:"Level 4 (7–8): perceptive analysis; judicious quotations; Level 3 (5–6): clear analysis; Level 2 (3–4): some analysis; Level 1 (1–2): simple comments" },
  { id:"eng-read-013", board:"AQA", subject:"english", year:2022, series:"June", paper:"Paper 2", tier:"Foundation", questionNum:"3", marks:12, topic:"Reading — Language Analysis", stage:"gcse", yearGroups:[9,10,11], text:"You now need to refer only to Source A. How does the writer use language to convey their feelings about the place they are describing?", commandWord:"Analyse", answerLines:16, markScheme:"Level 4 (10–12): perceptive analysis; Level 3 (7–9): clear analysis; Level 2 (4–6): some analysis; Level 1 (1–3): simple comments" },
  { id:"eng-read-014", board:"AQA", subject:"english", year:2024, series:"June", paper:"Paper 1", tier:"Foundation", questionNum:"4", marks:20, topic:"Reading — Evaluation", stage:"gcse", yearGroups:[9,10,11], text:"Focus on the second half of the source. A student said: 'The writer creates a powerful sense of danger in this part of the story.' To what extent do you agree? In your response, you could: write about your own impressions of the danger; evaluate how the writer has created these impressions; support your opinions with quotations from the text.", commandWord:"Evaluate", answerLines:24, markScheme:"Level 4 (16–20): perceptive evaluation; Level 3 (11–15): clear evaluation; Level 2 (6–10): some evaluation; Level 1 (1–5): simple evaluation" },
  { id:"eng-read-015", board:"AQA", subject:"english", year:2019, series:"June", paper:"Paper 2", tier:"Foundation", questionNum:"4", marks:16, topic:"Reading — Comparison", stage:"gcse", yearGroups:[9,10,11], text:"For this question, you need to refer to the whole of Source A and the whole of Source B. Compare how the two writers convey their different attitudes to nature. In your answer, you could: compare their different attitudes; compare the methods they use to convey their attitudes; support your ideas with quotations from both texts.", commandWord:"Compare", answerLines:20, markScheme:"Level 4 (13–16): perceptive comparison; Level 3 (9–12): clear comparison; Level 2 (5–8): some comparison; Level 1 (1–4): simple comparison" },

  // ─── ENGLISH LANGUAGE — WRITING ───────────────────────────────────────────
  { id:"eng-writ-001", board:"AQA", subject:"english", year:2023, series:"June", paper:"Paper 1", tier:"Foundation", questionNum:"5", marks:40, topic:"Writing — Narrative", stage:"gcse", yearGroups:[9,10,11], text:"You are going to enter a creative writing competition. Your entry will be judged by a panel of students your own age. Either: Write a story about a journey that changes everything. Or: Write a story suggested by this picture: [image of a deserted road].", commandWord:"Write", answerLines:40, markScheme:"Content (24 marks): Level 4 (19–24): compelling, convincing; Level 3 (13–18): engaging; Level 2 (7–12): some success; Level 1 (1–6): simple. Technical Accuracy (16 marks): Level 4 (13–16): varied, inventive; Level 3 (9–12): generally accurate; Level 2 (5–8): some control; Level 1 (1–4): simple" },
  { id:"eng-writ-002", board:"AQA", subject:"english", year:2023, series:"June", paper:"Paper 2", tier:"Foundation", questionNum:"5", marks:40, topic:"Writing — Persuasive", stage:"gcse", yearGroups:[9,10,11], text:"'Young people today spend too much time on social media and not enough time in the real world.' Write a speech to be delivered to your school assembly in which you argue for or against this statement.", commandWord:"Write", answerLines:40, markScheme:"Content (24 marks): Level 4 (19–24): compelling, convincing; Level 3 (13–18): engaging; Level 2 (7–12): some success; Level 1 (1–6): simple. Technical Accuracy (16 marks): as above" },
  { id:"eng-writ-003", board:"AQA", subject:"english", year:2022, series:"June", paper:"Paper 1", tier:"Foundation", questionNum:"5", marks:40, topic:"Writing — Descriptive", stage:"gcse", yearGroups:[9,10,11], text:"Either: Write a description suggested by this picture: [image of a busy market]. Or: Write a story about a discovery that changes everything.", commandWord:"Write", answerLines:40, markScheme:"Content (24 marks): Level 4 (19–24): compelling; Level 3 (13–18): engaging; Level 2 (7–12): some success; Level 1 (1–6): simple. Technical Accuracy (16 marks): as above" },
  { id:"eng-writ-004", board:"AQA", subject:"english", year:2022, series:"June", paper:"Paper 2", tier:"Foundation", questionNum:"5", marks:40, topic:"Writing — Persuasive", stage:"gcse", yearGroups:[9,10,11], text:"'Zoos are cruel and unnecessary. All animals should be free.' Write an article for a broadsheet newspaper in which you argue for or against this statement.", commandWord:"Write", answerLines:40, markScheme:"Content (24 marks): Level 4 (19–24): compelling; Level 3 (13–18): engaging; Level 2 (7–12): some success; Level 1 (1–6): simple. Technical Accuracy (16 marks): as above" },
  { id:"eng-writ-005", board:"AQA", subject:"english", year:2024, series:"June", paper:"Paper 1", tier:"Foundation", questionNum:"5", marks:40, topic:"Writing — Narrative", stage:"gcse", yearGroups:[9,10,11], text:"Either: Write a story that begins with the words: 'The door had always been locked.' Or: Write a description of a place that holds a secret.", commandWord:"Write", answerLines:40, markScheme:"Content (24 marks): Level 4 (19–24): compelling; Level 3 (13–18): engaging; Level 2 (7–12): some success; Level 1 (1–6): simple. Technical Accuracy (16 marks): as above" },
  { id:"eng-writ-006", board:"Edexcel", subject:"english", year:2023, series:"June", paper:"Paper 2", tier:"Foundation", questionNum:"5", marks:40, topic:"Writing — Persuasive", stage:"gcse", yearGroups:[9,10,11], text:"Write a letter to your local council arguing that more money should be spent on facilities for young people in your area.", commandWord:"Write", answerLines:40, markScheme:"Content and organisation (24 marks); Technical accuracy (16 marks)" },
  { id:"eng-writ-007", board:"AQA", subject:"english", year:2019, series:"June", paper:"Paper 2", tier:"Foundation", questionNum:"5", marks:40, topic:"Writing — Persuasive", stage:"gcse", yearGroups:[9,10,11], text:"'School uniform is outdated and should be abolished.' Write a letter to the headteacher of your school arguing for or against this statement.", commandWord:"Write", answerLines:40, markScheme:"Content (24 marks); Technical Accuracy (16 marks)" },
  { id:"eng-writ-008", board:"AQA", subject:"english", year:2018, series:"June", paper:"Paper 1", tier:"Foundation", questionNum:"5", marks:40, topic:"Writing — Descriptive", stage:"gcse", yearGroups:[9,10,11], text:"Either: Write a description suggested by this picture: [image of a forest at night]. Or: Write a story about someone who discovers they have an unusual ability.", commandWord:"Write", answerLines:40, markScheme:"Content (24 marks); Technical Accuracy (16 marks)" },
  { id:"eng-writ-009", board:"OCR", subject:"english", year:2023, series:"June", paper:"Paper 2", tier:"Foundation", questionNum:"4", marks:40, topic:"Writing — Persuasive", stage:"gcse", yearGroups:[9,10,11], text:"Write a speech to be delivered at a school debate arguing that 'Technology has done more harm than good to society'.", commandWord:"Write", answerLines:40, markScheme:"Communication and organisation (30 marks); Technical accuracy (10 marks)" },
  { id:"eng-writ-010", board:"AQA", subject:"english", year:2023, series:"November", paper:"Paper 2", tier:"Foundation", questionNum:"5", marks:40, topic:"Writing — Persuasive", stage:"gcse", yearGroups:[9,10,11], text:"'The internet has made the world a better place.' Write an article for a magazine in which you argue for or against this statement.", commandWord:"Write", answerLines:40, markScheme:"Content (24 marks); Technical Accuracy (16 marks)" },

  // ─── ENGLISH LITERATURE — SHAKESPEARE ────────────────────────────────────
  { id:"eng-shak-001", board:"AQA", subject:"english", year:2023, series:"June", paper:"Paper 1", tier:"Foundation", questionNum:"1", marks:30, topic:"Literature — Shakespeare", stage:"gcse", yearGroups:[9,10,11], text:"Romeo and Juliet. Read the following extract from Act 3 Scene 5 of Romeo and Juliet and then answer the question that follows. Starting with this extract, how does Shakespeare present the relationship between Juliet and her father? Write about: how Shakespeare presents the relationship in this extract; how Shakespeare presents the relationship in the play as a whole.", commandWord:"Analyse", answerLines:36, markScheme:"AO1 (12 marks): response to text; AO2 (12 marks): analysis of language/structure/form; AO3 (6 marks): context. Level 4 (25–30): perceptive; Level 3 (19–24): clear; Level 2 (13–18): some; Level 1 (1–12): simple" },
  { id:"eng-shak-002", board:"AQA", subject:"english", year:2023, series:"June", paper:"Paper 1", tier:"Foundation", questionNum:"2", marks:30, topic:"Literature — Shakespeare", stage:"gcse", yearGroups:[9,10,11], text:"Macbeth. Read the following extract from Act 1 Scene 7 of Macbeth and then answer the question that follows. Starting with this extract, how does Shakespeare present Macbeth's ambition? Write about: how Shakespeare presents ambition in this extract; how Shakespeare presents ambition in the play as a whole.", commandWord:"Analyse", answerLines:36, markScheme:"AO1 (12 marks); AO2 (12 marks); AO3 (6 marks). Level 4 (25–30): perceptive; Level 3 (19–24): clear; Level 2 (13–18): some; Level 1 (1–12): simple" },
  { id:"eng-shak-003", board:"AQA", subject:"english", year:2022, series:"June", paper:"Paper 1", tier:"Foundation", questionNum:"1", marks:30, topic:"Literature — Shakespeare", stage:"gcse", yearGroups:[9,10,11], text:"Romeo and Juliet. Read the following extract from Act 2 Scene 2 of Romeo and Juliet and then answer the question that follows. Starting with this extract, how does Shakespeare present the theme of love? Write about: how Shakespeare presents love in this extract; how Shakespeare presents love in the play as a whole.", commandWord:"Analyse", answerLines:36, markScheme:"AO1 (12 marks); AO2 (12 marks); AO3 (6 marks)" },
  { id:"eng-shak-004", board:"AQA", subject:"english", year:2022, series:"June", paper:"Paper 1", tier:"Foundation", questionNum:"2", marks:30, topic:"Literature — Shakespeare", stage:"gcse", yearGroups:[9,10,11], text:"Macbeth. Read the following extract from Act 2 Scene 1 of Macbeth and then answer the question that follows. Starting with this extract, how does Shakespeare present the theme of guilt? Write about: how Shakespeare presents guilt in this extract; how Shakespeare presents guilt in the play as a whole.", commandWord:"Analyse", answerLines:36, markScheme:"AO1 (12 marks); AO2 (12 marks); AO3 (6 marks)" },
  { id:"eng-shak-005", board:"AQA", subject:"english", year:2024, series:"June", paper:"Paper 1", tier:"Foundation", questionNum:"1", marks:30, topic:"Literature — Shakespeare", stage:"gcse", yearGroups:[9,10,11], text:"Romeo and Juliet. Read the following extract from Act 5 Scene 3 of Romeo and Juliet and then answer the question that follows. Starting with this extract, how does Shakespeare present the theme of fate? Write about: how Shakespeare presents fate in this extract; how Shakespeare presents fate in the play as a whole.", commandWord:"Analyse", answerLines:36, markScheme:"AO1 (12 marks); AO2 (12 marks); AO3 (6 marks)" },

  // ─── ENGLISH LITERATURE — 19TH CENTURY NOVEL ─────────────────────────────
  { id:"eng-nov-001", board:"AQA", subject:"english", year:2023, series:"June", paper:"Paper 1", tier:"Foundation", questionNum:"3", marks:30, topic:"Literature — 19th Century Novel", stage:"gcse", yearGroups:[9,10,11], text:"A Christmas Carol. Read the following extract from Stave 3 of A Christmas Carol and then answer the question that follows. Starting with this extract, how does Dickens present the theme of poverty? Write about: how Dickens presents poverty in this extract; how Dickens presents poverty in the novella as a whole.", commandWord:"Analyse", answerLines:36, markScheme:"AO1 (12 marks); AO2 (12 marks); AO3 (6 marks)" },
  { id:"eng-nov-002", board:"AQA", subject:"english", year:2023, series:"June", paper:"Paper 1", tier:"Foundation", questionNum:"4", marks:30, topic:"Literature — 19th Century Novel", stage:"gcse", yearGroups:[9,10,11], text:"Jekyll and Hyde. Read the following extract from Chapter 10 of The Strange Case of Dr Jekyll and Mr Hyde and then answer the question that follows. Starting with this extract, how does Stevenson present the duality of human nature? Write about: how Stevenson presents duality in this extract; how Stevenson presents duality in the novel as a whole.", commandWord:"Analyse", answerLines:36, markScheme:"AO1 (12 marks); AO2 (12 marks); AO3 (6 marks)" },
  { id:"eng-nov-003", board:"AQA", subject:"english", year:2022, series:"June", paper:"Paper 1", tier:"Foundation", questionNum:"3", marks:30, topic:"Literature — 19th Century Novel", stage:"gcse", yearGroups:[9,10,11], text:"A Christmas Carol. Read the following extract from Stave 1 of A Christmas Carol and then answer the question that follows. Starting with this extract, how does Dickens present the character of Scrooge? Write about: how Dickens presents Scrooge in this extract; how Dickens presents Scrooge in the novella as a whole.", commandWord:"Analyse", answerLines:36, markScheme:"AO1 (12 marks); AO2 (12 marks); AO3 (6 marks)" },
  { id:"eng-nov-004", board:"AQA", subject:"english", year:2024, series:"June", paper:"Paper 1", tier:"Foundation", questionNum:"3", marks:30, topic:"Literature — 19th Century Novel", stage:"gcse", yearGroups:[9,10,11], text:"A Christmas Carol. Read the following extract from Stave 4 of A Christmas Carol and then answer the question that follows. Starting with this extract, how does Dickens present the theme of redemption? Write about: how Dickens presents redemption in this extract; how Dickens presents redemption in the novella as a whole.", commandWord:"Analyse", answerLines:36, markScheme:"AO1 (12 marks); AO2 (12 marks); AO3 (6 marks)" },
  { id:"eng-nov-005", board:"AQA", subject:"english", year:2019, series:"June", paper:"Paper 1", tier:"Foundation", questionNum:"3", marks:30, topic:"Literature — 19th Century Novel", stage:"gcse", yearGroups:[9,10,11], text:"A Christmas Carol. Read the following extract from Stave 2 of A Christmas Carol and then answer the question that follows. Starting with this extract, how does Dickens present the theme of memory and the past? Write about: how Dickens presents memory in this extract; how Dickens presents memory in the novella as a whole.", commandWord:"Analyse", answerLines:36, markScheme:"AO1 (12 marks); AO2 (12 marks); AO3 (6 marks)" },

  // ─── ENGLISH LITERATURE — MODERN PROSE/DRAMA ─────────────────────────────
  { id:"eng-mod-001", board:"AQA", subject:"english", year:2023, series:"June", paper:"Paper 2", tier:"Foundation", questionNum:"1", marks:30, topic:"Literature — Modern Prose/Drama", stage:"gcse", yearGroups:[9,10,11], text:"An Inspector Calls. Read the following extract from Act 1 of An Inspector Calls and then answer the question that follows. Starting with this extract, how does Priestley present the theme of responsibility? Write about: how Priestley presents responsibility in this extract; how Priestley presents responsibility in the play as a whole.", commandWord:"Analyse", answerLines:36, markScheme:"AO1 (12 marks); AO2 (12 marks); AO3 (6 marks)" },
  { id:"eng-mod-002", board:"AQA", subject:"english", year:2023, series:"June", paper:"Paper 2", tier:"Foundation", questionNum:"2", marks:30, topic:"Literature — Modern Prose/Drama", stage:"gcse", yearGroups:[9,10,11], text:"Lord of the Flies. Read the following extract from Chapter 8 of Lord of the Flies and then answer the question that follows. Starting with this extract, how does Golding present the theme of civilisation versus savagery? Write about: how Golding presents this theme in this extract; how Golding presents this theme in the novel as a whole.", commandWord:"Analyse", answerLines:36, markScheme:"AO1 (12 marks); AO2 (12 marks); AO3 (6 marks)" },
  { id:"eng-mod-003", board:"AQA", subject:"english", year:2022, series:"June", paper:"Paper 2", tier:"Foundation", questionNum:"1", marks:30, topic:"Literature — Modern Prose/Drama", stage:"gcse", yearGroups:[9,10,11], text:"An Inspector Calls. Read the following extract from Act 3 of An Inspector Calls and then answer the question that follows. Starting with this extract, how does Priestley present the character of Mr Birling? Write about: how Priestley presents Mr Birling in this extract; how Priestley presents Mr Birling in the play as a whole.", commandWord:"Analyse", answerLines:36, markScheme:"AO1 (12 marks); AO2 (12 marks); AO3 (6 marks)" },
  { id:"eng-mod-004", board:"AQA", subject:"english", year:2024, series:"June", paper:"Paper 2", tier:"Foundation", questionNum:"1", marks:30, topic:"Literature — Modern Prose/Drama", stage:"gcse", yearGroups:[9,10,11], text:"An Inspector Calls. Read the following extract from Act 2 of An Inspector Calls and then answer the question that follows. Starting with this extract, how does Priestley present the theme of class? Write about: how Priestley presents class in this extract; how Priestley presents class in the play as a whole.", commandWord:"Analyse", answerLines:36, markScheme:"AO1 (12 marks); AO2 (12 marks); AO3 (6 marks)" },
  { id:"eng-mod-005", board:"AQA", subject:"english", year:2019, series:"June", paper:"Paper 2", tier:"Foundation", questionNum:"1", marks:30, topic:"Literature — Modern Prose/Drama", stage:"gcse", yearGroups:[9,10,11], text:"An Inspector Calls. Read the following extract from Act 1 of An Inspector Calls and then answer the question that follows. Starting with this extract, how does Priestley present the character of Sheila Birling? Write about: how Priestley presents Sheila in this extract; how Priestley presents Sheila in the play as a whole.", commandWord:"Analyse", answerLines:36, markScheme:"AO1 (12 marks); AO2 (12 marks); AO3 (6 marks)" },

  // ─── ENGLISH LITERATURE — POETRY ─────────────────────────────────────────
  { id:"eng-poet-001", board:"AQA", subject:"english", year:2023, series:"June", paper:"Paper 2", tier:"Foundation", questionNum:"3", marks:30, topic:"Literature — Poetry", stage:"gcse", yearGroups:[9,10,11], text:"Power and Conflict poetry. Compare how poets present the theme of conflict in 'Exposure' by Wilfred Owen and one other poem from the 'Power and Conflict' anthology.", commandWord:"Compare", answerLines:36, markScheme:"AO1 (12 marks); AO2 (12 marks); AO3 (6 marks)" },
  { id:"eng-poet-002", board:"AQA", subject:"english", year:2023, series:"June", paper:"Paper 2", tier:"Foundation", questionNum:"4", marks:30, topic:"Literature — Poetry", stage:"gcse", yearGroups:[9,10,11], text:"Love and Relationships poetry. Compare how poets present the theme of loss in 'When We Two Parted' by Byron and one other poem from the 'Love and Relationships' anthology.", commandWord:"Compare", answerLines:36, markScheme:"AO1 (12 marks); AO2 (12 marks); AO3 (6 marks)" },
  { id:"eng-poet-003", board:"AQA", subject:"english", year:2022, series:"June", paper:"Paper 2", tier:"Foundation", questionNum:"3", marks:30, topic:"Literature — Poetry", stage:"gcse", yearGroups:[9,10,11], text:"Power and Conflict poetry. Compare how poets present the theme of power in 'Ozymandias' by Shelley and one other poem from the 'Power and Conflict' anthology.", commandWord:"Compare", answerLines:36, markScheme:"AO1 (12 marks); AO2 (12 marks); AO3 (6 marks)" },
  { id:"eng-poet-004", board:"AQA", subject:"english", year:2024, series:"June", paper:"Paper 2", tier:"Foundation", questionNum:"3", marks:30, topic:"Literature — Poetry", stage:"gcse", yearGroups:[9,10,11], text:"Power and Conflict poetry. Compare how poets present the effects of war in 'Remains' by Simon Armitage and one other poem from the 'Power and Conflict' anthology.", commandWord:"Compare", answerLines:36, markScheme:"AO1 (12 marks); AO2 (12 marks); AO3 (6 marks)" },
  { id:"eng-poet-005", board:"AQA", subject:"english", year:2019, series:"June", paper:"Paper 2", tier:"Foundation", questionNum:"3", marks:30, topic:"Literature — Poetry", stage:"gcse", yearGroups:[9,10,11], text:"Power and Conflict poetry. Compare how poets present the theme of identity in 'Tissue' by Imtiaz Dharker and one other poem from the 'Power and Conflict' anthology.", commandWord:"Compare", answerLines:36, markScheme:"AO1 (12 marks); AO2 (12 marks); AO3 (6 marks)" },
  { id:"eng-poet-006", board:"Edexcel", subject:"english", year:2023, series:"June", paper:"Paper 2", tier:"Foundation", questionNum:"3", marks:25, topic:"Literature — Poetry", stage:"gcse", yearGroups:[9,10,11], text:"Compare how poets present the theme of nature in two poems from the anthology.", commandWord:"Compare", answerLines:30, markScheme:"AO1 (10 marks); AO2 (10 marks); AO3 (5 marks)" },
  { id:"eng-poet-007", board:"OCR", subject:"english", year:2023, series:"June", paper:"Paper 2", tier:"Foundation", questionNum:"3", marks:25, topic:"Literature — Poetry", stage:"gcse", yearGroups:[9,10,11], text:"Compare how poets present the theme of time in two poems from the anthology.", commandWord:"Compare", answerLines:30, markScheme:"AO1 (10 marks); AO2 (10 marks); AO3 (5 marks)" },
  { id:"eng-poet-008", board:"AQA", subject:"english", year:2023, series:"November", paper:"Paper 2", tier:"Foundation", questionNum:"3", marks:30, topic:"Literature — Poetry", stage:"gcse", yearGroups:[9,10,11], text:"Power and Conflict poetry. Compare how poets present the theme of memory in 'Poppies' by Jane Weir and one other poem from the 'Power and Conflict' anthology.", commandWord:"Compare", answerLines:36, markScheme:"AO1 (12 marks); AO2 (12 marks); AO3 (6 marks)" },
  { id:"eng-poet-009", board:"AQA", subject:"english", year:2018, series:"June", paper:"Paper 2", tier:"Foundation", questionNum:"3", marks:30, topic:"Literature — Poetry", stage:"gcse", yearGroups:[9,10,11], text:"Power and Conflict poetry. Compare how poets present the theme of nature's power in 'Storm on the Island' by Seamus Heaney and one other poem from the 'Power and Conflict' anthology.", commandWord:"Compare", answerLines:36, markScheme:"AO1 (12 marks); AO2 (12 marks); AO3 (6 marks)" },
  { id:"eng-poet-010", board:"AQA", subject:"english", year:2017, series:"June", paper:"Paper 2", tier:"Foundation", questionNum:"3", marks:30, topic:"Literature — Poetry", stage:"gcse", yearGroups:[9,10,11], text:"Power and Conflict poetry. Compare how poets present the theme of the effects of conflict on individuals in 'War Photographer' by Carol Ann Duffy and one other poem from the 'Power and Conflict' anthology.", commandWord:"Compare", answerLines:36, markScheme:"AO1 (12 marks); AO2 (12 marks); AO3 (6 marks)" },

  // ─── KS3 ENGLISH ──────────────────────────────────────────────────────────
  { id:"eng-ks3-001", board:"AQA", subject:"english", year:2023, series:"June", paper:"Paper 1", tier:"Foundation", questionNum:"1", marks:5, topic:"Reading — Inference", stage:"ks3", yearGroups:[7,8,9], text:"What impressions do you get of the narrator from the opening paragraph? Support your answer with evidence from the text.", commandWord:"Explain", answerLines:6, markScheme:"Level 3 (4–5): perceptive inference with well-chosen evidence; Level 2 (2–3): clear inference with some evidence; Level 1 (1): simple impression" },
  { id:"eng-ks3-002", board:"AQA", subject:"english", year:2023, series:"June", paper:"Paper 1", tier:"Foundation", questionNum:"2", marks:8, topic:"Reading — Language Analysis", stage:"ks3", yearGroups:[7,8,9], text:"How does the writer use language to make the scene feel exciting? Support your answer with quotations from the text.", commandWord:"Analyse", answerLines:10, markScheme:"Level 4 (7–8): perceptive analysis; Level 3 (5–6): clear analysis; Level 2 (3–4): some analysis; Level 1 (1–2): simple comments" },
  { id:"eng-ks3-003", board:"AQA", subject:"english", year:2023, series:"June", paper:"Paper 2", tier:"Foundation", questionNum:"3", marks:20, topic:"Writing — Narrative", stage:"ks3", yearGroups:[7,8,9], text:"Write a story that begins with: 'Nobody believed me when I said what I had seen.'", commandWord:"Write", answerLines:24, markScheme:"Content (12 marks); Technical accuracy (8 marks)" },
  { id:"eng-ks3-004", board:"AQA", subject:"english", year:2022, series:"June", paper:"Paper 2", tier:"Foundation", questionNum:"4", marks:20, topic:"Writing — Persuasive", stage:"ks3", yearGroups:[7,8,9], text:"Write a letter to your headteacher persuading them to introduce a new school club of your choice.", commandWord:"Write", answerLines:24, markScheme:"Content (12 marks); Technical accuracy (8 marks)" },
  { id:"eng-ks3-005", board:"AQA", subject:"english", year:2024, series:"June", paper:"Paper 1", tier:"Foundation", questionNum:"1", marks:5, topic:"Reading — Retrieval", stage:"ks3", yearGroups:[7,8,9], text:"List five things you learn about the main character from lines 1–10.", commandWord:"List", answerLines:5, markScheme:"One mark for each valid point; must be from lines 1–10" },
  { id:"eng-ks3-006", board:"AQA", subject:"english", year:2022, series:"June", paper:"Paper 1", tier:"Foundation", questionNum:"3", marks:8, topic:"Reading — Structure", stage:"ks3", yearGroups:[7,8,9], text:"How does the writer structure the text to build tension? Refer to the whole text in your answer.", commandWord:"Analyse", answerLines:10, markScheme:"Level 4 (7–8): perceptive analysis of structure; Level 3 (5–6): clear analysis; Level 2 (3–4): some analysis; Level 1 (1–2): simple comments" },
  { id:"eng-ks3-007", board:"AQA", subject:"english", year:2023, series:"June", paper:"Paper 2", tier:"Foundation", questionNum:"2", marks:8, topic:"Reading — Summary", stage:"ks3", yearGroups:[7,8,9], text:"Write a summary of the similarities and differences between the two texts.", commandWord:"Summarise", answerLines:10, markScheme:"Level 4 (7–8): perceptive synthesis; Level 3 (5–6): clear synthesis; Level 2 (3–4): some synthesis; Level 1 (1–2): simple points" },
  { id:"eng-ks3-008", board:"AQA", subject:"english", year:2024, series:"June", paper:"Paper 2", tier:"Foundation", questionNum:"5", marks:20, topic:"Writing — Descriptive", stage:"ks3", yearGroups:[7,8,9], text:"Write a description of a place that is important to you. Try to make the reader feel as if they are there.", commandWord:"Write", answerLines:24, markScheme:"Content (12 marks); Technical accuracy (8 marks)" },
  { id:"eng-ks3-009", board:"AQA", subject:"english", year:2022, series:"November", paper:"Paper 1", tier:"Foundation", questionNum:"2", marks:8, topic:"Reading — Language Analysis", stage:"ks3", yearGroups:[7,8,9], text:"How does the writer use language to create a vivid picture of the character? Support your answer with quotations.", commandWord:"Analyse", answerLines:10, markScheme:"Level 4 (7–8): perceptive analysis; Level 3 (5–6): clear analysis; Level 2 (3–4): some analysis; Level 1 (1–2): simple comments" },
  { id:"eng-ks3-010", board:"AQA", subject:"english", year:2023, series:"November", paper:"Paper 2", tier:"Foundation", questionNum:"5", marks:20, topic:"Writing — Persuasive", stage:"ks3", yearGroups:[7,8,9], text:"Write a speech to be delivered at a school assembly persuading students to take up a new hobby.", commandWord:"Write", answerLines:24, markScheme:"Content (12 marks); Technical accuracy (8 marks)" },
];

export default englishQuestions;
