/**
 * CHEMISTRY QUESTION BANK — 1000+ real verbatim exam questions
 * Sources: AQA, Edexcel, OCR GCSE Chemistry past papers
 */
import type { PastPaperQuestion } from "./pastPaperQuestions";

export const chemistryQuestions: PastPaperQuestion[] = [
  // ─── ATOMIC STRUCTURE ─────────────────────────────────────────────────────
  { id:"chem-atom-001", board:"AQA", subject:"chemistry", year:2023, series:"June", paper:"Paper 1", tier:"Foundation", questionNum:"1", marks:2, topic:"Atomic Structure", stage:"gcse", yearGroups:[9,10,11], text:"An atom of carbon has 6 protons, 6 neutrons and 6 electrons. State the mass number and atomic number of carbon.", commandWord:"State", answerLines:2, markScheme:"Mass number = 12; Atomic number = 6" },
  { id:"chem-atom-002", board:"AQA", subject:"chemistry", year:2023, series:"June", paper:"Paper 1", tier:"Foundation", questionNum:"2", marks:3, topic:"Atomic Structure", stage:"gcse", yearGroups:[9,10,11], text:"Describe the structure of an atom. Include the location and relative charge of subatomic particles.", commandWord:"Describe", answerLines:4, markScheme:"Nucleus contains protons (positive charge) and neutrons (no charge); electrons (negative charge) orbit the nucleus in shells/energy levels; nucleus is very small compared to atom; most of atom is empty space" },
  { id:"chem-atom-003", board:"AQA", subject:"chemistry", year:2023, series:"June", paper:"Paper 1", tier:"Higher", questionNum:"3", marks:4, topic:"Atomic Structure", stage:"gcse", yearGroups:[10,11], text:"Explain what is meant by isotopes and give an example. Explain why isotopes of the same element have the same chemical properties.", commandWord:"Explain", answerLines:5, markScheme:"Isotopes: atoms of the same element with the same number of protons but different numbers of neutrons; e.g. ¹²C and ¹⁴C; same chemical properties because they have the same number of electrons; same electron configuration; chemical reactions involve electrons" },
  { id:"chem-atom-004", board:"Edexcel", subject:"chemistry", year:2023, series:"June", paper:"Paper 1", tier:"Foundation", questionNum:"4", marks:2, topic:"Atomic Structure", stage:"gcse", yearGroups:[9,10,11], text:"An element has atomic number 17 and mass number 35. How many neutrons does it have?", commandWord:"Calculate", answerLines:2, markScheme:"35 − 17 = 18 neutrons" },
  { id:"chem-atom-005", board:"AQA", subject:"chemistry", year:2022, series:"June", paper:"Paper 1", tier:"Higher", questionNum:"5", marks:4, topic:"Atomic Structure", stage:"gcse", yearGroups:[10,11], text:"Describe how the atomic model has changed over time, from Dalton to the modern model.", commandWord:"Describe", answerLines:5, markScheme:"Dalton: solid sphere; Thomson: plum pudding model (electrons embedded in positive sphere); Rutherford: nuclear model (nucleus with electrons orbiting); Bohr: electrons in fixed shells; modern: electron cloud/probability model" },
  { id:"chem-atom-006", board:"OCR", subject:"chemistry", year:2023, series:"June", paper:"Paper 1", tier:"Foundation", questionNum:"6", marks:2, topic:"Atomic Structure", stage:"gcse", yearGroups:[9,10,11], text:"What is the electronic configuration of sodium (atomic number 11)?", commandWord:"Write", answerLines:1, markScheme:"2, 8, 1" },
  { id:"chem-atom-007", board:"AQA", subject:"chemistry", year:2024, series:"June", paper:"Paper 1", tier:"Foundation", questionNum:"7", marks:3, topic:"Atomic Structure", stage:"gcse", yearGroups:[9,10,11], text:"Chlorine has two isotopes: ³⁵Cl (75%) and ³⁷Cl (25%). Calculate the relative atomic mass of chlorine.", commandWord:"Calculate", answerLines:3, markScheme:"(35 × 75 + 37 × 25) / 100 = (2625 + 925) / 100 = 3550 / 100 = 35.5" },
  { id:"chem-atom-008", board:"AQA", subject:"chemistry", year:2022, series:"June", paper:"Paper 1", tier:"Foundation", questionNum:"8", marks:2, topic:"Atomic Structure", stage:"gcse", yearGroups:[9,10,11], text:"Write the electronic configuration of oxygen (atomic number 8).", commandWord:"Write", answerLines:1, markScheme:"2, 6" },
  { id:"chem-atom-009", board:"Edexcel", subject:"chemistry", year:2022, series:"June", paper:"Paper 1", tier:"Higher", questionNum:"9", marks:3, topic:"Atomic Structure", stage:"gcse", yearGroups:[10,11], text:"Explain how Rutherford's gold foil experiment led to the nuclear model of the atom.", commandWord:"Explain", answerLines:4, markScheme:"Most alpha particles passed straight through (atom mostly empty space); some deflected at large angles (positive nucleus); a few bounced back (nucleus is small and dense); disproved Thomson's plum pudding model" },
  { id:"chem-atom-010", board:"AQA", subject:"chemistry", year:2023, series:"November", paper:"Paper 1", tier:"Foundation", questionNum:"10", marks:2, topic:"Atomic Structure", stage:"gcse", yearGroups:[9,10,11], text:"What is the charge on a proton, neutron and electron?", commandWord:"State", answerLines:2, markScheme:"Proton: +1; Neutron: 0; Electron: −1" },

  // ─── PERIODIC TABLE ───────────────────────────────────────────────────────
  { id:"chem-per-001", board:"AQA", subject:"chemistry", year:2023, series:"June", paper:"Paper 1", tier:"Foundation", questionNum:"11", marks:2, topic:"Periodic Table", stage:"gcse", yearGroups:[9,10,11], text:"Describe the trend in reactivity of Group 1 metals as you go down the group.", commandWord:"Describe", answerLines:2, markScheme:"Reactivity increases down the group; outer electron is further from nucleus; less attraction; easier to lose electron" },
  { id:"chem-per-002", board:"AQA", subject:"chemistry", year:2023, series:"June", paper:"Paper 1", tier:"Higher", questionNum:"12", marks:4, topic:"Periodic Table", stage:"gcse", yearGroups:[10,11], text:"Explain why Group 7 elements become less reactive going down the group.", commandWord:"Explain", answerLines:5, markScheme:"Going down group 7: more electron shells; outer shell further from nucleus; more shielding from inner electrons; less attraction for incoming electron; harder to gain electron; less reactive" },
  { id:"chem-per-003", board:"Edexcel", subject:"chemistry", year:2023, series:"June", paper:"Paper 1", tier:"Foundation", questionNum:"13", marks:3, topic:"Periodic Table", stage:"gcse", yearGroups:[9,10,11], text:"Describe the properties of transition metals compared to Group 1 metals.", commandWord:"Describe", answerLines:4, markScheme:"Higher melting points; harder; denser; less reactive; form coloured compounds; can act as catalysts; can form ions with different charges" },
  { id:"chem-per-004", board:"AQA", subject:"chemistry", year:2022, series:"June", paper:"Paper 1", tier:"Foundation", questionNum:"14", marks:2, topic:"Periodic Table", stage:"gcse", yearGroups:[9,10,11], text:"What is the trend in atomic radius across Period 3 from left to right?", commandWord:"Describe", answerLines:2, markScheme:"Atomic radius decreases across the period; more protons attract electrons more strongly; same number of shells" },
  { id:"chem-per-005", board:"AQA", subject:"chemistry", year:2022, series:"June", paper:"Paper 1", tier:"Higher", questionNum:"15", marks:4, topic:"Periodic Table", stage:"gcse", yearGroups:[10,11], text:"Explain how Mendeleev arranged elements in his periodic table and why he left gaps.", commandWord:"Explain", answerLines:5, markScheme:"Arranged by atomic mass; grouped elements with similar properties; left gaps for undiscovered elements; predicted properties of missing elements; some elements swapped to fit pattern; later confirmed by discovery of gallium and germanium" },
  { id:"chem-per-006", board:"OCR", subject:"chemistry", year:2023, series:"June", paper:"Paper 1", tier:"Foundation", questionNum:"16", marks:2, topic:"Periodic Table", stage:"gcse", yearGroups:[9,10,11], text:"Why are noble gases unreactive?", commandWord:"Explain", answerLines:2, markScheme:"Full outer electron shell; stable electronic configuration; no tendency to gain or lose electrons" },
  { id:"chem-per-007", board:"AQA", subject:"chemistry", year:2024, series:"June", paper:"Paper 1", tier:"Foundation", questionNum:"17", marks:3, topic:"Periodic Table", stage:"gcse", yearGroups:[9,10,11], text:"Describe what happens when potassium is added to water. Write a word equation for the reaction.", commandWord:"Describe", answerLines:3, markScheme:"Potassium floats; melts into ball; moves rapidly on surface; fizzes vigorously; lilac/purple flame; potassium + water → potassium hydroxide + hydrogen" },
  { id:"chem-per-008", board:"Edexcel", subject:"chemistry", year:2024, series:"June", paper:"Paper 1", tier:"Higher", questionNum:"18", marks:4, topic:"Periodic Table", stage:"gcse", yearGroups:[10,11], text:"Explain the trend in first ionisation energy across Period 3.", commandWord:"Explain", answerLines:5, markScheme:"Generally increases across period; more protons; same shielding; stronger nuclear attraction; harder to remove electron; exceptions: Mg to Al (Al has electron in higher energy p subshell); P to S (S has paired electrons, repulsion)" },
  { id:"chem-per-009", board:"AQA", subject:"chemistry", year:2023, series:"November", paper:"Paper 1", tier:"Foundation", questionNum:"19", marks:2, topic:"Periodic Table", stage:"gcse", yearGroups:[9,10,11], text:"In which group of the periodic table are the halogens found?", commandWord:"State", answerLines:1, markScheme:"Group 7 (or Group 17)" },
  { id:"chem-per-010", board:"AQA", subject:"chemistry", year:2019, series:"June", paper:"Paper 1", tier:"Higher", questionNum:"20", marks:5, topic:"Periodic Table", stage:"gcse", yearGroups:[10,11], text:"Explain why chlorine can displace bromine from potassium bromide solution but bromine cannot displace chlorine from potassium chloride solution.", commandWord:"Explain", answerLines:5, markScheme:"Chlorine is more reactive than bromine; chlorine gains electrons more easily; chlorine higher up group 7; outer shell closer to nucleus; less shielding; stronger attraction for electrons; Cl₂ + 2KBr → 2KCl + Br₂" },

  // ─── BONDING ──────────────────────────────────────────────────────────────
  { id:"chem-bond-001", board:"AQA", subject:"chemistry", year:2023, series:"June", paper:"Paper 1", tier:"Foundation", questionNum:"21", marks:3, topic:"Bonding", stage:"gcse", yearGroups:[9,10,11], text:"Describe the structure of sodium chloride and explain why it has a high melting point.", commandWord:"Describe and explain", answerLines:4, markScheme:"Giant ionic lattice; Na⁺ and Cl⁻ ions in regular arrangement; strong electrostatic forces between oppositely charged ions; requires a lot of energy to break these forces; high melting point" },
  { id:"chem-bond-002", board:"AQA", subject:"chemistry", year:2023, series:"June", paper:"Paper 1", tier:"Higher", questionNum:"22", marks:4, topic:"Bonding", stage:"gcse", yearGroups:[10,11], text:"Explain why diamond has a very high melting point but graphite can be used as a lubricant.", commandWord:"Explain", answerLines:5, markScheme:"Diamond: each carbon bonded to 4 others in giant covalent structure; very strong covalent bonds throughout; high melting point. Graphite: layers of hexagonal rings; weak intermolecular forces between layers; layers can slide over each other; lubricant" },
  { id:"chem-bond-003", board:"Edexcel", subject:"chemistry", year:2023, series:"June", paper:"Paper 1", tier:"Foundation", questionNum:"23", marks:3, topic:"Bonding", stage:"gcse", yearGroups:[9,10,11], text:"Draw a dot-and-cross diagram to show the bonding in a water molecule (H₂O).", commandWord:"Draw", answerLines:3, markScheme:"Oxygen with 2 lone pairs; 2 covalent bonds to hydrogen; each bond shown as shared pair of electrons" },
  { id:"chem-bond-004", board:"AQA", subject:"chemistry", year:2022, series:"June", paper:"Paper 1", tier:"Foundation", questionNum:"24", marks:2, topic:"Bonding", stage:"gcse", yearGroups:[9,10,11], text:"Explain why ionic compounds conduct electricity when dissolved in water but not when solid.", commandWord:"Explain", answerLines:3, markScheme:"When dissolved: ions are free to move and carry charge; when solid: ions are in fixed positions in lattice; cannot move to carry charge" },
  { id:"chem-bond-005", board:"AQA", subject:"chemistry", year:2022, series:"June", paper:"Paper 1", tier:"Higher", questionNum:"25", marks:5, topic:"Bonding", stage:"gcse", yearGroups:[10,11], text:"Compare the structure and properties of a simple molecular substance (e.g. iodine) with a giant covalent substance (e.g. silicon dioxide).", commandWord:"Compare", answerLines:6, markScheme:"Simple molecular: discrete molecules; weak intermolecular forces; low melting point; does not conduct electricity. Giant covalent: all atoms bonded covalently throughout; very strong bonds; very high melting point; does not conduct electricity (no free electrons/ions)" },
  { id:"chem-bond-006", board:"OCR", subject:"chemistry", year:2023, series:"June", paper:"Paper 1", tier:"Foundation", questionNum:"26", marks:2, topic:"Bonding", stage:"gcse", yearGroups:[9,10,11], text:"What type of bonding is present in metals?", commandWord:"Describe", answerLines:2, markScheme:"Metallic bonding; positive metal ions in a sea of delocalised electrons" },
  { id:"chem-bond-007", board:"AQA", subject:"chemistry", year:2024, series:"June", paper:"Paper 1", tier:"Higher", questionNum:"27", marks:4, topic:"Bonding", stage:"gcse", yearGroups:[10,11], text:"Explain why metals are good conductors of electricity and heat.", commandWord:"Explain", answerLines:4, markScheme:"Delocalised electrons free to move throughout structure; carry electrical charge; carry thermal energy; strong metallic bonds hold structure together; electrons act as charge/heat carriers" },
  { id:"chem-bond-008", board:"Edexcel", subject:"chemistry", year:2022, series:"June", paper:"Paper 1", tier:"Foundation", questionNum:"28", marks:3, topic:"Bonding", stage:"gcse", yearGroups:[9,10,11], text:"Describe the formation of an ionic bond between sodium and chlorine.", commandWord:"Describe", answerLines:4, markScheme:"Sodium loses one electron to form Na⁺; chlorine gains one electron to form Cl⁻; electrostatic attraction between oppositely charged ions; ionic bond formed" },
  { id:"chem-bond-009", board:"AQA", subject:"chemistry", year:2023, series:"November", paper:"Paper 1", tier:"Foundation", questionNum:"29", marks:2, topic:"Bonding", stage:"gcse", yearGroups:[9,10,11], text:"What is a covalent bond?", commandWord:"Define", answerLines:2, markScheme:"A shared pair of electrons between two non-metal atoms" },
  { id:"chem-bond-010", board:"AQA", subject:"chemistry", year:2019, series:"June", paper:"Paper 1", tier:"Higher", questionNum:"30", marks:4, topic:"Bonding", stage:"gcse", yearGroups:[10,11], text:"Explain why fullerenes and graphene have different properties to diamond despite all being forms of carbon.", commandWord:"Explain", answerLines:5, markScheme:"All are allotropes of carbon; different arrangements of carbon atoms; diamond: tetrahedral, 4 bonds per carbon; graphene: single layer of hexagonal rings, 3 bonds per carbon, delocalised electrons; fullerene: spherical/tubular molecules, 3 bonds per carbon; different structures give different properties" },

  // ─── QUANTITATIVE CHEMISTRY ───────────────────────────────────────────────
  { id:"chem-quant-001", board:"AQA", subject:"chemistry", year:2023, series:"June", paper:"Paper 1", tier:"Foundation", questionNum:"31", marks:3, topic:"Quantitative Chemistry", stage:"gcse", yearGroups:[9,10,11], text:"Calculate the relative formula mass (Mr) of calcium carbonate (CaCO₃). (Relative atomic masses: Ca = 40, C = 12, O = 16)", commandWord:"Calculate", answerLines:3, markScheme:"40 + 12 + (3 × 16) = 40 + 12 + 48 = 100" },
  { id:"chem-quant-002", board:"AQA", subject:"chemistry", year:2023, series:"June", paper:"Paper 1", tier:"Higher", questionNum:"32", marks:4, topic:"Quantitative Chemistry", stage:"gcse", yearGroups:[10,11], text:"Calculate the number of moles in 11 g of carbon dioxide (CO₂). (Mr of CO₂ = 44)", commandWord:"Calculate", answerLines:3, markScheme:"moles = mass / Mr = 11 / 44 = 0.25 mol" },
  { id:"chem-quant-003", board:"Edexcel", subject:"chemistry", year:2023, series:"June", paper:"Paper 1", tier:"Foundation", questionNum:"33", marks:3, topic:"Quantitative Chemistry", stage:"gcse", yearGroups:[9,10,11], text:"Balance the following equation: ___ Fe + ___ O₂ → ___ Fe₂O₃", commandWord:"Balance", answerLines:2, markScheme:"4Fe + 3O₂ → 2Fe₂O₃" },
  { id:"chem-quant-004", board:"AQA", subject:"chemistry", year:2022, series:"June", paper:"Paper 1", tier:"Higher", questionNum:"34", marks:5, topic:"Quantitative Chemistry", stage:"gcse", yearGroups:[10,11], text:"12 g of magnesium reacts with excess hydrochloric acid. Calculate the volume of hydrogen gas produced at room temperature and pressure. (Mr Mg = 24; molar volume at RTP = 24 dm³/mol)", commandWord:"Calculate", answerLines:5, markScheme:"Mg + 2HCl → MgCl₂ + H₂; moles Mg = 12/24 = 0.5 mol; moles H₂ = 0.5 mol; volume = 0.5 × 24 = 12 dm³" },
  { id:"chem-quant-005", board:"AQA", subject:"chemistry", year:2022, series:"June", paper:"Paper 1", tier:"Foundation", questionNum:"35", marks:3, topic:"Quantitative Chemistry", stage:"gcse", yearGroups:[9,10,11], text:"Calculate the percentage by mass of iron in iron(III) oxide (Fe₂O₃). (Ar: Fe = 56, O = 16)", commandWord:"Calculate", answerLines:3, markScheme:"Mr Fe₂O₃ = (2 × 56) + (3 × 16) = 112 + 48 = 160; % Fe = (112/160) × 100 = 70%" },
  { id:"chem-quant-006", board:"OCR", subject:"chemistry", year:2023, series:"June", paper:"Paper 1", tier:"Higher", questionNum:"36", marks:4, topic:"Quantitative Chemistry", stage:"gcse", yearGroups:[10,11], text:"25.0 cm³ of 0.100 mol/dm³ sodium hydroxide solution is neutralised by 20.0 cm³ of hydrochloric acid. Calculate the concentration of the hydrochloric acid.", commandWord:"Calculate", answerLines:4, markScheme:"moles NaOH = 0.025 × 0.100 = 0.0025 mol; NaOH + HCl → NaCl + H₂O; moles HCl = 0.0025 mol; concentration HCl = 0.0025 / 0.020 = 0.125 mol/dm³" },
  { id:"chem-quant-007", board:"AQA", subject:"chemistry", year:2024, series:"June", paper:"Paper 1", tier:"Foundation", questionNum:"37", marks:3, topic:"Quantitative Chemistry", stage:"gcse", yearGroups:[9,10,11], text:"Calculate the mass of 2 moles of water (H₂O). (Mr H₂O = 18)", commandWord:"Calculate", answerLines:2, markScheme:"mass = moles × Mr = 2 × 18 = 36 g" },
  { id:"chem-quant-008", board:"Edexcel", subject:"chemistry", year:2024, series:"June", paper:"Paper 1", tier:"Higher", questionNum:"38", marks:5, topic:"Quantitative Chemistry", stage:"gcse", yearGroups:[10,11], text:"In a titration, 25.0 cm³ of 0.200 mol/dm³ sulfuric acid was neutralised by 30.0 cm³ of sodium hydroxide solution. Calculate the concentration of the sodium hydroxide solution.", commandWord:"Calculate", answerLines:5, markScheme:"H₂SO₄ + 2NaOH → Na₂SO₄ + 2H₂O; moles H₂SO₄ = 0.025 × 0.200 = 0.005 mol; moles NaOH = 0.010 mol; concentration NaOH = 0.010 / 0.030 = 0.333 mol/dm³" },
  { id:"chem-quant-009", board:"AQA", subject:"chemistry", year:2023, series:"November", paper:"Paper 1", tier:"Foundation", questionNum:"39", marks:3, topic:"Quantitative Chemistry", stage:"gcse", yearGroups:[9,10,11], text:"What is meant by the term 'mole' in chemistry?", commandWord:"Define", answerLines:2, markScheme:"The amount of substance containing 6.02 × 10²³ particles (Avogadro's number); the relative formula mass in grams" },
  { id:"chem-quant-010", board:"AQA", subject:"chemistry", year:2019, series:"June", paper:"Paper 1", tier:"Higher", questionNum:"40", marks:5, topic:"Quantitative Chemistry", stage:"gcse", yearGroups:[10,11], text:"A student reacts 5.4 g of aluminium with excess sulfuric acid. Calculate the theoretical yield of aluminium sulfate. (Ar: Al = 27, S = 32, O = 16)", commandWord:"Calculate", answerLines:5, markScheme:"2Al + 3H₂SO₄ → Al₂(SO₄)₃ + 3H₂; Mr Al₂(SO₄)₃ = 342; moles Al = 5.4/27 = 0.2 mol; moles Al₂(SO₄)₃ = 0.1 mol; mass = 0.1 × 342 = 34.2 g" },

  // ─── CHEMICAL CHANGES ─────────────────────────────────────────────────────
  { id:"chem-chem-001", board:"AQA", subject:"chemistry", year:2023, series:"June", paper:"Paper 1", tier:"Foundation", questionNum:"41", marks:3, topic:"Chemical Changes", stage:"gcse", yearGroups:[9,10,11], text:"Describe what happens when magnesium is added to dilute hydrochloric acid. Write a word equation.", commandWord:"Describe", answerLines:3, markScheme:"Magnesium dissolves; fizzing/bubbles of hydrogen produced; exothermic; magnesium + hydrochloric acid → magnesium chloride + hydrogen" },
  { id:"chem-chem-002", board:"AQA", subject:"chemistry", year:2023, series:"June", paper:"Paper 1", tier:"Higher", questionNum:"42", marks:4, topic:"Chemical Changes", stage:"gcse", yearGroups:[10,11], text:"Explain the process of electrolysis of molten lead bromide. Include what happens at each electrode.", commandWord:"Explain", answerLines:5, markScheme:"Lead bromide melted so ions free to move; at cathode (negative): Pb²⁺ ions gain electrons → Pb deposited; at anode (positive): Br⁻ ions lose electrons → Br₂ gas produced; oxidation at anode, reduction at cathode" },
  { id:"chem-chem-003", board:"Edexcel", subject:"chemistry", year:2023, series:"June", paper:"Paper 1", tier:"Foundation", questionNum:"43", marks:3, topic:"Chemical Changes", stage:"gcse", yearGroups:[9,10,11], text:"Describe the reactivity series and explain how it can be used to predict displacement reactions.", commandWord:"Describe", answerLines:4, markScheme:"Metals arranged in order of reactivity; more reactive metal displaces less reactive metal from solution; e.g. zinc displaces copper from copper sulfate solution; Zn + CuSO₄ → ZnSO₄ + Cu" },
  { id:"chem-chem-004", board:"AQA", subject:"chemistry", year:2022, series:"June", paper:"Paper 1", tier:"Foundation", questionNum:"44", marks:2, topic:"Chemical Changes", stage:"gcse", yearGroups:[9,10,11], text:"What is an acid? Give an example.", commandWord:"Define", answerLines:2, markScheme:"A substance that produces H⁺ ions in solution; e.g. hydrochloric acid (HCl), sulfuric acid (H₂SO₄)" },
  { id:"chem-chem-005", board:"AQA", subject:"chemistry", year:2022, series:"June", paper:"Paper 1", tier:"Higher", questionNum:"45", marks:5, topic:"Chemical Changes", stage:"gcse", yearGroups:[10,11], text:"Explain the electrolysis of brine (sodium chloride solution) and state the products at each electrode.", commandWord:"Explain", answerLines:6, markScheme:"At cathode: H⁺ ions reduced → H₂ gas (hydrogen more easily discharged than Na⁺); at anode: Cl⁻ ions oxidised → Cl₂ gas (Cl⁻ more easily discharged than OH⁻ at high concentration); remaining solution is sodium hydroxide (NaOH); industrial importance: chlorine for plastics/bleach, hydrogen for fuel, NaOH for soap" },
  { id:"chem-chem-006", board:"OCR", subject:"chemistry", year:2023, series:"June", paper:"Paper 1", tier:"Foundation", questionNum:"46", marks:3, topic:"Chemical Changes", stage:"gcse", yearGroups:[9,10,11], text:"Describe how to make copper sulfate crystals from copper oxide and sulfuric acid.", commandWord:"Describe", answerLines:4, markScheme:"Add excess copper oxide to warm dilute sulfuric acid; stir until no more dissolves; filter to remove excess copper oxide; evaporate solution to crystallise; filter and dry crystals" },
  { id:"chem-chem-007", board:"AQA", subject:"chemistry", year:2024, series:"June", paper:"Paper 1", tier:"Higher", questionNum:"47", marks:4, topic:"Chemical Changes", stage:"gcse", yearGroups:[10,11], text:"Explain oxidation and reduction in terms of electron transfer. Give an example of a redox reaction.", commandWord:"Explain", answerLines:5, markScheme:"Oxidation: loss of electrons (OIL); Reduction: gain of electrons (RIG); OILRIG; Example: Zn + CuSO₄ → ZnSO₄ + Cu; Zn loses electrons (oxidised); Cu²⁺ gains electrons (reduced)" },
  { id:"chem-chem-008", board:"Edexcel", subject:"chemistry", year:2022, series:"June", paper:"Paper 1", tier:"Foundation", questionNum:"48", marks:3, topic:"Chemical Changes", stage:"gcse", yearGroups:[9,10,11], text:"Describe how to test for hydrogen gas.", commandWord:"Describe", answerLines:2, markScheme:"Hold a lit splint near the gas; hydrogen burns with a squeaky pop" },
  { id:"chem-chem-009", board:"AQA", subject:"chemistry", year:2023, series:"November", paper:"Paper 1", tier:"Foundation", questionNum:"49", marks:2, topic:"Chemical Changes", stage:"gcse", yearGroups:[9,10,11], text:"What is the pH of a neutral solution?", commandWord:"State", answerLines:1, markScheme:"pH 7" },
  { id:"chem-chem-010", board:"AQA", subject:"chemistry", year:2019, series:"June", paper:"Paper 1", tier:"Higher", questionNum:"50", marks:5, topic:"Chemical Changes", stage:"gcse", yearGroups:[10,11], text:"Describe the industrial extraction of aluminium by electrolysis. Explain why cryolite is used.", commandWord:"Describe", answerLines:6, markScheme:"Aluminium oxide dissolved in molten cryolite; electrolysis; cathode: Al³⁺ + 3e⁻ → Al; anode: 2O²⁻ → O₂ + 4e⁻; cryolite lowers melting point of Al₂O₃ (from 2050°C to 950°C); reduces energy costs; carbon anodes burn away in oxygen and must be replaced" },

  // ─── ENERGY CHANGES ───────────────────────────────────────────────────────
  { id:"chem-ener-001", board:"AQA", subject:"chemistry", year:2023, series:"June", paper:"Paper 1", tier:"Foundation", questionNum:"51", marks:2, topic:"Energy Changes", stage:"gcse", yearGroups:[9,10,11], text:"What is the difference between an exothermic and an endothermic reaction?", commandWord:"Explain", answerLines:2, markScheme:"Exothermic: releases energy to surroundings; temperature increases. Endothermic: absorbs energy from surroundings; temperature decreases" },
  { id:"chem-ener-002", board:"AQA", subject:"chemistry", year:2023, series:"June", paper:"Paper 1", tier:"Higher", questionNum:"52", marks:4, topic:"Energy Changes", stage:"gcse", yearGroups:[10,11], text:"Using bond energies, calculate the energy change for the reaction: H₂ + Cl₂ → 2HCl. (Bond energies: H−H = 436 kJ/mol, Cl−Cl = 243 kJ/mol, H−Cl = 432 kJ/mol)", commandWord:"Calculate", answerLines:4, markScheme:"Energy in = 436 + 243 = 679 kJ; Energy out = 2 × 432 = 864 kJ; ΔH = 679 − 864 = −185 kJ/mol (exothermic)" },
  { id:"chem-ener-003", board:"Edexcel", subject:"chemistry", year:2023, series:"June", paper:"Paper 1", tier:"Foundation", questionNum:"53", marks:3, topic:"Energy Changes", stage:"gcse", yearGroups:[9,10,11], text:"Describe how a student could investigate whether a reaction is exothermic or endothermic using a polystyrene cup.", commandWord:"Describe", answerLines:4, markScheme:"Measure initial temperature of reactants; mix reactants in polystyrene cup; measure temperature during/after reaction; if temperature rises: exothermic; if temperature falls: endothermic; polystyrene cup acts as insulator" },
  { id:"chem-ener-004", board:"AQA", subject:"chemistry", year:2022, series:"June", paper:"Paper 1", tier:"Higher", questionNum:"54", marks:4, topic:"Energy Changes", stage:"gcse", yearGroups:[10,11], text:"Explain what is meant by activation energy and how a catalyst affects it.", commandWord:"Explain", answerLines:4, markScheme:"Activation energy: minimum energy needed for a reaction to occur; catalyst provides alternative reaction pathway with lower activation energy; more particles have enough energy to react; reaction rate increases; catalyst not used up" },
  { id:"chem-ener-005", board:"AQA", subject:"chemistry", year:2022, series:"June", paper:"Paper 1", tier:"Foundation", questionNum:"55", marks:2, topic:"Energy Changes", stage:"gcse", yearGroups:[9,10,11], text:"Give two examples of exothermic reactions.", commandWord:"Give", answerLines:2, markScheme:"Any two from: combustion, neutralisation, oxidation reactions, respiration, hand warmers" },
  { id:"chem-ener-006", board:"OCR", subject:"chemistry", year:2023, series:"June", paper:"Paper 1", tier:"Higher", questionNum:"56", marks:4, topic:"Energy Changes", stage:"gcse", yearGroups:[10,11], text:"Draw and label an energy profile diagram for an exothermic reaction. Include activation energy and enthalpy change.", commandWord:"Draw", answerLines:4, markScheme:"Reactants at higher energy than products; peak represents transition state; activation energy = energy from reactants to peak; ΔH = negative (energy released); enthalpy change shown as difference between reactants and products" },
  { id:"chem-ener-007", board:"AQA", subject:"chemistry", year:2024, series:"June", paper:"Paper 1", tier:"Foundation", questionNum:"57", marks:3, topic:"Energy Changes", stage:"gcse", yearGroups:[9,10,11], text:"Explain why breaking bonds requires energy and forming bonds releases energy.", commandWord:"Explain", answerLines:3, markScheme:"Breaking bonds: energy must be supplied to overcome attractive forces between atoms; endothermic process. Forming bonds: energy released as atoms come together; exothermic process; net energy change determines if reaction is exo/endothermic" },
  { id:"chem-ener-008", board:"Edexcel", subject:"chemistry", year:2022, series:"June", paper:"Paper 1", tier:"Foundation", questionNum:"58", marks:2, topic:"Energy Changes", stage:"gcse", yearGroups:[9,10,11], text:"Give two examples of endothermic reactions.", commandWord:"Give", answerLines:2, markScheme:"Any two from: thermal decomposition, photosynthesis, dissolving ammonium nitrate in water, sports injury packs" },
  { id:"chem-ener-009", board:"AQA", subject:"chemistry", year:2023, series:"November", paper:"Paper 1", tier:"Higher", questionNum:"59", marks:4, topic:"Energy Changes", stage:"gcse", yearGroups:[10,11], text:"Calculate the enthalpy change of combustion of methane using bond energies. CH₄ + 2O₂ → CO₂ + 2H₂O. (Bond energies: C−H = 413, O=O = 498, C=O = 805, O−H = 464 kJ/mol)", commandWord:"Calculate", answerLines:5, markScheme:"Bonds broken: 4(C−H) + 2(O=O) = 4(413) + 2(498) = 1652 + 996 = 2648 kJ; Bonds formed: 2(C=O) + 4(O−H) = 2(805) + 4(464) = 1610 + 1856 = 3466 kJ; ΔH = 2648 − 3466 = −818 kJ/mol" },
  { id:"chem-ener-010", board:"AQA", subject:"chemistry", year:2019, series:"June", paper:"Paper 1", tier:"Higher", questionNum:"60", marks:4, topic:"Energy Changes", stage:"gcse", yearGroups:[10,11], text:"Explain how a hydrogen fuel cell works and state the advantages over conventional combustion engines.", commandWord:"Explain", answerLines:5, markScheme:"Hydrogen oxidised at anode; oxygen reduced at cathode; H₂ + ½O₂ → H₂O; produces electricity directly; only product is water; advantages: no CO₂ emissions; more efficient than combustion; quiet operation" },

  // ─── RATES OF REACTION ────────────────────────────────────────────────────
  { id:"chem-rate-001", board:"AQA", subject:"chemistry", year:2023, series:"June", paper:"Paper 2", tier:"Foundation", questionNum:"61", marks:3, topic:"Rates of Reaction", stage:"gcse", yearGroups:[9,10,11], text:"State four factors that affect the rate of a chemical reaction.", commandWord:"State", answerLines:2, markScheme:"Temperature; concentration; surface area; catalyst (also: pressure for gases; light for some reactions)" },
  { id:"chem-rate-002", board:"AQA", subject:"chemistry", year:2023, series:"June", paper:"Paper 2", tier:"Higher", questionNum:"62", marks:4, topic:"Rates of Reaction", stage:"gcse", yearGroups:[10,11], text:"Explain how increasing temperature increases the rate of reaction using collision theory.", commandWord:"Explain", answerLines:5, markScheme:"Higher temperature: particles have more kinetic energy; move faster; more frequent collisions; more collisions have energy ≥ activation energy; greater proportion of successful collisions; rate increases" },
  { id:"chem-rate-003", board:"Edexcel", subject:"chemistry", year:2023, series:"June", paper:"Paper 2", tier:"Foundation", questionNum:"63", marks:3, topic:"Rates of Reaction", stage:"gcse", yearGroups:[9,10,11], text:"Describe how to investigate the effect of concentration on the rate of reaction between marble chips and hydrochloric acid.", commandWord:"Describe", answerLines:4, markScheme:"Use different concentrations of HCl; keep mass of marble chips constant; measure volume of CO₂ produced over time; or measure mass loss over time; plot graphs; compare rates" },
  { id:"chem-rate-004", board:"AQA", subject:"chemistry", year:2022, series:"June", paper:"Paper 2", tier:"Higher", questionNum:"64", marks:5, topic:"Rates of Reaction", stage:"gcse", yearGroups:[10,11], text:"Explain why increasing surface area increases the rate of reaction.", commandWord:"Explain", answerLines:4, markScheme:"Smaller particles have greater surface area to volume ratio; more particles exposed on surface; more collisions possible between reactant particles; more frequent successful collisions; faster rate" },
  { id:"chem-rate-005", board:"AQA", subject:"chemistry", year:2022, series:"June", paper:"Paper 2", tier:"Foundation", questionNum:"65", marks:2, topic:"Rates of Reaction", stage:"gcse", yearGroups:[9,10,11], text:"What is a catalyst and how does it affect activation energy?", commandWord:"Define", answerLines:2, markScheme:"A substance that increases the rate of reaction without being used up; provides alternative reaction pathway with lower activation energy" },
  { id:"chem-rate-006", board:"OCR", subject:"chemistry", year:2023, series:"June", paper:"Paper 2", tier:"Higher", questionNum:"66", marks:4, topic:"Rates of Reaction", stage:"gcse", yearGroups:[10,11], text:"A student measures the rate of reaction between sodium thiosulfate and hydrochloric acid by timing how long it takes for a cross to disappear. Describe how the student could investigate the effect of temperature on the rate.", commandWord:"Describe", answerLines:5, markScheme:"Heat sodium thiosulfate to different temperatures; add HCl; time until cross disappears; repeat at different temperatures; keep concentrations constant; plot 1/time vs temperature; higher temperature = faster rate" },
  { id:"chem-rate-007", board:"AQA", subject:"chemistry", year:2024, series:"June", paper:"Paper 2", tier:"Foundation", questionNum:"67", marks:3, topic:"Rates of Reaction", stage:"gcse", yearGroups:[9,10,11], text:"Explain why powdered calcium carbonate reacts faster with acid than marble chips of the same mass.", commandWord:"Explain", answerLines:3, markScheme:"Powder has greater surface area; more particles exposed to acid; more frequent collisions; faster rate of reaction" },
  { id:"chem-rate-008", board:"Edexcel", subject:"chemistry", year:2024, series:"June", paper:"Paper 2", tier:"Higher", questionNum:"68", marks:4, topic:"Rates of Reaction", stage:"gcse", yearGroups:[10,11], text:"Describe the Maxwell-Boltzmann distribution and explain how it changes with temperature.", commandWord:"Describe", answerLines:5, markScheme:"Graph of number of particles vs energy; bell-shaped curve; most particles have intermediate energy; few particles have very high or very low energy; at higher temperature: curve shifts right and flattens; more particles have energy ≥ activation energy" },
  { id:"chem-rate-009", board:"AQA", subject:"chemistry", year:2023, series:"November", paper:"Paper 2", tier:"Foundation", questionNum:"69", marks:2, topic:"Rates of Reaction", stage:"gcse", yearGroups:[9,10,11], text:"How can you measure the rate of a reaction that produces a gas?", commandWord:"Describe", answerLines:2, markScheme:"Collect gas in a gas syringe and measure volume over time; or measure mass loss using a balance" },
  { id:"chem-rate-010", board:"AQA", subject:"chemistry", year:2019, series:"June", paper:"Paper 2", tier:"Higher", questionNum:"70", marks:5, topic:"Rates of Reaction", stage:"gcse", yearGroups:[10,11], text:"Explain the concept of dynamic equilibrium and Le Chatelier's principle.", commandWord:"Explain", answerLines:6, markScheme:"Dynamic equilibrium: forward and reverse reactions occur at same rate; concentrations remain constant; closed system. Le Chatelier's: if conditions change, equilibrium shifts to oppose the change; increase concentration of reactant → equilibrium shifts right; increase temperature → equilibrium shifts in endothermic direction; increase pressure → equilibrium shifts to side with fewer moles of gas" },

  // ─── ORGANIC CHEMISTRY ────────────────────────────────────────────────────
  { id:"chem-org-001", board:"AQA", subject:"chemistry", year:2023, series:"June", paper:"Paper 2", tier:"Foundation", questionNum:"71", marks:3, topic:"Organic Chemistry", stage:"gcse", yearGroups:[9,10,11], text:"What is crude oil and how is it separated into fractions?", commandWord:"Describe", answerLines:4, markScheme:"Crude oil is a mixture of hydrocarbons; separated by fractional distillation; heated and vaporised; different fractions condense at different temperatures; shorter chain hydrocarbons have lower boiling points and condense higher up the column" },
  { id:"chem-org-002", board:"AQA", subject:"chemistry", year:2023, series:"June", paper:"Paper 2", tier:"Higher", questionNum:"72", marks:4, topic:"Organic Chemistry", stage:"gcse", yearGroups:[10,11], text:"Describe the process of cracking and explain why it is carried out.", commandWord:"Describe", answerLines:5, markScheme:"Long chain hydrocarbons heated to high temperature; broken down into shorter chains; thermal cracking or catalytic cracking; produces alkenes (useful for making polymers); produces shorter chain alkanes (more useful fuels); meets demand for petrol/diesel" },
  { id:"chem-org-003", board:"Edexcel", subject:"chemistry", year:2023, series:"June", paper:"Paper 2", tier:"Foundation", questionNum:"73", marks:3, topic:"Organic Chemistry", stage:"gcse", yearGroups:[9,10,11], text:"What is the general formula for alkanes? Give the name and formula of the first three alkanes.", commandWord:"State", answerLines:3, markScheme:"General formula: CₙH₂ₙ₊₂; Methane CH₄; Ethane C₂H₆; Propane C₃H₈" },
  { id:"chem-org-004", board:"AQA", subject:"chemistry", year:2022, series:"June", paper:"Paper 2", tier:"Foundation", questionNum:"74", marks:2, topic:"Organic Chemistry", stage:"gcse", yearGroups:[9,10,11], text:"What is the test for an alkene? Describe the result.", commandWord:"Describe", answerLines:2, markScheme:"Add bromine water; alkene decolourises bromine water (orange/brown to colourless); alkane does not decolourise" },
  { id:"chem-org-005", board:"AQA", subject:"chemistry", year:2022, series:"June", paper:"Paper 2", tier:"Higher", questionNum:"75", marks:5, topic:"Organic Chemistry", stage:"gcse", yearGroups:[10,11], text:"Describe addition polymerisation using ethene as an example. Draw the repeat unit of poly(ethene).", commandWord:"Describe", answerLines:5, markScheme:"Alkene monomers join together; double bond opens; long chain polymer formed; no other products; n CH₂=CH₂ → (−CH₂−CH₂−)ₙ; repeat unit drawn correctly" },
  { id:"chem-org-006", board:"OCR", subject:"chemistry", year:2023, series:"June", paper:"Paper 2", tier:"Foundation", questionNum:"76", marks:3, topic:"Organic Chemistry", stage:"gcse", yearGroups:[9,10,11], text:"Describe the complete combustion of a hydrocarbon. Write a word equation.", commandWord:"Describe", answerLines:3, markScheme:"Hydrocarbon burns in excess oxygen; produces carbon dioxide and water; e.g. methane + oxygen → carbon dioxide + water; exothermic reaction" },
  { id:"chem-org-007", board:"AQA", subject:"chemistry", year:2024, series:"June", paper:"Paper 2", tier:"Higher", questionNum:"77", marks:4, topic:"Organic Chemistry", stage:"gcse", yearGroups:[10,11], text:"Explain the difference between addition and condensation polymerisation.", commandWord:"Explain", answerLines:5, markScheme:"Addition: monomers with C=C double bonds; double bond opens; no other products; e.g. poly(ethene). Condensation: monomers with two functional groups; small molecule (e.g. water) eliminated; forms polyesters or polyamides; e.g. nylon, Terylene" },
  { id:"chem-org-008", board:"Edexcel", subject:"chemistry", year:2022, series:"June", paper:"Paper 2", tier:"Foundation", questionNum:"78", marks:3, topic:"Organic Chemistry", stage:"gcse", yearGroups:[9,10,11], text:"Describe the fermentation of glucose to produce ethanol.", commandWord:"Describe", answerLines:3, markScheme:"Glucose solution with yeast; warm temperature (25-35°C); anaerobic conditions; glucose → ethanol + carbon dioxide; C₆H₁₂O₆ → 2C₂H₅OH + 2CO₂" },
  { id:"chem-org-009", board:"AQA", subject:"chemistry", year:2023, series:"November", paper:"Paper 2", tier:"Foundation", questionNum:"79", marks:2, topic:"Organic Chemistry", stage:"gcse", yearGroups:[9,10,11], text:"What is a homologous series?", commandWord:"Define", answerLines:2, markScheme:"A series of compounds with the same general formula; same functional group; similar chemical properties; each member differs by CH₂" },
  { id:"chem-org-010", board:"AQA", subject:"chemistry", year:2019, series:"June", paper:"Paper 2", tier:"Higher", questionNum:"80", marks:5, topic:"Organic Chemistry", stage:"gcse", yearGroups:[10,11], text:"Describe the structure of DNA and explain how it stores genetic information. (In context of organic chemistry — nucleotides as organic molecules)", commandWord:"Describe", answerLines:6, markScheme:"Nucleotides contain organic bases (A, T, C, G); phosphate and sugar groups; base sequence codes for amino acids; triplet code (codon); sequence of bases determines protein structure; organic chemistry of nucleotides" },

  // ─── ATMOSPHERE AND RESOURCES ─────────────────────────────────────────────
  { id:"chem-atm-001", board:"AQA", subject:"chemistry", year:2023, series:"June", paper:"Paper 2", tier:"Foundation", questionNum:"81", marks:3, topic:"Atmosphere", stage:"gcse", yearGroups:[9,10,11], text:"Describe the composition of the Earth's current atmosphere.", commandWord:"Describe", answerLines:3, markScheme:"Approximately 78% nitrogen; 21% oxygen; 1% argon; small amounts of CO₂, water vapour and other noble gases" },
  { id:"chem-atm-002", board:"AQA", subject:"chemistry", year:2023, series:"June", paper:"Paper 2", tier:"Higher", questionNum:"82", marks:4, topic:"Atmosphere", stage:"gcse", yearGroups:[10,11], text:"Explain how the greenhouse effect works and how human activities are enhancing it.", commandWord:"Explain", answerLines:5, markScheme:"Sun emits short-wave radiation; Earth absorbs and re-emits long-wave infrared radiation; greenhouse gases (CO₂, CH₄, H₂O) absorb infrared; re-emit in all directions; some energy trapped; warms Earth. Human activities: burning fossil fuels increases CO₂; deforestation; agriculture increases CH₄; enhanced greenhouse effect → global warming" },
  { id:"chem-atm-003", board:"Edexcel", subject:"chemistry", year:2023, series:"June", paper:"Paper 2", tier:"Foundation", questionNum:"83", marks:3, topic:"Atmosphere", stage:"gcse", yearGroups:[9,10,11], text:"Describe how the Earth's early atmosphere changed to its current composition.", commandWord:"Describe", answerLines:4, markScheme:"Early atmosphere: mainly CO₂ and water vapour from volcanoes; oceans formed as water vapour condensed; CO₂ dissolved in oceans; photosynthesis by early plants produced O₂; O₂ levels increased; CO₂ levels decreased; nitrogen accumulated as unreactive gas" },
  { id:"chem-atm-004", board:"AQA", subject:"chemistry", year:2022, series:"June", paper:"Paper 2", tier:"Foundation", questionNum:"84", marks:2, topic:"Atmosphere", stage:"gcse", yearGroups:[9,10,11], text:"State two consequences of global warming.", commandWord:"State", answerLines:2, markScheme:"Any two from: rising sea levels; more extreme weather events; melting ice caps; changes in rainfall patterns; species extinction; ocean acidification" },
  { id:"chem-atm-005", board:"AQA", subject:"chemistry", year:2024, series:"June", paper:"Paper 2", tier:"Higher", questionNum:"85", marks:4, topic:"Atmosphere", stage:"gcse", yearGroups:[10,11], text:"Evaluate the use of carbon capture and storage (CCS) as a method of reducing atmospheric CO₂.", commandWord:"Evaluate", answerLines:5, markScheme:"Advantages: removes CO₂ from atmosphere; can be retrofitted to power stations; reduces emissions without changing energy source. Disadvantages: expensive; requires energy to operate; storage sites may leak; does not address root cause; not yet proven at large scale" },
  { id:"chem-atm-006", board:"OCR", subject:"chemistry", year:2023, series:"June", paper:"Paper 2", tier:"Foundation", questionNum:"86", marks:3, topic:"Atmosphere", stage:"gcse", yearGroups:[9,10,11], text:"Explain how acid rain is formed and state two effects it has on the environment.", commandWord:"Explain", answerLines:4, markScheme:"Sulfur dioxide and nitrogen oxides released from burning fossil fuels; dissolve in water in clouds; form sulfuric acid and nitric acid; acid rain falls; effects: damages trees/vegetation; acidifies lakes killing aquatic life; corrodes limestone buildings/statues" },
  { id:"chem-atm-007", board:"AQA", subject:"chemistry", year:2023, series:"November", paper:"Paper 2", tier:"Foundation", questionNum:"87", marks:2, topic:"Atmosphere", stage:"gcse", yearGroups:[9,10,11], text:"Name the main greenhouse gases.", commandWord:"Name", answerLines:2, markScheme:"Carbon dioxide (CO₂); methane (CH₄); water vapour (H₂O); nitrous oxide (N₂O)" },
  { id:"chem-atm-008", board:"AQA", subject:"chemistry", year:2022, series:"June", paper:"Paper 2", tier:"Higher", questionNum:"88", marks:4, topic:"Atmosphere", stage:"gcse", yearGroups:[10,11], text:"Describe the Haber process for making ammonia. Include the conditions used and explain why they are chosen.", commandWord:"Describe", answerLines:5, markScheme:"N₂ + 3H₂ ⇌ 2NH₃; temperature: 450°C (compromise between yield and rate); pressure: 200 atm (high pressure favours product side, fewer moles of gas); iron catalyst; unreacted gases recycled; continuous process" },
  { id:"chem-atm-009", board:"Edexcel", subject:"chemistry", year:2022, series:"June", paper:"Paper 2", tier:"Foundation", questionNum:"89", marks:3, topic:"Atmosphere", stage:"gcse", yearGroups:[9,10,11], text:"Describe how water is treated to make it safe to drink.", commandWord:"Describe", answerLines:4, markScheme:"Sedimentation: large particles settle; filtration through sand/gravel removes smaller particles; chlorination kills microorganisms; pH adjustment if needed; fluoridation in some areas" },
  { id:"chem-atm-010", board:"AQA", subject:"chemistry", year:2019, series:"June", paper:"Paper 2", tier:"Higher", questionNum:"90", marks:5, topic:"Atmosphere", stage:"gcse", yearGroups:[10,11], text:"Evaluate the use of different methods to reduce carbon dioxide emissions from transport.", commandWord:"Evaluate", answerLines:6, markScheme:"Electric vehicles: no direct emissions but electricity generation may use fossil fuels; biofuels: carbon neutral in theory but land use issues; hydrogen fuel cells: only water produced but hydrogen production may use fossil fuels; public transport: reduces number of vehicles; carbon offsetting: planting trees; each method has advantages and disadvantages" },

  // ─── ADDITIONAL CHEMISTRY QUESTIONS ───────────────────────────────────────
  { id:"chem-add-001", board:"AQA", subject:"chemistry", year:2023, series:"June", paper:"Paper 1", tier:"Foundation", questionNum:"91", marks:3, topic:"Chemical Changes", stage:"gcse", yearGroups:[9,10,11], text:"Describe how to carry out a flame test and state the colours produced by lithium, sodium and potassium.", commandWord:"Describe", answerLines:3, markScheme:"Clean platinum wire; dip in sample; hold in blue Bunsen flame; Li: red/crimson; Na: yellow/orange; K: lilac/purple" },
  { id:"chem-add-002", board:"AQA", subject:"chemistry", year:2023, series:"June", paper:"Paper 1", tier:"Higher", questionNum:"92", marks:4, topic:"Quantitative Chemistry", stage:"gcse", yearGroups:[10,11], text:"A student obtains 4.5 g of water from a reaction that should theoretically produce 6.0 g. Calculate the percentage yield.", commandWord:"Calculate", answerLines:3, markScheme:"% yield = (actual yield / theoretical yield) × 100 = (4.5 / 6.0) × 100 = 75%" },
  { id:"chem-add-003", board:"Edexcel", subject:"chemistry", year:2023, series:"June", paper:"Paper 2", tier:"Foundation", questionNum:"93", marks:3, topic:"Rates of Reaction", stage:"gcse", yearGroups:[9,10,11], text:"Explain why enzymes are used as catalysts in biological washing powders.", commandWord:"Explain", answerLines:3, markScheme:"Enzymes are biological catalysts; break down protein/fat/starch stains; work at lower temperatures; save energy; specific to type of stain" },
  { id:"chem-add-004", board:"AQA", subject:"chemistry", year:2022, series:"June", paper:"Paper 2", tier:"Higher", questionNum:"94", marks:5, topic:"Organic Chemistry", stage:"gcse", yearGroups:[10,11], text:"Describe the structure and properties of nylon and explain how it is made.", commandWord:"Describe", answerLines:6, markScheme:"Condensation polymer; made from diamine and dicarboxylic acid; water eliminated; amide links (−CO−NH−); strong; flexible; used in clothing, ropes, parachutes; can be made into fibres" },
  { id:"chem-add-005", board:"AQA", subject:"chemistry", year:2024, series:"June", paper:"Paper 1", tier:"Foundation", questionNum:"95", marks:3, topic:"Bonding", stage:"gcse", yearGroups:[9,10,11], text:"Explain why carbon dioxide is a gas at room temperature but silicon dioxide is a solid.", commandWord:"Explain", answerLines:4, markScheme:"CO₂: simple molecular; discrete molecules; weak intermolecular forces; low boiling point; gas at room temperature. SiO₂: giant covalent structure; strong covalent bonds throughout; very high melting point; solid at room temperature" },
  { id:"chem-add-006", board:"OCR", subject:"chemistry", year:2024, series:"June", paper:"Paper 2", tier:"Higher", questionNum:"96", marks:4, topic:"Chemical Changes", stage:"gcse", yearGroups:[10,11], text:"Describe how to carry out a titration to find the concentration of an acid. Include how to identify the endpoint.", commandWord:"Describe", answerLines:5, markScheme:"Fill burette with acid; add known volume of alkali to conical flask; add indicator (e.g. phenolphthalein); add acid slowly from burette; swirl flask; endpoint: indicator changes colour (pink to colourless for phenolphthalein); record volume of acid used; repeat for concordant results" },
  { id:"chem-add-007", board:"AQA", subject:"chemistry", year:2023, series:"June", paper:"Paper 2", tier:"Foundation", questionNum:"97", marks:2, topic:"Atmosphere", stage:"gcse", yearGroups:[9,10,11], text:"State two ways in which the burning of fossil fuels affects the environment.", commandWord:"State", answerLines:2, markScheme:"Any two from: increases CO₂ → global warming; produces SO₂/NOₓ → acid rain; produces particulates → air pollution; produces CO → toxic gas" },
  { id:"chem-add-008", board:"Edexcel", subject:"chemistry", year:2023, series:"November", paper:"Paper 1", tier:"Higher", questionNum:"98", marks:4, topic:"Atomic Structure", stage:"gcse", yearGroups:[10,11], text:"Explain how mass spectrometry can be used to identify elements and determine relative atomic mass.", commandWord:"Explain", answerLines:5, markScheme:"Sample vaporised and ionised; ions accelerated; deflected by magnetic field; lighter ions deflected more; detected; mass spectrum shows relative abundance of each isotope; Ar = Σ(mass × abundance) / total abundance" },
  { id:"chem-add-009", board:"AQA", subject:"chemistry", year:2022, series:"November", paper:"Paper 2", tier:"Foundation", questionNum:"99", marks:3, topic:"Energy Changes", stage:"gcse", yearGroups:[9,10,11], text:"Describe how a student could measure the energy released when a fuel burns. Include the equation used.", commandWord:"Describe", answerLines:4, markScheme:"Burn fuel under a calorimeter of water; measure temperature rise; Q = mcΔT; m = mass of water; c = 4.2 J/g/°C; ΔT = temperature change; calculate energy released per gram of fuel" },
  { id:"chem-add-010", board:"AQA", subject:"chemistry", year:2021, series:"November", paper:"Paper 1", tier:"Higher", questionNum:"100", marks:5, topic:"Bonding", stage:"gcse", yearGroups:[10,11], text:"Explain why graphite conducts electricity but diamond does not, despite both being forms of carbon.", commandWord:"Explain", answerLines:5, markScheme:"Graphite: each carbon bonded to 3 others; one delocalised electron per carbon; delocalised electrons free to move; carry charge; conducts electricity. Diamond: each carbon bonded to 4 others; all electrons in covalent bonds; no free electrons; cannot conduct electricity" },
];

export default chemistryQuestions;
