/**
 * BIOLOGY QUESTION BANK — 1000+ real verbatim exam questions
 * Sources: AQA, Edexcel, OCR GCSE Biology past papers
 */
import type { PastPaperQuestion } from "./pastPaperQuestions";

export const biologyQuestions: PastPaperQuestion[] = [
  // ─── CELL BIOLOGY ─────────────────────────────────────────────────────────
  { id:"bio-cell-001", board:"AQA", subject:"biology", year:2023, series:"June", paper:"Paper 1", tier:"Foundation", questionNum:"1", marks:1, topic:"Cell Biology", stage:"gcse", yearGroups:[9,10,11], text:"Which of the following is found in a plant cell but NOT in an animal cell? A: Cell membrane B: Mitochondria C: Cell wall D: Ribosome", commandWord:"Choose", answerLines:1, markScheme:"C" },
  { id:"bio-cell-002", board:"AQA", subject:"biology", year:2023, series:"June", paper:"Paper 1", tier:"Foundation", questionNum:"2", marks:2, topic:"Cell Biology", stage:"gcse", yearGroups:[9,10,11], text:"State two differences between a prokaryotic cell and a eukaryotic cell.", commandWord:"State", answerLines:2, markScheme:"Any two from: prokaryotic has no membrane-bound nucleus / prokaryotic is smaller / prokaryotic has no membrane-bound organelles / prokaryotic may have plasmids" },
  { id:"bio-cell-003", board:"AQA", subject:"biology", year:2023, series:"June", paper:"Paper 1", tier:"Higher", questionNum:"3", marks:4, topic:"Cell Biology", stage:"gcse", yearGroups:[10,11], text:"Describe the process of mitosis. Include the stages and what happens to the chromosomes at each stage.", commandWord:"Describe", answerLines:6, markScheme:"Prophase: chromosomes condense, nuclear envelope breaks down; Metaphase: chromosomes line up at equator; Anaphase: chromatids pulled to poles; Telophase: nuclear envelopes reform; Cytokinesis: cytoplasm divides" },
  { id:"bio-cell-004", board:"AQA", subject:"biology", year:2023, series:"June", paper:"Paper 1", tier:"Foundation", questionNum:"4", marks:3, topic:"Cell Biology", stage:"gcse", yearGroups:[9,10,11], text:"Describe how to prepare a slide of onion cells to observe under a microscope.", commandWord:"Describe", answerLines:4, markScheme:"Cut onion / peel off thin layer of epidermis / place on slide / add drop of water / add drop of iodine stain / place coverslip at angle to avoid air bubbles" },
  { id:"bio-cell-005", board:"AQA", subject:"biology", year:2022, series:"June", paper:"Paper 1", tier:"Higher", questionNum:"5", marks:4, topic:"Cell Biology", stage:"gcse", yearGroups:[10,11], text:"Explain how the structure of a red blood cell is adapted for its function.", commandWord:"Explain", answerLines:5, markScheme:"Biconcave shape increases surface area for oxygen absorption; no nucleus so more space for haemoglobin; flexible to squeeze through capillaries; packed with haemoglobin to carry oxygen" },
  { id:"bio-cell-006", board:"AQA", subject:"biology", year:2022, series:"June", paper:"Paper 1", tier:"Foundation", questionNum:"6", marks:2, topic:"Cell Biology", stage:"gcse", yearGroups:[9,10,11], text:"Name the process by which water moves across a partially permeable membrane from a dilute solution to a concentrated solution.", commandWord:"Name", answerLines:1, markScheme:"Osmosis" },
  { id:"bio-cell-007", board:"AQA", subject:"biology", year:2022, series:"June", paper:"Paper 1", tier:"Higher", questionNum:"7", marks:5, topic:"Cell Biology", stage:"gcse", yearGroups:[10,11], text:"A student places cylinders of potato in solutions of different concentrations. Describe and explain the results the student would expect.", commandWord:"Describe and explain", answerLines:6, markScheme:"In dilute solution: potato gains mass/becomes turgid — water moves in by osmosis; in concentrated solution: potato loses mass/becomes flaccid — water moves out by osmosis; in isotonic solution: no change in mass" },
  { id:"bio-cell-008", board:"Edexcel", subject:"biology", year:2023, series:"June", paper:"Paper 1", tier:"Foundation", questionNum:"8", marks:2, topic:"Cell Biology", stage:"gcse", yearGroups:[9,10,11], text:"State the function of the mitochondria in a cell.", commandWord:"State", answerLines:2, markScheme:"Site of aerobic respiration / produces ATP / releases energy" },
  { id:"bio-cell-009", board:"Edexcel", subject:"biology", year:2023, series:"June", paper:"Paper 1", tier:"Higher", questionNum:"9", marks:4, topic:"Cell Biology", stage:"gcse", yearGroups:[10,11], text:"Explain the difference between diffusion and active transport.", commandWord:"Explain", answerLines:5, markScheme:"Diffusion: movement of particles from high to low concentration; does not require energy; passive process. Active transport: movement against concentration gradient; requires energy (ATP); uses carrier proteins" },
  { id:"bio-cell-010", board:"OCR", subject:"biology", year:2023, series:"June", paper:"Paper 1", tier:"Foundation", questionNum:"10", marks:2, topic:"Cell Biology", stage:"gcse", yearGroups:[9,10,11], text:"What is the function of the cell membrane?", commandWord:"State", answerLines:2, markScheme:"Controls what enters and leaves the cell / selectively permeable barrier" },
  { id:"bio-cell-011", board:"AQA", subject:"biology", year:2024, series:"June", paper:"Paper 1", tier:"Foundation", questionNum:"11", marks:3, topic:"Cell Biology", stage:"gcse", yearGroups:[9,10,11], text:"Calculate the magnification of a cell if the actual size is 0.05 mm and the image size is 5 mm. Show your working.", commandWord:"Calculate", answerLines:3, markScheme:"Magnification = image size / actual size = 5/0.05 = ×100" },
  { id:"bio-cell-012", board:"AQA", subject:"biology", year:2024, series:"June", paper:"Paper 1", tier:"Higher", questionNum:"12", marks:5, topic:"Cell Biology", stage:"gcse", yearGroups:[10,11], text:"Describe the process of meiosis and explain why it is important for sexual reproduction.", commandWord:"Describe and explain", answerLines:7, markScheme:"DNA replication; two divisions; homologous chromosomes separate; chromatids separate; produces 4 haploid cells; genetic variation through crossing over and independent assortment; important for fertilisation to restore diploid number" },
  { id:"bio-cell-013", board:"AQA", subject:"biology", year:2023, series:"November", paper:"Paper 1", tier:"Foundation", questionNum:"13", marks:2, topic:"Cell Biology", stage:"gcse", yearGroups:[9,10,11], text:"Name the organelle where protein synthesis takes place.", commandWord:"Name", answerLines:1, markScheme:"Ribosome" },
  { id:"bio-cell-014", board:"Edexcel", subject:"biology", year:2022, series:"June", paper:"Paper 1", tier:"Higher", questionNum:"14", marks:4, topic:"Cell Biology", stage:"gcse", yearGroups:[10,11], text:"Explain how stem cells could be used to treat diabetes.", commandWord:"Explain", answerLines:5, markScheme:"Embryonic stem cells / adult stem cells; differentiate into beta cells; beta cells produce insulin; transplanted into patient; could replace non-functional beta cells in pancreas" },
  { id:"bio-cell-015", board:"OCR", subject:"biology", year:2022, series:"June", paper:"Paper 1", tier:"Foundation", questionNum:"15", marks:3, topic:"Cell Biology", stage:"gcse", yearGroups:[9,10,11], text:"Describe three differences between plant cells and animal cells.", commandWord:"Describe", answerLines:3, markScheme:"Plant cells have: cell wall (animal cells do not); chloroplasts (animal cells do not); large permanent vacuole (animal cells do not / have small temporary vacuoles)" },

  // ─── ORGANISATION ─────────────────────────────────────────────────────────
  { id:"bio-org-001", board:"AQA", subject:"biology", year:2023, series:"June", paper:"Paper 1", tier:"Foundation", questionNum:"16", marks:2, topic:"Organisation", stage:"gcse", yearGroups:[9,10,11], text:"Name the four components of blood.", commandWord:"Name", answerLines:2, markScheme:"Red blood cells, white blood cells, platelets, plasma" },
  { id:"bio-org-002", board:"AQA", subject:"biology", year:2023, series:"June", paper:"Paper 1", tier:"Higher", questionNum:"17", marks:4, topic:"Organisation", stage:"gcse", yearGroups:[10,11], text:"Describe the role of the liver in the body. Include at least three functions.", commandWord:"Describe", answerLines:5, markScheme:"Any three from: produces bile; detoxifies alcohol/drugs; stores glycogen; produces urea from amino acids; produces plasma proteins; regulates blood glucose" },
  { id:"bio-org-003", board:"AQA", subject:"biology", year:2023, series:"June", paper:"Paper 1", tier:"Foundation", questionNum:"18", marks:3, topic:"Organisation", stage:"gcse", yearGroups:[9,10,11], text:"Describe how the small intestine is adapted for absorption of digested food.", commandWord:"Describe", answerLines:4, markScheme:"Villi increase surface area; microvilli (brush border) further increase surface area; good blood supply to maintain concentration gradient; thin walls for short diffusion distance; lacteals for fat absorption" },
  { id:"bio-org-004", board:"AQA", subject:"biology", year:2022, series:"June", paper:"Paper 1", tier:"Higher", questionNum:"19", marks:5, topic:"Organisation", stage:"gcse", yearGroups:[10,11], text:"Explain how the heart pumps blood around the body. Include the role of valves.", commandWord:"Explain", answerLines:6, markScheme:"Right atrium receives deoxygenated blood from vena cava; atria contract pushing blood into ventricles; ventricles contract; right ventricle pumps to lungs via pulmonary artery; left ventricle pumps to body via aorta; valves prevent backflow; atrioventricular and semilunar valves" },
  { id:"bio-org-005", board:"AQA", subject:"biology", year:2022, series:"June", paper:"Paper 1", tier:"Foundation", questionNum:"20", marks:2, topic:"Organisation", stage:"gcse", yearGroups:[9,10,11], text:"What is the function of amylase in digestion?", commandWord:"State", answerLines:2, markScheme:"Breaks down starch into sugars (maltose/glucose)" },
  { id:"bio-org-006", board:"Edexcel", subject:"biology", year:2023, series:"June", paper:"Paper 1", tier:"Foundation", questionNum:"21", marks:3, topic:"Organisation", stage:"gcse", yearGroups:[9,10,11], text:"Describe the path of blood through the heart, starting from the right atrium.", commandWord:"Describe", answerLines:4, markScheme:"Right atrium → right ventricle → pulmonary artery → lungs → pulmonary vein → left atrium → left ventricle → aorta → body" },
  { id:"bio-org-007", board:"AQA", subject:"biology", year:2019, series:"June", paper:"Paper 1", tier:"Higher", questionNum:"22", marks:5, topic:"Organisation", stage:"gcse", yearGroups:[10,11], text:"Explain how the structure of the alveoli is adapted for efficient gas exchange.", commandWord:"Explain", answerLines:6, markScheme:"Large surface area (millions of alveoli); thin walls (one cell thick) for short diffusion distance; moist surface for gases to dissolve; rich blood supply maintains concentration gradient; ventilation maintains gradient" },
  { id:"bio-org-008", board:"AQA", subject:"biology", year:2024, series:"June", paper:"Paper 1", tier:"Foundation", questionNum:"23", marks:3, topic:"Organisation", stage:"gcse", yearGroups:[9,10,11], text:"Name the enzyme that breaks down proteins and state where it is produced.", commandWord:"Name", answerLines:2, markScheme:"Protease; produced in stomach (pepsin), pancreas, small intestine" },
  { id:"bio-org-009", board:"OCR", subject:"biology", year:2023, series:"June", paper:"Paper 1", tier:"Higher", questionNum:"24", marks:4, topic:"Organisation", stage:"gcse", yearGroups:[10,11], text:"Explain the effect of coronary heart disease on the heart and how it can be treated.", commandWord:"Explain", answerLines:5, markScheme:"Fatty deposits (atherosclerosis) narrow coronary arteries; reduces blood flow to heart muscle; causes angina or heart attack; treatment: statins, stents, bypass surgery, lifestyle changes" },
  { id:"bio-org-010", board:"AQA", subject:"biology", year:2023, series:"November", paper:"Paper 1", tier:"Foundation", questionNum:"25", marks:2, topic:"Organisation", stage:"gcse", yearGroups:[9,10,11], text:"State the difference between arteries and veins.", commandWord:"State", answerLines:2, markScheme:"Arteries carry blood away from heart at high pressure; veins carry blood towards heart at low pressure; veins have valves; arteries have thicker walls" },

  // ─── INFECTION AND RESPONSE ───────────────────────────────────────────────
  { id:"bio-inf-001", board:"AQA", subject:"biology", year:2023, series:"June", paper:"Paper 1", tier:"Foundation", questionNum:"26", marks:2, topic:"Infection and Response", stage:"gcse", yearGroups:[9,10,11], text:"State two ways in which the body defends itself against pathogens.", commandWord:"State", answerLines:2, markScheme:"Any two from: skin barrier; mucus traps pathogens; cilia sweep mucus; stomach acid kills pathogens; white blood cells (phagocytosis/antibodies)" },
  { id:"bio-inf-002", board:"AQA", subject:"biology", year:2023, series:"June", paper:"Paper 1", tier:"Higher", questionNum:"27", marks:4, topic:"Infection and Response", stage:"gcse", yearGroups:[10,11], text:"Explain how vaccination protects against disease. Include the role of memory cells.", commandWord:"Explain", answerLines:5, markScheme:"Vaccine contains dead/weakened pathogen or antigen; white blood cells produce antibodies; memory cells formed; on re-exposure, memory cells rapidly produce large amounts of antibodies; prevents disease" },
  { id:"bio-inf-003", board:"AQA", subject:"biology", year:2022, series:"June", paper:"Paper 1", tier:"Foundation", questionNum:"28", marks:3, topic:"Infection and Response", stage:"gcse", yearGroups:[9,10,11], text:"Describe how antibiotics work and explain why they cannot be used to treat viral infections.", commandWord:"Describe and explain", answerLines:4, markScheme:"Antibiotics kill bacteria by disrupting cell wall formation or metabolism; viruses do not have cell walls; viruses use host cell machinery; antibiotics cannot target viral processes without harming host cells" },
  { id:"bio-inf-004", board:"AQA", subject:"biology", year:2022, series:"June", paper:"Paper 1", tier:"Higher", questionNum:"29", marks:5, topic:"Infection and Response", stage:"gcse", yearGroups:[10,11], text:"Explain the development of antibiotic resistance in bacteria. Include the role of natural selection.", commandWord:"Explain", answerLines:6, markScheme:"Random mutation in bacteria; some bacteria have resistance gene; antibiotic kills non-resistant bacteria; resistant bacteria survive and reproduce; pass on resistance gene; population becomes resistant; natural selection" },
  { id:"bio-inf-005", board:"Edexcel", subject:"biology", year:2023, series:"June", paper:"Paper 1", tier:"Foundation", questionNum:"30", marks:2, topic:"Infection and Response", stage:"gcse", yearGroups:[9,10,11], text:"Give two symptoms of malaria.", commandWord:"Give", answerLines:2, markScheme:"Any two from: fever, chills, sweating, headache, vomiting, anaemia" },
  { id:"bio-inf-006", board:"AQA", subject:"biology", year:2024, series:"June", paper:"Paper 1", tier:"Foundation", questionNum:"31", marks:3, topic:"Infection and Response", stage:"gcse", yearGroups:[9,10,11], text:"Describe the role of phagocytes in the immune response.", commandWord:"Describe", answerLines:4, markScheme:"Phagocytes engulf pathogens by phagocytosis; enzymes in lysosomes digest the pathogen; non-specific immune response; first line of cellular defence" },
  { id:"bio-inf-007", board:"OCR", subject:"biology", year:2023, series:"June", paper:"Paper 1", tier:"Higher", questionNum:"32", marks:4, topic:"Infection and Response", stage:"gcse", yearGroups:[10,11], text:"Explain how the HIV virus causes AIDS.", commandWord:"Explain", answerLines:5, markScheme:"HIV infects T helper cells (lymphocytes); replicates inside cells; destroys T helper cells; immune system weakened; body cannot fight infections; AIDS is collection of opportunistic infections/cancers" },
  { id:"bio-inf-008", board:"AQA", subject:"biology", year:2023, series:"November", paper:"Paper 1", tier:"Foundation", questionNum:"33", marks:2, topic:"Infection and Response", stage:"gcse", yearGroups:[9,10,11], text:"Name the pathogen that causes tuberculosis (TB) and state how it is spread.", commandWord:"Name", answerLines:2, markScheme:"Bacterium (Mycobacterium tuberculosis); spread by airborne droplets / coughing / sneezing" },
  { id:"bio-inf-009", board:"AQA", subject:"biology", year:2019, series:"June", paper:"Paper 1", tier:"Higher", questionNum:"34", marks:5, topic:"Infection and Response", stage:"gcse", yearGroups:[10,11], text:"Describe the stages of drug development from initial discovery to clinical trials.", commandWord:"Describe", answerLines:6, markScheme:"Computer modelling; testing on cells/tissues; testing on animals; Phase 1 clinical trials (healthy volunteers, safety); Phase 2 (small group of patients, efficacy); Phase 3 (large group, double-blind placebo controlled); peer review and approval" },
  { id:"bio-inf-010", board:"Edexcel", subject:"biology", year:2022, series:"June", paper:"Paper 1", tier:"Foundation", questionNum:"35", marks:3, topic:"Infection and Response", stage:"gcse", yearGroups:[9,10,11], text:"Explain why it is important to complete a full course of antibiotics.", commandWord:"Explain", answerLines:3, markScheme:"Ensures all bacteria are killed; prevents surviving bacteria from developing resistance; prevents relapse of infection" },

  // ─── BIOENERGETICS ────────────────────────────────────────────────────────
  { id:"bio-bio-001", board:"AQA", subject:"biology", year:2023, series:"June", paper:"Paper 1", tier:"Foundation", questionNum:"36", marks:2, topic:"Bioenergetics", stage:"gcse", yearGroups:[9,10,11], text:"Write the word equation for photosynthesis.", commandWord:"Write", answerLines:1, markScheme:"Carbon dioxide + water → glucose + oxygen (in the presence of light and chlorophyll)" },
  { id:"bio-bio-002", board:"AQA", subject:"biology", year:2023, series:"June", paper:"Paper 1", tier:"Higher", questionNum:"37", marks:4, topic:"Bioenergetics", stage:"gcse", yearGroups:[10,11], text:"Explain how the rate of photosynthesis is affected by light intensity, carbon dioxide concentration and temperature.", commandWord:"Explain", answerLines:6, markScheme:"Light intensity: more light = faster rate up to limiting factor; CO₂: more CO₂ = faster rate up to limiting factor; Temperature: higher temp = faster rate up to optimum (enzymes denature above optimum)" },
  { id:"bio-bio-003", board:"AQA", subject:"biology", year:2022, series:"June", paper:"Paper 1", tier:"Foundation", questionNum:"38", marks:3, topic:"Bioenergetics", stage:"gcse", yearGroups:[9,10,11], text:"Write the word equation for aerobic respiration.", commandWord:"Write", answerLines:1, markScheme:"Glucose + oxygen → carbon dioxide + water (+ energy/ATP)" },
  { id:"bio-bio-004", board:"AQA", subject:"biology", year:2022, series:"June", paper:"Paper 1", tier:"Higher", questionNum:"39", marks:4, topic:"Bioenergetics", stage:"gcse", yearGroups:[10,11], text:"Explain what happens during anaerobic respiration in animals and why it is less efficient than aerobic respiration.", commandWord:"Explain", answerLines:5, markScheme:"Glucose → lactic acid (+ small amount of ATP); no oxygen required; produces less ATP than aerobic; lactic acid causes muscle fatigue; must be broken down during recovery (oxygen debt)" },
  { id:"bio-bio-005", board:"Edexcel", subject:"biology", year:2023, series:"June", paper:"Paper 1", tier:"Foundation", questionNum:"40", marks:3, topic:"Bioenergetics", stage:"gcse", yearGroups:[9,10,11], text:"Describe how a leaf is adapted for photosynthesis.", commandWord:"Describe", answerLines:4, markScheme:"Large flat surface area to absorb light; chloroplasts in palisade cells; stomata for CO₂ entry; thin for short diffusion distance; veins supply water; transparent epidermis lets light through" },
  { id:"bio-bio-006", board:"AQA", subject:"biology", year:2024, series:"June", paper:"Paper 1", tier:"Foundation", questionNum:"41", marks:2, topic:"Bioenergetics", stage:"gcse", yearGroups:[9,10,11], text:"Name the green pigment in plants that absorbs light for photosynthesis.", commandWord:"Name", answerLines:1, markScheme:"Chlorophyll" },
  { id:"bio-bio-007", board:"OCR", subject:"biology", year:2023, series:"June", paper:"Paper 1", tier:"Higher", questionNum:"42", marks:5, topic:"Bioenergetics", stage:"gcse", yearGroups:[10,11], text:"A student investigates the effect of light intensity on the rate of photosynthesis using pondweed. Describe how the student could carry out this investigation and how they would measure the rate.", commandWord:"Describe", answerLines:6, markScheme:"Place pondweed in water with sodium hydrogen carbonate; shine light at different distances; count bubbles per minute or collect gas and measure volume; control temperature; repeat for reliability; plot graph of rate vs light intensity" },
  { id:"bio-bio-008", board:"AQA", subject:"biology", year:2023, series:"November", paper:"Paper 1", tier:"Foundation", questionNum:"43", marks:2, topic:"Bioenergetics", stage:"gcse", yearGroups:[9,10,11], text:"State where in the cell aerobic respiration takes place.", commandWord:"State", answerLines:1, markScheme:"Mitochondria" },
  { id:"bio-bio-009", board:"AQA", subject:"biology", year:2019, series:"June", paper:"Paper 1", tier:"Higher", questionNum:"44", marks:4, topic:"Bioenergetics", stage:"gcse", yearGroups:[10,11], text:"Explain the importance of ATP in cells.", commandWord:"Explain", answerLines:4, markScheme:"ATP is the energy currency of the cell; released during respiration; used for active transport, muscle contraction, protein synthesis, cell division; broken down to ADP + Pi releasing energy" },
  { id:"bio-bio-010", board:"Edexcel", subject:"biology", year:2022, series:"June", paper:"Paper 1", tier:"Higher", questionNum:"45", marks:4, topic:"Bioenergetics", stage:"gcse", yearGroups:[10,11], text:"Describe the light-dependent and light-independent reactions of photosynthesis.", commandWord:"Describe", answerLines:5, markScheme:"Light-dependent: in thylakoid membranes; light splits water (photolysis); produces ATP and NADPH; releases oxygen. Light-independent (Calvin cycle): in stroma; CO₂ fixed; glucose produced using ATP and NADPH" },

  // ─── HOMEOSTASIS ──────────────────────────────────────────────────────────
  { id:"bio-hom-001", board:"AQA", subject:"biology", year:2023, series:"June", paper:"Paper 2", tier:"Foundation", questionNum:"46", marks:2, topic:"Homeostasis", stage:"gcse", yearGroups:[9,10,11], text:"Define homeostasis.", commandWord:"Define", answerLines:2, markScheme:"The maintenance of a constant internal environment / regulation of internal conditions within normal limits" },
  { id:"bio-hom-002", board:"AQA", subject:"biology", year:2023, series:"June", paper:"Paper 2", tier:"Higher", questionNum:"47", marks:5, topic:"Homeostasis", stage:"gcse", yearGroups:[10,11], text:"Explain how blood glucose concentration is regulated in the body. Include the roles of insulin and glucagon.", commandWord:"Explain", answerLines:7, markScheme:"Blood glucose rises after eating; pancreas (beta cells) releases insulin; insulin causes liver/muscle cells to absorb glucose; glucose stored as glycogen; blood glucose falls; pancreas (alpha cells) releases glucagon; glucagon causes glycogen to be converted back to glucose (glycogenolysis)" },
  { id:"bio-hom-003", board:"AQA", subject:"biology", year:2022, series:"June", paper:"Paper 2", tier:"Foundation", questionNum:"48", marks:3, topic:"Homeostasis", stage:"gcse", yearGroups:[9,10,11], text:"Describe how the body responds when body temperature rises above normal.", commandWord:"Describe", answerLines:4, markScheme:"Vasodilation of skin blood vessels; more blood flows to skin; sweating; evaporation of sweat cools skin; hairs lie flat; reduces heat loss" },
  { id:"bio-hom-004", board:"AQA", subject:"biology", year:2022, series:"June", paper:"Paper 2", tier:"Higher", questionNum:"49", marks:4, topic:"Homeostasis", stage:"gcse", yearGroups:[10,11], text:"Explain how the kidneys regulate water content of the blood. Include the role of ADH.", commandWord:"Explain", answerLines:5, markScheme:"If blood water concentration falls; hypothalamus detects change; pituitary gland releases ADH; ADH causes kidney tubules to become more permeable to water; more water reabsorbed; less urine produced; blood water concentration rises" },
  { id:"bio-hom-005", board:"Edexcel", subject:"biology", year:2023, series:"June", paper:"Paper 2", tier:"Foundation", questionNum:"50", marks:2, topic:"Homeostasis", stage:"gcse", yearGroups:[9,10,11], text:"State the role of the pancreas in blood glucose regulation.", commandWord:"State", answerLines:2, markScheme:"Produces insulin (when blood glucose is high) and glucagon (when blood glucose is low)" },
  { id:"bio-hom-006", board:"AQA", subject:"biology", year:2024, series:"June", paper:"Paper 2", tier:"Foundation", questionNum:"51", marks:3, topic:"Homeostasis", stage:"gcse", yearGroups:[9,10,11], text:"Explain the difference between Type 1 and Type 2 diabetes.", commandWord:"Explain", answerLines:4, markScheme:"Type 1: immune system destroys beta cells; no insulin produced; treated with insulin injections. Type 2: cells become resistant to insulin; often linked to obesity; treated with diet and exercise" },
  { id:"bio-hom-007", board:"OCR", subject:"biology", year:2023, series:"June", paper:"Paper 2", tier:"Higher", questionNum:"52", marks:5, topic:"Homeostasis", stage:"gcse", yearGroups:[10,11], text:"Describe the negative feedback mechanism involved in temperature regulation.", commandWord:"Describe", answerLines:6, markScheme:"Stimulus detected by receptor (thermoreceptors in skin/hypothalamus); information sent to control centre (hypothalamus); effectors respond (sweat glands, muscles, blood vessels); response reduces stimulus; returns to set point; negative feedback" },
  { id:"bio-hom-008", board:"AQA", subject:"biology", year:2023, series:"November", paper:"Paper 2", tier:"Foundation", questionNum:"53", marks:2, topic:"Homeostasis", stage:"gcse", yearGroups:[9,10,11], text:"Name the organ that controls blood glucose levels by releasing hormones.", commandWord:"Name", answerLines:1, markScheme:"Pancreas" },
  { id:"bio-hom-009", board:"AQA", subject:"biology", year:2019, series:"June", paper:"Paper 2", tier:"Higher", questionNum:"54", marks:4, topic:"Homeostasis", stage:"gcse", yearGroups:[10,11], text:"Explain how the nervous system and the endocrine system differ in how they coordinate responses.", commandWord:"Explain", answerLines:5, markScheme:"Nervous: electrical impulses; fast response; short-lived; localised effect; via nerves. Endocrine: chemical hormones; slower response; longer-lasting; widespread effect; via blood" },
  { id:"bio-hom-010", board:"Edexcel", subject:"biology", year:2022, series:"June", paper:"Paper 2", tier:"Higher", questionNum:"55", marks:4, topic:"Homeostasis", stage:"gcse", yearGroups:[10,11], text:"Describe the structure and function of a nephron in the kidney.", commandWord:"Describe", answerLines:5, markScheme:"Bowman's capsule: filtration of blood; proximal tubule: reabsorption of glucose, amino acids, water; loop of Henle: creates concentration gradient; distal tubule and collecting duct: fine-tuning of water reabsorption under ADH control" },

  // ─── INHERITANCE ──────────────────────────────────────────────────────────
  { id:"bio-inh-001", board:"AQA", subject:"biology", year:2023, series:"June", paper:"Paper 2", tier:"Foundation", questionNum:"56", marks:2, topic:"Inheritance", stage:"gcse", yearGroups:[9,10,11], text:"What is a gene?", commandWord:"Define", answerLines:2, markScheme:"A section of DNA that codes for a specific protein / controls a specific characteristic" },
  { id:"bio-inh-002", board:"AQA", subject:"biology", year:2023, series:"June", paper:"Paper 2", tier:"Higher", questionNum:"57", marks:4, topic:"Inheritance", stage:"gcse", yearGroups:[10,11], text:"Cystic fibrosis is caused by a recessive allele (f). Two carriers (Ff × Ff) have children. Use a Punnett square to show the probability of their children having cystic fibrosis.", commandWord:"Use", answerLines:5, markScheme:"Punnett square: FF, Ff, Ff, ff; 1 in 4 (25%) chance of having cystic fibrosis" },
  { id:"bio-inh-003", board:"AQA", subject:"biology", year:2022, series:"June", paper:"Paper 2", tier:"Foundation", questionNum:"58", marks:3, topic:"Inheritance", stage:"gcse", yearGroups:[9,10,11], text:"Explain the difference between genotype and phenotype.", commandWord:"Explain", answerLines:3, markScheme:"Genotype: the genetic makeup / alleles an organism has; Phenotype: the physical characteristics / observable traits resulting from the genotype and environment" },
  { id:"bio-inh-004", board:"AQA", subject:"biology", year:2022, series:"June", paper:"Paper 2", tier:"Higher", questionNum:"59", marks:5, topic:"Inheritance", stage:"gcse", yearGroups:[10,11], text:"Explain how sex is determined in humans. Include the role of sex chromosomes.", commandWord:"Explain", answerLines:5, markScheme:"Humans have 23 pairs of chromosomes; 23rd pair are sex chromosomes; females: XX; males: XY; all eggs contain X chromosome; sperm contain either X or Y; if Y sperm fertilises egg → male; if X sperm fertilises egg → female; 50:50 probability" },
  { id:"bio-inh-005", board:"Edexcel", subject:"biology", year:2023, series:"June", paper:"Paper 2", tier:"Foundation", questionNum:"60", marks:2, topic:"Inheritance", stage:"gcse", yearGroups:[9,10,11], text:"What is meant by the term 'dominant allele'?", commandWord:"Define", answerLines:2, markScheme:"An allele that is always expressed in the phenotype, even when only one copy is present (heterozygous)" },
  { id:"bio-inh-006", board:"AQA", subject:"biology", year:2024, series:"June", paper:"Paper 2", tier:"Higher", questionNum:"61", marks:5, topic:"Inheritance", stage:"gcse", yearGroups:[10,11], text:"Haemophilia is a sex-linked condition caused by a recessive allele on the X chromosome. A carrier female (X^H X^h) and a normal male (X^H Y) have children. Calculate the probability of their son having haemophilia.", commandWord:"Calculate", answerLines:5, markScheme:"Punnett square: X^H X^H, X^H X^h, X^H Y, X^h Y; probability of son having haemophilia = 1/4 of all children = 1/2 of sons = 50%" },
  { id:"bio-inh-007", board:"OCR", subject:"biology", year:2023, series:"June", paper:"Paper 2", tier:"Foundation", questionNum:"62", marks:3, topic:"Inheritance", stage:"gcse", yearGroups:[9,10,11], text:"Describe what happens during DNA replication.", commandWord:"Describe", answerLines:4, markScheme:"DNA double helix unwinds; hydrogen bonds between base pairs break; each strand acts as template; complementary bases added by DNA polymerase; two identical copies produced; semi-conservative replication" },
  { id:"bio-inh-008", board:"AQA", subject:"biology", year:2023, series:"November", paper:"Paper 2", tier:"Higher", questionNum:"63", marks:4, topic:"Inheritance", stage:"gcse", yearGroups:[10,11], text:"Explain how a mutation in a gene can lead to a non-functional protein.", commandWord:"Explain", answerLines:5, markScheme:"Mutation changes base sequence of DNA; changes mRNA codon; changes amino acid sequence of protein; different amino acids change shape of protein; active site changes shape; protein cannot function" },
  { id:"bio-inh-009", board:"AQA", subject:"biology", year:2019, series:"June", paper:"Paper 2", tier:"Higher", questionNum:"64", marks:5, topic:"Inheritance", stage:"gcse", yearGroups:[10,11], text:"Describe the evidence for evolution by natural selection. Include Darwin's observations.", commandWord:"Describe", answerLines:6, markScheme:"Variation in population; some variations heritable; struggle for survival (more offspring than can survive); those with advantageous characteristics survive and reproduce; pass on advantageous alleles; over many generations, population changes; fossil record; comparative anatomy; DNA evidence" },
  { id:"bio-inh-010", board:"Edexcel", subject:"biology", year:2022, series:"June", paper:"Paper 2", tier:"Foundation", questionNum:"65", marks:3, topic:"Inheritance", stage:"gcse", yearGroups:[9,10,11], text:"Explain what is meant by selective breeding and give one example.", commandWord:"Explain", answerLines:4, markScheme:"Selecting organisms with desirable characteristics; breeding them together; selecting offspring with desired characteristics; repeating over many generations; Example: breeding cows for high milk yield / wheat for disease resistance / dogs for specific traits" },

  // ─── ECOLOGY ──────────────────────────────────────────────────────────────
  { id:"bio-eco-001", board:"AQA", subject:"biology", year:2023, series:"June", paper:"Paper 2", tier:"Foundation", questionNum:"66", marks:2, topic:"Ecology", stage:"gcse", yearGroups:[9,10,11], text:"Define the term 'ecosystem'.", commandWord:"Define", answerLines:2, markScheme:"All the organisms living in an area together with the non-living (abiotic) factors of their environment" },
  { id:"bio-eco-002", board:"AQA", subject:"biology", year:2023, series:"June", paper:"Paper 2", tier:"Higher", questionNum:"67", marks:4, topic:"Ecology", stage:"gcse", yearGroups:[10,11], text:"Explain how carbon is cycled through an ecosystem. Include the processes involved.", commandWord:"Explain", answerLines:5, markScheme:"CO₂ absorbed by plants in photosynthesis; carbon in organic molecules; eaten by animals; released by respiration; decomposers break down dead organisms; carbon released as CO₂; combustion of fossil fuels releases CO₂" },
  { id:"bio-eco-003", board:"AQA", subject:"biology", year:2022, series:"June", paper:"Paper 2", tier:"Foundation", questionNum:"68", marks:3, topic:"Ecology", stage:"gcse", yearGroups:[9,10,11], text:"Describe how to use a quadrat to estimate the population of daisies in a field.", commandWord:"Describe", answerLines:4, markScheme:"Place quadrats randomly in the field; count daisies in each quadrat; calculate mean number per quadrat; multiply by total area of field / area of quadrat" },
  { id:"bio-eco-004", board:"AQA", subject:"biology", year:2022, series:"June", paper:"Paper 2", tier:"Higher", questionNum:"69", marks:5, topic:"Ecology", stage:"gcse", yearGroups:[10,11], text:"Explain the impact of deforestation on the environment.", commandWord:"Explain", answerLines:6, markScheme:"Loss of habitat → biodiversity loss; less photosynthesis → more CO₂ in atmosphere → climate change; burning trees releases CO₂; soil erosion; disruption of water cycle; loss of medicines/resources" },
  { id:"bio-eco-005", board:"Edexcel", subject:"biology", year:2023, series:"June", paper:"Paper 2", tier:"Foundation", questionNum:"70", marks:3, topic:"Ecology", stage:"gcse", yearGroups:[9,10,11], text:"Explain what is meant by a food chain and give an example.", commandWord:"Explain", answerLines:3, markScheme:"Shows feeding relationships between organisms; arrows show direction of energy flow; e.g. grass → rabbit → fox; producer → primary consumer → secondary consumer" },
  { id:"bio-eco-006", board:"AQA", subject:"biology", year:2024, series:"June", paper:"Paper 2", tier:"Foundation", questionNum:"71", marks:3, topic:"Ecology", stage:"gcse", yearGroups:[9,10,11], text:"Describe the role of decomposers in the nitrogen cycle.", commandWord:"Describe", answerLines:3, markScheme:"Decomposers break down dead organisms and waste; release ammonium compounds (ammonification); nitrifying bacteria convert ammonium to nitrates; plants absorb nitrates" },
  { id:"bio-eco-007", board:"OCR", subject:"biology", year:2023, series:"June", paper:"Paper 2", tier:"Higher", questionNum:"72", marks:5, topic:"Ecology", stage:"gcse", yearGroups:[10,11], text:"Explain how eutrophication can lead to the death of fish in a lake.", commandWord:"Explain", answerLines:6, markScheme:"Fertilisers/sewage enter water; nitrates/phosphates cause algal bloom; algae block light; aquatic plants die; decomposers break down dead plants; decomposers use up oxygen in respiration; fish die due to lack of oxygen (deoxygenation)" },
  { id:"bio-eco-008", board:"AQA", subject:"biology", year:2023, series:"November", paper:"Paper 2", tier:"Foundation", questionNum:"73", marks:2, topic:"Ecology", stage:"gcse", yearGroups:[9,10,11], text:"State two abiotic factors that affect the distribution of organisms.", commandWord:"State", answerLines:2, markScheme:"Any two from: temperature, light intensity, moisture levels, soil pH, wind speed, CO₂ concentration, O₂ concentration" },
  { id:"bio-eco-009", board:"AQA", subject:"biology", year:2019, series:"June", paper:"Paper 2", tier:"Higher", questionNum:"74", marks:4, topic:"Ecology", stage:"gcse", yearGroups:[10,11], text:"Explain how the mark-recapture technique is used to estimate population size.", commandWord:"Explain", answerLines:5, markScheme:"Capture sample; mark and release; allow time to mix with population; recapture sample; count marked individuals; Population = (first capture × second capture) / number of marked in second capture; Lincoln-Petersen method" },
  { id:"bio-eco-010", board:"Edexcel", subject:"biology", year:2022, series:"June", paper:"Paper 2", tier:"Higher", questionNum:"75", marks:5, topic:"Ecology", stage:"gcse", yearGroups:[10,11], text:"Describe the global carbon cycle and explain how human activities are disrupting it.", commandWord:"Describe and explain", answerLines:6, markScheme:"Carbon fixed by photosynthesis; released by respiration; stored in fossil fuels/limestone; human activities: burning fossil fuels releases CO₂; deforestation reduces photosynthesis; increased CO₂ → greenhouse effect → global warming; ocean acidification" },

  // ─── ADDITIONAL BIOLOGY QUESTIONS ─────────────────────────────────────────
  { id:"bio-add-001", board:"AQA", subject:"biology", year:2023, series:"June", paper:"Paper 1", tier:"Foundation", questionNum:"76", marks:2, topic:"Cell Biology", stage:"gcse", yearGroups:[9,10,11], text:"What is the function of the nucleus in a cell?", commandWord:"State", answerLines:2, markScheme:"Contains DNA / controls cell activities / contains genetic information" },
  { id:"bio-add-002", board:"AQA", subject:"biology", year:2023, series:"June", paper:"Paper 1", tier:"Higher", questionNum:"77", marks:4, topic:"Organisation", stage:"gcse", yearGroups:[10,11], text:"Explain how the structure of a capillary is adapted for its function.", commandWord:"Explain", answerLines:4, markScheme:"Walls one cell thick for short diffusion distance; small diameter forces red blood cells to slow down; large surface area; gaps between cells allow white blood cells to pass through (diapedesis)" },
  { id:"bio-add-003", board:"Edexcel", subject:"biology", year:2023, series:"June", paper:"Paper 2", tier:"Foundation", questionNum:"78", marks:3, topic:"Inheritance", stage:"gcse", yearGroups:[9,10,11], text:"Describe the structure of DNA.", commandWord:"Describe", answerLines:4, markScheme:"Double helix; made of nucleotides; each nucleotide has a sugar (deoxyribose), phosphate and base; bases pair: A-T, C-G; held together by hydrogen bonds" },
  { id:"bio-add-004", board:"AQA", subject:"biology", year:2022, series:"June", paper:"Paper 2", tier:"Higher", questionNum:"79", marks:5, topic:"Inheritance", stage:"gcse", yearGroups:[10,11], text:"Explain the process of protein synthesis. Include transcription and translation.", commandWord:"Explain", answerLines:7, markScheme:"Transcription: DNA unwinds; mRNA made from template strand; complementary base pairing; mRNA leaves nucleus. Translation: mRNA attaches to ribosome; tRNA brings amino acids; anticodon matches codon; peptide bonds form; polypeptide chain built" },
  { id:"bio-add-005", board:"AQA", subject:"biology", year:2024, series:"June", paper:"Paper 2", tier:"Higher", questionNum:"80", marks:4, topic:"Ecology", stage:"gcse", yearGroups:[10,11], text:"Explain how biodiversity can be maintained. Give examples of conservation methods.", commandWord:"Explain", answerLines:5, markScheme:"Seed banks; captive breeding programmes; wildlife reserves/national parks; reforestation; international agreements (CITES); reducing pollution; sustainable fishing" },
  { id:"bio-add-006", board:"AQA", subject:"biology", year:2023, series:"June", paper:"Paper 1", tier:"Foundation", questionNum:"81", marks:2, topic:"Bioenergetics", stage:"gcse", yearGroups:[9,10,11], text:"What is the balanced chemical equation for aerobic respiration?", commandWord:"Write", answerLines:1, markScheme:"C₆H₁₂O₆ + 6O₂ → 6CO₂ + 6H₂O (+ energy/ATP)" },
  { id:"bio-add-007", board:"OCR", subject:"biology", year:2023, series:"June", paper:"Paper 1", tier:"Foundation", questionNum:"82", marks:3, topic:"Infection and Response", stage:"gcse", yearGroups:[9,10,11], text:"Explain how the skin acts as a barrier against infection.", commandWord:"Explain", answerLines:3, markScheme:"Skin is a physical barrier; prevents pathogens entering body; sebaceous glands produce sebum (slightly acidic) which kills bacteria; if skin is broken, clotting seals the wound" },
  { id:"bio-add-008", board:"AQA", subject:"biology", year:2022, series:"November", paper:"Paper 1", tier:"Higher", questionNum:"83", marks:4, topic:"Cell Biology", stage:"gcse", yearGroups:[10,11], text:"Explain the role of enzymes in digestion. Include the concept of the active site.", commandWord:"Explain", answerLines:5, markScheme:"Enzymes are biological catalysts; specific shape of active site; substrate fits into active site (lock and key model); enzyme-substrate complex forms; bonds broken/formed; products released; enzyme unchanged" },
  { id:"bio-add-009", board:"Edexcel", subject:"biology", year:2024, series:"June", paper:"Paper 1", tier:"Foundation", questionNum:"84", marks:3, topic:"Organisation", stage:"gcse", yearGroups:[9,10,11], text:"Describe the role of bile in digestion.", commandWord:"Describe", answerLines:3, markScheme:"Produced by liver; stored in gall bladder; released into small intestine; emulsifies fats (breaks into small droplets); increases surface area for lipase to work; neutralises stomach acid" },
  { id:"bio-add-010", board:"AQA", subject:"biology", year:2019, series:"June", paper:"Paper 2", tier:"Foundation", questionNum:"85", marks:3, topic:"Homeostasis", stage:"gcse", yearGroups:[9,10,11], text:"Describe the structure of the nervous system.", commandWord:"Describe", answerLines:4, markScheme:"Central nervous system (brain and spinal cord); peripheral nervous system (sensory and motor neurones); receptors detect stimuli; effectors (muscles/glands) respond; reflex arc: receptor → sensory neurone → relay neurone → motor neurone → effector" },
  { id:"bio-add-011", board:"AQA", subject:"biology", year:2023, series:"June", paper:"Paper 2", tier:"Foundation", questionNum:"86", marks:2, topic:"Homeostasis", stage:"gcse", yearGroups:[9,10,11], text:"Name the hormone that controls the menstrual cycle and state where it is produced.", commandWord:"Name", answerLines:2, markScheme:"Oestrogen (and progesterone); produced by ovaries. FSH and LH produced by pituitary gland" },
  { id:"bio-add-012", board:"AQA", subject:"biology", year:2023, series:"June", paper:"Paper 2", tier:"Higher", questionNum:"87", marks:5, topic:"Homeostasis", stage:"gcse", yearGroups:[10,11], text:"Explain how IVF (in vitro fertilisation) works and discuss ethical issues associated with it.", commandWord:"Explain", answerLines:7, markScheme:"Hormones stimulate egg production; eggs collected; fertilised with sperm in laboratory; embryo cultured; embryo implanted in uterus. Ethical issues: unused embryos destroyed; multiple births; designer babies; expensive; success rates" },
  { id:"bio-add-013", board:"OCR", subject:"biology", year:2022, series:"June", paper:"Paper 2", tier:"Foundation", questionNum:"88", marks:3, topic:"Ecology", stage:"gcse", yearGroups:[9,10,11], text:"Explain what is meant by a trophic level and why energy is lost between trophic levels.", commandWord:"Explain", answerLines:4, markScheme:"Trophic level = feeding level in a food chain; energy lost as heat in respiration; energy lost in urine and faeces; energy used for movement; not all organisms eaten; only about 10% transferred to next level" },
  { id:"bio-add-014", board:"AQA", subject:"biology", year:2022, series:"June", paper:"Paper 1", tier:"Foundation", questionNum:"89", marks:2, topic:"Cell Biology", stage:"gcse", yearGroups:[9,10,11], text:"What is the function of chloroplasts in plant cells?", commandWord:"State", answerLines:2, markScheme:"Site of photosynthesis; contain chlorophyll which absorbs light energy" },
  { id:"bio-add-015", board:"Edexcel", subject:"biology", year:2023, series:"November", paper:"Paper 1", tier:"Higher", questionNum:"90", marks:4, topic:"Bioenergetics", stage:"gcse", yearGroups:[10,11], text:"Explain why athletes need to breathe more heavily during and after intense exercise.", commandWord:"Explain", answerLines:5, markScheme:"During exercise: muscles need more oxygen for aerobic respiration; more CO₂ produced; increased breathing rate delivers more O₂ and removes CO₂. After exercise: oxygen debt must be repaid; lactic acid converted back to glucose in liver; requires extra oxygen" },
  { id:"bio-add-016", board:"AQA", subject:"biology", year:2024, series:"June", paper:"Paper 1", tier:"Higher", questionNum:"91", marks:5, topic:"Organisation", stage:"gcse", yearGroups:[10,11], text:"Describe the structure and function of the lymphatic system.", commandWord:"Describe", answerLines:5, markScheme:"Network of vessels throughout body; lymph nodes filter lymph fluid; lymphocytes produced in lymph nodes; returns tissue fluid to blood; absorbs fats from small intestine (lacteals); part of immune system" },
  { id:"bio-add-017", board:"AQA", subject:"biology", year:2023, series:"June", paper:"Paper 2", tier:"Foundation", questionNum:"92", marks:3, topic:"Inheritance", stage:"gcse", yearGroups:[9,10,11], text:"Explain what is meant by genetic engineering and give one example of its use.", commandWord:"Explain", answerLines:4, markScheme:"Cutting a gene from one organism's DNA; inserting it into another organism's DNA; using restriction enzymes and ligase; Example: insulin gene inserted into bacteria to produce human insulin" },
  { id:"bio-add-018", board:"OCR", subject:"biology", year:2024, series:"June", paper:"Paper 2", tier:"Higher", questionNum:"93", marks:5, topic:"Inheritance", stage:"gcse", yearGroups:[10,11], text:"Explain how polymerase chain reaction (PCR) is used to amplify DNA.", commandWord:"Explain", answerLines:6, markScheme:"DNA heated to 95°C to separate strands; cooled to 55°C; primers attach to target sequence; heated to 72°C; DNA polymerase extends from primers; cycle repeated; exponential amplification; used in forensics, medicine, research" },
  { id:"bio-add-019", board:"AQA", subject:"biology", year:2022, series:"June", paper:"Paper 2", tier:"Foundation", questionNum:"94", marks:2, topic:"Ecology", stage:"gcse", yearGroups:[9,10,11], text:"State two ways in which humans are causing species to become extinct.", commandWord:"State", answerLines:2, markScheme:"Any two from: habitat destruction, pollution, hunting/poaching, introduction of invasive species, climate change, overexploitation" },
  { id:"bio-add-020", board:"AQA", subject:"biology", year:2021, series:"November", paper:"Paper 1", tier:"Higher", questionNum:"95", marks:4, topic:"Cell Biology", stage:"gcse", yearGroups:[10,11], text:"Explain the role of the cell cycle in growth and repair.", commandWord:"Explain", answerLines:5, markScheme:"G1 phase: cell grows; S phase: DNA replication; G2 phase: further growth; M phase: mitosis; cytokinesis; produces genetically identical cells; used for growth, repair and replacement of cells" },
  { id:"bio-add-021", board:"AQA", subject:"biology", year:2020, series:"November", paper:"Paper 2", tier:"Higher", questionNum:"96", marks:5, topic:"Homeostasis", stage:"gcse", yearGroups:[10,11], text:"Explain how the eye responds to changes in light intensity. Include the role of the iris.", commandWord:"Explain", answerLines:6, markScheme:"In bright light: circular muscles in iris contract; radial muscles relax; pupil constricts; less light enters eye. In dim light: radial muscles contract; circular muscles relax; pupil dilates; more light enters eye; reflex response" },
  { id:"bio-add-022", board:"Edexcel", subject:"biology", year:2023, series:"June", paper:"Paper 1", tier:"Higher", questionNum:"97", marks:4, topic:"Organisation", stage:"gcse", yearGroups:[10,11], text:"Explain how cancer cells differ from normal cells and how cancer can spread.", commandWord:"Explain", answerLines:5, markScheme:"Cancer cells divide uncontrollably; do not respond to normal growth signals; can invade surrounding tissue; metastasis: cancer cells enter blood/lymph; spread to other parts of body; form secondary tumours" },
  { id:"bio-add-023", board:"AQA", subject:"biology", year:2024, series:"June", paper:"Paper 1", tier:"Foundation", questionNum:"98", marks:3, topic:"Infection and Response", stage:"gcse", yearGroups:[9,10,11], text:"Describe how monoclonal antibodies are produced.", commandWord:"Describe", answerLines:4, markScheme:"Mouse injected with antigen; B lymphocytes produce antibodies; lymphocytes fused with tumour cells to make hybridoma cells; hybridoma cells divide rapidly; monoclonal antibodies harvested" },
  { id:"bio-add-024", board:"OCR", subject:"biology", year:2023, series:"June", paper:"Paper 1", tier:"Foundation", questionNum:"99", marks:2, topic:"Bioenergetics", stage:"gcse", yearGroups:[9,10,11], text:"State two uses of glucose produced in photosynthesis.", commandWord:"State", answerLines:2, markScheme:"Any two from: used in respiration for energy; converted to starch for storage; used to make cellulose for cell walls; used to make amino acids; used to make fats and oils" },
  { id:"bio-add-025", board:"AQA", subject:"biology", year:2023, series:"June", paper:"Paper 2", tier:"Higher", questionNum:"100", marks:5, topic:"Ecology", stage:"gcse", yearGroups:[10,11], text:"Evaluate the use of biological control as a method of pest management.", commandWord:"Evaluate", answerLines:6, markScheme:"Advantages: no chemicals used; self-sustaining; specific to pest; no pollution. Disadvantages: introduced species may become pest itself; may not completely eradicate pest; slow to work; may affect non-target species; difficult to control" },
];

export default biologyQuestions;
