/**
 * SEND section-label helpers (IMP-10).
 *
 * The Section 1/2/3 group dividers shown on a worksheet are generated by the
 * renderer from a fixed label table — NOT from each section's `title`. That is
 * why the post-validator's anxiety title rewrite never reached the live page
 * (it only changes `section.title`). For an Anxiety / SEMH pupil we remap the
 * *displayed* divider label to low-threat, invitational wording.
 *
 * These are pure string helpers so they can be unit-tested without rendering
 * the (very large) WorksheetRenderer component.
 */

/** True when the resolved SEND profile is anxiety / SEMH / mental-health. */
export function isAnxietySendProfile(sendNeedId: unknown): boolean {
  return /anxiet|semh|emotion|mental[\s-]?health/i.test(String(sendNeedId || ""));
}

/**
 * Map a standard group-divider label to its anxiety-friendly equivalent.
 * Unknown labels are returned unchanged.
 */
export function toInvitationalSectionLabel(baseLabel: string): string {
  const label = String(baseLabel || "");
  if (/CHALLENGE/i.test(label)) return "OPTIONAL BONUS — only if you want to!";
  if (/SECTION\s*1|RECALL|WARM[\s-]?UP/i.test(label)) return "WARM-UP — no pressure, you've got this!";
  if (/SECTION\s*2|UNDERSTANDING/i.test(label)) return "BUILDING YOUR UNDERSTANDING";
  if (/SECTION\s*3|APPLICATION/i.test(label)) return "STRETCH YOURSELF — take your time";
  return label;
}
