import AIToolPage from "@/components/AIToolPage";
import { BookHeart } from "lucide-react";
import { useUserPreferences } from "@/contexts/UserPreferencesContext";

const situations = [
  "Going to a new school","Lunchtime routines","Dealing with change","Making friends","Asking for help","Managing anger","Waiting my turn","Fire drills","School trips","Assemblies","Changing for PE","Using the toilet at school","Playtime rules","Working in a group","Losing a game","Unexpected events","Visiting the doctor","Haircuts","Supermarket trips","Loud noises","Sensory overload","Saying goodbye","Transitions between lessons",
].map(s => ({ value: s, label: s }));

const ages = ["3-5","5-7","7-9","9-11","11-14","14-18"].map(a => ({ value: a, label: `Age ${a}` }));

function formatSocialStory(text: string, logoUrl?: string, schoolName?: string): string {
  const logoHtml = logoUrl
    ? `<img src="${logoUrl}" alt="School logo" style="height:40px;width:auto;object-fit:contain;border-radius:4px;" />`
    : `<div style="width:36px;height:36px;border-radius:8px;background:linear-gradient(135deg,#4f46e5,#7c3aed);display:flex;align-items:center;justify-content:center;font-size:18px;">📖</div>`;

  // Split story body from "How to Use" staff guidance
  const howToUseIdx = text.search(/\n?How to Use/i);
  const storyText   = howToUseIdx >= 0 ? text.slice(0, howToUseIdx).trim() : text.trim();
  const staffText   = howToUseIdx >= 0 ? text.slice(howToUseIdx).trim() : "";

  const renderParagraphs = (t: string) => t.split(/\n\n+/).filter(p => p.trim()).map(p => {
    const s = p.trim();
    if (s.startsWith("##")) return `<h3 style="font-size:15px;font-weight:700;color:#4f46e5;margin:16px 0 6px;">${s.replace(/^##\s*/, "")}</h3>`;
    if (s.startsWith("#"))  return `<h2 style="font-size:18px;font-weight:800;color:#4f46e5;margin:20px 0 8px;">${s.replace(/^#\s*/, "")}</h2>`;
    return `<p style="font-size:14px;color:#1f2937;line-height:1.8;margin:0 0 12px;">${s}</p>`;
  }).join("");

  const printBtns = `
  <div class="no-print" style="display:flex;gap:10px;padding:12px 22px;background:#f5f3ff;border-top:1px solid #ddd6fe;flex-wrap:wrap;">
    <button onclick="window.print()" style="display:flex;align-items:center;gap:6px;padding:8px 16px;background:#4f46e5;color:#fff;border:none;border-radius:8px;font-size:13px;font-weight:600;cursor:pointer;">
      Print Story (student copy)
    </button>
    <button onclick="(function(){
      var s=document.getElementById('social-staff-guidance');
      var b=document.getElementById('social-story-body');
      if(!s||!b)return;
      b.style.display='none';
      s.classList.remove('no-print');
      window.print();
      b.style.display='';
      s.classList.add('no-print');
    })()" style="display:flex;align-items:center;gap:6px;padding:8px 16px;background:#fff;color:#4f46e5;border:2px solid #4f46e5;border-radius:8px;font-size:13px;font-weight:600;cursor:pointer;">
      Print Staff Guidance only
    </button>
  </div>`;

  const staffSection = staffText ? `
  <div id="social-staff-guidance" class="no-print" style="margin-top:4px;border:2px solid #6366f1;border-radius:12px;overflow:hidden;">
    <div style="background:linear-gradient(135deg,#4f46e5,#3730a3);padding:10px 18px;">
      <div style="font-size:13px;font-weight:800;color:#fff;">Staff &amp; Parent Guidance</div>
      <div style="font-size:11px;color:rgba(255,255,255,0.75);">How to use this story — do not give to student</div>
    </div>
    <div style="padding:14px 18px;background:#f5f3ff;font-size:13px;color:#374151;line-height:1.7;">
      ${renderParagraphs(staffText.replace(/^How to Use[^\n]*\n?/i, ""))}
    </div>
  </div>` : "";

  return `<div style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;max-width:640px;margin:0 auto;">
  ${printBtns}
  <div id="social-story-body" style="background:#fff;border-radius:16px;overflow:hidden;box-shadow:0 4px 20px rgba(79,70,229,0.12);border:2px solid #c7d2fe;">
    <div style="background:linear-gradient(135deg,#4f46e5,#7c3aed);padding:18px 22px;display:flex;align-items:center;gap:12px;">
      ${logoHtml}
      <div>
        <div style="font-size:16px;font-weight:800;color:white;">Social Story</div>
        <div style="font-size:11px;color:rgba(255,255,255,0.75);">${schoolName || "Adaptly"} · Carol Gray methodology</div>
      </div>
    </div>
    <div style="padding:20px 24px;">${renderParagraphs(storyText)}</div>
    <div style="padding:10px 22px;background:#f5f3ff;border-top:1px solid #ddd6fe;font-size:10px;color:#9ca3af;">Generated by Adaptly · This story is confidential and person-centred · adaptly.co.uk</div>
  </div>
  ${staffSection}
  </div>`;
}

export default function SocialStories() {
  const { preferences } = useUserPreferences();
  return (
    <AIToolPage
      assignable={true}
      title="Social Stories Generator"
      description="Create personalised Carol Gray-style social stories for autism and behaviour support"
      icon={<BookHeart className="w-5 h-5 text-white" />}
      accentColor="bg-violet-600"
      fields={[
        { id: "studentName", label: "Student Initials", type: "text", placeholder: "e.g. A.J.", required: true, span: "half", maxLength: 4, hint: "Initials only (max 4 chars) — do not enter full names (GDPR)" },
        { id: "ageRange", label: "Age Range", type: "select", options: ages, required: true, span: "half" },
        { id: "situation", label: "Situation / Topic", type: "select", options: situations, required: true, span: "half" },
        { id: "customSituation", label: "Or describe a custom situation", type: "text", placeholder: "e.g. Moving to secondary school", span: "half" },
        { id: "challenge", label: "Specific Challenge / Behaviour", type: "textarea", placeholder: "What does the student find difficult about this situation?", required: true, span: "full" },
        { id: "interests", label: "Student's Interests (optional)", type: "text", placeholder: "e.g. trains, Minecraft, dinosaurs — to personalise the story", span: "full" },
        { id: "perspective", label: "Perspective Sentences", type: "select", options: [{ value: "yes", label: "Include (recommended)" }, { value: "no", label: "Exclude" }], span: "half" },
        { id: "length", label: "Story Length", type: "select", options: [{ value: "short", label: "Short (6-8 sentences)" }, { value: "medium", label: "Medium (10-14 sentences)" }, { value: "long", label: "Long (16-20 sentences)" }], span: "half" },
      ]}
      buildPrompt={(v) => ({
        system: `You are an expert in autism education and Carol Gray's Social Stories™ methodology. You strictly follow the Carol Gray 10.2 ratio rule.

CARROL GRAY RATIO RULE — CRITICAL: For every 1 directive/control sentence, you MUST write at least 2 descriptive or perspective sentences. Before outputting the story, count your sentence types:
- Descriptive sentences: describe what happens, where, who is involved, what people do (most sentences)
- Perspective sentences: describe how others think, feel, or react ("My teacher feels happy when...")
- Coaching sentences: suggest what the student can try ("I can try to...")
- Affirmative sentences: express values or reassurance ("Many children find this tricky at first")
- Control sentences: strategies the student chooses ("I will...", "I can choose to...")

Directive/control sentences = coaching + control sentences combined. If your ratio is less than 2:1 (descriptive+perspective vs directive+control), add more descriptive sentences before outputting.

Your stories are warm, positive, and empowering — never negative, threatening, or shame-inducing. Write in first person, present tense, using simple language appropriate for the age group.`,
        user: `Write a Social Story for:

Name: ${v.studentName}
Age: ${v.ageRange}
Situation: ${v.customSituation || v.situation}
Challenge: ${v.challenge}
${v.interests ? `Interests to incorporate: ${v.interests}` : ""}
Length: ${v.length || "medium"}
Include perspective sentences: ${v.perspective !== "no" ? "Yes" : "No"}

STRUCTURE REQUIREMENTS:
1. A positive title describing the situation
2. Opening descriptive sentences (2-3): what the situation is, where it happens, who is involved
3. Descriptive/perspective sentences (majority of story): what happens, how people feel, what others do
4. ${v.perspective !== "no" ? "Perspective sentences (2-3): how others think and feel during this situation" : ""}
5. Coaching sentences (max 2): what the student can try ("I can try to...")
6. Affirmative sentences (1-2): reassurance and values
7. Control sentence (max 1): a strategy the student chooses
8. Closing affirmation: positive, empowering ending

After the story, on a new line starting with "How to Use This Story:", provide a brief note for the teacher/parent on how to read and use this story effectively.

IMPORTANT: Write in first person ("I"), present tense. Simple, clear language. Warm and positive throughout. Check your ratio before finishing — descriptive+perspective sentences must outnumber coaching+control sentences by at least 2:1.`,
        maxTokens: 2000,
      })}
      formatOutput={(text) => formatSocialStory(text, preferences.schoolLogoUrl, preferences.schoolName)}
      outputTitle={(v) => `Social Story: ${v.customSituation || v.situation} — ${v.studentName}`}
    />
  );
}
