import AIToolPage from "@/components/AIToolPage";
import { BookHeart } from "lucide-react";
import { useUserPreferences } from "@/contexts/UserPreferencesContext";

const situations = [
  "Going to a new school","Lunchtime routines","Dealing with change","Making friends","Asking for help","Managing anger","Waiting my turn","Fire drills","School trips","Assemblies","Changing for PE","Using the toilet at school","Playtime rules","Working in a group","Losing a game","Unexpected events","Visiting the doctor","Haircuts","Supermarket trips","Loud noises","Sensory overload","Saying goodbye","Transitions between lessons",
].map(s => ({ value: s, label: s }));

const ages = ["3-5","5-7","7-9","9-11","11-14","14-18"].map(a => ({ value: a, label: `Age ${a}` }));

function formatSocialStory(text: string, logoUrl?: string, schoolName?: string): string {
  const logoHtml = logoUrl
    ? `<img src="${logoUrl}" alt="School logo" style="height:40px;width:auto;object-fit:contain;border-radius:4px;" />`
    : `<div style="width:36px;height:36px;border-radius:8px;background:linear-gradient(135deg,#f43f5e,#ec4899);display:flex;align-items:center;justify-content:center;font-size:18px;">📖</div>`;

  const paragraphs = text.split(/\n\n+/).filter(p => p.trim());
  const bodyHtml = paragraphs.map(p => {
    const t = p.trim();
    if (t.startsWith("##")) return `<h3 style="font-size:15px;font-weight:700;color:#be185d;margin:16px 0 6px;">${t.replace(/^##\s*/, "")}</h3>`;
    if (t.startsWith("#")) return `<h2 style="font-size:18px;font-weight:800;color:#be185d;margin:20px 0 8px;">${t.replace(/^#\s*/, "")}</h2>`;
    if (t.startsWith("How to Use")) return `<div style="margin-top:20px;padding:14px;background:#fdf2f8;border-left:4px solid #f43f5e;border-radius:0 8px 8px 0;"><p style="font-size:11px;font-weight:700;color:#be185d;margin:0 0 6px;text-transform:uppercase;letter-spacing:0.5px;">For Staff & Parents</p><p style="font-size:13px;color:#374151;margin:0;line-height:1.6;">${t.replace(/^How to Use.*?\n/i, "")}</p></div>`;
    return `<p style="font-size:14px;color:#1f2937;line-height:1.8;margin:0 0 12px;">${t}</p>`;
  }).join("");

  return `<div style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;max-width:640px;margin:0 auto;background:#fff;border-radius:16px;overflow:hidden;box-shadow:0 4px 20px rgba(244,63,94,0.12);">
    <div style="background:linear-gradient(135deg,#f43f5e,#ec4899);padding:18px 22px;display:flex;align-items:center;gap:12px;">
      ${logoHtml}
      <div>
        <div style="font-size:16px;font-weight:800;color:white;">Social Story</div>
        <div style="font-size:11px;color:rgba(255,255,255,0.75);">${schoolName || "Adaptly"} · Carol Gray methodology</div>
      </div>
    </div>
    <div style="padding:20px 24px;">${bodyHtml}</div>
    <div style="padding:10px 22px;background:#fff0f5;border-top:1px solid #fce7f3;font-size:10px;color:#9ca3af;">Generated by Adaptly · This story is confidential and person-centred · adaptly.co.uk</div>
  </div>`;
}

export default function SocialStories() {
  const { preferences } = useUserPreferences();
  return (
    <AIToolPage
      assignable={true}
      title="Social Stories Generator"
      description="Create personalised Carol Gray-style social stories for autism and behaviour support"
      icon={<BookHeart className="w-5 h-5 text-white" />}
      accentColor="bg-rose-500"
      fields={[
        { id: "studentName", label: "Student Initials", type: "text", placeholder: "e.g. A.J.", required: true, span: "half", maxLength: 4, hint: "Initials only (max 4 chars) — do not enter full names (GDPR)" },
        { id: "ageRange", label: "Age Range", type: "select", options: ages, required: true, span: "half" },
        { id: "situation", label: "Situation / Topic", type: "select", options: situations, required: true, span: "half" },
        { id: "customSituation", label: "Or describe a custom situation", type: "text", placeholder: "e.g. Moving to secondary school", span: "half" },
        { id: "challenge", label: "Specific Challenge / Behaviour", type: "textarea", placeholder: "What does the student find difficult about this situation?", required: true, span: "full" },
        { id: "interests", label: "Student's Interests (optional)", type: "text", placeholder: "e.g. trains, Minecraft, dinosaurs — to personalise the story", span: "full" },
        { id: "perspective", label: "Perspective Sentences", type: "select", options: [{ value: "yes", label: "Include (recommended)" }, { value: "no", label: "Exclude" }], span: "half" },
        { id: "length", label: "Story Length", type: "select", options: [{ value: "short", label: "Short (6-8 sentences)" }, { value: "medium", label: "Medium (10-14 sentences)" }, { value: "long", label: "Long (16-20 sentences)" }], span: "half" },
      ]}
      buildPrompt={(v) => ({
        system: `You are an expert in autism education and Carol Gray's Social Stories™ methodology. You write social stories that follow the 10.2 ratio (for every directive/control sentence, there are at least 2 descriptive/perspective sentences). Your stories are warm, positive, and empowering — never negative or threatening. You write in first person, present tense, using simple language appropriate for the age group.`,
        user: `Write a Social Story for:

Name: ${v.studentName}
Age: ${v.ageRange}
Situation: ${v.customSituation || v.situation}
Challenge: ${v.challenge}
${v.interests ? `Interests to incorporate: ${v.interests}` : ""}
Length: ${v.length || "medium"}
Include perspective sentences: ${v.perspective !== "no" ? "Yes" : "No"}

Follow Carol Gray's Social Stories™ format:
- Title that describes the situation positively
- Descriptive sentences (what happens, where, who is involved)
- Perspective sentences (how others think/feel — if included)
- Coaching sentences (what the student can try)
- Affirmative sentences (values, reassurance)
- Control sentences (strategies the student chooses)

Write in first person ("I"), present tense. Use simple, clear language. Be warm and positive. End with an affirming statement. After the story, provide a brief "How to Use This Story" note for the teacher/parent.`,
        maxTokens: 2000,
      })}
      formatOutput={(text) => formatSocialStory(text, preferences.schoolLogoUrl, preferences.schoolName)}
      outputTitle={(v) => `Social Story: ${v.customSituation || v.situation} — ${v.studentName}`}
    />
  );
}
