/**
 * PupilPassportShare — `/share/passport/:token`
 *
 * Public-token-protected, large-print, supply-teacher 60-second view of a
 * pupil's passport. Designed to be read in the 60 seconds before period 1.
 *
 * Token is generated by Pupil Passport "Share with supply teacher" button
 * and stored in localStorage on the issuing teacher's device. (When a real
 * server endpoint exists this resolves over the network instead.)
 */
import { useEffect, useState } from "react";
import { useParams, Link } from "wouter";
import { Card, CardContent } from "@/components/ui/card";
import { ShieldAlert, BookOpen, Sparkles, AlertTriangle, IdCard, Clock } from "lucide-react";

interface ShareRecord {
  token: string;
  pupilName: string;
  yearGroup?: string;
  sendNeeds?: string[];
  body: string;            // raw passport markdown
  expiresAt: string;
  issuedBy: string;
}

const SHARE_KEY = "adaptly_passport_shares_v1";

export function readShare(token: string): ShareRecord | null {
  try {
    const raw = localStorage.getItem(SHARE_KEY);
    if (!raw) return null;
    const all: ShareRecord[] = JSON.parse(raw);
    const found = all.find(s => s.token === token);
    if (!found) return null;
    if (new Date(found.expiresAt) < new Date()) return null;
    return found;
  } catch {
    return null;
  }
}

export function writeShare(s: Omit<ShareRecord, "token"> & { token?: string }): ShareRecord {
  let all: ShareRecord[] = [];
  try { all = JSON.parse(localStorage.getItem(SHARE_KEY) || "[]"); } catch {}
  const token = s.token || `pp_${Date.now().toString(36)}${Math.random().toString(36).slice(2, 8)}`;
  const rec: ShareRecord = { ...s, token };
  all = all.filter(r => r.token !== token).concat(rec);
  // Cap at 100 share records.
  all = all.slice(-100);
  try { localStorage.setItem(SHARE_KEY, JSON.stringify(all)); } catch {}
  return rec;
}

export default function PupilPassportShare() {
  const { token } = useParams();
  const [share, setShare] = useState<ShareRecord | null | undefined>(undefined); // undefined = loading

  useEffect(() => {
    if (!token) { setShare(null); return; }
    setShare(readShare(token));
  }, [token]);

  if (share === undefined) {
    return <div className="p-8 text-center text-xs text-muted-foreground">Loading…</div>;
  }

  if (!share) {
    return (
      <div className="min-h-screen flex items-center justify-center px-4">
        <Card className="max-w-sm">
          <CardContent className="p-6 text-center space-y-2">
            <AlertTriangle className="w-8 h-8 text-red-500 mx-auto" />
            <p className="text-sm font-bold">Link expired or invalid</p>
            <p className="text-xs text-muted-foreground">This passport share link is no longer active. Please ask the SENCO for a fresh link.</p>
            <Link href="/login"><span className="text-xs text-brand underline">Back to Adaptly</span></Link>
          </CardContent>
        </Card>
      </div>
    );
  }

  // Parse body into rough sections for the 60-second card.
  const sections = parseSections(share.body);

  return (
    <div className="min-h-screen bg-gradient-to-b from-amber-50 to-white py-6 px-4 print:bg-white print:py-2">
      <div className="max-w-3xl mx-auto space-y-4">
        <Card className="border-amber-300 shadow-md print:shadow-none">
          <CardContent className="p-5">
            <div className="flex items-start gap-4">
              <div className="w-14 h-14 rounded-2xl bg-amber-500 text-white text-xl font-black flex items-center justify-center flex-shrink-0">
                <IdCard className="w-7 h-7" />
              </div>
              <div className="flex-1 min-w-0">
                <p className="text-[10px] font-bold uppercase tracking-widest text-amber-700">60-second supply teacher card</p>
                <h1 className="text-3xl font-black leading-tight">{share.pupilName}</h1>
                <p className="text-base text-foreground/80">{share.yearGroup || "—"}</p>
                {share.sendNeeds && share.sendNeeds.length > 0 && (
                  <div className="flex flex-wrap gap-1.5 mt-2">
                    {share.sendNeeds.map(n => (
                      <span key={n} className="text-sm font-semibold px-2.5 py-1 rounded-full bg-amber-100 text-amber-800">{n}</span>
                    ))}
                  </div>
                )}
              </div>
            </div>
          </CardContent>
        </Card>

        {sections.map(s => (
          <Card key={s.title} className="print:shadow-none">
            <CardContent className="p-4">
              <p className="text-[11px] font-bold uppercase tracking-widest text-foreground/60 mb-1.5 flex items-center gap-1.5">
                {s.title.toLowerCase().includes("strength") ? <Sparkles className="w-3.5 h-3.5 text-emerald-500" /> :
                 s.title.toLowerCase().includes("strateg") ? <ShieldAlert className="w-3.5 h-3.5 text-blue-500" /> :
                 s.title.toLowerCase().includes("learn") ? <BookOpen className="w-3.5 h-3.5 text-purple-500" /> :
                 <Sparkles className="w-3.5 h-3.5 text-amber-500" />}
                {s.title}
              </p>
              <pre className="text-base leading-relaxed font-sans whitespace-pre-wrap">{s.body}</pre>
            </CardContent>
          </Card>
        ))}

        <div className="text-center text-[10px] text-muted-foreground space-y-1">
          <p className="flex items-center justify-center gap-1.5">
            <Clock className="w-3 h-3" />
            Link expires {new Date(share.expiresAt).toLocaleString("en-GB")}
          </p>
          <p>Issued by {share.issuedBy} via Adaptly · For staff use only · Treat as confidential</p>
        </div>
      </div>
    </div>
  );
}

function parseSections(body: string): Array<{ title: string; body: string }> {
  const lines = body.split("\n");
  const out: Array<{ title: string; body: string }> = [];
  let cur: { title: string; body: string } | null = null;
  for (const line of lines) {
    const head = line.match(/^(?:#{1,3}\s+|\*\*)(.+?)(?:\*\*|:)?$/);
    if (head && line.match(/^#{1,3}\s+/)) {
      if (cur) out.push(cur);
      cur = { title: head[1].trim(), body: "" };
    } else if (cur) {
      cur.body += (cur.body ? "\n" : "") + line;
    } else {
      cur = { title: "Overview", body: line };
    }
  }
  if (cur) out.push(cur);
  return out.map(s => ({ ...s, body: s.body.trim() })).filter(s => s.body);
}
