/**
 * A-Level Humanities — diagram catalogue.
 *
 * Bundled: English Lit / Lang, History, Geography, Politics, Classics,
 * Philosophy, Religious Studies, Sociology.
 *
 * Target: ~430 entries combined.
 */
import { emitTitled } from "../../_helpers.mjs";

const STYLE_FRAME = "Boxed planner with dotted writing lines, headings in coloured pills";
const STYLE_MAP = "Silhouette portraits in grey, coloured arrows for ally / rival / family / mentor, no copyrighted text";
const STYLE_HIST = "Sepia/parchment palette, silhouette portraits in grey, dates in serif typeface";
const STYLE_GEO = "Naturalistic palette, contour-style cross-sections, label leaders to the right";

export function build(ctx) {
  // ── A-Level English Literature ──────────────────────────────────────────
  emitTitled(ctx, {
    subject: "English Literature",
    year_band: "A-Level",
    topic: "Literary theory and frameworks",
    year_group: "Year 12",
    description: "Critical-theory frame for A-Level English Lit.",
    style_notes: STYLE_FRAME,
    tags: ["A-Level", "english-literature", "critical-theory"],
  }, [
    "Liberal humanism — universal values card",
    "Marxist criticism — base/superstructure card",
    "Feminist criticism — first / second / third / fourth wave",
    "Post-structuralism — Derrida deconstruction card",
    "New Historicism — text in context card",
    "Postcolonial criticism — Said's Orientalism card",
    "Eco-criticism — nature in literature",
    "Reader-response criticism — Iser / Fish",
    "Psychoanalytic criticism — Freudian / Lacanian",
    "Queer theory card",
  ]);

  emitTitled(ctx, {
    subject: "English Literature",
    year_band: "A-Level",
    topic: "Set-text relationship maps (copyright-safe)",
    year_group: "Year 13",
    description: "Simplified character relationship map for an A-Level set text — silhouettes only, no copyrighted text.",
    style_notes: STYLE_MAP,
    tags: ["A-Level", "english-literature", "set-text", "character-map"],
  }, [
    "Character map — Hamlet (court of Denmark)",
    "Character map — Othello (Venetian society and Cyprus garrison)",
    "Character map — King Lear (royal court and the heath)",
    "Character map — The Tempest (Prospero's island)",
    "Character map — Doctor Faustus (Faustus, Mephistopheles, the Good and Bad Angel)",
    "Character map — Pride and Prejudice (Bennet family and suitors)",
    "Character map — Wuthering Heights (Earnshaws and Lintons)",
    "Character map — Jane Eyre (Lowood, Thornfield, Moor House, Ferndean)",
    "Character map — Frankenstein (Walton, Victor, Creature, family)",
    "Character map — The Great Gatsby (East Egg, West Egg, Valley of Ashes)",
    "Character map — A Streetcar Named Desire (Kowalski household)",
    "Character map — The Kite Runner (Amir's circle)",
    "Character map — A Doll's House (Helmer household)",
    "Character map — The Handmaid's Tale (Gilead structure)",
    "Character map — Beloved (Sweet Home and 124)",
    "Character map — The Bloody Chamber (gothic intertexts)",
    "Character map — Atonement (Tallis family across timelines)",
    "Character map — Mrs Dalloway / Hours intertextual map",
    "Character map — Top Girls (Marlene's office and dinner party)",
    "Character map — Death of a Salesman (Loman family)",
    "Character map — A View from the Bridge (Carbone household)",
    "Character map — The Picture of Dorian Gray (Dorian, Basil, Henry)",
    "Character map — The Awakening (Pontellier circle)",
    "Character map — Brideshead Revisited (Flyte family)",
  ]);

  emitTitled(ctx, {
    subject: "English Literature",
    year_band: "A-Level",
    topic: "Form, structure and analysis frames",
    year_group: "Year 13",
    description: "A-Level form / structure / analysis frame.",
    style_notes: STYLE_FRAME,
    tags: ["A-Level", "english-literature", "analysis"],
  }, [
    "Tragic hero — Aristotelian arc card",
    "Comic structure — Northrop Frye's modes",
    "Bildungsroman structure — protagonist development arc",
    "Frame narrative — embedded vs framing layers",
    "Unreliable narrator — types card",
    "Stream of consciousness — diagram of free indirect style",
    "Genre conventions — gothic / dystopian / pastoral / urban / postmodern",
    "Dystopian opening planner — A-Level depth",
    "Comparative essay structure — point-by-point vs block",
    "Essay introduction — thesis statement template",
    "Essay conclusion — synthesis and so what?",
    "AO breakdown for A-Level — AO1 / AO2 / AO3 / AO4 / AO5",
    "Coursework planning grid — primary text / critical readings / approach",
    "Voice / persona / poet triangle (poetry analysis)",
    "Volta detector — sonnet structure card",
  ]);

  // ── A-Level English Language ────────────────────────────────────────────
  emitTitled(ctx, {
    subject: "English Language",
    year_band: "A-Level",
    topic: "Frameworks of analysis",
    year_group: "Year 12",
    description: "A-Level English Language framework diagram.",
    style_notes: STYLE_FRAME,
    tags: ["A-Level", "english-language", "frameworks"],
  }, [
    "Phonology — IPA chart card",
    "Lexis and semantics — semantic field web",
    "Grammar — syntactic tree diagram",
    "Pragmatics — Grice's maxims card",
    "Discourse — turn-taking in conversation",
    "Semantic change — types card (broadening, narrowing, melioration, pejoration)",
    "Sociolinguistic variation — Labov's department store study card",
    "Lakoff's deficit model card",
    "Tannen's difference model card",
    "Cameron's myth-of-Mars-and-Venus card",
  ]);

  emitTitled(ctx, {
    subject: "English Language",
    year_band: "A-Level",
    topic: "Language change and child language",
    year_group: "Year 13",
    description: "Language-change or child-language diagram.",
    style_notes: STYLE_FRAME,
    tags: ["A-Level", "english-language", "language-change"],
  }, [
    "Old English to Modern English timeline",
    "Great Vowel Shift diagram",
    "Standardisation of English — five stages",
    "Prescriptivism vs descriptivism card",
    "Influences on English — borrowings from other languages",
    "Theories of child language — nativist (Chomsky)",
    "Theories of child language — behaviourist (Skinner)",
    "Theories of child language — interactionist (Bruner)",
    "Theories of child language — social interactionist (Vygotsky)",
    "Stages of language acquisition timeline",
    "Stages of writing acquisition (Kroll's model)",
    "Stages of reading acquisition (Chall)",
    "Phonological development chart",
    "Lexical and grammatical development chart",
    "Halliday's functions of language card",
  ]);

  // ── A-Level History ─────────────────────────────────────────────────────
  emitTitled(ctx, {
    subject: "History",
    year_band: "A-Level",
    topic: "Skills frames",
    year_group: "Year 12",
    description: "A-Level History skills frame.",
    style_notes: STYLE_HIST,
    tags: ["A-Level", "history", "skills"],
  }, [
    "Source utility 4-box — A-Level depth (NOP plus tone, audience)",
    "Source provenance card — A-Level evaluation",
    "Cause-consequence diamond-9 — A-Level extended",
    "Comparing two interpretations — A-Level frame",
    "Significance criteria — A-Level extended",
    "Historiography wheel — major schools (Whig, Marxist, revisionist, post-revisionist)",
    "Tier-3 vocab — A-Level command words",
    "Essay structure — five-paragraph for A-Level",
    "Coursework planning — A-Level NEA",
    "Chronology timeline — long durée vs event",
  ]);

  emitTitled(ctx, {
    subject: "History",
    year_band: "A-Level",
    topic: "Periods and case studies",
    year_group: "Year 13",
    description: "A-Level History period diagram.",
    style_notes: STYLE_HIST,
    tags: ["A-Level", "history", "case-studies"],
  }, [
    "Tudor monarchs — Henry VII to Elizabeth I family tree",
    "Tudor reformation timeline 1517–1603",
    "Stuart kings family tree — James I to Anne",
    "English Civil War — Royalists vs Parliamentarians comparison",
    "British Empire 1815–1914 map",
    "Causes of WW1 — A-Level extended (MAIN plus structural)",
    "Russian Revolutions 1905 / Feb 1917 / Oct 1917 timeline",
    "Soviet Union — Lenin / Stalin / Khrushchev / Brezhnev / Gorbachev family tree",
    "Weimar Germany — political crises ladder",
    "Rise of Nazi Germany — five-step diagram",
    "Holocaust stages — A-Level depth",
    "WW2 European theatre — full map",
    "WW2 Pacific theatre — full map",
    "Cold War tension graph — A-Level depth (1945–91)",
    "Decolonisation in Africa — independence dates map",
    "Civil Rights Movement (US) — A-Level depth timeline",
    "China — Qing fall to Mao to Deng family tree of leaders",
    "Indian independence — Partition map",
    "Apartheid South Africa — timeline 1948–94",
    "Cuba — pre-revolution to Castro to today",
  ]);

  // ── A-Level Geography ───────────────────────────────────────────────────
  emitTitled(ctx, {
    subject: "Geography",
    year_band: "A-Level",
    topic: "Physical and human geography",
    year_group: "Year 12",
    description: "A-Level Geography diagram.",
    style_notes: STYLE_GEO,
    tags: ["A-Level", "geography"],
  }, [
    "Plate tectonics — A-Level full diagram with hot spots",
    "Volcanic hazard cross-sections — six types",
    "Earthquake P / S / L wave seismograms",
    "Coastal sediment cell — UK example",
    "Glacial budget — A-Level detail",
    "Periglacial features — patterned ground, ice wedges",
    "River regime hydrograph",
    "Drainage basin water balance",
    "Carbon cycle — A-Level fluxes and stores",
    "Water cycle — A-Level fluxes and stores",
    "Hadley / Ferrel / polar cell tri-cell model",
    "ENSO — El Niño vs La Niña diagrams",
    "Tropical-storm formation — A-Level depth",
    "Climate change — RCP scenarios graph",
    "Urbanisation — global trends with megacities map",
    "Bid-rent theory model",
    "Mann's urban model (UK city)",
    "Globalisation — supply chain and TNC structures",
    "Migration — Lee's push-pull model",
    "Demographic transition model — five stages",
    "Population pyramid — youthful / mature / ageing",
    "World HDI choropleth map",
    "Brandt line and core-periphery model",
    "Rostow's stages of economic growth",
    "Frank's dependency theory",
    "Synoptic chart — UK depression",
    "Soils — climax soil profiles (podzol, brown earth, gley)",
    "Ecosystem nutrient cycle — Gersmehl diagrams (rainforest, savanna, deciduous)",
  ]);

  // ── A-Level Politics ────────────────────────────────────────────────────
  emitTitled(ctx, {
    subject: "Politics",
    year_band: "A-Level",
    topic: "UK and US politics",
    year_group: "Year 13",
    description: "A-Level Politics diagram.",
    style_notes: "Concept map style with central pill",
    tags: ["A-Level", "politics"],
  }, [
    "UK political system — three branches",
    "Sources of the UK constitution",
    "Devolution — Scotland / Wales / NI / Greater London",
    "Path of a UK Bill — first reading to royal assent",
    "Cabinet vs shadow cabinet card",
    "Voting systems — FPTP / AMS / STV / SV / list PR comparison",
    "UK general election seats vs votes share graph",
    "UK political ideology spectrum",
    "Conservatism — traditional / one-nation / new right",
    "Liberalism — classical vs modern",
    "Socialism — revolutionary / democratic / third way",
    "Anarchism — individualist vs collectivist",
    "Feminism — first to fourth wave",
    "Multiculturalism / nationalism comparison",
    "Ecologism — shallow vs deep",
    "US system — separation of powers triangle",
    "US system — checks and balances summary",
    "US Bill of Rights — ten amendments card",
    "US Supreme Court — landmark cases timeline",
    "US presidential election — electoral college map",
    "US two-party system — Democrats vs Republicans comparison",
    "EU institutions — Commission / Parliament / Council / ECJ",
    "EU treaties — Rome to Lisbon timeline",
    "International relations — realism vs liberalism vs constructivism",
    "Globalisation in IR — economic / political / cultural",
  ]);

  // ── A-Level Classics ────────────────────────────────────────────────────
  emitTitled(ctx, {
    subject: "Classics",
    year_band: "A-Level",
    topic: "Classical Civilisation",
    year_group: "Year 12",
    description: "A-Level Classics diagram.",
    style_notes: "Greco-Roman line-art with annotated labels",
    tags: ["A-Level", "classics"],
  }, [
    "Greek city-state layout — agora, acropolis, walls",
    "Athenian democracy — institutions diagram",
    "Spartan dual-kingship and ephors structure",
    "Greek hoplite phalanx formation",
    "Persian wars campaign map",
    "Peloponnesian War alliances map",
    "Alexander the Great — empire map",
    "Greek pantheon family tree",
    "Greek theatre layout — orchestra, skene, theatron",
    "Greek tragedy structure card",
    "Iliad and Odyssey — narrative structure (no verbatim text)",
    "Homer's epic similes diagram",
    "Roman Republic — Senate, magistrates, assemblies",
    "Roman empire at greatest extent — map",
    "Roman army organisation diagram",
    "Roman fort layout (e.g. Vindolanda)",
    "Roman house layout — domus and villa",
    "Roman pantheon — family tree (Greco-Roman correspondences)",
    "Aeneid — narrative structure",
    "Roman amphitheatre — Colosseum diagram",
    "Roman roads in Britain map",
    "Constantine and Christianisation timeline",
    "Pompeii / Herculaneum — Vesuvius eruption sequence",
    "Greek vase styles — black-figure vs red-figure",
    "Greek temple architecture — Doric / Ionic / Corinthian columns",
  ]);

  // ── A-Level Philosophy ──────────────────────────────────────────────────
  emitTitled(ctx, {
    subject: "Philosophy",
    year_band: "A-Level",
    topic: "Epistemology, ethics, mind, religion",
    year_group: "Year 13",
    description: "A-Level Philosophy diagram.",
    style_notes: "Concept map style with reasoning arrows",
    tags: ["A-Level", "philosophy"],
  }, [
    "Tripartite definition of knowledge — JTB diagram",
    "Gettier counter-examples card",
    "Innatism vs empiricism comparison",
    "Plato's Theory of Forms — line and cave diagrams",
    "Descartes' Meditations — methodic doubt outline",
    "Hume's fork — relations of ideas vs matters of fact",
    "Kant's categories card",
    "Russell's argument from analogy of mind",
    "Mind-body problem — substance vs property dualism",
    "Identity theory and functionalism comparison",
    "Behaviourism — logical vs methodological",
    "Eliminative materialism card",
    "Personal identity — Locke's memory theory",
    "Personal identity — Parfit and psychological continuity",
    "Free will vs determinism card",
    "Compatibilism — Hume / Frankfurt",
    "Utilitarianism — Bentham vs Mill",
    "Kantian deontology — categorical imperative",
    "Virtue ethics — Aristotle's golden mean",
    "Meta-ethics — cognitivism vs non-cognitivism",
    "Naturalistic fallacy card",
    "Ontological argument — Anselm's reductio",
    "Cosmological argument — Aquinas' five ways",
    "Teleological argument — Paley's watch",
    "Problem of evil — logical vs evidential",
    "Theodicies — Augustinian vs Irenaean",
  ]);

  // ── A-Level Religious Studies ───────────────────────────────────────────
  emitTitled(ctx, {
    subject: "Religious Studies",
    year_band: "A-Level",
    topic: "Philosophy and ethics",
    year_group: "Year 13",
    description: "A-Level RS philosophy / ethics diagram.",
    style_notes: "Concept map with religious vs secular branches",
    tags: ["A-Level", "religious-studies"],
  }, [
    "Arguments for God's existence — five-argument web",
    "Religious experience — types card (mystical, conversion, corporate)",
    "Religious language — cognitivism vs non-cognitivism",
    "Verification and falsification card",
    "Wittgenstein's language games card",
    "Body / soul / mind — religious views card",
    "Life after death — religious views card",
    "Natural Law — Aquinas card",
    "Situation Ethics — Fletcher's four working principles",
    "Kantian ethics — three formulations",
    "Utilitarianism — act vs rule",
    "Virtue ethics in religious context",
    "Religious responses to bioethics — abortion / euthanasia / embryology",
    "Religious responses to environmental ethics",
    "Religious responses to business ethics",
    "Sexual ethics — religious responses",
    "Christianity — historical Jesus vs Christ of faith",
    "Christianity — Atonement theories (penal substitution, ransom, moral influence)",
    "Christianity — liberation theology",
    "Christianity — feminist theology",
    "Christianity — secularisation thesis",
    "Christianity — pluralism / inclusivism / exclusivism",
    "Islam — Sunni vs Shi'a comparison (no figurative depiction of the Prophet ﷺ)",
    "Islam — Sharia sources and schools",
    "Hindu — six darshana traditions",
    "Buddhist Five Aggregates and Three Marks",
    "Sikh — five takhts and Khalsa",
    "Judaism — Torah / Talmud / Mishnah relationships",
  ]);

  // ── A-Level Sociology ──────────────────────────────────────────────────
  emitTitled(ctx, {
    subject: "Sociology",
    year_band: "A-Level",
    topic: "Theory and methods",
    year_group: "Year 13",
    description: "A-Level Sociology theory diagram.",
    style_notes: "Concept map style",
    tags: ["A-Level", "sociology"],
  }, [
    "Functionalism — Parsons / Merton extended",
    "Marxism — classical vs neo-Marxism",
    "Feminism — radical / liberal / Marxist / black / postmodern",
    "Interactionism — Mead, Goffman, Becker",
    "Postmodernism — Baudrillard, Lyotard",
    "Realism — Sayer / Bhaskar",
    "Structure vs agency continuum extended",
    "Methodology — positivism vs interpretivism",
    "Triangulation methods card",
    "Reflexivity in research card",
    "Globalisation theories — sceptics / hyperglobalists / transformationalists",
    "Crime control — left realism vs right realism",
    "Crime — labelling theory and moral panics",
    "Beliefs — secularisation thesis",
    "Beliefs — fundamentalism types",
    "Beliefs — sects, cults, denominations comparison",
    "Stratification — class / status / party (Weber)",
    "Stratification — gender, ethnicity, age",
    "Health inequalities — biomedical vs social model",
  ]);
}
