/**
 * A-Level Biology, Chemistry, Physics — diagram catalogue.
 *
 * Anchored to AQA, Pearson Edexcel, OCR A/B and CIE A-Level science
 * specifications. Bundled to keep file count manageable.
 *
 * Target: ~440 entries combined (~150 each, with bonus depth in Bio).
 */
import { emitTitled } from "../../_helpers.mjs";

const STYLE_BIO = "Clean line-art, soft fill, label leaders to the right, exam-paper white";
const STYLE_CHEM = "Skeletal/structural formula in black, mechanism arrows curly red";
const STYLE_PHYS = "Black-axis graph or apparatus diagram, vectors in red, exam-paper feel";

export function build(ctx) {
  // ── A-Level Biology ─────────────────────────────────────────────────────
  emitTitled(ctx, {
    subject: "Biology",
    year_band: "A-Level",
    topic: "Biological molecules",
    year_group: "Year 12",
    description: "A-Level Biology biological-molecule diagram.",
    style_notes: STYLE_BIO,
    tags: ["A-Level", "biology", "molecules"],
  }, [
    "Carbohydrates — α and β glucose ring structures",
    "Carbohydrates — maltose, sucrose, lactose disaccharide formation",
    "Carbohydrates — starch (amylose / amylopectin) structure",
    "Carbohydrates — glycogen branched structure",
    "Carbohydrates — cellulose with β-1,4 glycosidic bonds",
    "Lipids — triglyceride structure (glycerol + 3 fatty acids)",
    "Lipids — saturated vs unsaturated fatty acid card",
    "Lipids — phospholipid structure with hydrophilic head",
    "Proteins — amino acid general structure",
    "Proteins — peptide bond formation",
    "Proteins — primary / secondary / tertiary / quaternary structure",
    "Proteins — α-helix and β-pleated sheet",
    "Proteins — globular vs fibrous comparison",
    "Enzyme — induced-fit model",
    "Enzyme inhibition — competitive vs non-competitive",
    "DNA — full antiparallel double helix with base pairs",
    "DNA replication — semi-conservative model with helicase / polymerase",
    "DNA replication — leading vs lagging strand with Okazaki fragments",
    "RNA — mRNA, tRNA, rRNA comparison",
    "Transcription — DNA to mRNA at the nucleus",
    "Translation — ribosome with tRNA bringing amino acids",
    "ATP structure — adenine + ribose + 3 phosphates",
    "ATP hydrolysis to ADP + Pi card",
    "Water — hydrogen-bonded structure and properties",
  ]);

  emitTitled(ctx, {
    subject: "Biology",
    year_band: "A-Level",
    topic: "Cells and transport",
    year_group: "Year 12",
    description: "A-Level cell / transport diagram.",
    style_notes: STYLE_BIO,
    tags: ["A-Level", "biology", "cells"],
  }, [
    "Eukaryotic cell — A-Level fully labelled with all organelles",
    "Prokaryotic cell — A-Level labelled (DNA, plasmids, ribosomes 70S, capsule)",
    "Mitochondrion — labelled with cristae, matrix, ATP synthase",
    "Chloroplast — labelled with grana, stroma, thylakoids",
    "Endoplasmic reticulum — rough vs smooth comparison",
    "Golgi apparatus — vesicle traffic diagram",
    "Lysosomes — phagocytosis and digestion",
    "Cytoskeleton — microfilaments / intermediate / microtubules",
    "Plasma membrane — fluid mosaic model",
    "Cholesterol in the membrane diagram",
    "Diffusion vs facilitated diffusion comparison",
    "Active transport — Na⁺/K⁺ pump diagram",
    "Co-transport — glucose absorption in the gut",
    "Endocytosis vs exocytosis comparison",
    "Cell cycle — interphase, mitosis, cytokinesis with checkpoints",
    "Mitosis — full sequence of stages",
    "Meiosis — full sequence including crossing over",
    "Stem cells — totipotent / pluripotent / multipotent / unipotent",
    "Cancer — uncontrolled mitosis diagram",
  ]);

  emitTitled(ctx, {
    subject: "Biology",
    year_band: "A-Level",
    topic: "Genetics and gene expression",
    year_group: "Year 13",
    description: "A-Level genetics diagram.",
    style_notes: STYLE_BIO,
    tags: ["A-Level", "biology", "genetics"],
  }, [
    "Mendelian genetics — monohybrid cross",
    "Mendelian genetics — dihybrid cross 9:3:3:1",
    "Codominance — blood groups card",
    "Sex linkage — pedigree of haemophilia",
    "Linkage and crossing over diagram",
    "Hardy-Weinberg equilibrium — formula card",
    "Allele frequency change — selection diagram",
    "Genetic drift vs gene flow comparison",
    "Speciation — allopatric vs sympatric",
    "Gene mutation types — substitution / deletion / insertion",
    "Chromosomal mutation — duplication / inversion / translocation",
    "Lac operon — induced gene expression",
    "Trp operon — repressed gene expression",
    "Epigenetics — DNA methylation and histone modification",
    "Stem cell therapy — bone marrow transplant card",
    "Recombinant DNA — restriction enzymes and ligase",
    "Gene cloning — vector insertion diagram",
    "Polymerase chain reaction — three-step thermal cycle",
    "Gel electrophoresis — DNA fragment separation",
    "DNA fingerprinting — STR profiling card",
    "CRISPR-Cas9 — gene editing diagram",
  ]);

  emitTitled(ctx, {
    subject: "Biology",
    year_band: "A-Level",
    topic: "Energy transfers — photosynthesis and respiration",
    year_group: "Year 13",
    description: "Bioenergetics diagram for A-Level Biology.",
    style_notes: STYLE_BIO,
    tags: ["A-Level", "biology", "bioenergetics"],
  }, [
    "Light-dependent reaction — Z-scheme of electron flow",
    "Light-dependent reaction — photosystems I and II",
    "Light-dependent reaction — non-cyclic photophosphorylation",
    "Light-dependent reaction — cyclic photophosphorylation",
    "Calvin cycle — full reactions with RuBisCO",
    "Limiting factors of photosynthesis — three graphs",
    "Glycolysis — full steps card",
    "Link reaction — pyruvate to acetyl CoA",
    "Krebs (citric acid) cycle — fully labelled",
    "Oxidative phosphorylation — electron transport chain",
    "Chemiosmosis — proton gradient and ATP synthase",
    "Anaerobic respiration — lactate fermentation",
    "Anaerobic respiration — alcohol fermentation in yeast",
    "Respiratory quotient (RQ) card",
  ]);

  emitTitled(ctx, {
    subject: "Biology",
    year_band: "A-Level",
    topic: "Physiology and homeostasis",
    year_group: "Year 13",
    description: "A-Level physiology diagram.",
    style_notes: STYLE_BIO,
    tags: ["A-Level", "biology", "physiology"],
  }, [
    "Heart — A-Level fully labelled with electrical conduction (SAN, AVN, bundle of His, Purkinje)",
    "Cardiac cycle — pressure-volume loops",
    "Blood vessels — comparison of artery / arteriole / capillary / venule / vein",
    "Tissue fluid formation and return diagram",
    "Lung structure — A-Level labelled with surfactant cells",
    "Spirometer trace — labelled (tidal volume, IRV, ERV, RV)",
    "Mammalian gas exchange — alveolus with capillary",
    "Insect gas exchange — tracheal system",
    "Fish gas exchange — countercurrent flow at gills",
    "Plant gas exchange — leaf stomata and mesophyll",
    "Xylem and phloem cross-section — A-Level detail",
    "Transpiration — cohesion-tension theory",
    "Phloem translocation — mass-flow hypothesis",
    "Nephron — full A-Level labelling with osmoregulation",
    "ADH and water reabsorption — receptor pathway",
    "Liver lobule — A-Level labelled (portal triad, sinusoid)",
    "Blood glucose regulation — insulin and glucagon receptor pathways",
    "Negative feedback loop — generic A-Level diagram",
    "Thermoregulation — hypothalamus pathway",
    "Reflex arc — spinal cord cross-section",
    "Resting potential — Na⁺/K⁺ pump diagram",
    "Action potential — labelled phases on axon",
    "Synapse — vesicle release and receptor binding",
    "Cholinergic synapse — acetylcholine breakdown",
    "Neuromuscular junction diagram",
    "Sliding filament theory — sarcomere diagrams",
    "Muscle fibre types — slow vs fast comparison",
    "Eye accommodation — near vs far",
    "Photoreceptors — rod vs cone comparison",
  ]);

  emitTitled(ctx, {
    subject: "Biology",
    year_band: "A-Level",
    topic: "Ecology and biodiversity",
    year_group: "Year 13",
    description: "A-Level ecology diagram.",
    style_notes: STYLE_BIO,
    tags: ["A-Level", "biology", "ecology"],
  }, [
    "Energy flow through an ecosystem — gross / net primary productivity",
    "Carbon cycle — A-Level detailed",
    "Nitrogen cycle — A-Level detailed with bacteria",
    "Phosphorus cycle — A-Level diagram",
    "Succession — primary on bare rock to climax community",
    "Succession — secondary after disturbance",
    "Population growth — exponential vs logistic curves",
    "Predator-prey cycle — phase-shifted curves",
    "Carrying capacity card",
    "Species richness vs evenness card",
    "Simpson's index of diversity formula",
    "Mark-release-recapture — Lincoln Index",
    "Belt transect with kite diagram",
    "Quadrat sampling — random / systematic",
    "Biodiversity hotspots map",
    "Conservation methods card",
  ]);

  // ── A-Level Chemistry ──────────────────────────────────────────────────
  emitTitled(ctx, {
    subject: "Chemistry",
    year_band: "A-Level",
    topic: "Atomic structure and bonding",
    year_group: "Year 12",
    description: "A-Level Chemistry atomic / bonding diagram.",
    style_notes: STYLE_CHEM,
    tags: ["A-Level", "chemistry", "atomic-structure"],
  }, [
    "s, p, d, f orbitals — shape diagrams",
    "Electron configuration — boxes-and-arrows for first-row d-block",
    "Mass spectrometer — labelled (ionisation, acceleration, deflection, detection)",
    "Mass spectrum interpretation — molecular ion peak",
    "Isotopes from a mass spectrum",
    "Successive ionisation energies — log graph",
    "Periodic trends — atomic radius across a period and down a group",
    "Periodic trends — first ionisation energy across periods 2 and 3",
    "Bonding triangle — ionic / covalent / metallic / polar covalent",
    "Lewis structures — common molecules card",
    "VSEPR — shapes of molecules card (linear, trigonal, tetrahedral, etc.)",
    "Bond polarity and dipole moment",
    "Hydrogen bonding — water and DNA examples",
    "Permanent dipole vs van der Waals comparison",
    "Solubility of ionic vs covalent in water card",
  ]);

  emitTitled(ctx, {
    subject: "Chemistry",
    year_band: "A-Level",
    topic: "Energetics and equilibria",
    year_group: "Year 13",
    description: "A-Level Chemistry energetics / equilibria diagram.",
    style_notes: STYLE_CHEM,
    tags: ["A-Level", "chemistry", "energetics"],
  }, [
    "Born-Haber cycle — sodium chloride worked",
    "Born-Haber cycle — magnesium oxide worked",
    "Hess's law — generic energy cycle",
    "Bond enthalpy calculation card",
    "Entropy change ΔS card",
    "Gibbs free energy — ΔG = ΔH − TΔS",
    "Spontaneity decision card",
    "Energy profile with multiple steps and intermediates",
    "Reaction-rate-determining-step diagram",
    "Maxwell-Boltzmann distribution — temperature shift",
    "Maxwell-Boltzmann distribution — catalyst lowers Ea",
    "Equilibrium constant Kc — formula and worked example",
    "Equilibrium constant Kp — partial pressure card",
    "Le Chatelier — pressure / temperature / concentration / catalyst summary",
    "Brønsted-Lowry acid / base card",
    "Strong vs weak acid pH curve — titration",
    "pH calculation — strong acid worked example",
    "pKa and Ka relationship card",
    "Buffer solution — Henderson-Hasselbalch worked",
    "Buffer action — addition of small acid / base",
    "Indicator choice for titrations card",
    "Solubility product Ksp card",
  ]);

  emitTitled(ctx, {
    subject: "Chemistry",
    year_band: "A-Level",
    topic: "Inorganic and transition metals",
    year_group: "Year 13",
    description: "A-Level Chemistry inorganic diagram.",
    style_notes: STYLE_CHEM,
    tags: ["A-Level", "chemistry", "inorganic"],
  }, [
    "Group 2 reactivity trend — reactions with water and oxygen",
    "Group 7 halogens — disproportionation reactions",
    "Period 3 oxides — bonding and pH trend",
    "Transition metal definition card",
    "Variable oxidation states card",
    "Coloured complex ions — d-d transition diagram",
    "Octahedral complex — six-ligand diagram",
    "Tetrahedral complex — four-ligand diagram",
    "Square-planar complex card",
    "Cis-trans isomerism in complex ions",
    "Optical isomerism in complex ions",
    "Catalysis — homogeneous (V₂O₅ Contact process)",
    "Catalysis — heterogeneous (Haber process)",
    "Electrochemical cell — labelled (electrolyte, electrodes, salt bridge)",
    "Standard hydrogen electrode card",
    "Electrode potential table — interpretation",
    "Fuel cells — A-Level detail",
  ]);

  emitTitled(ctx, {
    subject: "Chemistry",
    year_band: "A-Level",
    topic: "Organic chemistry and analysis",
    year_group: "Year 13",
    description: "A-Level organic mechanism / analysis diagram.",
    style_notes: STYLE_CHEM,
    tags: ["A-Level", "chemistry", "organic"],
  }, [
    "Nomenclature — IUPAC rules card",
    "Stereoisomerism — E/Z (cis/trans) card",
    "Optical isomerism — R/S enantiomers",
    "Free-radical substitution — methane and chlorine mechanism",
    "Electrophilic addition — alkene with HBr (Markovnikov)",
    "Electrophilic addition — alkene with Br₂",
    "Nucleophilic substitution — SN1 vs SN2 mechanisms",
    "Elimination — E1 vs E2 mechanisms",
    "Electrophilic aromatic substitution — nitration of benzene",
    "Friedel-Crafts acylation mechanism",
    "Oxidation of alcohols — primary, secondary, tertiary outcomes",
    "Reflux apparatus — labelled",
    "Distillation apparatus — labelled",
    "Carbonyls — aldehydes vs ketones",
    "Carbonyls — addition with HCN mechanism",
    "Carboxylic acid — acidity comparison card",
    "Esterification mechanism",
    "Amines — basicity card and formation",
    "Amino acids — zwitterion and isoelectric point",
    "Polypeptide formation — condensation",
    "Hydrolysis of ester / amide",
    "Addition polymers — polyethene chain",
    "Condensation polymers — polyester / polyamide / DNA / proteins",
    "IR spectroscopy — characteristic absorption ranges chart",
    "¹H NMR — chemical shift table and integration",
    "¹³C NMR — chemical shift table",
    "Mass spectrometry — fragmentation patterns",
    "TLC chromatography card",
    "Gas chromatography card",
    "Test for carbonyl — Brady's reagent",
    "Test for aldehyde — Tollens' reagent",
    "Test for primary alcohol — chromate(VI)",
  ]);

  // ── A-Level Physics ────────────────────────────────────────────────────
  emitTitled(ctx, {
    subject: "Physics",
    year_band: "A-Level",
    topic: "Mechanics and materials",
    year_group: "Year 12",
    description: "A-Level Physics mechanics / materials diagram.",
    style_notes: STYLE_PHYS,
    tags: ["A-Level", "physics", "mechanics"],
  }, [
    "Vector resolution — components on inclined plane",
    "Moments — meter rule equilibrium",
    "Centre of mass / centre of gravity",
    "Couple and torque card",
    "Free-body diagram — block on inclined plane with friction",
    "Newton's three laws summary card",
    "Projectile motion — full trajectory diagram",
    "Stopping distance with reaction time graph",
    "Stress-strain graph — elastic, yield, plastic, ultimate, breaking",
    "Stress-strain graph — ductile vs brittle vs polymer",
    "Young's modulus formula card",
    "Hooke's law revisited at A-Level",
    "Energy conservation — projectile launching",
    "Power — instantaneous vs average card",
    "Efficiency calculation card",
  ]);

  emitTitled(ctx, {
    subject: "Physics",
    year_band: "A-Level",
    topic: "Waves, optics, quantum",
    year_group: "Year 12",
    description: "A-Level Physics waves / quantum diagram.",
    style_notes: STYLE_PHYS,
    tags: ["A-Level", "physics", "waves", "quantum"],
  }, [
    "Wave properties — period, frequency, wavelength, phase",
    "Superposition — constructive and destructive interference",
    "Stationary wave on a string — fundamental and harmonics",
    "Stationary wave in a pipe — closed vs open ends",
    "Polarisation diagram — vertical and horizontal",
    "Refraction — Snell's law worked",
    "Total internal reflection — critical angle worked",
    "Lens — converging and diverging",
    "Diffraction — single slit pattern",
    "Diffraction — double slit pattern (Young's experiment)",
    "Diffraction grating — n λ = d sin θ formula card",
    "Photoelectric effect — apparatus and threshold frequency",
    "Photoelectric equation — hf = φ + KEmax",
    "Wave-particle duality card",
    "Electron diffraction diagram",
    "Energy levels — atomic transitions and emission spectrum",
    "Continuous vs line spectra card",
    "Hydrogen energy-level diagram",
    "Photon emission/absorption diagram",
  ]);

  emitTitled(ctx, {
    subject: "Physics",
    year_band: "A-Level",
    topic: "Electricity, fields, capacitors",
    year_group: "Year 12",
    description: "A-Level Physics electricity / fields diagram.",
    style_notes: STYLE_PHYS,
    tags: ["A-Level", "physics", "electricity", "fields"],
  }, [
    "Series and parallel resistor combinations",
    "Potential divider — fixed and variable",
    "EMF and internal resistance graph",
    "Capacitor — labelled (plates, dielectric, leads)",
    "Capacitance formula card and energy ½CV²",
    "Capacitor charging curve — exponential",
    "Capacitor discharging curve — exponential",
    "RC time constant card",
    "Coulomb's law — point charges diagram",
    "Electric field around a point charge",
    "Electric field between parallel plates",
    "Equipotential lines around a point charge",
    "Gravitational field around a point mass",
    "Gravitational potential and equipotentials",
    "Comparing electric and gravitational fields card",
    "Magnetic field around a wire / solenoid",
    "Force on a current-carrying wire — F = BIL",
    "Force on a moving charge — F = BQv",
    "Mass spectrometer — A-Level circular motion",
    "Cyclotron diagram",
    "Electromagnetic induction — Faraday's law",
    "Lenz's law diagram",
    "Transformer — A-Level efficiency considerations",
    "AC generator and rectification — half/full wave",
  ]);

  emitTitled(ctx, {
    subject: "Physics",
    year_band: "A-Level",
    topic: "Thermal, nuclear, astrophysics",
    year_group: "Year 13",
    description: "A-Level thermal / nuclear / astrophysics diagram.",
    style_notes: STYLE_PHYS,
    tags: ["A-Level", "physics", "thermal", "nuclear", "astrophysics"],
  }, [
    "Ideal gas equation — pV = nRT card",
    "Boyle's law / Charles's law / Gay-Lussac's law graphs",
    "Brownian motion — particle path diagram",
    "Kinetic theory — average kinetic energy and temperature",
    "Specific heat capacity — q = mcΔT card",
    "Specific latent heat — q = mL card",
    "Heating curve with phase changes",
    "Carnot cycle — pV diagram",
    "Atomic structure — Rutherford / Bohr / quantum",
    "Binding energy per nucleon — curve labelled",
    "Mass defect calculation card",
    "Nuclear fission — chain reaction diagram",
    "Nuclear fusion — proton-proton chain",
    "Radioactive decay equation — N = N₀ e^(-λt)",
    "Activity formula card and half-life",
    "Decay-curve graph with multiple half-lives",
    "Detector — Geiger-Müller tube diagram",
    "Stellar Hertzsprung-Russell diagram",
    "Stellar life cycle — low- vs high-mass routes",
    "Black-body spectrum and Wien's law",
    "Stefan-Boltzmann law card",
    "Doppler shift in stellar spectra",
    "Hubble's law — recession velocity vs distance",
    "Cosmic microwave background — angular spectrum sketch",
    "Special relativity — time dilation diagram",
    "Special relativity — length contraction diagram",
  ]);

  emitTitled(ctx, {
    subject: "Physics",
    year_band: "A-Level",
    topic: "Circular and harmonic motion",
    year_group: "Year 13",
    description: "Circular / SHM diagram for A-Level Physics.",
    style_notes: STYLE_PHYS,
    tags: ["A-Level", "physics", "circular-motion", "SHM"],
  }, [
    "Uniform circular motion — centripetal acceleration",
    "Centripetal force formula card and worked example (car on banked track)",
    "Conical pendulum diagram",
    "Vertical loop — minimum speed at top",
    "Simple harmonic motion — x, v, a graphs",
    "Mass on a spring — period formula card",
    "Simple pendulum — period formula card",
    "SHM energy graphs — KE and PE vs displacement",
    "Damped SHM graph — light, critical, heavy",
    "Resonance graph — amplitude vs driving frequency",
  ]);
}
