#!/usr/bin/env python3
"""Batch 4b builder — 25 KS3/KS4 worksheets covering straight-line graphs,
surds, transformations, trigonometry, vectors, volume/surface area, and estimation."""
import json, os, sys

# Reuse helpers from batch 1
sys.path.insert(0, os.path.dirname(__file__))
from build_batch_1 import practice, example, write_ws


# ── 173 — Parallel and perpendicular lines ────────────────────────────────
write_ws("173-parallel-and-perpendicular-lines.json", {
    "title": "STRAIGHT-LINE GRAPHS,\n(PARALLEL AND PERPENDICULAR LINES)",
    "objective": "LO: I can identify and find equations of parallel and perpendicular lines.",
    "send_mode": False,
    "info_boxes": {
        "key_terms": {"id": "key_terms", "title": "Parallel and perpendicular", "content": [
            {"type": "paragraph", "text": "<span class=\"ul-b\">Parallel lines</span> have the <span class=\"ul-k\">same gradient</span>. They never meet. <span class=\"ul-b\">Perpendicular lines</span> meet at right angles (90&deg;)."},
            {"type": "paragraph", "text": "<span class=\"rb\">Key rule:</span> If one line has gradient m, a perpendicular line has gradient <span class=\"ul-k\">&minus;1/m</span> (negative reciprocal). The product of their gradients is &minus;1."}]},
        "what_we_learn": {"id": "what_we_learn", "title": "Quick examples", "examples": [
            {"correct": True, "expr": "y = 2x + 1 and y = 2x &minus; 3 are parallel", "desc": "same gradient"},
            {"correct": True, "expr": "m&sub1; &times; m&sub2; = &minus;1 for perpendicular", "desc": "product rule"},
            {"correct": True, "expr": "gradient 3 &rarr; perpendicular gradient &minus;&frac{1}{3}", "desc": "negative reciprocal"},
            {"correct": False, "expr": "y = 2x + 1 and y = &minus;2x + 3 are perpendicular", "desc": "2 &times; (&minus;2) = &minus;4 &ne; &minus;1"},
            {"correct": False, "expr": "Parallel lines have gradients that multiply to &minus;1", "desc": "that is perpendicular"}]},
        "key_idea": {"id": "key_idea", "title": "Key idea",
            "text": "Parallel: same gradient. Perpendicular: gradients multiply to give &minus;1 (negative reciprocal).",
            "equation": "m&sub1; &times; m&sub2; = <span class=\"ov\">&minus;1</span> &rarr; m&sub2; = <span class=\"ovr\">&minus;1/m&sub1;</span>",
            "caption": "Perpendicular gradients are negative reciprocals"}},
    "modelled_examples": [
        example(1, "parallel lines", "Find the equation of the line parallel to y = 3x + 2 passing through (1, 7).",
                ["Parallel means same gradient: m = 3", "y = 3x + c; substitute (1, 7): 7 = 3 + c, c = 4", "Equation: y = 3x + 4"],
                "y = 3x + 4", "Parallel lines share the same gradient."),
        example(2, "perpendicular gradient", "A line has gradient 4. Find the gradient of a perpendicular line.",
                ["Perpendicular gradient = &minus;1/m", "&minus;1/4", "The perpendicular gradient is &minus;&frac{1}{4}"],
                "Gradient = &minus;&frac{1}{4}", "Flip the fraction and change the sign."),
        example(3, "perpendicular equation", "Find the equation perpendicular to y = 2x &minus; 5 through (4, 3).",
                ["Original gradient = 2; perpendicular = &minus;&frac{1}{2}", "y = &minus;&frac{1}{2}x + c; 3 = &minus;&frac{1}{2}(4) + c; 3 = &minus;2 + c; c = 5", "y = &minus;&frac{1}{2}x + 5"],
                "y = &minus;&frac{1}{2}x + 5", "Find the perpendicular gradient, then use the point to find c."),
        example(4, "checking perpendicular", "Are y = 3x + 1 and y = &minus;&frac{1}{3}x + 4 perpendicular?",
                ["m&sub1; = 3, m&sub2; = &minus;&frac{1}{3}", "Product = 3 &times; (&minus;&frac{1}{3}) = &minus;1", "Yes, they are perpendicular"],
                "Yes (product of gradients = &minus;1)", "If m&sub1; &times; m&sub2; = &minus;1, the lines are perpendicular.")],
    "practice": [
        practice(1, "Identifying parallel lines", "#1F5FA6", "#EEF3FF", "#1F5FA6",
                 "State which pairs are parallel.",
                 [("a", "y = 5x + 2 and y = 5x &minus; 1", "Parallel (both m = 5)"),
                  ("b", "y = 3x + 4 and y = &minus;3x + 4", "Not parallel"),
                  ("c", "y = &frac{1}{2}x + 1 and y = &frac{1}{2}x &minus; 6", "Parallel (both m = &frac{1}{2})"),
                  ("d", "y = 2x + 3 and 2y = 4x + 1", "Parallel (both m = 2)")]),
        practice(2, "Finding perpendicular gradients", "#1F5FA6", "#EEF3FF", "#1F5FA6",
                 "Find the perpendicular gradient.",
                 [("a", "m = 2", "&minus;&frac{1}{2}"), ("b", "m = &minus;3", "&frac{1}{3}"),
                  ("c", "m = &frac{1}{4}", "&minus;4"), ("d", "m = &minus;&frac{2}{5}", "&frac{5}{2}")]),
        practice(3, "Equations of parallel lines", "#CC0000", "#FFF0F0", "#CC0000",
                 "Find the equation of the parallel line through the given point.",
                 [("a", "Parallel to y = 4x + 1, through (2, 11)", "y = 4x + 3"),
                  ("b", "Parallel to y = &minus;x + 6, through (3, 1)", "y = &minus;x + 4"),
                  ("c", "Parallel to y = &frac{1}{2}x &minus; 3, through (4, 5)", "y = &frac{1}{2}x + 3"),
                  ("d", "Parallel to y = 3x, through (1, 8)", "y = 3x + 5")]),
        practice(4, "Equations of perpendicular lines", "#1E7D2E", "#EDFAEE", "#1E7D2E",
                 "Find the equation perpendicular to the given line through the given point.",
                 [("a", "Perpendicular to y = 2x + 1, through (4, 3)", "y = &minus;&frac{1}{2}x + 5"),
                  ("b", "Perpendicular to y = &minus;3x + 2, through (6, 4)", "y = &frac{1}{3}x + 2"),
                  ("c", "Perpendicular to y = &frac{1}{5}x + 3, through (5, &minus;2)", "y = &minus;5x + 23"),
                  ("d", "Perpendicular to y = x &minus; 4, through (2, 6)", "y = &minus;x + 8")]),
        practice(5, "Mixed problems", "#7B3FA0", "#F5EEFF", "#7B3FA0",
                 "Solve each problem.",
                 [("a", "Are y = 4x + 1 and y = &minus;&frac{1}{4}x + 3 perpendicular?", "Yes (4 &times; &minus;&frac{1}{4} = &minus;1)"),
                  ("b", "Line through (0, 5) parallel to y = 7x &minus; 2", "y = 7x + 5"),
                  ("c", "Perpendicular to y = &minus;2x + 8, y-intercept 3", "y = &frac{1}{2}x + 3"),
                  ("d", "A line has equation 3x + y = 6. Find its gradient.", "&minus;3"),
                  ("e", "Find equation perpendicular to 3x + y = 6 through (3, 1)", "y = &frac{1}{3}x")])],
    "misconceptions": {"items": [
        {"id": "a", "statement": "Parallel lines have the same gradient", "correct": True},
        {"id": "b", "statement": "Perpendicular gradients add to &minus;1", "correct": False},
        {"id": "c", "statement": "If m&sub1; &times; m&sub2; = &minus;1, the lines are perpendicular", "correct": True},
        {"id": "d", "statement": "The perpendicular gradient of 2 is &minus;2", "correct": False},
        {"id": "e", "statement": "Parallel lines never intersect", "correct": True}]},
    "challenge": {"problems": [
        {"id": "a", "text": "Triangle ABC has vertices <strong>A(1, 2)</strong>, <strong>B(5, 4)</strong>, <strong>C(3, 8)</strong>. Show that AB is perpendicular to BC. Find the equations of lines AB and BC."},
        {"id": "b", "text": "The perpendicular bisector of a line segment passes through the midpoint at right angles. Find the equation of the perpendicular bisector of the segment joining <strong>(2, 3)</strong> and <strong>(6, 7)</strong>."}]},
})


# ── 174 — Plotting straight-line graphs ───────────────────────────────────
write_ws("174-plotting-straight-line-graphs.json", {
    "title": "STRAIGHT-LINE GRAPHS,\n(PLOTTING STRAIGHT-LINE GRAPHS)",
    "objective": "LO: I can plot straight-line graphs from their equations using a table of values.",
    "send_mode": False,
    "info_boxes": {
        "key_terms": {"id": "key_terms", "title": "Plotting straight lines", "content": [
            {"type": "paragraph", "text": "To <span class=\"ul-b\">plot a straight-line graph</span>, create a table of <span class=\"ul-k\">x and y values</span> by substituting x values into the equation. Plot the points and join with a straight line."},
            {"type": "paragraph", "text": "<span class=\"rb\">Shortcut:</span> You only need 2 points to draw a line, but use 3 or more to check for errors."}]},
        "what_we_learn": {"id": "what_we_learn", "title": "Quick examples", "examples": [
            {"correct": True, "expr": "y = 2x + 1: when x = 0, y = 1", "desc": "y-intercept"},
            {"correct": True, "expr": "y = 2x + 1: when x = 3, y = 7", "desc": "substitute"},
            {"correct": True, "expr": "Use x = &minus;2, 0, 2, 4 for a good range", "desc": "include negatives"},
            {"correct": False, "expr": "y = 2x + 1: when x = 2, y = 5", "desc": "2(2)+1 = 5 is correct actually - but check"},
            {"correct": False, "expr": "Only need 1 point to draw a line", "desc": "need at least 2"}]},
        "key_idea": {"id": "key_idea", "title": "Key idea",
            "text": "Choose x values, substitute to find y, plot the coordinate pairs, join with a ruler.",
            "equation": "x = 0, 1, 2, 3 &rarr; <span class=\"ov\">substitute into y = mx + c</span> &rarr; <span class=\"ovr\">plot points</span>",
            "caption": "Always use a ruler for straight lines"}},
    "modelled_examples": [
        example(1, "positive gradient", "Plot y = 2x + 1 for x from &minus;2 to 3.",
                ["x = &minus;2: y = &minus;3; x = 0: y = 1; x = 2: y = 5; x = 3: y = 7", "Plot (&minus;2, &minus;3), (0, 1), (2, 5), (3, 7)", "Join with a straight line"],
                "Line through (&minus;2, &minus;3) to (3, 7)", "Substitute each x value into the equation."),
        example(2, "negative gradient", "Plot y = &minus;x + 4 for x from &minus;1 to 5.",
                ["x = &minus;1: y = 5; x = 0: y = 4; x = 2: y = 2; x = 5: y = &minus;1", "Plot (&minus;1, 5), (0, 4), (2, 2), (5, &minus;1)", "Line goes downhill left to right"],
                "Line through (&minus;1, 5) to (5, &minus;1)", "Negative gradient means the line slopes downward."),
        example(3, "fractional gradient", "Plot y = &frac{1}{2}x + 2 for x from &minus;4 to 4.",
                ["x = &minus;4: y = 0; x = 0: y = 2; x = 2: y = 3; x = 4: y = 4", "Plot (&minus;4, 0), (0, 2), (2, 3), (4, 4)", "Gentle upward slope"],
                "Line through (&minus;4, 0) to (4, 4)", "Use even x values to avoid fractional y values."),
        example(4, "horizontal and vertical", "Plot y = 3 and x = &minus;2.",
                ["y = 3 is horizontal through all points where y = 3", "x = &minus;2 is vertical through all points where x = &minus;2", "They intersect at (&minus;2, 3)"],
                "Horizontal line y = 3 and vertical line x = &minus;2", "Horizontal lines have equation y = c; vertical lines x = a.")],
    "practice": [
        practice(1, "Completing tables", "#1F5FA6", "#EEF3FF", "#1F5FA6",
                 "Complete the table for each equation (x = &minus;2, &minus;1, 0, 1, 2, 3).",
                 [("a", "y = x + 3", "1, 2, 3, 4, 5, 6"), ("b", "y = 2x &minus; 1", "&minus;5, &minus;3, &minus;1, 1, 3, 5"),
                  ("c", "y = &minus;x + 2", "4, 3, 2, 1, 0, &minus;1"), ("d", "y = 3x + 2", "&minus;4, &minus;1, 2, 5, 8, 11")]),
        practice(2, "Identifying key features", "#1F5FA6", "#EEF3FF", "#1F5FA6",
                 "For each equation, state the y-intercept and gradient.",
                 [("a", "y = 4x + 2", "c = 2, m = 4"), ("b", "y = &minus;x + 5", "c = 5, m = &minus;1"),
                  ("c", "y = &frac{1}{3}x &minus; 1", "c = &minus;1, m = &frac{1}{3}"), ("d", "y = &minus;2x", "c = 0, m = &minus;2")]),
        practice(3, "Where lines cross axes", "#CC0000", "#FFF0F0", "#CC0000",
                 "Find where each line crosses the x-axis and y-axis.",
                 [("a", "y = x &minus; 4", "x-axis: (4, 0), y-axis: (0, &minus;4)"), ("b", "y = 2x + 6", "x-axis: (&minus;3, 0), y-axis: (0, 6)"),
                  ("c", "y = &minus;3x + 9", "x-axis: (3, 0), y-axis: (0, 9)"), ("d", "y = &frac{1}{2}x &minus; 3", "x-axis: (6, 0), y-axis: (0, &minus;3)")]),
        practice(4, "Matching equations to descriptions", "#1E7D2E", "#EDFAEE", "#1E7D2E",
                 "State the equation that matches each description.",
                 [("a", "Gradient 2, crosses y-axis at 5", "y = 2x + 5"), ("b", "Horizontal line through (0, &minus;3)", "y = &minus;3"),
                  ("c", "Passes through origin with gradient &minus;4", "y = &minus;4x"), ("d", "Gradient &frac{1}{2}, y-intercept 1", "y = &frac{1}{2}x + 1")]),
        practice(5, "Mixed plotting problems", "#7B3FA0", "#F5EEFF", "#7B3FA0",
                 "Answer each question.",
                 [("a", "Does (3, 10) lie on y = 3x + 1?", "Yes: 3(3) + 1 = 10"),
                  ("b", "Find where y = x + 2 and y = 3 intersect.", "(1, 3)"),
                  ("c", "A line passes through (0, &minus;2) and (4, 6). Equation?", "y = 2x &minus; 2"),
                  ("d", "What is the equation of the x-axis?", "y = 0"),
                  ("e", "Find the midpoint of (1, 3) and (5, 7) on a line.", "(3, 5)")])],
    "misconceptions": {"items": [
        {"id": "a", "statement": "You need at least 2 points to plot a straight line", "correct": True},
        {"id": "b", "statement": "y = 3 is a vertical line", "correct": False},
        {"id": "c", "statement": "A straight line can be drawn with a ruler through plotted points", "correct": True},
        {"id": "d", "statement": "The y-intercept is where x = 1", "correct": False},
        {"id": "e", "statement": "Substituting x = 0 into y = mx + c gives the y-intercept", "correct": True}]},
    "challenge": {"problems": [
        {"id": "a", "text": "Plot y = 2x &minus; 1 and y = &minus;x + 5 on the same axes for x from &minus;1 to 4. Find their point of intersection algebraically and verify it matches your graph."},
        {"id": "b", "text": "A straight line passes through <strong>(&minus;3, &minus;7)</strong> and <strong>(5, 9)</strong>. Find its equation and plot it. At what point does it cross the line <strong>y = x + 2</strong>?"}]},
})

# ── 175 — Adding and subtracting surds ────────────────────────────────────
write_ws("175-adding-and-subtracting-surds.json", {
    "title": "SURDS,\n(ADDING AND SUBTRACTING SURDS)",
    "objective": "LO: I can add and subtract surds by simplifying and collecting like terms.",
    "send_mode": False,
    "info_boxes": {
        "key_terms": {"id": "key_terms", "title": "Adding and subtracting surds", "content": [
            {"type": "paragraph", "text": "A <span class=\"ul-b\">surd</span> is a root that cannot be simplified to a whole number (e.g. &radic;2, &radic;5). We can only add/subtract <span class=\"ul-k\">like surds</span> (same number under the root)."},
            {"type": "paragraph", "text": "<span class=\"rb\">Rule:</span> a&radic;n + b&radic;n = (a + b)&radic;n. Simplify surds first to find like terms."}]},
        "what_we_learn": {"id": "what_we_learn", "title": "Quick examples", "examples": [
            {"correct": True, "expr": "3&radic;2 + 5&radic;2 = 8&radic;2", "desc": "like surds"},
            {"correct": True, "expr": "&radic;8 + &radic;2 = 2&radic;2 + &radic;2 = 3&radic;2", "desc": "simplify first"},
            {"correct": True, "expr": "7&radic;3 &minus; 2&radic;3 = 5&radic;3", "desc": "subtract like surds"},
            {"correct": False, "expr": "&radic;2 + &radic;3 = &radic;5", "desc": "cannot add unlike surds"},
            {"correct": False, "expr": "3&radic;2 + 4&radic;3 = 7&radic;5", "desc": "unlike surds stay separate"}]},
        "key_idea": {"id": "key_idea", "title": "Key idea",
            "text": "Simplify each surd, then add or subtract the coefficients of like surds.",
            "equation": "a<span class=\"ov\">&radic;n</span> + b<span class=\"ov\">&radic;n</span> = <span class=\"ovr\">(a + b)&radic;n</span>",
            "caption": "Only like surds can be combined"}},
    "modelled_examples": [
        example(1, "like surds", "Simplify 4&radic;5 + 7&radic;5.",
                ["Same surd (&radic;5)", "Add coefficients: 4 + 7 = 11", "= 11&radic;5"],
                "11&radic;5", "Add the numbers in front of the same surd."),
        example(2, "simplify then add", "Simplify &radic;12 + &radic;27.",
                ["&radic;12 = &radic;(4&times;3) = 2&radic;3", "&radic;27 = &radic;(9&times;3) = 3&radic;3", "2&radic;3 + 3&radic;3 = 5&radic;3"],
                "5&radic;3", "Simplify each surd first to reveal like terms."),
        example(3, "subtraction", "Simplify &radic;50 &minus; &radic;18.",
                ["&radic;50 = &radic;(25&times;2) = 5&radic;2", "&radic;18 = &radic;(9&times;2) = 3&radic;2", "5&radic;2 &minus; 3&radic;2 = 2&radic;2"],
                "2&radic;2", "Simplify, then subtract coefficients of like surds."),
        example(4, "mixed expression", "Simplify 2&radic;3 + &radic;48 &minus; &radic;12.",
                ["&radic;48 = 4&radic;3; &radic;12 = 2&radic;3", "2&radic;3 + 4&radic;3 &minus; 2&radic;3", "= 4&radic;3"],
                "4&radic;3", "Simplify all surds, then collect like terms.")],
    "practice": [
        practice(1, "Adding like surds", "#1F5FA6", "#EEF3FF", "#1F5FA6",
                 "Simplify each expression.",
                 [("a", "2&radic;3 + 5&radic;3", "7&radic;3"), ("b", "6&radic;7 + 3&radic;7", "9&radic;7"),
                  ("c", "&radic;5 + 4&radic;5", "5&radic;5"), ("d", "8&radic;2 + &radic;2", "9&radic;2")]),
        practice(2, "Subtracting like surds", "#1F5FA6", "#EEF3FF", "#1F5FA6",
                 "Simplify each expression.",
                 [("a", "9&radic;2 &minus; 4&radic;2", "5&radic;2"), ("b", "7&radic;3 &minus; 3&radic;3", "4&radic;3"),
                  ("c", "10&radic;5 &minus; 6&radic;5", "4&radic;5"), ("d", "5&radic;11 &minus; 5&radic;11", "0")]),
        practice(3, "Simplify then combine", "#CC0000", "#FFF0F0", "#CC0000",
                 "Simplify the surds first, then add or subtract.",
                 [("a", "&radic;8 + &radic;2", "3&radic;2"), ("b", "&radic;12 + &radic;75", "7&radic;3"),
                  ("c", "&radic;50 &minus; &radic;32", "&radic;2"), ("d", "&radic;45 + &radic;20", "5&radic;5")]),
        practice(4, "Mixed expressions", "#1E7D2E", "#EDFAEE", "#1E7D2E",
                 "Simplify fully.",
                 [("a", "3&radic;2 + &radic;8", "5&radic;2"), ("b", "2&radic;5 + &radic;45 &minus; &radic;20", "3&radic;5"),
                  ("c", "&radic;27 + &radic;48 &minus; &radic;3", "6&radic;3"), ("d", "4&radic;7 &minus; &radic;28 + &radic;63", "5&radic;7")]),
        practice(5, "Challenge simplification", "#7B3FA0", "#F5EEFF", "#7B3FA0",
                 "Simplify each expression completely.",
                 [("a", "&radic;72 + &radic;50 &minus; &radic;8", "9&radic;2"), ("b", "2&radic;12 &minus; &radic;27 + &radic;75", "6&radic;3"),
                  ("c", "&radic;98 &minus; &radic;32 + &radic;18", "6&radic;2"), ("d", "3&radic;20 + 2&radic;45 &minus; &radic;80", "8&radic;5"),
                  ("e", "&radic;200 &minus; &radic;50 + &radic;8", "7&radic;2 + 2&radic;2 = 9... Actually: 10&radic;2 &minus; 5&radic;2 + 2&radic;2 = 7&radic;2")])],
    "misconceptions": {"items": [
        {"id": "a", "statement": "3&radic;2 + 5&radic;2 = 8&radic;2", "correct": True},
        {"id": "b", "statement": "&radic;3 + &radic;5 = &radic;8", "correct": False},
        {"id": "c", "statement": "&radic;12 = 2&radic;3", "correct": True},
        {"id": "d", "statement": "&radic;8 + &radic;8 = &radic;16 = 4", "correct": False},
        {"id": "e", "statement": "You must simplify surds before adding them", "correct": True}]},
    "challenge": {"problems": [
        {"id": "a", "text": "Simplify <strong>&radic;75 + &radic;48 &minus; &radic;108 + &radic;27</strong>. Express your answer in the form a&radic;3."},
        {"id": "b", "text": "The sides of a triangle are <strong>&radic;50 cm</strong>, <strong>&radic;32 cm</strong>, and <strong>&radic;8 cm</strong>. Find the perimeter in simplified surd form."}]},
})


# ── 176 — Multiplying and dividing surds ──────────────────────────────────
write_ws("176-multiplying-and-dividing-surds.json", {
    "title": "SURDS,\n(MULTIPLYING AND DIVIDING SURDS)",
    "objective": "LO: I can multiply and divide surds, simplifying where possible.",
    "send_mode": False,
    "info_boxes": {
        "key_terms": {"id": "key_terms", "title": "Multiplying and dividing surds", "content": [
            {"type": "paragraph", "text": "To <span class=\"ul-b\">multiply</span> surds: &radic;a &times; &radic;b = &radic;(ab). To <span class=\"ul-b\">divide</span>: &radic;a &divide; &radic;b = &radic;(a/b). Always <span class=\"ul-k\">simplify</span> the result."},
            {"type": "paragraph", "text": "<span class=\"rb\">Key fact:</span> &radic;a &times; &radic;a = a. This is useful for rationalising and expanding brackets."}]},
        "what_we_learn": {"id": "what_we_learn", "title": "Quick examples", "examples": [
            {"correct": True, "expr": "&radic;3 &times; &radic;5 = &radic;15", "desc": "multiply radicands"},
            {"correct": True, "expr": "&radic;6 &times; &radic;6 = 6", "desc": "same surd squared"},
            {"correct": True, "expr": "&radic;20 &divide; &radic;5 = &radic;4 = 2", "desc": "divide radicands"},
            {"correct": False, "expr": "&radic;3 &times; &radic;5 = &radic;8", "desc": "multiply, not add: &radic;15"},
            {"correct": False, "expr": "2&radic;3 &times; 4&radic;3 = 8&radic;9", "desc": "= 8 &times; 3 = 24"}]},
        "key_idea": {"id": "key_idea", "title": "Key idea",
            "text": "Multiply: &radic;a &times; &radic;b = &radic;(ab). Divide: &radic;a &divide; &radic;b = &radic;(a/b). Simplify the result.",
            "equation": "&radic;a &times; &radic;b = <span class=\"ov\">&radic;(ab)</span> | &radic;a &divide; &radic;b = <span class=\"ovr\">&radic;(a/b)</span>",
            "caption": "Always simplify the final answer"}},
    "modelled_examples": [
        example(1, "multiplying surds", "Simplify &radic;3 &times; &radic;12.",
                ["&radic;3 &times; &radic;12 = &radic;(3 &times; 12)", "= &radic;36", "= 6"],
                "6", "Multiply the numbers under the root, then simplify."),
        example(2, "with coefficients", "Simplify 2&radic;5 &times; 3&radic;2.",
                ["Multiply coefficients: 2 &times; 3 = 6", "Multiply surds: &radic;5 &times; &radic;2 = &radic;10", "= 6&radic;10"],
                "6&radic;10", "Multiply the numbers outside together and the surds together."),
        example(3, "dividing surds", "Simplify &radic;72 &divide; &radic;2.",
                ["&radic;72 &divide; &radic;2 = &radic;(72/2)", "= &radic;36", "= 6"],
                "6", "Divide the radicands, then simplify."),
        example(4, "expanding brackets", "Expand and simplify &radic;3(2 + &radic;3).",
                ["&radic;3 &times; 2 = 2&radic;3", "&radic;3 &times; &radic;3 = 3", "= 2&radic;3 + 3"],
                "2&radic;3 + 3", "Distribute the surd across the bracket.")],
    "practice": [
        practice(1, "Multiplying simple surds", "#1F5FA6", "#EEF3FF", "#1F5FA6",
                 "Simplify each product.",
                 [("a", "&radic;2 &times; &radic;8", "4"), ("b", "&radic;5 &times; &radic;5", "5"),
                  ("c", "&radic;3 &times; &radic;7", "&radic;21"), ("d", "&radic;6 &times; &radic;24", "12")]),
        practice(2, "With coefficients", "#1F5FA6", "#EEF3FF", "#1F5FA6",
                 "Simplify each product.",
                 [("a", "3&radic;2 &times; 4&radic;2", "24"), ("b", "2&radic;3 &times; 5&radic;3", "30"),
                  ("c", "4&radic;5 &times; 2&radic;3", "8&radic;15"), ("d", "3&radic;7 &times; &radic;7", "21")]),
        practice(3, "Dividing surds", "#CC0000", "#FFF0F0", "#CC0000",
                 "Simplify each division.",
                 [("a", "&radic;50 &divide; &radic;2", "5"), ("b", "&radic;48 &divide; &radic;3", "4"),
                  ("c", "6&radic;10 &divide; 2&radic;5", "3&radic;2"), ("d", "&radic;75 &divide; &radic;3", "5")]),
        practice(4, "Expanding brackets", "#1E7D2E", "#EDFAEE", "#1E7D2E",
                 "Expand and simplify.",
                 [("a", "&radic;2(3 + &radic;2)", "3&radic;2 + 2"), ("b", "&radic;5(4 &minus; &radic;5)", "4&radic;5 &minus; 5"),
                  ("c", "2&radic;3(1 + &radic;3)", "2&radic;3 + 6"), ("d", "&radic;7(&radic;7 + 2&radic;3)", "7 + 2&radic;21")]),
        practice(5, "Mixed multiplication and division", "#7B3FA0", "#F5EEFF", "#7B3FA0",
                 "Simplify each expression.",
                 [("a", "&radic;2 &times; &radic;3 &times; &radic;6", "6"), ("b", "(2&radic;3)&sup2;", "12"),
                  ("c", "&radic;45 &divide; &radic;5", "3"), ("d", "(&radic;5 + 1)(&radic;5 &minus; 1)", "4"),
                  ("e", "(3 + &radic;2)(3 &minus; &radic;2)", "7")])],
    "misconceptions": {"items": [
        {"id": "a", "statement": "&radic;a &times; &radic;b = &radic;(ab)", "correct": True},
        {"id": "b", "statement": "&radic;3 &times; &radic;5 = &radic;8", "correct": False},
        {"id": "c", "statement": "&radic;a &times; &radic;a = a", "correct": True},
        {"id": "d", "statement": "(2&radic;3)&sup2; = 2&radic;9 = 6", "correct": False},
        {"id": "e", "statement": "&radic;a &divide; &radic;b = &radic;(a/b)", "correct": True}]},
    "challenge": {"problems": [
        {"id": "a", "text": "Expand and simplify <strong>(&radic;3 + &radic;5)(&radic;3 &minus; &radic;5)</strong>. What do you notice about the result? Use this to explain why (a + b)(a &minus; b) = a&sup2; &minus; b&sup2;."},
        {"id": "b", "text": "Show that <strong>(&radic;2 + &radic;3)&sup2; = 5 + 2&radic;6</strong>. Hence find the value of <strong>(&radic;2 + &radic;3)&sup2; + (&radic;2 &minus; &radic;3)&sup2;</strong>."}]},
})

# ── 177 — Rationalising the denominator ───────────────────────────────────
write_ws("177-rationalising-the-denominator.json", {
    "title": "SURDS,\n(RATIONALISING THE DENOMINATOR)",
    "objective": "LO: I can rationalise the denominator of a surd fraction.",
    "send_mode": False,
    "info_boxes": {
        "key_terms": {"id": "key_terms", "title": "Rationalising", "content": [
            {"type": "paragraph", "text": "<span class=\"ul-b\">Rationalising</span> means removing the surd from the <span class=\"ul-k\">denominator</span> (bottom) of a fraction by multiplying top and bottom by an appropriate expression."},
            {"type": "paragraph", "text": "<span class=\"rb\">Methods:</span> For &frac{a}{&radic;b}, multiply by &frac{&radic;b}{&radic;b}. For &frac{a}{c + &radic;d}, multiply by &frac{c &minus; &radic;d}{c &minus; &radic;d} (conjugate)."}]},
        "what_we_learn": {"id": "what_we_learn", "title": "Quick examples", "examples": [
            {"correct": True, "expr": "&frac{1}{&radic;2} = &frac{&radic;2}{2}", "desc": "multiply by &radic;2/&radic;2"},
            {"correct": True, "expr": "&frac{6}{&radic;3} = &frac{6&radic;3}{3} = 2&radic;3", "desc": "simplify after"},
            {"correct": True, "expr": "&frac{1}{2+&radic;3} uses conjugate 2&minus;&radic;3", "desc": "difference of squares"},
            {"correct": False, "expr": "&frac{1}{&radic;5} = &frac{1}{5}", "desc": "must multiply properly"},
            {"correct": False, "expr": "&frac{3}{&radic;2} = 3&radic;2", "desc": "= &frac{3&radic;2}{2}"}]},
        "key_idea": {"id": "key_idea", "title": "Key idea",
            "text": "Multiply numerator and denominator by the surd (or conjugate) to eliminate the irrational denominator.",
            "equation": "&frac{a}{&radic;b} &times; <span class=\"ov\">&frac{&radic;b}{&radic;b}</span> = <span class=\"ovr\">&frac{a&radic;b}{b}</span>",
            "caption": "The denominator becomes rational"}},
    "modelled_examples": [
        example(1, "simple rationalising", "Rationalise &frac{5}{&radic;3}.",
                ["Multiply by &frac{&radic;3}{&radic;3}", "= &frac{5&radic;3}{&radic;3 &times; &radic;3}", "= &frac{5&radic;3}{3}"],
                "&frac{5&radic;3}{3}", "Multiply top and bottom by &radic;3."),
        example(2, "simplify after", "Rationalise &frac{6}{&radic;2}.",
                ["Multiply by &frac{&radic;2}{&radic;2}: &frac{6&radic;2}{2}", "Simplify: 6/2 = 3", "= 3&radic;2"],
                "3&radic;2", "Always simplify the fraction after rationalising."),
        example(3, "conjugate method", "Rationalise &frac{1}{3 + &radic;2}.",
                ["Multiply by &frac{3 &minus; &radic;2}{3 &minus; &radic;2}", "Numerator: 3 &minus; &radic;2", "Denominator: 9 &minus; 2 = 7"],
                "&frac{3 &minus; &radic;2}{7}", "Use the conjugate: (a + b)(a &minus; b) = a&sup2; &minus; b&sup2;."),
        example(4, "harder conjugate", "Rationalise &frac{4}{&radic;5 &minus; 1}.",
                ["Multiply by &frac{&radic;5 + 1}{&radic;5 + 1}", "Num: 4(&radic;5 + 1) = 4&radic;5 + 4", "Den: 5 &minus; 1 = 4"],
                "&radic;5 + 1", "Simplify the fraction: &frac{4&radic;5 + 4}{4} = &radic;5 + 1.")],
    "practice": [
        practice(1, "Simple rationalising", "#1F5FA6", "#EEF3FF", "#1F5FA6",
                 "Rationalise the denominator.",
                 [("a", "&frac{1}{&radic;5}", "&frac{&radic;5}{5}"), ("b", "&frac{3}{&radic;7}", "&frac{3&radic;7}{7}"),
                  ("c", "&frac{4}{&radic;2}", "2&radic;2"), ("d", "&frac{10}{&radic;5}", "2&radic;5")]),
        practice(2, "Simplify after rationalising", "#1F5FA6", "#EEF3FF", "#1F5FA6",
                 "Rationalise and fully simplify.",
                 [("a", "&frac{6}{&radic;3}", "2&radic;3"), ("b", "&frac{8}{&radic;2}", "4&radic;2"),
                  ("c", "&frac{12}{&radic;6}", "2&radic;6"), ("d", "&frac{15}{&radic;5}", "3&radic;5")]),
        practice(3, "Conjugate method (addition)", "#CC0000", "#FFF0F0", "#CC0000",
                 "Rationalise using the conjugate.",
                 [("a", "&frac{1}{1 + &radic;2}", "&radic;2 &minus; 1"), ("b", "&frac{1}{3 + &radic;5}", "&frac{3 &minus; &radic;5}{4}"),
                  ("c", "&frac{2}{4 + &radic;3}", "&frac{8 &minus; 2&radic;3}{13}"), ("d", "&frac{5}{2 + &radic;7}", "&frac{10 &minus; 5&radic;7}{&minus;3}")]),
        practice(4, "Conjugate method (subtraction)", "#1E7D2E", "#EDFAEE", "#1E7D2E",
                 "Rationalise the denominator.",
                 [("a", "&frac{1}{&radic;3 &minus; 1}", "&frac{&radic;3 + 1}{2}"), ("b", "&frac{3}{&radic;5 &minus; 2}", "3(&radic;5 + 2)"),
                  ("c", "&frac{4}{&radic;7 &minus; &radic;3}", "&radic;7 + &radic;3"), ("d", "&frac{6}{5 &minus; &radic;2}", "&frac{6(5 + &radic;2)}{23}")]),
        practice(5, "Mixed rationalising", "#7B3FA0", "#F5EEFF", "#7B3FA0",
                 "Rationalise and simplify fully.",
                 [("a", "&frac{2}{&radic;8}", "&frac{&radic;2}{2}"), ("b", "&frac{&radic;3}{&radic;12}", "&frac{1}{2}"),
                  ("c", "&frac{1}{1 + &radic;3}", "&frac{&radic;3 &minus; 1}{2}"), ("d", "&frac{&radic;5 + 1}{&radic;5 &minus; 1}", "&frac{3 + &radic;5}{2}"),
                  ("e", "&frac{6}{3&radic;2}", "&radic;2")])],
    "misconceptions": {"items": [
        {"id": "a", "statement": "To rationalise &frac{a}{&radic;b}, multiply top and bottom by &radic;b", "correct": True},
        {"id": "b", "statement": "&frac{1}{&radic;2} = &frac{1}{2}", "correct": False},
        {"id": "c", "statement": "The conjugate of (a + &radic;b) is (a &minus; &radic;b)", "correct": True},
        {"id": "d", "statement": "&frac{4}{&radic;2} = 4&radic;2", "correct": False},
        {"id": "e", "statement": "(a + &radic;b)(a &minus; &radic;b) = a&sup2; &minus; b", "correct": True}]},
    "challenge": {"problems": [
        {"id": "a", "text": "Show that <strong>&frac{1}{&radic;2 + 1} + &frac{1}{&radic;2 &minus; 1} = 2&radic;2</strong> by rationalising each fraction."},
        {"id": "b", "text": "Simplify <strong>&frac{&radic;3 + 1}{&radic;3 &minus; 1} &minus; &frac{&radic;3 &minus; 1}{&radic;3 + 1}</strong>. Give your answer in the form a&radic;b."}]},
})


# ── 178 — Simplifying surds ───────────────────────────────────────────────
write_ws("178-simplifying-surds.json", {
    "title": "SURDS,\n(SIMPLIFYING SURDS)",
    "objective": "LO: I can simplify surds by finding the largest square factor.",
    "send_mode": False,
    "info_boxes": {
        "key_terms": {"id": "key_terms", "title": "Simplifying surds", "content": [
            {"type": "paragraph", "text": "To <span class=\"ul-b\">simplify a surd</span>, find the largest <span class=\"ul-k\">perfect square factor</span> of the number under the root. Use &radic;(ab) = &radic;a &times; &radic;b."},
            {"type": "paragraph", "text": "<span class=\"rb\">Method:</span> Find the largest square number that divides into the radicand: 4, 9, 16, 25, 36, 49, 64, 81, 100..."}]},
        "what_we_learn": {"id": "what_we_learn", "title": "Quick examples", "examples": [
            {"correct": True, "expr": "&radic;12 = &radic;(4&times;3) = 2&radic;3", "desc": "largest square factor 4"},
            {"correct": True, "expr": "&radic;50 = &radic;(25&times;2) = 5&radic;2", "desc": "largest square factor 25"},
            {"correct": True, "expr": "&radic;72 = &radic;(36&times;2) = 6&radic;2", "desc": "largest square factor 36"},
            {"correct": False, "expr": "&radic;12 = &radic;6 &times; &radic;2", "desc": "not simplified: use &radic;4"},
            {"correct": False, "expr": "&radic;50 = &radic;10 &times; &radic;5", "desc": "need a square factor"}]},
        "key_idea": {"id": "key_idea", "title": "Key idea",
            "text": "Find the LARGEST perfect square that divides the number, then take its root outside.",
            "equation": "&radic;n = &radic;(a&sup2; &times; b) = <span class=\"ov\">a</span><span class=\"ovr\">&radic;b</span>",
            "caption": "a&sup2; is the largest square factor of n"}},
    "modelled_examples": [
        example(1, "basic simplification", "Simplify &radic;18.",
                ["Largest square factor of 18: 9", "&radic;18 = &radic;(9 &times; 2)", "= 3&radic;2"],
                "3&radic;2", "9 is the largest perfect square that divides 18."),
        example(2, "larger number", "Simplify &radic;200.",
                ["Largest square factor: 100", "&radic;200 = &radic;(100 &times; 2)", "= 10&radic;2"],
                "10&radic;2", "100 divides into 200, and &radic;100 = 10."),
        example(3, "with coefficient", "Simplify 3&radic;32.",
                ["&radic;32 = &radic;(16 &times; 2) = 4&radic;2", "3 &times; 4&radic;2", "= 12&radic;2"],
                "12&radic;2", "Simplify the surd first, then multiply by the coefficient."),
        example(4, "checking if simplified", "Is 5&radic;6 fully simplified?",
                ["Check factors of 6: 1, 2, 3, 6", "No perfect square factors (other than 1)", "Yes, 5&radic;6 is fully simplified"],
                "Yes, fully simplified", "A surd is simplified when no perfect square divides the radicand.")],
    "practice": [
        practice(1, "Basic simplification", "#1F5FA6", "#EEF3FF", "#1F5FA6",
                 "Simplify each surd.",
                 [("a", "&radic;8", "2&radic;2"), ("b", "&radic;20", "2&radic;5"),
                  ("c", "&radic;45", "3&radic;5"), ("d", "&radic;28", "2&radic;7")]),
        practice(2, "Larger numbers", "#1F5FA6", "#EEF3FF", "#1F5FA6",
                 "Simplify each surd.",
                 [("a", "&radic;48", "4&radic;3"), ("b", "&radic;75", "5&radic;3"),
                  ("c", "&radic;98", "7&radic;2"), ("d", "&radic;125", "5&radic;5")]),
        practice(3, "With coefficients", "#CC0000", "#FFF0F0", "#CC0000",
                 "Simplify fully.",
                 [("a", "2&radic;12", "4&radic;3"), ("b", "5&radic;8", "10&radic;2"),
                  ("c", "3&radic;50", "15&radic;2"), ("d", "4&radic;27", "12&radic;3")]),
        practice(4, "Already simplified?", "#1E7D2E", "#EDFAEE", "#1E7D2E",
                 "State whether each surd is fully simplified. If not, simplify it.",
                 [("a", "&radic;15", "Yes"), ("b", "&radic;24", "No: 2&radic;6"),
                  ("c", "3&radic;7", "Yes"), ("d", "2&radic;18", "No: 6&radic;2")]),
        practice(5, "Mixed simplification", "#7B3FA0", "#F5EEFF", "#7B3FA0",
                 "Simplify each expression fully.",
                 [("a", "&radic;108", "6&radic;3"), ("b", "&radic;180", "6&radic;5"),
                  ("c", "2&radic;80", "8&radic;5"), ("d", "&radic;242", "11&radic;2"),
                  ("e", "3&radic;300", "30&radic;3")])],
    "misconceptions": {"items": [
        {"id": "a", "statement": "&radic;12 = 2&radic;3 because 4 is the largest square factor", "correct": True},
        {"id": "b", "statement": "&radic;12 = &radic;4 + &radic;8", "correct": False},
        {"id": "c", "statement": "A surd is simplified when no square number divides the radicand", "correct": True},
        {"id": "d", "statement": "&radic;50 = 25&radic;2", "correct": False},
        {"id": "e", "statement": "&radic;(a&sup2; &times; b) = a&radic;b", "correct": True}]},
    "challenge": {"problems": [
        {"id": "a", "text": "Find the value of n such that <strong>&radic;n = 12&radic;3</strong>. Verify your answer by squaring both sides."},
        {"id": "b", "text": "Simplify <strong>&radic;(2&sup4; &times; 3&sup3; &times; 5&sup2;)</strong>. Express your answer in the form a&radic;b where b has no perfect square factors."}]},
})

# ── 179 — Enlargement ─────────────────────────────────────────────────────
write_ws("179-enlargement.json", {
    "title": "TRANSFORMATIONS,\n(ENLARGEMENT)",
    "objective": "LO: I can enlarge a shape by a given scale factor from a centre of enlargement.",
    "send_mode": False,
    "info_boxes": {
        "key_terms": {"id": "key_terms", "title": "Enlargement", "content": [
            {"type": "paragraph", "text": "An <span class=\"ul-b\">enlargement</span> changes the size of a shape using a <span class=\"ul-k\">scale factor</span> and a <span class=\"ul-k\">centre of enlargement</span>. Multiply each distance from the centre by the scale factor."},
            {"type": "paragraph", "text": "<span class=\"rb\">Note:</span> SF > 1 makes bigger. 0 < SF < 1 makes smaller. Negative SF gives enlargement on the other side."}]},
        "what_we_learn": {"id": "what_we_learn", "title": "Quick examples", "examples": [
            {"correct": True, "expr": "SF 2 from centre: all distances doubled", "desc": "basic enlargement"},
            {"correct": True, "expr": "SF &frac{1}{2}: shape becomes half the size", "desc": "fractional SF"},
            {"correct": True, "expr": "SF &minus;1: same size, rotated 180&deg;", "desc": "negative SF"},
            {"correct": False, "expr": "Enlargement only makes shapes bigger", "desc": "fractional SF makes smaller"},
            {"correct": False, "expr": "SF 3 means add 3 to coordinates", "desc": "multiply distances, not add"}]},
        "key_idea": {"id": "key_idea", "title": "Key idea",
            "text": "New distance from centre = original distance &times; scale factor. Count from centre to each vertex.",
            "equation": "New position = Centre + SF &times; <span class=\"ov\">(Point &minus; Centre)</span>",
            "caption": "Multiply the vector from centre to point by SF"}},
    "modelled_examples": [
        example(1, "SF 2 from origin", "Enlarge triangle with vertices (1,1), (3,1), (1,3) by SF 2, centre (0,0).",
                ["Multiply each coordinate by 2", "(1,1)&rarr;(2,2), (3,1)&rarr;(6,2), (1,3)&rarr;(2,6)", "New triangle: (2,2), (6,2), (2,6)"],
                "(2,2), (6,2), (2,6)", "When centre is origin, just multiply all coordinates by SF."),
        example(2, "SF 3 from a point", "Enlarge point (2,1) by SF 3, centre (1,0).",
                ["Vector from centre to point: (2&minus;1, 1&minus;0) = (1, 1)", "Multiply by 3: (3, 3)", "New position: (1+3, 0+3) = (4, 3)"],
                "(4, 3)", "Find vector from centre, multiply by SF, add back to centre."),
        example(3, "fractional SF", "Enlarge point (6,4) by SF &frac{1}{2}, centre (0,0).",
                ["Multiply coordinates by &frac{1}{2}", "(6 &times; &frac{1}{2}, 4 &times; &frac{1}{2})", "= (3, 2)"],
                "(3, 2)", "A scale factor less than 1 reduces the shape."),
        example(4, "finding the SF", "A shape has vertex at (2,3). After enlargement from (0,0) it moves to (6,9). Find SF.",
                ["SF = new distance / original distance", "6/2 = 3 or 9/3 = 3", "Scale factor = 3"],
                "SF = 3", "Divide the new coordinate by the original.")],
    "practice": [
        practice(1, "SF from origin", "#1F5FA6", "#EEF3FF", "#1F5FA6",
                 "Enlarge each point by the given SF from (0,0).",
                 [("a", "(2, 3) SF 2", "(4, 6)"), ("b", "(1, 4) SF 3", "(3, 12)"),
                  ("c", "(4, 6) SF &frac{1}{2}", "(2, 3)"), ("d", "(5, 2) SF 4", "(20, 8)")]),
        practice(2, "SF from a centre", "#1F5FA6", "#EEF3FF", "#1F5FA6",
                 "Enlarge each point by SF 2 from the given centre.",
                 [("a", "Point (3,2), centre (1,1)", "(5, 3)"), ("b", "Point (4,3), centre (2,1)", "(6, 5)"),
                  ("c", "Point (5,4), centre (1,2)", "(9, 6)"), ("d", "Point (2,5), centre (0,1)", "(4, 9)")]),
        practice(3, "Fractional scale factors", "#CC0000", "#FFF0F0", "#CC0000",
                 "Enlarge each point from (0,0).",
                 [("a", "(8, 6) SF &frac{1}{2}", "(4, 3)"), ("b", "(9, 12) SF &frac{1}{3}", "(3, 4)"),
                  ("c", "(10, 4) SF &frac{1}{2}", "(5, 2)"), ("d", "(6, 15) SF &frac{2}{3}", "(4, 10)")]),
        practice(4, "Finding scale factors", "#1E7D2E", "#EDFAEE", "#1E7D2E",
                 "Find the scale factor of each enlargement from (0,0).",
                 [("a", "(2,1) &rarr; (6,3)", "SF = 3"), ("b", "(4,3) &rarr; (8,6)", "SF = 2"),
                  ("c", "(6,9) &rarr; (2,3)", "SF = &frac{1}{3}"), ("d", "(5,10) &rarr; (10,20)", "SF = 2")]),
        practice(5, "Mixed enlargement", "#7B3FA0", "#F5EEFF", "#7B3FA0",
                 "Solve each problem.",
                 [("a", "Enlarge (1,2) SF 3, centre (0,0)", "(3, 6)"),
                  ("b", "Enlarge (4,1) SF 2, centre (2,1)", "(6, 1)"),
                  ("c", "Shape area = 5 cm&sup2;, SF = 3. New area?", "45 cm&sup2;"),
                  ("d", "Side 4 cm becomes 12 cm. Scale factor?", "3"),
                  ("e", "Enlarge (3,5) SF &minus;1, centre (1,2)", "(&minus;1, &minus;1)")])],
    "misconceptions": {"items": [
        {"id": "a", "statement": "In an enlargement, multiply distances from the centre by the SF", "correct": True},
        {"id": "b", "statement": "A scale factor of &frac{1}{2} makes the shape bigger", "correct": False},
        {"id": "c", "statement": "Area scale factor = (length SF)&sup2;", "correct": True},
        {"id": "d", "statement": "Enlargement always increases the size of a shape", "correct": False},
        {"id": "e", "statement": "A negative scale factor places the image on the other side of the centre", "correct": True}]},
    "challenge": {"problems": [
        {"id": "a", "text": "A triangle has vertices at <strong>(1,1), (4,1), (1,3)</strong>. It is enlarged by SF 2 from centre <strong>(1,1)</strong>. Find the vertices of the enlarged triangle."},
        {"id": "b", "text": "A shape is enlarged by SF &minus;2 from centre <strong>(3,2)</strong>. The image of point P is at <strong>(&minus;1, 8)</strong>. Find the original position of P."}]},
})


# ── 180 — Reflection ──────────────────────────────────────────────────────
write_ws("180-reflection.json", {
    "title": "TRANSFORMATIONS,\n(REFLECTION)",
    "objective": "LO: I can reflect shapes in given mirror lines and describe reflections.",
    "send_mode": False,
    "info_boxes": {
        "key_terms": {"id": "key_terms", "title": "Reflection", "content": [
            {"type": "paragraph", "text": "A <span class=\"ul-b\">reflection</span> flips a shape over a <span class=\"ul-k\">mirror line</span>. Each point and its image are the same perpendicular distance from the mirror line."},
            {"type": "paragraph", "text": "<span class=\"rb\">Common mirror lines:</span> x-axis (y = 0), y-axis (x = 0), y = x, y = &minus;x, or lines like x = 2."}]},
        "what_we_learn": {"id": "what_we_learn", "title": "Quick examples", "examples": [
            {"correct": True, "expr": "(3, 2) reflected in y-axis &rarr; (&minus;3, 2)", "desc": "x changes sign"},
            {"correct": True, "expr": "(3, 2) reflected in x-axis &rarr; (3, &minus;2)", "desc": "y changes sign"},
            {"correct": True, "expr": "(3, 2) reflected in y = x &rarr; (2, 3)", "desc": "swap x and y"},
            {"correct": False, "expr": "Reflection in y-axis changes the y-coordinate", "desc": "it changes x"},
            {"correct": False, "expr": "Reflected shapes change size", "desc": "size stays the same"}]},
        "key_idea": {"id": "key_idea", "title": "Key idea",
            "text": "Every point is the same distance from the mirror line as its image, measured perpendicularly.",
            "equation": "y-axis: (x, y) &rarr; (<span class=\"ov\">&minus;x</span>, y) | x-axis: (x, y) &rarr; (x, <span class=\"ovr\">&minus;y</span>)",
            "caption": "The mirror line is the perpendicular bisector of each point and its image"}},
    "modelled_examples": [
        example(1, "in y-axis", "Reflect (4, 3) in the y-axis.",
                ["The y-axis is x = 0", "x-coordinate changes sign: 4 &rarr; &minus;4", "y stays the same: (−4, 3)"],
                "(&minus;4, 3)", "Reflecting in the y-axis negates the x-coordinate."),
        example(2, "in x-axis", "Reflect (&minus;2, 5) in the x-axis.",
                ["The x-axis is y = 0", "y-coordinate changes sign: 5 &rarr; &minus;5", "x stays: (&minus;2, &minus;5)"],
                "(&minus;2, &minus;5)", "Reflecting in the x-axis negates the y-coordinate."),
        example(3, "in y = x", "Reflect (1, 4) in the line y = x.",
                ["For y = x, swap the coordinates", "x becomes y and y becomes x", "(1, 4) &rarr; (4, 1)"],
                "(4, 1)", "Reflecting in y = x swaps the x and y coordinates."),
        example(4, "in vertical line", "Reflect (5, 3) in the line x = 2.",
                ["Distance from x = 2: 5 &minus; 2 = 3 units right", "Image is 3 units left of x = 2: 2 &minus; 3 = &minus;1", "(&minus;1, 3)"],
                "(&minus;1, 3)", "Count the perpendicular distance and go the same distance the other side.")],
    "practice": [
        practice(1, "Reflection in y-axis", "#1F5FA6", "#EEF3FF", "#1F5FA6",
                 "Reflect each point in the y-axis.",
                 [("a", "(3, 5)", "(&minus;3, 5)"), ("b", "(&minus;2, 4)", "(2, 4)"),
                  ("c", "(7, &minus;1)", "(&minus;7, &minus;1)"), ("d", "(&minus;6, 0)", "(6, 0)")]),
        practice(2, "Reflection in x-axis", "#1F5FA6", "#EEF3FF", "#1F5FA6",
                 "Reflect each point in the x-axis.",
                 [("a", "(4, 2)", "(4, &minus;2)"), ("b", "(1, &minus;3)", "(1, 3)"),
                  ("c", "(&minus;5, 7)", "(&minus;5, &minus;7)"), ("d", "(0, &minus;4)", "(0, 4)")]),
        practice(3, "Reflection in y = x", "#CC0000", "#FFF0F0", "#CC0000",
                 "Reflect each point in the line y = x.",
                 [("a", "(2, 5)", "(5, 2)"), ("b", "(1, 7)", "(7, 1)"),
                  ("c", "(&minus;3, 4)", "(4, &minus;3)"), ("d", "(6, &minus;2)", "(&minus;2, 6)")]),
        practice(4, "Reflection in other lines", "#1E7D2E", "#EDFAEE", "#1E7D2E",
                 "Reflect each point in the given line.",
                 [("a", "(5, 3) in x = 3", "(1, 3)"), ("b", "(1, 4) in y = 2", "(1, 0)"),
                  ("c", "(7, 1) in x = 4", "(1, 1)"), ("d", "(3, 6) in y = 4", "(3, 2)")]),
        practice(5, "Describing reflections", "#7B3FA0", "#F5EEFF", "#7B3FA0",
                 "Describe the single reflection that maps the first point to the second.",
                 [("a", "(3, 2) &rarr; (&minus;3, 2)", "Reflection in y-axis"),
                  ("b", "(4, 5) &rarr; (4, &minus;5)", "Reflection in x-axis"),
                  ("c", "(1, 6) &rarr; (6, 1)", "Reflection in y = x"),
                  ("d", "(7, 3) &rarr; (1, 3)", "Reflection in x = 4"),
                  ("e", "(2, 7) &rarr; (2, 3)", "Reflection in y = 5")])],
    "misconceptions": {"items": [
        {"id": "a", "statement": "Reflecting in the y-axis changes the sign of the x-coordinate", "correct": True},
        {"id": "b", "statement": "Reflection changes the size of the shape", "correct": False},
        {"id": "c", "statement": "Reflecting in y = x swaps the x and y coordinates", "correct": True},
        {"id": "d", "statement": "Reflecting in the x-axis changes the x-coordinate", "correct": False},
        {"id": "e", "statement": "The mirror line is equidistant from a point and its image", "correct": True}]},
    "challenge": {"problems": [
        {"id": "a", "text": "A triangle has vertices <strong>A(1, 2), B(4, 2), C(4, 5)</strong>. It is reflected in the line <strong>y = x</strong>. Find the coordinates of the image and describe the relationship between the triangle and its image."},
        {"id": "b", "text": "Point P(a, b) is reflected in the line <strong>y = &minus;x</strong>. The image is P'(&minus;b, &minus;a). Verify this rule for the point <strong>(3, 5)</strong> and prove it works for any point."}]},
})

# ── 181 — Rotation ────────────────────────────────────────────────────────
write_ws("181-rotation.json", {
    "title": "TRANSFORMATIONS,\n(ROTATION)",
    "objective": "LO: I can rotate shapes about a given centre and describe rotations.",
    "send_mode": False,
    "info_boxes": {
        "key_terms": {"id": "key_terms", "title": "Rotation", "content": [
            {"type": "paragraph", "text": "A <span class=\"ul-b\">rotation</span> turns a shape about a fixed point called the <span class=\"ul-k\">centre of rotation</span>. You need to know the centre, the <span class=\"ul-k\">angle</span> and the <span class=\"ul-k\">direction</span> (clockwise or anticlockwise)."},
            {"type": "paragraph", "text": "<span class=\"rb\">Key rotations:</span> 90&deg; CW: (x,y)&rarr;(y,&minus;x). 90&deg; ACW: (x,y)&rarr;(&minus;y,x). 180&deg;: (x,y)&rarr;(&minus;x,&minus;y). All about the origin."}]},
        "what_we_learn": {"id": "what_we_learn", "title": "Quick examples", "examples": [
            {"correct": True, "expr": "90&deg; CW about (0,0): (3,1) &rarr; (1,&minus;3)", "desc": "(x,y)&rarr;(y,&minus;x)"},
            {"correct": True, "expr": "180&deg; about (0,0): (3,1) &rarr; (&minus;3,&minus;1)", "desc": "negate both"},
            {"correct": True, "expr": "90&deg; ACW about (0,0): (3,1) &rarr; (&minus;1,3)", "desc": "(x,y)&rarr;(&minus;y,x)"},
            {"correct": False, "expr": "90&deg; CW: (3,1) &rarr; (&minus;3,&minus;1)", "desc": "that is 180&deg;"},
            {"correct": False, "expr": "Rotation changes the size of the shape", "desc": "size stays the same"}]},
        "key_idea": {"id": "key_idea", "title": "Key idea",
            "text": "To describe a rotation: state the centre, angle, and direction. Size and shape are preserved.",
            "equation": "90&deg; CW: (x,y) &rarr; <span class=\"ov\">(y, &minus;x)</span> about origin",
            "caption": "Every point stays the same distance from the centre"}},
    "modelled_examples": [
        example(1, "90 CW about origin", "Rotate (2, 5) by 90&deg; clockwise about (0,0).",
                ["Rule: (x, y) &rarr; (y, &minus;x)", "(2, 5) &rarr; (5, &minus;2)", "Image is (5, &minus;2)"],
                "(5, &minus;2)", "Apply the 90&deg; CW rule: swap and negate the new y."),
        example(2, "180 about origin", "Rotate (&minus;3, 4) by 180&deg; about (0,0).",
                ["Rule: (x, y) &rarr; (&minus;x, &minus;y)", "(&minus;3, 4) &rarr; (3, &minus;4)", "Image is (3, &minus;4)"],
                "(3, &minus;4)", "180&deg; rotation negates both coordinates."),
        example(3, "90 ACW about origin", "Rotate (4, &minus;1) by 90&deg; anticlockwise about (0,0).",
                ["Rule: (x, y) &rarr; (&minus;y, x)", "(4, &minus;1) &rarr; (1, 4)", "Image is (1, 4)"],
                "(1, 4)", "90&deg; ACW: negate y then swap."),
        example(4, "about another centre", "Rotate (5, 3) by 180&deg; about (2, 1).",
                ["Translate to origin: (5&minus;2, 3&minus;1) = (3, 2)", "Apply 180&deg;: (&minus;3, &minus;2)", "Translate back: (&minus;3+2, &minus;2+1) = (&minus;1, &minus;1)"],
                "(&minus;1, &minus;1)", "Subtract centre, rotate, then add centre back.")],
    "practice": [
        practice(1, "90&deg; CW about origin", "#1F5FA6", "#EEF3FF", "#1F5FA6",
                 "Rotate each point 90&deg; clockwise about (0,0).",
                 [("a", "(1, 3)", "(3, &minus;1)"), ("b", "(4, 2)", "(2, &minus;4)"),
                  ("c", "(&minus;2, 5)", "(5, 2)"), ("d", "(0, &minus;3)", "(&minus;3, 0)")]),
        practice(2, "180&deg; about origin", "#1F5FA6", "#EEF3FF", "#1F5FA6",
                 "Rotate each point 180&deg; about (0,0).",
                 [("a", "(3, 1)", "(&minus;3, &minus;1)"), ("b", "(&minus;2, 4)", "(2, &minus;4)"),
                  ("c", "(5, &minus;3)", "(&minus;5, 3)"), ("d", "(&minus;1, &minus;6)", "(1, 6)")]),
        practice(3, "90&deg; ACW about origin", "#CC0000", "#FFF0F0", "#CC0000",
                 "Rotate each point 90&deg; anticlockwise about (0,0).",
                 [("a", "(2, 4)", "(&minus;4, 2)"), ("b", "(5, 1)", "(&minus;1, 5)"),
                  ("c", "(&minus;3, 2)", "(&minus;2, &minus;3)"), ("d", "(6, &minus;2)", "(2, 6)")]),
        practice(4, "About other centres", "#1E7D2E", "#EDFAEE", "#1E7D2E",
                 "Rotate 180&deg; about the given centre.",
                 [("a", "(4, 3) about (2, 2)", "(0, 1)"), ("b", "(5, 1) about (3, 3)", "(1, 5)"),
                  ("c", "(1, 6) about (3, 4)", "(5, 2)"), ("d", "(7, 2) about (4, 3)", "(1, 4)")]),
        practice(5, "Describing rotations", "#7B3FA0", "#F5EEFF", "#7B3FA0",
                 "Describe the single rotation that maps A to B (about origin).",
                 [("a", "(2, 3) &rarr; (3, &minus;2)", "90&deg; clockwise"),
                  ("b", "(4, 1) &rarr; (&minus;4, &minus;1)", "180&deg;"),
                  ("c", "(1, 5) &rarr; (&minus;5, 1)", "90&deg; anticlockwise"),
                  ("d", "(&minus;3, 2) &rarr; (2, 3)", "90&deg; clockwise"),
                  ("e", "(6, &minus;2) &rarr; (&minus;6, 2)", "180&deg;")])],
    "misconceptions": {"items": [
        {"id": "a", "statement": "A rotation preserves the size and shape of a figure", "correct": True},
        {"id": "b", "statement": "90&deg; CW about origin: (x,y) &rarr; (&minus;x, &minus;y)", "correct": False},
        {"id": "c", "statement": "180&deg; rotation about origin: (x,y) &rarr; (&minus;x, &minus;y)", "correct": True},
        {"id": "d", "statement": "You don't need to state direction for a 180&deg; rotation", "correct": True},
        {"id": "e", "statement": "90&deg; CW is the same as 270&deg; ACW", "correct": True}]},
    "challenge": {"problems": [
        {"id": "a", "text": "Triangle PQR has vertices <strong>P(1,1), Q(4,1), R(4,3)</strong>. Rotate it 90&deg; anticlockwise about <strong>(1,1)</strong>. Find the new vertices."},
        {"id": "b", "text": "A point (a, b) is rotated 90&deg; clockwise about <strong>(2, 3)</strong>. Its image is <strong>(5, 1)</strong>. Find the original point (a, b)."}]},
})


# ── 182 — Translation ─────────────────────────────────────────────────────
write_ws("182-translation.json", {
    "title": "TRANSFORMATIONS,\n(TRANSLATION)",
    "objective": "LO: I can translate shapes using column vectors and describe translations.",
    "send_mode": False,
    "info_boxes": {
        "key_terms": {"id": "key_terms", "title": "Translation", "content": [
            {"type": "paragraph", "text": "A <span class=\"ul-b\">translation</span> slides every point of a shape the same distance in the same direction. It is described by a <span class=\"ul-k\">column vector</span>."},
            {"type": "paragraph", "text": "<span class=\"rb\">Column vector:</span> The top number is horizontal movement (+ right, &minus; left). The bottom is vertical (+ up, &minus; down)."}]},
        "what_we_learn": {"id": "what_we_learn", "title": "Quick examples", "examples": [
            {"correct": True, "expr": "Vector (3, &minus;2): right 3, down 2", "desc": "positive x, negative y"},
            {"correct": True, "expr": "(2,5) translated by (3,1) = (5,6)", "desc": "add vector"},
            {"correct": True, "expr": "Translation preserves size, shape and orientation", "desc": "no rotation"},
            {"correct": False, "expr": "Vector (3, &minus;2) means left 3, up 2", "desc": "positive = right/up"},
            {"correct": False, "expr": "Translation changes the size of the shape", "desc": "only position changes"}]},
        "key_idea": {"id": "key_idea", "title": "Key idea",
            "text": "Add the column vector to each point: new point = original + vector.",
            "equation": "(x, y) + <span class=\"ov\">(a, b)</span> = <span class=\"ovr\">(x+a, y+b)</span>",
            "caption": "a = horizontal shift, b = vertical shift"}},
    "modelled_examples": [
        example(1, "applying a vector", "Translate (3, 2) by the vector (4, &minus;1).",
                ["Add horizontal: 3 + 4 = 7", "Add vertical: 2 + (&minus;1) = 1", "Image: (7, 1)"],
                "(7, 1)", "Add each component of the vector to the corresponding coordinate."),
        example(2, "negative vector", "Translate (5, 3) by the vector (&minus;2, &minus;4).",
                ["Add horizontal: 5 + (&minus;2) = 3", "Add vertical: 3 + (&minus;4) = &minus;1", "Image: (3, &minus;1)"],
                "(3, &minus;1)", "Negative components move left or down."),
        example(3, "describing a translation", "(1, 4) is mapped to (5, 2). Describe the translation.",
                ["Horizontal: 5 &minus; 1 = 4 (right)", "Vertical: 2 &minus; 4 = &minus;2 (down)", "Vector: (4, &minus;2)"],
                "Translation by vector (4, &minus;2)", "Subtract original from image to find the vector."),
        example(4, "translating a shape", "Triangle (1,1), (3,1), (2,4) translated by (&minus;3, 2).",
                ["(1,1) &rarr; (&minus;2, 3)", "(3,1) &rarr; (0, 3)", "(2,4) &rarr; (&minus;1, 6)"],
                "(&minus;2,3), (0,3), (&minus;1,6)", "Apply the same vector to every vertex.")],
    "practice": [
        practice(1, "Applying vectors", "#1F5FA6", "#EEF3FF", "#1F5FA6",
                 "Translate each point by the given vector.",
                 [("a", "(2, 3) by (4, 1)", "(6, 4)"), ("b", "(5, 1) by (&minus;3, 2)", "(2, 3)"),
                  ("c", "(&minus;1, 4) by (3, &minus;5)", "(2, &minus;1)"), ("d", "(0, 0) by (&minus;2, &minus;3)", "(&minus;2, &minus;3)")]),
        practice(2, "Finding the vector", "#1F5FA6", "#EEF3FF", "#1F5FA6",
                 "Find the translation vector from the first point to the second.",
                 [("a", "(1, 2) to (4, 5)", "(3, 3)"), ("b", "(5, 3) to (2, 7)", "(&minus;3, 4)"),
                  ("c", "(3, &minus;1) to (&minus;2, 4)", "(&minus;5, 5)"), ("d", "(&minus;4, 6) to (1, 1)", "(5, &minus;5)")]),
        practice(3, "Translating shapes", "#CC0000", "#FFF0F0", "#CC0000",
                 "Translate each set of vertices by vector (2, &minus;3).",
                 [("a", "(1,4), (3,4), (2,6)", "(3,1), (5,1), (4,3)"), ("b", "(0,5), (4,5), (4,7), (0,7)", "(2,2), (6,2), (6,4), (2,4)"),
                  ("c", "(2,1), (5,1), (5,3)", "(4,&minus;2), (7,&minus;2), (7,0)"), ("d", "(&minus;1,3), (2,3), (2,5), (&minus;1,5)", "(1,0), (4,0), (4,2), (1,2)")]),
        practice(4, "Reverse translations", "#1E7D2E", "#EDFAEE", "#1E7D2E",
                 "Find the original point before the translation.",
                 [("a", "Image (7, 2), vector (3, &minus;1). Original?", "(4, 3)"), ("b", "Image (1, 5), vector (&minus;4, 2). Original?", "(5, 3)"),
                  ("c", "Image (&minus;2, 0), vector (&minus;5, &minus;3). Original?", "(3, 3)"), ("d", "Image (6, &minus;1), vector (2, &minus;4). Original?", "(4, 3)")]),
        practice(5, "Mixed translation problems", "#7B3FA0", "#F5EEFF", "#7B3FA0",
                 "Solve each problem.",
                 [("a", "(3, 7) translated by (&minus;5, 3)", "(&minus;2, 10)"),
                  ("b", "Vector to map (2, &minus;1) to (6, 4)?", "(4, 5)"),
                  ("c", "After vector (a, 3), (1, 2) maps to (4, 5). Find a.", "3"),
                  ("d", "Two translations: (2, 1) then (3, &minus;4). Combined vector?", "(5, &minus;3)"),
                  ("e", "Reverse of vector (3, &minus;2)?", "(&minus;3, 2)")])],
    "misconceptions": {"items": [
        {"id": "a", "statement": "A translation is described by a column vector", "correct": True},
        {"id": "b", "statement": "A positive x-component means move left", "correct": False},
        {"id": "c", "statement": "Translation preserves size, shape and orientation", "correct": True},
        {"id": "d", "statement": "Translating by (0, 0) moves the shape to the origin", "correct": False},
        {"id": "e", "statement": "To find the vector, subtract original from image", "correct": True}]},
    "challenge": {"problems": [
        {"id": "a", "text": "A shape is translated by vector <strong>(3, &minus;2)</strong> and then by vector <strong>(&minus;5, 4)</strong>. Find the single vector that has the same effect as both translations combined."},
        {"id": "b", "text": "Point A(2, 1) is translated to A'(5, 4). Point B is translated by the same vector to B'(1, 7). Find the coordinates of B and the length of AB."}]},
})


# -- 183 -- Exact trigonometric values --
write_ws("183-exact-trigonometric-values.json", {
    "title": "TRIGONOMETRY,\n(EXACT TRIGONOMETRIC VALUES)",
    "objective": "LO: I can recall and use exact trigonometric values for 0, 30, 45, 60 and 90 degrees.",
    "send_mode": False,
    "info_boxes": {
        "key_terms": {"id": "key_terms", "title": "Exact trig values", "content": [
            {"type": "paragraph", "text": "The <span class=\"ul-b\">exact trigonometric values</span> for common angles (0&deg;, 30&deg;, 45&deg;, 60&deg;, 90&deg;) can be expressed as <span class=\"ul-k\">fractions and surds</span> rather than decimals."},
            {"type": "paragraph", "text": "<span class=\"rb\">Key values:</span> sin 30&deg; = &frac{1}{2}, cos 60&deg; = &frac{1}{2}, tan 45&deg; = 1, sin 45&deg; = &frac{&radic;2}{2}."}]},
        "what_we_learn": {"id": "what_we_learn", "title": "Values to memorise", "examples": [
            {"correct": True, "expr": "sin 30&deg; = &frac{1}{2}", "desc": "from 30-60-90 triangle"},
            {"correct": True, "expr": "cos 45&deg; = &frac{&radic;2}{2}", "desc": "from 45-45-90 triangle"},
            {"correct": True, "expr": "tan 60&deg; = &radic;3", "desc": "sin 60 / cos 60"},
            {"correct": False, "expr": "sin 45&deg; = &frac{1}{2}", "desc": "sin 45 = &radic;2/2"},
            {"correct": False, "expr": "cos 90&deg; = 1", "desc": "cos 90 = 0"}]},
        "key_idea": {"id": "key_idea", "title": "Key idea",
            "text": "Learn the exact values from the 30-60-90 and 45-45-90 triangles.",
            "equation": "sin 60&deg; = <span class=\"ov\">&frac{&radic;3}{2}</span> | cos 30&deg; = <span class=\"ovr\">&frac{&radic;3}{2}</span>",
            "caption": "sin and cos are complementary: sin x = cos(90 &minus; x)"}},
    "modelled_examples": [
        example(1, "sin values", "State the exact value of sin 60&deg;.",
                ["From the 30-60-90 triangle", "Opposite = &radic;3, hypotenuse = 2", "sin 60&deg; = &frac{&radic;3}{2}"],
                "sin 60&deg; = &frac{&radic;3}{2}", "The 30-60-90 triangle has sides 1, &radic;3, 2."),
        example(2, "cos values", "Find the exact value of cos 30&deg;.",
                ["From the 30-60-90 triangle", "Adjacent = &radic;3, hypotenuse = 2", "cos 30&deg; = &frac{&radic;3}{2}"],
                "cos 30&deg; = &frac{&radic;3}{2}", "cos 30 = sin 60 (complementary angles)."),
        example(3, "tan values", "Find the exact value of tan 45&deg;.",
                ["From the 45-45-90 triangle", "Opposite = adjacent = 1", "tan 45&deg; = 1/1 = 1"],
                "tan 45&deg; = 1", "In a 45-45-90 triangle, the two legs are equal."),
        example(4, "using exact values", "Find the hypotenuse when the opposite is 8 and angle is 30&deg;.",
                ["sin 30&deg; = opp/hyp = 8/hyp", "&frac{1}{2} = 8/hyp", "hyp = 16"],
                "Hypotenuse = 16", "Substitute the exact value of sin 30&deg; = &frac{1}{2}.")],
    "practice": [
        practice(1, "Recall sin values", "#1F5FA6", "#EEF3FF", "#1F5FA6",
                 "State the exact value.",
                 [("a", "sin 0&deg;", "0"), ("b", "sin 30&deg;", "&frac{1}{2}"),
                  ("c", "sin 45&deg;", "&frac{&radic;2}{2}"), ("d", "sin 90&deg;", "1")]),
        practice(2, "Recall cos values", "#1F5FA6", "#EEF3FF", "#1F5FA6",
                 "State the exact value.",
                 [("a", "cos 0&deg;", "1"), ("b", "cos 30&deg;", "&frac{&radic;3}{2}"),
                  ("c", "cos 60&deg;", "&frac{1}{2}"), ("d", "cos 90&deg;", "0")]),
        practice(3, "Recall tan values", "#CC0000", "#FFF0F0", "#CC0000",
                 "State the exact value.",
                 [("a", "tan 0&deg;", "0"), ("b", "tan 30&deg;", "&frac{&radic;3}{3}"),
                  ("c", "tan 45&deg;", "1"), ("d", "tan 60&deg;", "&radic;3")]),
        practice(4, "Finding lengths", "#1E7D2E", "#EDFAEE", "#1E7D2E",
                 "Use exact values to find the unknown.",
                 [("a", "sin 30&deg; = x/10. Find x.", "5"), ("b", "cos 60&deg; = 6/h. Find h.", "12"),
                  ("c", "tan 45&deg; = y/7. Find y.", "7"), ("d", "sin 60&deg; = 9/h. Find h.", "6&radic;3")]),
        practice(5, "Mixed exact values", "#7B3FA0", "#F5EEFF", "#7B3FA0",
                 "Calculate exactly.",
                 [("a", "sin 30&deg; + cos 60&deg;", "1"), ("b", "sin&sup2; 45&deg; + cos&sup2; 45&deg;", "1"),
                  ("c", "2 sin 30&deg; cos 30&deg;", "&frac{&radic;3}{2}"), ("d", "tan 60&deg; &minus; tan 30&deg;", "&frac{2&radic;3}{3}"),
                  ("e", "sin 60&deg; &divide; cos 60&deg;", "&radic;3")])],
    "misconceptions": {"items": [
        {"id": "a", "statement": "sin 30&deg; = cos 60&deg; = &frac{1}{2}", "correct": True},
        {"id": "b", "statement": "sin 45&deg; = &frac{1}{2}", "correct": False},
        {"id": "c", "statement": "tan 45&deg; = 1", "correct": True},
        {"id": "d", "statement": "sin 90&deg; = 0", "correct": False},
        {"id": "e", "statement": "sin&sup2; x + cos&sup2; x = 1 for any angle x", "correct": True}]},
    "challenge": {"problems": [
        {"id": "a", "text": "An equilateral triangle has side length <strong>10 cm</strong>. Using exact values, find the height and area."},
        {"id": "b", "text": "Show that <strong>sin&sup2; 60&deg; + cos&sup2; 60&deg; = 1</strong>. Find <strong>sin 60&deg; cos 30&deg; + sin 30&deg; cos 60&deg;</strong>."}]},
})
