#!/usr/bin/env python3
"""Batch 5 builder - final 5 KS3/KS4 worksheets covering Vectors (190) and
Volume and Surface Area (191-194)."""
import json, os, sys

# Reuse helpers from batch 1
sys.path.insert(0, os.path.dirname(__file__))
from build_batch_1 import practice, example, write_ws


# == 190 - Writing and representing vectors ====================================
write_ws("190-writing-and-representing-vectors.json", {
    "title": "VECTORS,\n(WRITING AND REPRESENTING VECTORS)",
    "objective": "LO: I can write vectors using column notation and represent them on a grid.",
    "send_mode": False,
    "info_boxes": {
        "key_terms": {"id": "key_terms", "title": "Writing and representing vectors", "content": [
            {"type": "paragraph", "text": "A <span class=\"ul-b\">vector</span> describes a movement with both magnitude (size) and direction. We write column vectors as <span class=\"ul-k\">(x, y)</span> where x is the horizontal movement and y is the vertical movement."},
            {"type": "paragraph", "text": "<span class=\"rb\">Convention:</span> Positive x means right, negative x means left. Positive y means up, negative y means down. Vectors are equal if they have the same magnitude and direction."}]},
        "what_we_learn": {"id": "what_we_learn", "title": "Quick examples", "examples": [
            {"correct": True, "expr": "(3, 2) means 3 right and 2 up", "desc": "positive components"},
            {"correct": True, "expr": "(-1, 4) means 1 left and 4 up", "desc": "negative x means left"},
            {"correct": True, "expr": "(3, 2) and (3, 2) drawn at different points are equal", "desc": "same magnitude and direction"},
            {"correct": False, "expr": "(3, 2) means 3 up and 2 right", "desc": "x is horizontal (first), y is vertical (second)"},
            {"correct": False, "expr": "(2, 5) and (-2, -5) are the same vector", "desc": "they have opposite directions"}]},
        "key_idea": {"id": "key_idea", "title": "Key idea",
            "text": "A column vector gives horizontal then vertical displacement. Equal vectors have the same column vector regardless of starting point.",
            "equation": "<span class=\"ov\">vector</span> = <span class=\"ovr\">(horizontal, vertical)</span>",
            "caption": "Right and up are positive; left and down are negative"}},
    "modelled_examples": [
        example(1, "writing a column vector", "Write the vector that moves from A(1, 3) to B(4, 7) as a column vector.",
                ["Horizontal: 4 - 1 = 3 (right)", "Vertical: 7 - 3 = 4 (up)", "Column vector: (3, 4)"],
                "(3, 4)", "Subtract the start coordinates from the end coordinates."),
        example(2, "negative components", "Write the vector from P(5, 6) to Q(2, 1).",
                ["Horizontal: 2 - 5 = -3 (left)", "Vertical: 1 - 6 = -5 (down)", "Column vector: (-3, -5)"],
                "(-3, -5)", "Negative values show movement left or down."),
        example(3, "drawing a vector on a grid", "Draw the vector (4, -2) starting from point (1, 5).",
                ["Start at (1, 5)", "Move 4 right: x = 1 + 4 = 5", "Move 2 down: y = 5 + (-2) = 3. End at (5, 3)"],
                "Arrow from (1, 5) to (5, 3)", "Plot the start, apply the vector, mark the end with an arrow."),
        example(4, "identifying equal vectors", "Are (2, 3) from A(0, 0) and (2, 3) from B(4, 1) equal vectors?",
                ["First vector: same column (2, 3)", "Second vector: same column (2, 3)", "Same magnitude and direction, so they are equal"],
                "Yes, they are equal", "Position does not matter; only magnitude and direction define a vector.")],
    "practice": [
        practice(1, "Writing column vectors", "#1F5FA6", "#EEF3FF", "#1F5FA6",
                 "Write each movement as a column vector.",
                 [("a", "3 right, 5 up", "(3, 5)"), ("b", "2 left, 4 up", "(-2, 4)"),
                  ("c", "6 right, 1 down", "(6, -1)"), ("d", "4 left, 3 down", "(-4, -3)")]),
        practice(2, "From coordinates", "#1F5FA6", "#EEF3FF", "#1F5FA6",
                 "Find the column vector from the first point to the second.",
                 [("a", "(1, 2) to (4, 6)", "(3, 4)"), ("b", "(5, 7) to (2, 3)", "(-3, -4)"),
                  ("c", "(0, 0) to (6, -2)", "(6, -2)"), ("d", "(3, 8) to (3, 1)", "(0, -7)")]),
        practice(3, "Negative and zero components", "#CC0000", "#FFF0F0", "#CC0000",
                 "Write the column vector.",
                 [("a", "(7, 4) to (7, 9)", "(0, 5)"), ("b", "(3, 5) to (-2, 5)", "(-5, 0)"),
                  ("c", "(-1, -3) to (2, -6)", "(3, -3)"), ("d", "(-4, 2) to (-1, -4)", "(3, -6)")]),
        practice(4, "Drawing vectors", "#1E7D2E", "#EDFAEE", "#1E7D2E",
                 "Starting from the given point, state the end point after applying the vector.",
                 [("a", "Start (2, 3), vector (4, 1)", "(6, 4)"), ("b", "Start (5, 6), vector (-3, 2)", "(2, 8)"),
                  ("c", "Start (0, 4), vector (2, -4)", "(2, 0)"), ("d", "Start (7, 1), vector (-5, -1)", "(2, 0)")]),
        practice(5, "Mixed vector problems", "#7B3FA0", "#F5EEFF", "#7B3FA0",
                 "Solve each problem.",
                 [("a", "Write the return vector (opposite) of (3, -2)", "(-3, 2)"),
                  ("b", "A to B is (4, 5). B to C is (1, -3). Find A to C.", "(5, 2)"),
                  ("c", "P to Q is (-2, 6). What is Q to P?", "(2, -6)"),
                  ("d", "Vector (a, 3) moves (2, 1) to (5, 4). Find a.", "3"),
                  ("e", "Are (4, -1) and (-4, 1) equal, opposite, or neither?", "Opposite")])],
    "misconceptions": {"items": [
        {"id": "a", "statement": "(3, -2) means 3 right and 2 down", "correct": True},
        {"id": "b", "statement": "(3, -2) means 3 up and 2 left", "correct": False},
        {"id": "c", "statement": "Two vectors with the same column vector are equal regardless of position", "correct": True},
        {"id": "d", "statement": "(0, 5) means no movement at all", "correct": False},
        {"id": "e", "statement": "The negative of (a, b) is (-a, -b)", "correct": True}]},
    "challenge": {"problems": [
        {"id": "a", "text": "A drone starts at position <strong>(2, 3)</strong> on a grid. It follows three vectors in sequence: <strong>(4, 1)</strong>, then <strong>(-2, 5)</strong>, then <strong>(1, -3)</strong>. What is the drone\u2019s final position? Write a single vector that would take the drone directly from start to finish."},
        {"id": "b", "text": "Points A(1, 2), B(4, 6), C(7, 10) lie on a grid. Write the vectors AB and BC as column vectors. What do you notice? Explain why A, B, and C must be collinear (lie on the same straight line)."}]},
})


# == 191 - Surface area of cylinders and spheres ===============================
write_ws("191-surface-area-of-cylinders-and-spheres.json", {
    "title": "VOLUME AND SURFACE AREA,\n(SURFACE AREA OF CYLINDERS AND SPHERES)",
    "objective": "LO: I can calculate the surface area of cylinders and spheres using formulae.",
    "send_mode": False,
    "info_boxes": {
        "key_terms": {"id": "key_terms", "title": "Surface area of cylinders and spheres", "content": [
            {"type": "paragraph", "text": "The <span class=\"ul-b\">surface area</span> of a 3D shape is the total area of all its faces. A cylinder has two circular ends and a curved surface that unfolds into a rectangle. A <span class=\"ul-k\">sphere</span> has a single curved surface."},
            {"type": "paragraph", "text": "<span class=\"rb\">Formulae:</span> Cylinder SA = 2\u03c0r\u00b2 + 2\u03c0rh. Sphere SA = 4\u03c0r\u00b2. Always include units\u00b2 in your answer."}]},
        "what_we_learn": {"id": "what_we_learn", "title": "Quick examples", "examples": [
            {"correct": True, "expr": "Cylinder: 2\u03c0r\u00b2 + 2\u03c0rh", "desc": "two circles plus curved surface"},
            {"correct": True, "expr": "Sphere: 4\u03c0r\u00b2", "desc": "four times the area of a great circle"},
            {"correct": True, "expr": "Curved surface of cylinder = 2\u03c0rh", "desc": "rectangle when unrolled"},
            {"correct": False, "expr": "Cylinder SA = \u03c0r\u00b2h", "desc": "that is the volume formula"},
            {"correct": False, "expr": "Sphere SA = 2\u03c0r\u00b2", "desc": "must be 4\u03c0r\u00b2"}]},
        "key_idea": {"id": "key_idea", "title": "Key idea",
            "text": "Surface area is the total area covering the outside of a 3D shape. Use the correct formula for each shape.",
            "equation": "Cylinder SA = <span class=\"ov\">2\u03c0r\u00b2</span> + <span class=\"ovr\">2\u03c0rh</span>",
            "caption": "Two circular ends plus the curved surface area"}},
    "modelled_examples": [
        example(1, "cylinder surface area", "Find the surface area of a cylinder with radius 5 cm and height 8 cm. Give your answer to 1 d.p.",
                ["Two circles: 2\u03c0r\u00b2 = 2 \u00d7 \u03c0 \u00d7 5\u00b2 = 50\u03c0", "Curved surface: 2\u03c0rh = 2 \u00d7 \u03c0 \u00d7 5 \u00d7 8 = 80\u03c0", "Total = 50\u03c0 + 80\u03c0 = 130\u03c0 = 408.4 cm\u00b2"],
                "408.4 cm\u00b2", "Add the area of both circles and the curved surface."),
        example(2, "sphere surface area", "Find the surface area of a sphere with radius 6 cm. Give your answer to 1 d.p.",
                ["SA = 4\u03c0r\u00b2", "= 4 \u00d7 \u03c0 \u00d7 6\u00b2", "= 144\u03c0 = 452.4 cm\u00b2"],
                "452.4 cm\u00b2", "Substitute the radius into 4\u03c0r\u00b2."),
        example(3, "hemisphere surface area", "Find the total surface area of a solid hemisphere with radius 4 cm. Give your answer to 1 d.p.",
                ["Curved surface = half sphere = 2\u03c0r\u00b2 = 2 \u00d7 \u03c0 \u00d7 16 = 32\u03c0", "Flat circle = \u03c0r\u00b2 = 16\u03c0", "Total = 32\u03c0 + 16\u03c0 = 48\u03c0 = 150.8 cm\u00b2"],
                "150.8 cm\u00b2", "A solid hemisphere has a curved part plus a flat circular base."),
        example(4, "cylinder with no top", "A tin can (open top) has radius 3 cm and height 10 cm. Find the surface area to 1 d.p.",
                ["One circle (base): \u03c0r\u00b2 = 9\u03c0", "Curved surface: 2\u03c0rh = 2 \u00d7 \u03c0 \u00d7 3 \u00d7 10 = 60\u03c0", "Total = 9\u03c0 + 60\u03c0 = 69\u03c0 = 216.8 cm\u00b2"],
                "216.8 cm\u00b2", "Open-top means only one circular end is included.")],
    "practice": [
        practice(1, "Cylinder surface area", "#1F5FA6", "#EEF3FF", "#1F5FA6",
                 "Find the total surface area of each cylinder. Round to 1 d.p.",
                 [("a", "r = 3 cm, h = 7 cm", "188.5 cm\u00b2"), ("b", "r = 4 cm, h = 10 cm", "351.9 cm\u00b2"),
                  ("c", "r = 2 cm, h = 9 cm", "138.2 cm\u00b2"), ("d", "r = 6 cm, h = 5 cm", "414.7 cm\u00b2")]),
        practice(2, "Sphere surface area", "#1F5FA6", "#EEF3FF", "#1F5FA6",
                 "Find the surface area of each sphere. Round to 1 d.p.",
                 [("a", "r = 5 cm", "314.2 cm\u00b2"), ("b", "r = 3 cm", "113.1 cm\u00b2"),
                  ("c", "r = 10 cm", "1256.6 cm\u00b2"), ("d", "r = 7 cm", "615.8 cm\u00b2")]),
        practice(3, "Hemispheres", "#CC0000", "#FFF0F0", "#CC0000",
                 "Find the total surface area of each solid hemisphere. Round to 1 d.p.",
                 [("a", "r = 5 cm", "235.6 cm\u00b2"), ("b", "r = 8 cm", "603.2 cm\u00b2"),
                  ("c", "r = 2 cm", "37.7 cm\u00b2"), ("d", "r = 6 cm", "339.3 cm\u00b2")]),
        practice(4, "Open cylinders", "#1E7D2E", "#EDFAEE", "#1E7D2E",
                 "Find the surface area of each open-top cylinder. Round to 1 d.p.",
                 [("a", "r = 4 cm, h = 6 cm", "201.1 cm\u00b2"), ("b", "r = 5 cm, h = 12 cm", "455.5 cm\u00b2"),
                  ("c", "r = 3 cm, h = 8 cm", "179.1 cm\u00b2"), ("d", "r = 7 cm, h = 4 cm", "330.0 cm\u00b2")]),
        practice(5, "Mixed problems", "#7B3FA0", "#F5EEFF", "#7B3FA0",
                 "Solve each surface area problem. Round to 1 d.p.",
                 [("a", "Cylinder: r = 2.5 cm, h = 6 cm. Total SA?", "133.5 cm\u00b2"),
                  ("b", "Sphere with diameter 14 cm. SA?", "615.8 cm\u00b2"),
                  ("c", "Hemisphere: r = 9 cm. Total SA?", "763.4 cm\u00b2"),
                  ("d", "Cylinder with no ends: r = 4 cm, h = 10 cm. Curved SA?", "251.3 cm\u00b2"),
                  ("e", "Sphere with circumference 31.4 cm. Find r, then SA.", "r = 5 cm, SA = 314.2 cm\u00b2")])],
    "misconceptions": {"items": [
        {"id": "a", "statement": "Cylinder SA = 2\u03c0r\u00b2 + 2\u03c0rh includes both circles and the curved surface", "correct": True},
        {"id": "b", "statement": "Sphere SA = 2\u03c0r\u00b2", "correct": False},
        {"id": "c", "statement": "The curved surface area of a cylinder equals 2\u03c0rh", "correct": True},
        {"id": "d", "statement": "A hemisphere has surface area exactly half of a full sphere", "correct": False},
        {"id": "e", "statement": "Surface area is always measured in square units", "correct": True}]},
    "challenge": {"problems": [
        {"id": "a", "text": "A cylindrical water tank has radius <strong>1.2 m</strong> and height <strong>2 m</strong>. The outside (including top and base) needs painting. Paint covers <strong>8 m\u00b2 per litre</strong> and costs <strong>\u00a37.50 per litre</strong>. Find the total cost of paint needed."},
        {"id": "b", "text": "A solid shape is made from a hemisphere of radius <strong>5 cm</strong> joined to a cylinder of the same radius and height <strong>8 cm</strong>. Find the total surface area of the shape. (The join between hemisphere and cylinder is not an external surface.)"}]},
})


# == 192 - Surface area of prisms ==============================================
write_ws("192-surface-area-of-prisms.json", {
    "title": "VOLUME AND SURFACE AREA,\n(SURFACE AREA OF PRISMS)",
    "objective": "LO: I can calculate the surface area of prisms by finding the area of each face.",
    "send_mode": False,
    "info_boxes": {
        "key_terms": {"id": "key_terms", "title": "Surface area of prisms", "content": [
            {"type": "paragraph", "text": "A <span class=\"ul-b\">prism</span> is a 3D shape with a uniform cross-section. Its <span class=\"ul-k\">surface area</span> is the sum of the areas of all its faces: two identical end faces plus the rectangular side faces."},
            {"type": "paragraph", "text": "<span class=\"rb\">Method:</span> Find the area of the cross-section (end face), double it for both ends, then add the areas of each rectangular side. SA = 2 \u00d7 (area of cross-section) + (perimeter of cross-section) \u00d7 length."}]},
        "what_we_learn": {"id": "what_we_learn", "title": "Quick examples", "examples": [
            {"correct": True, "expr": "Cuboid: SA = 2(lw + lh + wh)", "desc": "three pairs of rectangular faces"},
            {"correct": True, "expr": "Triangular prism: 2 triangles + 3 rectangles", "desc": "count all faces"},
            {"correct": True, "expr": "SA = 2A + Ph (A = end area, P = perimeter, h = length)", "desc": "general prism formula"},
            {"correct": False, "expr": "SA = area of cross-section \u00d7 length", "desc": "that gives volume, not surface area"},
            {"correct": False, "expr": "A triangular prism has 4 faces", "desc": "it has 5 faces: 2 triangles + 3 rectangles"}]},
        "key_idea": {"id": "key_idea", "title": "Key idea",
            "text": "Surface area of a prism = 2 times the end face area plus the lateral (side) area. The lateral area equals perimeter of cross-section times length.",
            "equation": "SA = <span class=\"ov\">2A</span> + <span class=\"ovr\">P \u00d7 l</span>",
            "caption": "A = area of end face, P = perimeter of end, l = length of prism"}},
    "modelled_examples": [
        example(1, "cuboid", "Find the surface area of a cuboid 6 cm by 4 cm by 3 cm.",
                ["Three pairs of faces: 6\u00d74 = 24, 6\u00d73 = 18, 4\u00d73 = 12", "Double each: 48 + 36 + 24", "SA = 108 cm\u00b2"],
                "108 cm\u00b2", "A cuboid has three different pairs of rectangular faces."),
        example(2, "triangular prism", "A triangular prism has a right-angled triangle cross-section (base 6, height 8, hypotenuse 10 cm) and length 12 cm. Find the SA.",
                ["Two triangles: 2 \u00d7 \u00bd \u00d7 6 \u00d7 8 = 48 cm\u00b2", "Three rectangles: 6\u00d712 + 8\u00d712 + 10\u00d712 = 72 + 96 + 120 = 288 cm\u00b2", "SA = 48 + 288 = 336 cm\u00b2"],
                "336 cm\u00b2", "Find all five faces: two triangles and three rectangles."),
        example(3, "L-shaped prism", "An L-shaped prism has cross-section area 20 cm\u00b2, perimeter 24 cm, and length 10 cm. Find the SA.",
                ["Two ends: 2 \u00d7 20 = 40 cm\u00b2", "Lateral area: 24 \u00d7 10 = 240 cm\u00b2", "SA = 40 + 240 = 280 cm\u00b2"],
                "280 cm\u00b2", "Use the general formula when end area and perimeter are given."),
        example(4, "trapezoidal prism", "A prism has a trapezium cross-section with parallel sides 5 cm and 9 cm, height 4 cm, slant sides 5 cm each, and length 15 cm.",
                ["End area: \u00bd(5 + 9) \u00d7 4 = 28 cm\u00b2. Two ends = 56 cm\u00b2", "Perimeter: 5 + 9 + 5 + 5 = 24 cm", "Lateral area: 24 \u00d7 15 = 360 cm\u00b2. SA = 56 + 360 = 416 cm\u00b2"],
                "416 cm\u00b2", "Find the trapezium area, then use SA = 2A + Pl.")],
    "practice": [
        practice(1, "Cuboids", "#1F5FA6", "#EEF3FF", "#1F5FA6",
                 "Find the surface area of each cuboid.",
                 [("a", "5 cm \u00d7 3 cm \u00d7 2 cm", "62 cm\u00b2"), ("b", "8 cm \u00d7 4 cm \u00d7 3 cm", "136 cm\u00b2"),
                  ("c", "10 cm \u00d7 6 cm \u00d7 4 cm", "248 cm\u00b2"), ("d", "7 cm \u00d7 7 cm \u00d7 7 cm", "294 cm\u00b2")]),
        practice(2, "Triangular prisms", "#1F5FA6", "#EEF3FF", "#1F5FA6",
                 "Find the surface area of each triangular prism.",
                 [("a", "Triangle: base 6, height 4, hyp 5 cm. Length 10 cm.", "184 cm\u00b2"),
                  ("b", "Triangle: base 8, height 3, hyp 5 cm. Length 12 cm.", "216 cm\u00b2"),
                  ("c", "Triangle: base 5, height 12, hyp 13 cm. Length 8 cm.", "308 cm\u00b2"),
                  ("d", "Equilateral triangle side 6 cm. Length 10 cm.", "211.2 cm\u00b2")]),
        practice(3, "Using SA = 2A + Pl", "#CC0000", "#FFF0F0", "#CC0000",
                 "Given the cross-section area A, perimeter P, and length l, find the SA.",
                 [("a", "A = 15 cm\u00b2, P = 20 cm, l = 8 cm", "190 cm\u00b2"), ("b", "A = 24 cm\u00b2, P = 22 cm, l = 10 cm", "268 cm\u00b2"),
                  ("c", "A = 30 cm\u00b2, P = 28 cm, l = 6 cm", "228 cm\u00b2"), ("d", "A = 18 cm\u00b2, P = 18 cm, l = 12 cm", "252 cm\u00b2")]),
        practice(4, "Trapezoidal prisms", "#1E7D2E", "#EDFAEE", "#1E7D2E",
                 "Find the surface area of each trapezoidal prism.",
                 [("a", "Parallel sides 4, 8 cm; height 3 cm; slant sides 5 cm each; length 10 cm", "256 cm\u00b2"),
                  ("b", "Parallel sides 6, 10 cm; height 4 cm; slant sides 5 cm each; length 12 cm", "440 cm\u00b2"),
                  ("c", "Parallel sides 3, 7 cm; height 3 cm; slant sides 4 cm each; length 9 cm", "192 cm\u00b2"),
                  ("d", "Parallel sides 5, 11 cm; height 4 cm; slant sides 5 cm each; length 14 cm", "532 cm\u00b2")]),
        practice(5, "Mixed prism problems", "#7B3FA0", "#F5EEFF", "#7B3FA0",
                 "Solve each problem.",
                 [("a", "Cube with side 5 cm. SA?", "150 cm\u00b2"),
                  ("b", "Triangular prism: isosceles triangle base 10, equal sides 13, height 12 cm. Length 20 cm.", "840 cm\u00b2"),
                  ("c", "Cuboid SA = 340 cm\u00b2. If l = 10, w = 5, find h.", "6 cm"),
                  ("d", "A pentagonal prism: end area 45 cm\u00b2, perimeter 30 cm, length 8 cm.", "330 cm\u00b2"),
                  ("e", "Hexagonal prism: end area 54 cm\u00b2, perimeter 36 cm, length 10 cm.", "468 cm\u00b2")])],
    "misconceptions": {"items": [
        {"id": "a", "statement": "SA of a prism = 2 \u00d7 end area + perimeter \u00d7 length", "correct": True},
        {"id": "b", "statement": "SA of a prism = cross-section area \u00d7 length", "correct": False},
        {"id": "c", "statement": "A triangular prism has 5 faces", "correct": True},
        {"id": "d", "statement": "All faces of a prism are rectangles", "correct": False},
        {"id": "e", "statement": "To find SA you must add the area of every single face", "correct": True}]},
    "challenge": {"problems": [
        {"id": "a", "text": "A chocolate box is a triangular prism with an equilateral triangle cross-section of side <strong>8 cm</strong> and length <strong>20 cm</strong>. The box needs wrapping with <strong>10% extra</strong> paper for overlaps. How much wrapping paper is needed in cm\u00b2?"},
        {"id": "b", "text": "A swimming pool has a trapezoidal cross-section: one end is <strong>1 m deep</strong>, the other is <strong>2.5 m deep</strong>, the pool is <strong>25 m long</strong> and <strong>10 m wide</strong>. Find the total internal surface area that needs tiling (base and all four sides, no top)."}]},
})


# == 193 - Volume of prisms and cylinders ======================================
write_ws("193-volume-of-prisms-and-cylinders.json", {
    "title": "VOLUME AND SURFACE AREA,\n(VOLUME OF PRISMS AND CYLINDERS)",
    "objective": "LO: I can calculate the volume of prisms and cylinders using the formula V = area of cross-section times length.",
    "send_mode": False,
    "info_boxes": {
        "key_terms": {"id": "key_terms", "title": "Volume of prisms and cylinders", "content": [
            {"type": "paragraph", "text": "The <span class=\"ul-b\">volume</span> of a prism equals the area of its cross-section multiplied by its length. A <span class=\"ul-k\">cylinder</span> is a circular prism, so its volume = \u03c0r\u00b2h."},
            {"type": "paragraph", "text": "<span class=\"rb\">Key formulae:</span> Prism: V = A \u00d7 l (A = cross-section area, l = length). Cylinder: V = \u03c0r\u00b2h. Volume is measured in cubic units (cm\u00b3, m\u00b3)."}]},
        "what_we_learn": {"id": "what_we_learn", "title": "Quick examples", "examples": [
            {"correct": True, "expr": "Cuboid: V = l \u00d7 w \u00d7 h", "desc": "rectangle cross-section \u00d7 length"},
            {"correct": True, "expr": "Cylinder: V = \u03c0r\u00b2h", "desc": "circle area \u00d7 height"},
            {"correct": True, "expr": "Triangular prism: V = \u00bd \u00d7 b \u00d7 h \u00d7 l", "desc": "triangle area \u00d7 length"},
            {"correct": False, "expr": "Volume = surface area \u00d7 height", "desc": "volume uses cross-section area, not surface area"},
            {"correct": False, "expr": "Cylinder V = 2\u03c0rh", "desc": "that is the curved surface area, not volume"}]},
        "key_idea": {"id": "key_idea", "title": "Key idea",
            "text": "Volume of any prism = area of cross-section multiplied by the length (or height) of the prism.",
            "equation": "V = <span class=\"ov\">A</span> \u00d7 <span class=\"ovr\">l</span>",
            "caption": "A = area of the uniform cross-section, l = length of the prism"}},
    "modelled_examples": [
        example(1, "cuboid", "Find the volume of a cuboid 8 cm by 5 cm by 3 cm.",
                ["Cross-section area = 8 \u00d7 5 = 40 cm\u00b2", "Volume = 40 \u00d7 3", "= 120 cm\u00b3"],
                "120 cm\u00b3", "A cuboid is a rectangular prism."),
        example(2, "cylinder", "Find the volume of a cylinder with radius 4 cm and height 10 cm. Round to 1 d.p.",
                ["Cross-section area = \u03c0r\u00b2 = \u03c0 \u00d7 4\u00b2 = 16\u03c0", "Volume = 16\u03c0 \u00d7 10 = 160\u03c0", "= 502.7 cm\u00b3"],
                "502.7 cm\u00b3", "Substitute into V = \u03c0r\u00b2h."),
        example(3, "triangular prism", "Find the volume of a triangular prism with base 6 cm, height 4 cm, and length 15 cm.",
                ["Triangle area = \u00bd \u00d7 6 \u00d7 4 = 12 cm\u00b2", "Volume = 12 \u00d7 15", "= 180 cm\u00b3"],
                "180 cm\u00b3", "Find the triangle area first, then multiply by the length."),
        example(4, "trapezoidal prism", "A prism has a trapezium cross-section with parallel sides 5 cm and 9 cm, height 4 cm, and length 12 cm.",
                ["Trapezium area = \u00bd(5 + 9) \u00d7 4 = 28 cm\u00b2", "Volume = 28 \u00d7 12", "= 336 cm\u00b3"],
                "336 cm\u00b3", "Use the trapezium formula for the cross-section.")],
    "practice": [
        practice(1, "Cuboids", "#1F5FA6", "#EEF3FF", "#1F5FA6",
                 "Find the volume of each cuboid.",
                 [("a", "6 cm \u00d7 4 cm \u00d7 3 cm", "72 cm\u00b3"), ("b", "10 cm \u00d7 5 cm \u00d7 2 cm", "100 cm\u00b3"),
                  ("c", "8 cm \u00d7 8 cm \u00d7 8 cm", "512 cm\u00b3"), ("d", "12 cm \u00d7 3 cm \u00d7 5 cm", "180 cm\u00b3")]),
        practice(2, "Cylinders", "#1F5FA6", "#EEF3FF", "#1F5FA6",
                 "Find the volume of each cylinder. Round to 1 d.p.",
                 [("a", "r = 3 cm, h = 10 cm", "282.7 cm\u00b3"), ("b", "r = 5 cm, h = 8 cm", "628.3 cm\u00b3"),
                  ("c", "r = 2 cm, h = 15 cm", "188.5 cm\u00b3"), ("d", "r = 7 cm, h = 6 cm", "923.6 cm\u00b3")]),
        practice(3, "Triangular prisms", "#CC0000", "#FFF0F0", "#CC0000",
                 "Find the volume of each triangular prism.",
                 [("a", "Base 8, height 5, length 12 cm", "240 cm\u00b3"), ("b", "Base 10, height 6, length 9 cm", "270 cm\u00b3"),
                  ("c", "Base 7, height 4, length 20 cm", "280 cm\u00b3"), ("d", "Base 12, height 3, length 8 cm", "144 cm\u00b3")]),
        practice(4, "Other prisms", "#1E7D2E", "#EDFAEE", "#1E7D2E",
                 "Find the volume using V = A \u00d7 l.",
                 [("a", "Trapezium: parallel sides 4, 8; height 3; length 10 cm", "180 cm\u00b3"),
                  ("b", "Cross-section area 25 cm\u00b2, length 14 cm", "350 cm\u00b3"),
                  ("c", "L-shape cross-section area 32 cm\u00b2, length 6 cm", "192 cm\u00b3"),
                  ("d", "Hexagonal cross-section area 42 cm\u00b2, length 9 cm", "378 cm\u00b3")]),
        practice(5, "Mixed volume problems", "#7B3FA0", "#F5EEFF", "#7B3FA0",
                 "Solve each problem.",
                 [("a", "Cylinder: diameter 10 cm, height 7 cm. Volume?", "549.8 cm\u00b3"),
                  ("b", "Prism volume = 360 cm\u00b3. Cross-section area = 30 cm\u00b2. Find length.", "12 cm"),
                  ("c", "Cylinder volume = 200\u03c0 cm\u00b3. Height = 8 cm. Find the radius.", "5 cm"),
                  ("d", "Cuboid: l = 9, w = 4. Volume = 252 cm\u00b3. Find h.", "7 cm"),
                  ("e", "Triangular prism: base 6, length 10. Volume = 180 cm\u00b3. Find height of triangle.", "6 cm")])],
    "misconceptions": {"items": [
        {"id": "a", "statement": "Volume of a prism = area of cross-section \u00d7 length", "correct": True},
        {"id": "b", "statement": "Volume of a cylinder = 2\u03c0rh", "correct": False},
        {"id": "c", "statement": "V = \u03c0r\u00b2h requires the radius, not the diameter", "correct": True},
        {"id": "d", "statement": "Volume and surface area use the same formula", "correct": False},
        {"id": "e", "statement": "Volume is measured in cubic units such as cm\u00b3", "correct": True}]},
    "challenge": {"problems": [
        {"id": "a", "text": "A cylindrical tank of radius <strong>0.5 m</strong> and height <strong>1.2 m</strong> is filled with water. The water is poured into a rectangular tank measuring <strong>1 m by 0.8 m</strong>. What depth does the water reach? Give your answer to the nearest cm."},
        {"id": "b", "text": "A triangular prism-shaped chocolate bar has a cross-section that is an equilateral triangle with side <strong>4 cm</strong>. The bar is <strong>18 cm</strong> long. If chocolate weighs <strong>1.3 g per cm\u00b3</strong>, find the mass of the bar to the nearest gram."}]},
})


# == 194 - Volume of pyramids, cones and spheres ===============================
write_ws("194-volume-of-pyramids-cones-and-spheres.json", {
    "title": "VOLUME AND SURFACE AREA,\n(VOLUME OF PYRAMIDS, CONES AND SPHERES)",
    "objective": "LO: I can calculate the volume of pyramids, cones and spheres using standard formulae.",
    "send_mode": False,
    "info_boxes": {
        "key_terms": {"id": "key_terms", "title": "Volume of pyramids, cones and spheres", "content": [
            {"type": "paragraph", "text": "A <span class=\"ul-b\">pyramid</span> has a polygon base and triangular faces meeting at an apex. A <span class=\"ul-k\">cone</span> is a circular pyramid. Their volumes are one-third of the corresponding prism or cylinder."},
            {"type": "paragraph", "text": "<span class=\"rb\">Key formulae:</span> Pyramid: V = &frac{1}{3} \u00d7 base area \u00d7 height. Cone: V = &frac{1}{3}\u03c0r\u00b2h. Sphere: V = &frac{4}{3}\u03c0r\u00b3."}]},
        "what_we_learn": {"id": "what_we_learn", "title": "Quick examples", "examples": [
            {"correct": True, "expr": "Pyramid: V = &frac{1}{3} \u00d7 base area \u00d7 h", "desc": "one-third of the prism with same base"},
            {"correct": True, "expr": "Cone: V = &frac{1}{3}\u03c0r\u00b2h", "desc": "one-third of the cylinder"},
            {"correct": True, "expr": "Sphere: V = &frac{4}{3}\u03c0r\u00b3", "desc": "uses radius cubed"},
            {"correct": False, "expr": "Cone V = \u03c0r\u00b2h", "desc": "must include the &frac{1}{3} factor"},
            {"correct": False, "expr": "Sphere V = 4\u03c0r\u00b2", "desc": "that is surface area, not volume"}]},
        "key_idea": {"id": "key_idea", "title": "Key idea",
            "text": "Pyramids and cones have volume equal to one-third of the corresponding prism or cylinder. A sphere uses its own formula with r cubed.",
            "equation": "V = <span class=\"ov\">&frac{1}{3}</span> \u00d7 <span class=\"ovr\">base area \u00d7 h</span>",
            "caption": "The &frac{1}{3} factor applies to all pyramids and cones"}},
    "modelled_examples": [
        example(1, "square-based pyramid", "Find the volume of a pyramid with a square base of side 6 cm and height 10 cm.",
                ["Base area = 6 \u00d7 6 = 36 cm\u00b2", "V = &frac{1}{3} \u00d7 36 \u00d7 10", "= 120 cm\u00b3"],
                "120 cm\u00b3", "Find the base area first, then multiply by one-third of the height."),
        example(2, "cone", "Find the volume of a cone with radius 5 cm and height 12 cm. Round to 1 d.p.",
                ["V = &frac{1}{3}\u03c0r\u00b2h", "= &frac{1}{3} \u00d7 \u03c0 \u00d7 25 \u00d7 12", "= 100\u03c0 = 314.2 cm\u00b3"],
                "314.2 cm\u00b3", "Substitute into the cone formula and evaluate."),
        example(3, "sphere", "Find the volume of a sphere with radius 3 cm. Round to 1 d.p.",
                ["V = &frac{4}{3}\u03c0r\u00b3", "= &frac{4}{3} \u00d7 \u03c0 \u00d7 27", "= 36\u03c0 = 113.1 cm\u00b3"],
                "113.1 cm\u00b3", "Cube the radius, then multiply by &frac{4}{3}\u03c0."),
        example(4, "hemisphere", "Find the volume of a hemisphere with radius 6 cm. Round to 1 d.p.",
                ["Full sphere: V = &frac{4}{3}\u03c0 \u00d7 6\u00b3 = &frac{4}{3}\u03c0 \u00d7 216 = 288\u03c0", "Hemisphere = half: &frac{1}{2} \u00d7 288\u03c0 = 144\u03c0", "= 452.4 cm\u00b3"],
                "452.4 cm\u00b3", "Find the full sphere volume, then halve it.")],
    "practice": [
        practice(1, "Pyramids", "#1F5FA6", "#EEF3FF", "#1F5FA6",
                 "Find the volume of each pyramid.",
                 [("a", "Square base side 4 cm, height 9 cm", "48 cm\u00b3"), ("b", "Square base side 10 cm, height 12 cm", "400 cm\u00b3"),
                  ("c", "Rectangular base 6 \u00d7 8 cm, height 15 cm", "240 cm\u00b3"), ("d", "Triangular base area 20 cm\u00b2, height 9 cm", "60 cm\u00b3")]),
        practice(2, "Cones", "#1F5FA6", "#EEF3FF", "#1F5FA6",
                 "Find the volume of each cone. Round to 1 d.p.",
                 [("a", "r = 3 cm, h = 7 cm", "66.0 cm\u00b3"), ("b", "r = 4 cm, h = 9 cm", "150.8 cm\u00b3"),
                  ("c", "r = 6 cm, h = 10 cm", "377.0 cm\u00b3"), ("d", "r = 5 cm, h = 15 cm", "392.7 cm\u00b3")]),
        practice(3, "Spheres", "#CC0000", "#FFF0F0", "#CC0000",
                 "Find the volume of each sphere. Round to 1 d.p.",
                 [("a", "r = 4 cm", "268.1 cm\u00b3"), ("b", "r = 6 cm", "904.8 cm\u00b3"),
                  ("c", "r = 10 cm", "4188.8 cm\u00b3"), ("d", "Diameter 14 cm", "1436.8 cm\u00b3")]),
        practice(4, "Hemispheres and composite shapes", "#1E7D2E", "#EDFAEE", "#1E7D2E",
                 "Find the volume. Round to 1 d.p.",
                 [("a", "Hemisphere: r = 5 cm", "261.8 cm\u00b3"), ("b", "Hemisphere: r = 8 cm", "1072.3 cm\u00b3"),
                  ("c", "Cone on top of hemisphere, both r = 3 cm, cone h = 4 cm", "93.8 cm\u00b3"),
                  ("d", "Cylinder r = 4, h = 10 plus hemisphere r = 4 on top", "637.7 cm\u00b3")]),
        practice(5, "Mixed volume problems", "#7B3FA0", "#F5EEFF", "#7B3FA0",
                 "Solve each problem. Round to 1 d.p. where needed.",
                 [("a", "Cone: diameter 8 cm, height 12 cm. Volume?", "201.1 cm\u00b3"),
                  ("b", "Sphere volume = 288\u03c0 cm\u00b3. Find the radius.", "6 cm"),
                  ("c", "Pyramid base 5 \u00d7 5 cm, volume = 75 cm\u00b3. Find height.", "9 cm"),
                  ("d", "Cone volume = 150 cm\u00b3, height = 10 cm. Find radius to 1 d.p.", "3.8 cm"),
                  ("e", "How many times bigger is a sphere of radius 6 than one of radius 3?", "8 times")])],
    "misconceptions": {"items": [
        {"id": "a", "statement": "Volume of a cone = &frac{1}{3}\u03c0r\u00b2h", "correct": True},
        {"id": "b", "statement": "Volume of a cone = \u03c0r\u00b2h", "correct": False},
        {"id": "c", "statement": "Volume of a sphere uses r\u00b3 (radius cubed)", "correct": True},
        {"id": "d", "statement": "Doubling the radius of a sphere doubles its volume", "correct": False},
        {"id": "e", "statement": "A hemisphere volume is half of &frac{4}{3}\u03c0r\u00b3", "correct": True}]},
    "challenge": {"problems": [
        {"id": "a", "text": "An ice cream cone has radius <strong>3 cm</strong> and height <strong>12 cm</strong>. A hemisphere of ice cream (same radius) sits on top. Find the total volume of cone plus ice cream. If the ice cream melts into the cone, will it overflow? Show your working."},
        {"id": "b", "text": "A solid metal cone has base radius <strong>6 cm</strong> and height <strong>10 cm</strong>. It is melted down and recast into a sphere. Find the radius of the sphere. Give your answer to 1 decimal place."}]},
})
