/**
 * FunFactsCarousel — shown during AI generation for non-admin accounts.
 * Cycles through SEND/education fun facts every 4.5 seconds with a CSS opacity fade.
 * Uses a single interval registered once on mount — no AnimatePresence re-mount issues.
 */
import React, { useState, useEffect, useRef } from "react";
import { Lightbulb } from "lucide-react";

const FACTS = [
  { fact: "Did you know? 1 in 5 children in the UK has a special educational need or disability." },
  { fact: "The average SENCO manages support for over 100 pupils — Adaptly helps them do it in a fraction of the time." },
  { fact: "Worksheets adapted for dyslexia use wider line spacing, sans-serif fonts, and pastel overlays to reduce visual stress." },
  { fact: "Children with ADHD often thrive with chunked tasks and tick-box formats — exactly how Adaptly structures their work." },
  { fact: "Early identification of SEND needs (before age 7) leads to significantly better long-term outcomes." },
  { fact: "The SEND Code of Practice 2015 requires schools to follow a 'graduated approach' — Assess, Plan, Do, Review." },
  { fact: "ASC pupils often benefit from literal language and structured, predictable layouts — Adaptly applies this automatically." },
  { fact: "Over 1.5 million pupils in England are on the SEND register — that's nearly 1 in 6 school children." },
  { fact: "Parental engagement is one of the strongest predictors of positive SEND outcomes. The Parent Portal bridges that gap." },
  { fact: "A well-written EHCP can unlock thousands of pounds of additional support for a child. Adaptly helps get the wording right." },
  { fact: "Colour overlays can improve reading speed by up to 25% for pupils with visual stress or Irlen syndrome." },
  { fact: "The Equality Act 2010 requires schools to make 'reasonable adjustments' for disabled pupils — Adaptly makes this effortless." },
  { fact: "Speech, Language and Communication Needs (SLCN) is the most common primary need on the SEND register." },
  { fact: "Pupils with dyscalculia often benefit from visual representations and step-by-step scaffolding — built into every Adaptly maths worksheet." },
  { fact: "AI-generated feedback can be tailored to a pupil's communication style — simpler language for some, more detailed for others." },
  { fact: "Transition planning for SEND pupils should begin at Year 9 — Adaptly's tools help document the journey from day one." },
  { fact: "Every worksheet generated by Adaptly is curriculum-aligned to the National Curriculum and major exam boards." },
];

interface FunFactsCarouselProps {
  className?: string;
}

export function FunFactsCarousel({ className = "" }: FunFactsCarouselProps) {
  const startIdx = useRef(Math.floor(Math.random() * FACTS.length));
  const [index, setIndex] = useState(startIdx.current);
  const [fading, setFading] = useState(false);

  useEffect(() => {
    // Register the interval exactly once. The empty deps array prevents
    // re-registration when parent state changes during generation.
    const interval = setInterval(() => {
      setFading(true);
      setTimeout(() => {
        setIndex(i => (i + 1) % FACTS.length);
        setFading(false);
      }, 350);
    }, 4500);
    return () => clearInterval(interval);
  }, []); // eslint-disable-line react-hooks/exhaustive-deps

  const fact = FACTS[index];

  return (
    <div className={`w-full ${className}`}>
      <div className="flex items-center gap-1.5 mb-2 justify-center">
        <Lightbulb className="w-3.5 h-3.5 text-amber-400" />
        <span className="text-[10px] font-bold tracking-widest uppercase text-amber-400">Did you know?</span>
      </div>
      <div
        style={{
          transition: "opacity 0.35s ease",
          opacity: fading ? 0 : 1,
          textAlign: "center",
          minHeight: "52px",
        }}
      >
        <p className="text-xs text-muted-foreground leading-relaxed px-2">
          {fact.fact}
        </p>
      </div>
      {/* Dot indicators */}
      <div className="flex justify-center gap-1 mt-3">
        {FACTS.map((_, i) => (
          <div
            key={i}
            style={{
              borderRadius: "9999px",
              transition: "all 0.3s",
              width: i === index ? "12px" : "6px",
              height: "6px",
              background: i === index ? "var(--brand, #4f46e5)" : "rgba(100,100,100,0.2)",
            }}
          />
        ))}
      </div>
    </div>
  );
}
