/**
 * FunFactsCarousel — shown during AI generation for non-admin accounts.
 * Cycles through SEND/education fun facts every 4 seconds with a smooth fade.
 */
import React, { useState, useEffect } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { Lightbulb } from "lucide-react";

const FACTS = [
  { fact: "Did you know? 1 in 5 children in the UK has a special educational need or disability.", emoji: "📚" },
  { fact: "The average SENCO manages support for over 100 pupils — Adaptly helps them do it in a fraction of the time.", emoji: "⚡" },
  { fact: "Worksheets adapted for dyslexia use wider line spacing, sans-serif fonts, and pastel overlays to reduce visual stress.", emoji: "🎨" },
  { fact: "Children with ADHD often thrive with chunked tasks and tick-box formats — exactly how Adaptly structures their work.", emoji: "✅" },
  { fact: "Early identification of SEND needs (before age 7) leads to significantly better long-term outcomes.", emoji: "🌱" },
  { fact: "The SEND Code of Practice 2015 requires schools to follow a 'graduated approach' — Assess, Plan, Do, Review.", emoji: "🔄" },
  { fact: "ASC pupils often benefit from literal language and structured, predictable layouts — Adaptly applies this automatically.", emoji: "🧩" },
  { fact: "Over 1.5 million pupils in England are on the SEND register — that's nearly 1 in 6 school children.", emoji: "📊" },
  { fact: "Parental engagement is one of the strongest predictors of positive SEND outcomes. The Parent Portal bridges that gap.", emoji: "🤝" },
  { fact: "A well-written EHCP can unlock thousands of pounds of additional support for a child. Adaptly helps get the wording right.", emoji: "📝" },
  { fact: "Colour overlays can improve reading speed by up to 25% for pupils with visual stress or Irlen syndrome.", emoji: "🌈" },
  { fact: "The Equality Act 2010 requires schools to make 'reasonable adjustments' for disabled pupils — Adaptly makes this effortless.", emoji: "⚖️" },
  { fact: "Speech, Language and Communication Needs (SLCN) is the most common primary need on the SEND register.", emoji: "💬" },
  { fact: "Pupils with dyscalculia often benefit from visual representations and step-by-step scaffolding — built into every Adaptly maths worksheet.", emoji: "🔢" },
  { fact: "The Skill Ladder tracks progress across 6 domains, giving SENCOs real evidence for EHCP reviews and parent meetings.", emoji: "📈" },
  { fact: "AI-generated feedback can be tailored to a pupil's communication style — simpler language for some, more detailed for others.", emoji: "🤖" },
  { fact: "Transition planning for SEND pupils should begin at Year 9 — Adaptly's tools help document the journey from day one.", emoji: "🎓" },
  { fact: "Every worksheet generated by Adaptly is curriculum-aligned to the National Curriculum and major exam boards.", emoji: "🏫" },
];

interface FunFactsCarouselProps {
  className?: string;
}

export function FunFactsCarousel({ className = "" }: FunFactsCarouselProps) {
  const [index, setIndex] = useState(() => Math.floor(Math.random() * FACTS.length));
  const [visible, setVisible] = useState(true);

  useEffect(() => {
    const interval = setInterval(() => {
      setVisible(false);
      setTimeout(() => {
        setIndex(i => (i + 1) % FACTS.length);
        setVisible(true);
      }, 400);
    }, 4500);
    return () => clearInterval(interval);
  }, []);

  const fact = FACTS[index];

  return (
    <div className={`w-full ${className}`}>
      <div className="flex items-center gap-1.5 mb-2 justify-center">
        <Lightbulb className="w-3.5 h-3.5 text-amber-400" />
        <span className="text-[10px] font-bold tracking-widest uppercase text-amber-400">Did you know?</span>
      </div>
      <AnimatePresence mode="wait">
        {visible && (
          <motion.div
            key={index}
            initial={{ opacity: 0, y: 8 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: -8 }}
            transition={{ duration: 0.35, ease: "easeInOut" }}
            className="text-center"
          >
            <span className="text-lg block mb-1">{fact.emoji}</span>
            <p className="text-xs text-muted-foreground leading-relaxed px-2">
              {fact.fact}
            </p>
          </motion.div>
        )}
      </AnimatePresence>
      {/* Dot indicators */}
      <div className="flex justify-center gap-1 mt-3">
        {FACTS.map((_, i) => (
          <div
            key={i}
            className={`rounded-full transition-all duration-300 ${
              i === index ? "w-3 h-1.5 bg-brand" : "w-1.5 h-1.5 bg-muted-foreground/30"
            }`}
          />
        ))}
      </div>
    </div>
  );
}
