/**
 * AUTO-GENERATED by scripts/build-maths-gold.mjs — DO NOT EDIT BY HAND.
 *
 * Lightweight index of the bundled "gold" maths worksheets. The heavy content
 * lives in ./worksheets.json and is loaded lazily by loadGoldWorksheet().
 *
 * Regenerate: node scripts/build-maths-gold.mjs
 */
import type { GoldWorksheet } from "@/lib/mathsGoldRenderer";

export interface GoldManifestEntry {
  /** filename stem, e.g. "021-substitution-into-expressions" */
  slug: string;
  /** canonical worksheet number from PLAN.md */
  num: number;
  /** topic name, matches SUBTOPICS_MAP keys */
  topic: string;
  /** subtopic name, matches SUBTOPICS_MAP values */
  subtopic: string;
  /** normalised topic slug (for fallback matching) */
  topicSlug: string;
  /** normalised subtopic slug (for fallback matching) */
  subtopicSlug: string;
}

export const MATHS_GOLD_MANIFEST: GoldManifestEntry[] = [
  {
    "slug": "021-substitution-into-expressions",
    "num": 21,
    "topic": "Algebra — Simple Formulae and Sequences",
    "subtopic": "Substitution into expressions",
    "topicSlug": "algebra-simple-formulae-and-sequences",
    "subtopicSlug": "substitution-into-expressions"
  },
  {
    "slug": "022-using-and-writing-simple-formulae",
    "num": 22,
    "topic": "Algebra — Simple Formulae and Sequences",
    "subtopic": "Using and writing simple formulae",
    "topicSlug": "algebra-simple-formulae-and-sequences",
    "subtopicSlug": "using-and-writing-simple-formulae"
  },
  {
    "slug": "023-expanding-double-brackets",
    "num": 23,
    "topic": "Algebraic Expressions",
    "subtopic": "Expanding double brackets",
    "topicSlug": "algebraic-expressions",
    "subtopicSlug": "expanding-double-brackets"
  },
  {
    "slug": "024-expanding-single-brackets",
    "num": 24,
    "topic": "Algebraic Expressions",
    "subtopic": "Expanding single brackets",
    "topicSlug": "algebraic-expressions",
    "subtopicSlug": "expanding-single-brackets"
  },
  {
    "slug": "025-factorising-expressions",
    "num": 25,
    "topic": "Algebraic Expressions",
    "subtopic": "Factorising expressions",
    "topicSlug": "algebraic-expressions",
    "subtopicSlug": "factorising-expressions"
  },
  {
    "slug": "026-angles-in-parallel-lines",
    "num": 26,
    "topic": "Angles",
    "subtopic": "Angles in parallel lines",
    "topicSlug": "angles",
    "subtopicSlug": "angles-in-parallel-lines"
  },
  {
    "slug": "027-angles-in-polygons",
    "num": 27,
    "topic": "Angles",
    "subtopic": "Angles in polygons",
    "topicSlug": "angles",
    "subtopicSlug": "angles-in-polygons"
  },
  {
    "slug": "028-angles-in-triangles-and-quadrilaterals",
    "num": 28,
    "topic": "Angles",
    "subtopic": "Angles in triangles and quadrilaterals",
    "topicSlug": "angles",
    "subtopicSlug": "angles-in-triangles-and-quadrilaterals"
  },
  {
    "slug": "029-angles-on-a-straight-line-and-at-a-point",
    "num": 29,
    "topic": "Angles",
    "subtopic": "Angles on a straight line and at a point",
    "topicSlug": "angles",
    "subtopicSlug": "angles-on-a-straight-line-and-at-a-point"
  },
  {
    "slug": "030-area-of-rectangles-triangles-and-parallelograms",
    "num": 30,
    "topic": "Area and Perimeter",
    "subtopic": "Area of rectangles, triangles and parallelograms",
    "topicSlug": "area-and-perimeter",
    "subtopicSlug": "area-of-rectangles-triangles-and-parallelograms"
  },
  {
    "slug": "031-area-of-trapeziums-and-composite-shapes",
    "num": 31,
    "topic": "Area and Perimeter",
    "subtopic": "Area of trapeziums and composite shapes",
    "topicSlug": "area-and-perimeter",
    "subtopicSlug": "area-of-trapeziums-and-composite-shapes"
  },
  {
    "slug": "032-circumference-of-a-circle",
    "num": 32,
    "topic": "Area and Perimeter",
    "subtopic": "Circumference of a circle",
    "topicSlug": "area-and-perimeter",
    "subtopicSlug": "circumference-of-a-circle"
  },
  {
    "slug": "039-comparing-fractions-decimals-and-percentages",
    "num": 39,
    "topic": "Decimals and Percentages",
    "subtopic": "Comparing fractions, decimals and percentages",
    "topicSlug": "decimals-and-percentages",
    "subtopicSlug": "comparing-fractions-decimals-and-percentages"
  },
  {
    "slug": "040-finding-percentages-of-amounts",
    "num": 40,
    "topic": "Decimals and Percentages",
    "subtopic": "Finding percentages of amounts",
    "topicSlug": "decimals-and-percentages",
    "subtopicSlug": "finding-percentages-of-amounts"
  },
  {
    "slug": "041-percentage-increase-and-decrease",
    "num": 41,
    "topic": "Decimals and Percentages",
    "subtopic": "Percentage increase and decrease",
    "topicSlug": "decimals-and-percentages",
    "subtopicSlug": "percentage-increase-and-decrease"
  },
  {
    "slug": "042-percentages-as-fractions-and-decimals",
    "num": 42,
    "topic": "Decimals and Percentages",
    "subtopic": "Percentages as fractions and decimals",
    "topicSlug": "decimals-and-percentages",
    "subtopicSlug": "percentages-as-fractions-and-decimals"
  },
  {
    "slug": "043-adding-and-subtracting-decimals",
    "num": 43,
    "topic": "Decimals — All Operations",
    "subtopic": "Adding and subtracting decimals",
    "topicSlug": "decimals-all-operations",
    "subtopicSlug": "adding-and-subtracting-decimals"
  },
  {
    "slug": "044-dividing-decimals",
    "num": 44,
    "topic": "Decimals — All Operations",
    "subtopic": "Dividing decimals",
    "topicSlug": "decimals-all-operations",
    "subtopicSlug": "dividing-decimals"
  },
  {
    "slug": "045-multiplying-decimals",
    "num": 45,
    "topic": "Decimals — All Operations",
    "subtopic": "Multiplying decimals",
    "topicSlug": "decimals-all-operations",
    "subtopicSlug": "multiplying-decimals"
  },
  {
    "slug": "046-rounding-decimals-to-decimal-places",
    "num": 46,
    "topic": "Decimals — All Operations",
    "subtopic": "Rounding decimals to decimal places",
    "topicSlug": "decimals-all-operations",
    "subtopicSlug": "rounding-decimals-to-decimal-places"
  },
  {
    "slug": "047-bidmas-bodmas",
    "num": 47,
    "topic": "Four Operations and Order of Operations",
    "subtopic": "BIDMAS/BODMAS",
    "topicSlug": "four-operations-and-order-of-operations",
    "subtopicSlug": "bidmas-bodmas"
  },
  {
    "slug": "048-checking-answers-using-inverse-operations",
    "num": 48,
    "topic": "Four Operations and Order of Operations",
    "subtopic": "Checking answers using inverse operations",
    "topicSlug": "four-operations-and-order-of-operations",
    "subtopicSlug": "checking-answers-using-inverse-operations"
  },
  {
    "slug": "049-multi-step-calculations",
    "num": 49,
    "topic": "Four Operations and Order of Operations",
    "subtopic": "Multi-step calculations",
    "topicSlug": "four-operations-and-order-of-operations",
    "subtopicSlug": "multi-step-calculations"
  },
  {
    "slug": "050-adding-and-subtracting-fractions",
    "num": 50,
    "topic": "Fractions",
    "subtopic": "Adding and subtracting fractions",
    "topicSlug": "fractions",
    "subtopicSlug": "adding-and-subtracting-fractions"
  },
  {
    "slug": "051-algebraic-fractions",
    "num": 51,
    "topic": "Fractions",
    "subtopic": "Algebraic fractions",
    "topicSlug": "fractions",
    "subtopicSlug": "algebraic-fractions"
  },
  {
    "slug": "052-dividing-fractions",
    "num": 52,
    "topic": "Fractions",
    "subtopic": "Dividing fractions",
    "topicSlug": "fractions",
    "subtopicSlug": "dividing-fractions"
  },
  {
    "slug": "053-multiplying-fractions",
    "num": 53,
    "topic": "Fractions",
    "subtopic": "Multiplying fractions",
    "topicSlug": "fractions",
    "subtopicSlug": "multiplying-fractions"
  },
  {
    "slug": "066-adding-and-subtracting-fractions-different-denominators",
    "num": 66,
    "topic": "Fractions — All Operations",
    "subtopic": "Adding and subtracting fractions (different denominators)",
    "topicSlug": "fractions-all-operations",
    "subtopicSlug": "adding-and-subtracting-fractions-different-denominators"
  },
  {
    "slug": "067-dividing-fractions",
    "num": 67,
    "topic": "Fractions — All Operations",
    "subtopic": "Dividing fractions",
    "topicSlug": "fractions-all-operations",
    "subtopicSlug": "dividing-fractions"
  },
  {
    "slug": "068-fractions-of-amounts",
    "num": 68,
    "topic": "Fractions — All Operations",
    "subtopic": "Fractions of amounts",
    "topicSlug": "fractions-all-operations",
    "subtopicSlug": "fractions-of-amounts"
  },
  {
    "slug": "069-multiplying-fractions",
    "num": 69,
    "topic": "Fractions — All Operations",
    "subtopic": "Multiplying fractions",
    "topicSlug": "fractions-all-operations",
    "subtopicSlug": "multiplying-fractions"
  },
  {
    "slug": "070-adding-and-subtracting-algebraic-fractions",
    "num": 70,
    "topic": "Fractions — Secondary",
    "subtopic": "Adding and subtracting algebraic fractions",
    "topicSlug": "fractions-secondary",
    "subtopicSlug": "adding-and-subtracting-algebraic-fractions"
  },
  {
    "slug": "071-equations-involving-fractions",
    "num": 71,
    "topic": "Fractions — Secondary",
    "subtopic": "Equations involving fractions",
    "topicSlug": "fractions-secondary",
    "subtopicSlug": "equations-involving-fractions"
  },
  {
    "slug": "072-multiplying-and-dividing-algebraic-fractions",
    "num": 72,
    "topic": "Fractions — Secondary",
    "subtopic": "Multiplying and dividing algebraic fractions",
    "topicSlug": "fractions-secondary",
    "subtopicSlug": "multiplying-and-dividing-algebraic-fractions"
  },
  {
    "slug": "073-simplifying-algebraic-fractions",
    "num": 73,
    "topic": "Fractions — Secondary",
    "subtopic": "Simplifying algebraic fractions",
    "topicSlug": "fractions-secondary",
    "subtopicSlug": "simplifying-algebraic-fractions"
  },
  {
    "slug": "078-converting-between-fdp",
    "num": 78,
    "topic": "Fractions, Decimals and Percentages",
    "subtopic": "Converting between fractions, decimals and percentages",
    "topicSlug": "fractions-decimals-and-percentages",
    "subtopicSlug": "converting-between-fractions-decimals-and-percentages"
  },
  {
    "slug": "079-ordering-fdp",
    "num": 79,
    "topic": "Fractions, Decimals and Percentages",
    "subtopic": "Ordering FDP",
    "topicSlug": "fractions-decimals-and-percentages",
    "subtopicSlug": "ordering-fdp"
  },
  {
    "slug": "080-percentage-change",
    "num": 80,
    "topic": "Fractions, Decimals and Percentages",
    "subtopic": "Percentage change",
    "topicSlug": "fractions-decimals-and-percentages",
    "subtopicSlug": "percentage-change"
  },
  {
    "slug": "081-recurring-decimals",
    "num": 81,
    "topic": "Fractions, Decimals and Percentages",
    "subtopic": "Recurring decimals",
    "topicSlug": "fractions-decimals-and-percentages",
    "subtopicSlug": "recurring-decimals"
  },
  {
    "slug": "082-sketching-quadratic-cubic-and-reciprocal-graphs",
    "num": 82,
    "topic": "Functions and Graphs",
    "subtopic": "Sketching quadratic, cubic and reciprocal graphs",
    "topicSlug": "functions-and-graphs",
    "subtopicSlug": "sketching-quadratic-cubic-and-reciprocal-graphs"
  },
  {
    "slug": "083-transformations-of-graphs",
    "num": 83,
    "topic": "Functions and Graphs",
    "subtopic": "Transformations of graphs",
    "topicSlug": "functions-and-graphs",
    "subtopicSlug": "transformations-of-graphs"
  },
  {
    "slug": "084-calculations-in-standard-form",
    "num": 84,
    "topic": "Indices and Standard Form",
    "subtopic": "Calculations in standard form",
    "topicSlug": "indices-and-standard-form",
    "subtopicSlug": "calculations-in-standard-form"
  },
  {
    "slug": "085-double-inequalities",
    "num": 85,
    "topic": "Linear Inequalities",
    "subtopic": "Double inequalities",
    "topicSlug": "linear-inequalities",
    "subtopicSlug": "double-inequalities"
  },
  {
    "slug": "086-inequalities-in-two-variables",
    "num": 86,
    "topic": "Linear Inequalities",
    "subtopic": "Inequalities in two variables",
    "topicSlug": "linear-inequalities",
    "subtopicSlug": "inequalities-in-two-variables"
  },
  {
    "slug": "087-representing-inequalities-on-a-number-line",
    "num": 87,
    "topic": "Linear Inequalities",
    "subtopic": "Representing inequalities on a number line",
    "topicSlug": "linear-inequalities",
    "subtopicSlug": "representing-inequalities-on-a-number-line"
  },
  {
    "slug": "088-10-times-table",
    "num": 88,
    "topic": "Multiplication and Division (2, 5, 10 Times Tables)",
    "subtopic": "10 times table",
    "topicSlug": "multiplication-and-division-2-5-10-times-tables",
    "subtopicSlug": "10-times-table"
  },
  {
    "slug": "089-2-times-table",
    "num": 89,
    "topic": "Multiplication and Division (2, 5, 10 Times Tables)",
    "subtopic": "2 times table",
    "topicSlug": "multiplication-and-division-2-5-10-times-tables",
    "subtopicSlug": "2-times-table"
  },
  {
    "slug": "090-5-times-table",
    "num": 90,
    "topic": "Multiplication and Division (2, 5, 10 Times Tables)",
    "subtopic": "5 times table",
    "topicSlug": "multiplication-and-division-2-5-10-times-tables",
    "subtopicSlug": "5-times-table"
  },
  {
    "slug": "091-division-as-the-inverse-of-multiplication",
    "num": 91,
    "topic": "Multiplication and Division (2, 5, 10 Times Tables)",
    "subtopic": "Division as the inverse of multiplication",
    "topicSlug": "multiplication-and-division-2-5-10-times-tables",
    "subtopicSlug": "division-as-the-inverse-of-multiplication"
  },
  {
    "slug": "092-3-times-table",
    "num": 92,
    "topic": "Multiplication and Division (3, 4, 8 Times Tables)",
    "subtopic": "3 times table",
    "topicSlug": "multiplication-and-division-3-4-8-times-tables",
    "subtopicSlug": "3-times-table"
  },
  {
    "slug": "093-4-times-table",
    "num": 93,
    "topic": "Multiplication and Division (3, 4, 8 Times Tables)",
    "subtopic": "4 times table",
    "topicSlug": "multiplication-and-division-3-4-8-times-tables",
    "subtopicSlug": "4-times-table"
  },
  {
    "slug": "094-8-times-table",
    "num": 94,
    "topic": "Multiplication and Division (3, 4, 8 Times Tables)",
    "subtopic": "8 times table",
    "topicSlug": "multiplication-and-division-3-4-8-times-tables",
    "subtopicSlug": "8-times-table"
  },
  {
    "slug": "095-mixed-times-table-practice",
    "num": 95,
    "topic": "Multiplication and Division (3, 4, 8 Times Tables)",
    "subtopic": "Mixed times table practice",
    "topicSlug": "multiplication-and-division-3-4-8-times-tables",
    "subtopicSlug": "mixed-times-table-practice"
  },
  {
    "slug": "096-dividing-by-10-100-and-1000",
    "num": 96,
    "topic": "Multiplication and Division (Multi-Digit)",
    "subtopic": "Dividing by 10, 100 and 1000",
    "topicSlug": "multiplication-and-division-multi-digit",
    "subtopicSlug": "dividing-by-10-100-and-1000"
  },
  {
    "slug": "097-long-division",
    "num": 97,
    "topic": "Multiplication and Division (Multi-Digit)",
    "subtopic": "Long division",
    "topicSlug": "multiplication-and-division-multi-digit",
    "subtopicSlug": "long-division"
  },
  {
    "slug": "098-long-multiplication",
    "num": 98,
    "topic": "Multiplication and Division (Multi-Digit)",
    "subtopic": "Long multiplication",
    "topicSlug": "multiplication-and-division-multi-digit",
    "subtopicSlug": "long-multiplication"
  },
  {
    "slug": "099-multiplying-by-10-100-and-1000",
    "num": 99,
    "topic": "Multiplication and Division (Multi-Digit)",
    "subtopic": "Multiplying by 10, 100 and 1000",
    "topicSlug": "multiplication-and-division-multi-digit",
    "subtopicSlug": "multiplying-by-10-100-and-1000"
  },
  {
    "slug": "100-6-7-9-11-12-times-tables",
    "num": 100,
    "topic": "Multiplication and Division (Times Tables to 12×12)",
    "subtopic": "6, 7, 9, 11, 12 times tables",
    "topicSlug": "multiplication-and-division-times-tables-to-12-12",
    "subtopicSlug": "6-7-9-11-12-times-tables"
  },
  {
    "slug": "102-short-division",
    "num": 102,
    "topic": "Multiplication and Division (Times Tables to 12×12)",
    "subtopic": "Short division",
    "topicSlug": "multiplication-and-division-times-tables-to-12-12",
    "subtopicSlug": "short-division"
  },
  {
    "slug": "103-short-multiplication",
    "num": 103,
    "topic": "Multiplication and Division (Times Tables to 12×12)",
    "subtopic": "Short multiplication",
    "topicSlug": "multiplication-and-division-times-tables-to-12-12",
    "subtopicSlug": "short-multiplication"
  },
  {
    "slug": "104-compound-interest-and-depreciation",
    "num": 104,
    "topic": "Percentages",
    "subtopic": "Compound interest and depreciation",
    "topicSlug": "percentages",
    "subtopicSlug": "compound-interest-and-depreciation"
  },
  {
    "slug": "105-percentage-increase-and-decrease",
    "num": 105,
    "topic": "Percentages",
    "subtopic": "Percentage increase and decrease",
    "topicSlug": "percentages",
    "subtopicSlug": "percentage-increase-and-decrease"
  },
  {
    "slug": "106-percentage-of-an-amount",
    "num": 106,
    "topic": "Percentages",
    "subtopic": "Percentage of an amount",
    "topicSlug": "percentages",
    "subtopicSlug": "percentage-of-an-amount"
  },
  {
    "slug": "107-finding-any-percentage-of-an-amount",
    "num": 107,
    "topic": "Percentages of Amounts",
    "subtopic": "Finding any percentage of an amount",
    "topicSlug": "percentages-of-amounts",
    "subtopicSlug": "finding-any-percentage-of-an-amount"
  },
  {
    "slug": "108-percentage-increase-and-decrease-primary",
    "num": 108,
    "topic": "Percentages of Amounts",
    "subtopic": "Percentage increase and decrease",
    "topicSlug": "percentages-of-amounts",
    "subtopicSlug": "percentage-increase-and-decrease"
  },
  {
    "slug": "132-estimating-calculations",
    "num": 132,
    "topic": "Place Value and Ordering Integers",
    "subtopic": "Estimating calculations",
    "topicSlug": "place-value-and-ordering-integers",
    "subtopicSlug": "estimating-calculations"
  },
  {
    "slug": "133-ordering-positive-and-negative-integers",
    "num": 133,
    "topic": "Place Value and Ordering Integers",
    "subtopic": "Ordering positive and negative integers",
    "topicSlug": "place-value-and-ordering-integers",
    "subtopicSlug": "ordering-positive-and-negative-integers"
  },
  {
    "slug": "134-reading-and-writing-large-integers",
    "num": 134,
    "topic": "Place Value and Ordering Integers",
    "subtopic": "Reading and writing large integers",
    "topicSlug": "place-value-and-ordering-integers",
    "subtopicSlug": "reading-and-writing-large-integers"
  },
  {
    "slug": "135-rounding-to-significant-figures",
    "num": 135,
    "topic": "Place Value and Ordering Integers",
    "subtopic": "Rounding to significant figures",
    "topicSlug": "place-value-and-ordering-integers",
    "subtopicSlug": "rounding-to-significant-figures"
  },
  {
    "slug": "136-basic-probability-single-events",
    "num": 136,
    "topic": "Probability",
    "subtopic": "Basic probability — single events",
    "topicSlug": "probability",
    "subtopicSlug": "basic-probability-single-events"
  },
  {
    "slug": "137-conditional-probability-and-venn-diagrams",
    "num": 137,
    "topic": "Probability",
    "subtopic": "Conditional probability and Venn diagrams",
    "topicSlug": "probability",
    "subtopicSlug": "conditional-probability-and-venn-diagrams"
  },
  {
    "slug": "138-mutually-exclusive-events",
    "num": 138,
    "topic": "Probability",
    "subtopic": "Mutually exclusive events",
    "topicSlug": "probability",
    "subtopicSlug": "mutually-exclusive-events"
  },
  {
    "slug": "139-tree-diagrams",
    "num": 139,
    "topic": "Probability",
    "subtopic": "Tree diagrams",
    "topicSlug": "probability",
    "subtopicSlug": "tree-diagrams"
  },
  {
    "slug": "140-direct-proportion",
    "num": 140,
    "topic": "Proportion",
    "subtopic": "Direct proportion",
    "topicSlug": "proportion",
    "subtopicSlug": "direct-proportion"
  },
  {
    "slug": "141-inverse-proportion",
    "num": 141,
    "topic": "Proportion",
    "subtopic": "Inverse proportion",
    "topicSlug": "proportion",
    "subtopicSlug": "inverse-proportion"
  },
  {
    "slug": "142-proportion-graphs",
    "num": 142,
    "topic": "Proportion",
    "subtopic": "Proportion graphs",
    "topicSlug": "proportion",
    "subtopicSlug": "proportion-graphs"
  },
  {
    "slug": "143-proportion-in-context",
    "num": 143,
    "topic": "Proportion",
    "subtopic": "Proportion in context (recipes, maps, scale)",
    "topicSlug": "proportion",
    "subtopicSlug": "proportion-in-context-recipes-maps-scale"
  },
  {
    "slug": "144-applying-pythagoras-in-2d-problems",
    "num": 144,
    "topic": "Pythagoras' Theorem",
    "subtopic": "Applying Pythagoras in 2D problems",
    "topicSlug": "pythagoras-theorem",
    "subtopicSlug": "applying-pythagoras-in-2d-problems"
  },
  {
    "slug": "145-applying-pythagoras-in-3d-problems",
    "num": 145,
    "topic": "Pythagoras' Theorem",
    "subtopic": "Applying Pythagoras in 3D problems",
    "topicSlug": "pythagoras-theorem",
    "subtopicSlug": "applying-pythagoras-in-3d-problems"
  },
  {
    "slug": "146-finding-a-shorter-side",
    "num": 146,
    "topic": "Pythagoras' Theorem",
    "subtopic": "Finding a shorter side",
    "topicSlug": "pythagoras-theorem",
    "subtopicSlug": "finding-a-shorter-side"
  },
  {
    "slug": "147-finding-the-hypotenuse",
    "num": 147,
    "topic": "Pythagoras' Theorem",
    "subtopic": "Finding the hypotenuse",
    "topicSlug": "pythagoras-theorem",
    "subtopicSlug": "finding-the-hypotenuse"
  },
  {
    "slug": "148-completing-the-square",
    "num": 148,
    "topic": "Quadratic Equations",
    "subtopic": "Completing the square",
    "topicSlug": "quadratic-equations",
    "subtopicSlug": "completing-the-square"
  },
  {
    "slug": "149-discriminant",
    "num": 149,
    "topic": "Quadratic Equations",
    "subtopic": "Discriminant",
    "topicSlug": "quadratic-equations",
    "subtopicSlug": "discriminant"
  },
  {
    "slug": "150-factorising-quadratics",
    "num": 150,
    "topic": "Quadratic Equations",
    "subtopic": "Factorising quadratics",
    "topicSlug": "quadratic-equations",
    "subtopicSlug": "factorising-quadratics"
  },
  {
    "slug": "151-best-value-problems",
    "num": 151,
    "topic": "Ratio",
    "subtopic": "Best value problems",
    "topicSlug": "ratio",
    "subtopicSlug": "best-value-problems"
  },
  {
    "slug": "152-dividing-in-a-ratio",
    "num": 152,
    "topic": "Ratio",
    "subtopic": "Dividing in a ratio",
    "topicSlug": "ratio",
    "subtopicSlug": "dividing-in-a-ratio"
  },
  {
    "slug": "153-ratio-and-proportion-problems",
    "num": 153,
    "topic": "Ratio",
    "subtopic": "Ratio and proportion problems",
    "topicSlug": "ratio",
    "subtopicSlug": "ratio-and-proportion-problems"
  },
  {
    "slug": "154-simplifying-ratios",
    "num": 154,
    "topic": "Ratio",
    "subtopic": "Simplifying ratios",
    "topicSlug": "ratio",
    "subtopicSlug": "simplifying-ratios"
  },
  {
    "slug": "155-dividing-quantities-in-a-given-ratio",
    "num": 155,
    "topic": "Ratio and Proportion",
    "subtopic": "Dividing quantities in a given ratio",
    "topicSlug": "ratio-and-proportion",
    "subtopicSlug": "dividing-quantities-in-a-given-ratio"
  },
  {
    "slug": "156-scale-factors",
    "num": 156,
    "topic": "Ratio and Proportion",
    "subtopic": "Scale factors",
    "topicSlug": "ratio-and-proportion",
    "subtopicSlug": "scale-factors"
  },
  {
    "slug": "157-fibonacci-type-sequences",
    "num": 157,
    "topic": "Sequences",
    "subtopic": "Fibonacci-type sequences",
    "topicSlug": "sequences",
    "subtopicSlug": "fibonacci-type-sequences"
  },
  {
    "slug": "158-geometric-sequences",
    "num": 158,
    "topic": "Sequences",
    "subtopic": "Geometric sequences",
    "topicSlug": "sequences",
    "subtopicSlug": "geometric-sequences"
  },
  {
    "slug": "159-quadratic-sequences",
    "num": 159,
    "topic": "Sequences",
    "subtopic": "Quadratic sequences",
    "topicSlug": "sequences",
    "subtopicSlug": "quadratic-sequences"
  },
  {
    "slug": "160-non-linear-simultaneous-equations",
    "num": 160,
    "topic": "Simultaneous Equations",
    "subtopic": "Non-linear simultaneous equations",
    "topicSlug": "simultaneous-equations",
    "subtopicSlug": "non-linear-simultaneous-equations"
  },
  {
    "slug": "161-solving-by-elimination",
    "num": 161,
    "topic": "Simultaneous Equations",
    "subtopic": "Solving by elimination",
    "topicSlug": "simultaneous-equations",
    "subtopicSlug": "solving-by-elimination"
  },
  {
    "slug": "162-solving-by-substitution",
    "num": 162,
    "topic": "Simultaneous Equations",
    "subtopic": "Solving by substitution",
    "topicSlug": "simultaneous-equations",
    "subtopicSlug": "solving-by-substitution"
  },
  {
    "slug": "163-equations-with-brackets",
    "num": 163,
    "topic": "Solving Linear Equations",
    "subtopic": "Equations with brackets",
    "topicSlug": "solving-linear-equations",
    "subtopicSlug": "equations-with-brackets"
  },
  {
    "slug": "164-equations-with-unknowns-on-both-sides",
    "num": 164,
    "topic": "Solving Linear Equations",
    "subtopic": "Equations with unknowns on both sides",
    "topicSlug": "solving-linear-equations",
    "subtopicSlug": "equations-with-unknowns-on-both-sides"
  },
  {
    "slug": "165-one-step-equations",
    "num": 165,
    "topic": "Solving Linear Equations",
    "subtopic": "One-step equations",
    "topicSlug": "solving-linear-equations",
    "subtopicSlug": "one-step-equations"
  },
  {
    "slug": "166-two-step-equations",
    "num": 166,
    "topic": "Solving Linear Equations",
    "subtopic": "Two-step equations",
    "topicSlug": "solving-linear-equations",
    "subtopicSlug": "two-step-equations"
  },
  {
    "slug": "167-cumulative-frequency-and-box-plots",
    "num": 167,
    "topic": "Statistics",
    "subtopic": "Cumulative frequency and box plots",
    "topicSlug": "statistics",
    "subtopicSlug": "cumulative-frequency-and-box-plots"
  },
  {
    "slug": "168-frequency-tables-and-grouped-data",
    "num": 168,
    "topic": "Statistics",
    "subtopic": "Frequency tables and grouped data",
    "topicSlug": "statistics",
    "subtopicSlug": "frequency-tables-and-grouped-data"
  },
  {
    "slug": "169-histograms",
    "num": 169,
    "topic": "Statistics",
    "subtopic": "Histograms",
    "topicSlug": "statistics",
    "subtopicSlug": "histograms"
  },
  {
    "slug": "170-mean-median-mode-and-range",
    "num": 170,
    "topic": "Statistics",
    "subtopic": "Mean, median, mode and range",
    "topicSlug": "statistics",
    "subtopicSlug": "mean-median-mode-and-range"
  },
  {
    "slug": "171-equation-of-a-straight-line",
    "num": 171,
    "topic": "Straight-Line Graphs",
    "subtopic": "Equation of a straight line (y = mx + c)",
    "topicSlug": "straight-line-graphs",
    "subtopicSlug": "equation-of-a-straight-line-y-mx-c"
  },
  {
    "slug": "172-gradient-and-y-intercept",
    "num": 172,
    "topic": "Straight-Line Graphs",
    "subtopic": "Gradient and y-intercept",
    "topicSlug": "straight-line-graphs",
    "subtopicSlug": "gradient-and-y-intercept"
  },
  {
    "slug": "173-parallel-and-perpendicular-lines",
    "num": 173,
    "topic": "Straight-Line Graphs",
    "subtopic": "Parallel and perpendicular lines",
    "topicSlug": "straight-line-graphs",
    "subtopicSlug": "parallel-and-perpendicular-lines"
  },
  {
    "slug": "174-plotting-straight-line-graphs",
    "num": 174,
    "topic": "Straight-Line Graphs",
    "subtopic": "Plotting straight-line graphs",
    "topicSlug": "straight-line-graphs",
    "subtopicSlug": "plotting-straight-line-graphs"
  },
  {
    "slug": "175-adding-and-subtracting-surds",
    "num": 175,
    "topic": "Surds",
    "subtopic": "Adding and subtracting surds",
    "topicSlug": "surds",
    "subtopicSlug": "adding-and-subtracting-surds"
  },
  {
    "slug": "176-multiplying-and-dividing-surds",
    "num": 176,
    "topic": "Surds",
    "subtopic": "Multiplying and dividing surds",
    "topicSlug": "surds",
    "subtopicSlug": "multiplying-and-dividing-surds"
  },
  {
    "slug": "177-rationalising-the-denominator",
    "num": 177,
    "topic": "Surds",
    "subtopic": "Rationalising the denominator",
    "topicSlug": "surds",
    "subtopicSlug": "rationalising-the-denominator"
  },
  {
    "slug": "178-simplifying-surds",
    "num": 178,
    "topic": "Surds",
    "subtopic": "Simplifying surds",
    "topicSlug": "surds",
    "subtopicSlug": "simplifying-surds"
  },
  {
    "slug": "179-enlargement",
    "num": 179,
    "topic": "Transformations",
    "subtopic": "Enlargement",
    "topicSlug": "transformations",
    "subtopicSlug": "enlargement"
  },
  {
    "slug": "180-reflection",
    "num": 180,
    "topic": "Transformations",
    "subtopic": "Reflection",
    "topicSlug": "transformations",
    "subtopicSlug": "reflection"
  },
  {
    "slug": "181-rotation",
    "num": 181,
    "topic": "Transformations",
    "subtopic": "Rotation",
    "topicSlug": "transformations",
    "subtopicSlug": "rotation"
  },
  {
    "slug": "182-translation",
    "num": 182,
    "topic": "Transformations",
    "subtopic": "Translation",
    "topicSlug": "transformations",
    "subtopicSlug": "translation"
  },
  {
    "slug": "183-exact-trigonometric-values",
    "num": 183,
    "topic": "Trigonometry",
    "subtopic": "Exact trigonometric values",
    "topicSlug": "trigonometry",
    "subtopicSlug": "exact-trigonometric-values"
  },
  {
    "slug": "184-soh-cah-toa-finding-angles",
    "num": 184,
    "topic": "Trigonometry",
    "subtopic": "SOH CAH TOA — finding angles",
    "topicSlug": "trigonometry",
    "subtopicSlug": "soh-cah-toa-finding-angles"
  },
  {
    "slug": "185-soh-cah-toa-finding-sides",
    "num": 185,
    "topic": "Trigonometry",
    "subtopic": "SOH CAH TOA — finding sides",
    "topicSlug": "trigonometry",
    "subtopicSlug": "soh-cah-toa-finding-sides"
  },
  {
    "slug": "186-sine-and-cosine-rules",
    "num": 186,
    "topic": "Trigonometry",
    "subtopic": "Sine and cosine rules",
    "topicSlug": "trigonometry",
    "subtopicSlug": "sine-and-cosine-rules"
  },
  {
    "slug": "187-adding-and-subtracting-vectors",
    "num": 187,
    "topic": "Vectors",
    "subtopic": "Adding and subtracting vectors",
    "topicSlug": "vectors",
    "subtopicSlug": "adding-and-subtracting-vectors"
  },
  {
    "slug": "188-multiplying-vectors-by-a-scalar",
    "num": 188,
    "topic": "Vectors",
    "subtopic": "Multiplying vectors by a scalar",
    "topicSlug": "vectors",
    "subtopicSlug": "multiplying-vectors-by-a-scalar"
  },
  {
    "slug": "189-vector-geometry-proofs",
    "num": 189,
    "topic": "Vectors",
    "subtopic": "Vector geometry proofs",
    "topicSlug": "vectors",
    "subtopicSlug": "vector-geometry-proofs"
  },
  {
    "slug": "190-writing-and-representing-vectors",
    "num": 190,
    "topic": "Vectors",
    "subtopic": "Writing and representing vectors",
    "topicSlug": "vectors",
    "subtopicSlug": "writing-and-representing-vectors"
  },
  {
    "slug": "191-surface-area-of-cylinders-and-spheres",
    "num": 191,
    "topic": "Volume and Surface Area",
    "subtopic": "Surface area of cylinders and spheres",
    "topicSlug": "volume-and-surface-area",
    "subtopicSlug": "surface-area-of-cylinders-and-spheres"
  },
  {
    "slug": "192-surface-area-of-prisms",
    "num": 192,
    "topic": "Volume and Surface Area",
    "subtopic": "Surface area of prisms",
    "topicSlug": "volume-and-surface-area",
    "subtopicSlug": "surface-area-of-prisms"
  },
  {
    "slug": "193-volume-of-prisms-and-cylinders",
    "num": 193,
    "topic": "Volume and Surface Area",
    "subtopic": "Volume of prisms and cylinders",
    "topicSlug": "volume-and-surface-area",
    "subtopicSlug": "volume-of-prisms-and-cylinders"
  },
  {
    "slug": "194-volume-of-pyramids-cones-and-spheres",
    "num": 194,
    "topic": "Volume and Surface Area",
    "subtopic": "Volume of pyramids, cones and spheres",
    "topicSlug": "volume-and-surface-area",
    "subtopicSlug": "volume-of-pyramids-cones-and-spheres"
  }
];

/** Composite-key index: "${topicSlug}|||${subtopicSlug}" → entry. */
const BY_COMPOSITE = new Map<string, GoldManifestEntry>();
/** Fallback index: subtopicSlug → entries (may collide across topics). */
const BY_SUBTOPIC = new Map<string, GoldManifestEntry[]>();
for (const e of MATHS_GOLD_MANIFEST) {
  BY_COMPOSITE.set(`${e.topicSlug}|||${e.subtopicSlug}`, e);
  const list = BY_SUBTOPIC.get(e.subtopicSlug) ?? [];
  list.push(e);
  BY_SUBTOPIC.set(e.subtopicSlug, list);
}

function normalise(s: string): string {
  return String(s)
    .toLowerCase()
    .replace(/&[a-z]+;/g, " ")
    .replace(/[—–-]/g, " ")
    .replace(/[^a-z0-9]+/g, " ")
    .trim()
    .replace(/\s+/g, "-");
}

/**
 * Find the gold worksheet entry for a topic + subtopic, if one exists.
 * Tiered match: exact composite key first, then unambiguous subtopic slug.
 */
export function findGoldEntry(
  topic: string | undefined,
  subtopic: string | undefined
): GoldManifestEntry | null {
  if (!subtopic) return null;
  const subSlug = normalise(subtopic);
  if (topic) {
    const exact = BY_COMPOSITE.get(`${normalise(topic)}|||${subSlug}`);
    if (exact) return exact;
  }
  const candidates = BY_SUBTOPIC.get(subSlug);
  if (candidates && candidates.length === 1) return candidates[0];
  return null;
}

/** True if a gold landscape worksheet exists for this topic + subtopic. */
export function hasGoldWorksheet(
  topic: string | undefined,
  subtopic: string | undefined
): boolean {
  return findGoldEntry(topic, subtopic) !== null;
}

/** Lazily load the full worksheet content for a manifest slug. */
export async function loadGoldWorksheet(
  slug: string
): Promise<GoldWorksheet | null> {
  const mod = await import("./worksheets.json");
  const data = (mod.default ?? mod) as Record<string, GoldWorksheet>;
  return data[slug] ?? null;
}
